ezsystems/ezpublish-kernel

eZ/Publish/API/Repository/RoleService.php, eZ/Publish/Core/REST/Client/RoleService.php, eZ/Publish/Core/Repository/RoleService.php, eZ/Publish/Core/SignalSlot/RoleService.php, eZ/Publish/Core/SignalSlot/Tests/RoleServiceTest.php
=> EZP-23847: Add Role API parameter to get inherited RoleAssignments

eZ/Bundle/EzPublishCoreBundle/Console/Application.php, eZ/Bundle/EzPublishLegacyBundle/EventListener/LegacyKernelListener.php, eZ/Bundle/EzPublishLegacyBundle/Resources/config/services.yml
> https://jira.ez.no/browse/EZP-23865
=> Fix EZP-23865: Fix legacy kernel manual reset in core console application

eZ/Publish/Core/MVC/Legacy/SignalSlot/AbstractLegacySlot.php
Will take care of clearing HTTP caches until EZP-23897 is finished.
=> Workaround: re-enabled legacy HTTP cache clearing

doc/specifications/io/io_url_decoration.md, doc/specifications/io/native_io_handlers.md, eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
> https://jira.ez.no/browse/EZP-23864
Forgotten dependency...
=> EZP-23864: Removed dependency on legacy root dir

eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php, eZ/Publish/API/Repository/Values/Content/Query/Criterion.php, eZ/Publish/Core/FieldType/BinaryBase/Type.php, eZ/Publish/Core/FieldType/BinaryBase/Value.php, eZ/Publish/Core/FieldType/Image/Type.php, eZ/Publish/Core/FieldType/Image/Value.php, eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php, eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Depth.php, eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/ParentContentType.php, eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/ParentLocation.php, eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Identifier/ParentContentType.php, eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Identifier/Section.php, eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php, eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSizeExtensionTest.php, eZ/Publish/Core/Persistence/Doctrine/ConnectionHandler.php, eZ/Publish/Core/REST/Server/Controller/ContentType.php, eZ/Publish/Core/REST/Server/Controller/User.php, eZ/Publish/Core/Repository/ContentService.php, eZ/Publish/Core/Repository/ContentTypeService.php, eZ/Publish/Core/Repository/Repository.php, eZ/Publish/Core/Repository/Tests/Service/Integration/ContentBase.php, eZ/Publish/Core/Repository/Tests/Service/Mock/RepositoryTest.php, eZ/Publish/Core/SignalSlot/Repository.php
This just fixes some issues, there are still tons of issues by all of us*
\* myself, @pspanja, @yannickroger, @lolautruche, @bdunogier, @dpobel, @StephaneDiot, @glye: Please have a look [here](https://insight.sensiolabs.com/projects/0885c0ce-4b9f-4b89-aa9c-e8f9f7a315e0/analyses/122) to know what to avoid, so we don't keep on creating more of these issues.
(waiting for travis)
=> Fix some Insight issues

doc/bc/changes-6.0.md
=> typo in 6.0 bc changes doc

doc/bc/changes-5.3.md, doc/bc/changes-5.4.md, doc/bc/changes-6.0.md
This PR resolves https://jira.ez.no/browse/EZP-23940
Added BC notes for versions `6.0`, `5.4` and `5.3`.
=> EZP-23940: BC notes (Decouple search handlers from Persistence)

doc/specifications/image/image_alias_imagine.md
Update LiipImagineBundle documentation links
=> Update LiipImagineBundle documentation links

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php, eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Issue: https://jira.ez.no/browse/EZP-24025
Is being tested here : https://github.com/ezsystems/ezpublish-community/pull/230
=> Fix EZP-24025: Make sure to clear cache on install

Readme.md
https://jira.ez.no/browse/EZP-23993
If approved, this should be added to other repos too: ezpublish-legacy at the very least, but possibly all of them?
=> Implement EZP-23993: Clarify and document how security issues should be reported

eZ/Publish/Core/Pagination/Pagerfanta/ContentSearchHitAdapter.php, eZ/Publish/Core/Pagination/Pagerfanta/LocationSearchHitAdapter.php, eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php, eZ/Publish/Core/Pagination/Tests/LocationSearchHitAdapterTest.php, eZ/Publish/Core/Repository/UserService.php
https://jira.ez.no/browse/EZP-24092
Also see DemoBundle PR:
https://github.com/ezsystems/DemoBundle/pull/146
=> EZP-24092: Optimize queries to not perform count when not needed

eZ/Publish/Core/REST/Server/Controller/Content.php
JIRA: https://jira.ez.no/browse/EZP-24065
See https://github.com/ezsystems/PlatformUIBundle/pull/210
=> EZP-24065: Fixed a wrong usage of the repository/section service

eZ/Publish/API/Repository/Tests/FieldType/ISBNIntegrationTest.php, eZ/Publish/Core/FieldType/ISBN/SearchField.php, eZ/Publish/Core/settings/indexable_fieldtypes.yml
This PR resolves https://jira.ez.no/browse/EZP-24319
=> Implement EZP-24319: Indexable ISBN field type

eZ/Publish/API/Repository/Values/Content/Query/Criterion/Field.php
=> Fixed typo in Criterion/Field phpdoc

eZ/Publish/Core/settings/repository.yml
https://jira.ez.no/browse/EZP-24360
Added a property for a class and a service definition.
=> Fixed EZP-24360: added a service definition for LanguageService

eZ/Bundle/EzPublishRestBundle/DependencyInjection/Security/RestSessionBasedFactory.php
> https://jira.ez.no/browse/EZP-24367
Complements https://github.com/ezsystems/LegacyBridge/pull/26
=> EZP-24367: Ensures RestAuthenticator is not rememberme aware

eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
> https://jira.ez.no/browse/EZP-24379
See https://github.com/ezsystems/PlatformUIBundle/pull/236
Nothing critical, but definitely nicer than WTF sorting.
Would be better if configurable, but this one is a low hanging fruit, so...
=> EZP-24379: Made ContentType listing ordered by identifier

eZ/Publish/Core/FieldType/BinaryBase/Type.php, eZ/Publish/Core/FieldType/FieldType.php, eZ/Publish/Core/FieldType/Tests/BinaryBaseTest.php, eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/BinaryFile.php
Needed for the form mapper, see PR https://github.com/ezsystems/repository-forms/pull/22
https://jira.ez.no/browse/EZP-24441
=> Fix EZP-24441: Implement FieldDefinition form mapper for ezbinaryfile

bin/.travis/prepare_behat.sh
ping @lolautruche 
Temp fix until we use branch alias.
=> Fix Behat failure by setting alias to dev-master

.gitignore, .travis.yml, bin/.travis/install_composer_github_key.sh, bin/.travis/prepare_unittest.sh, composer.lock
Hypothesis: we were using private github token that is not valid anymore, and as it is private is should not have been shared in the first place as github actively disables any token they find in source code on github. So seems we are maybe hitting Github API limits again, however Composer is not really helpful on that to verify if this is the case. *Ps: I'm also experiencing extreme slowness from Travis as well, so that makes the situation even worse.*
Hypothesis2: Issues with packagist after update on Friday.
There is no good way to setup auth token for an open source project *(secure env variables won't work on forks)*, so if can't get token to work we will need to do one or several of:
- reduce number of jobs *(disable allowed failing tests, move search and storage engines out, behat …
=> [Travis] Try to get it running again

doc/bc/changes-6.0.md, eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml, eZ/Bundle/EzPublishCoreBundle/Resources/views/Security/login.html.twig, eZ/Bundle/EzPublishRestBundle/EventListener/CsrfListener.php, eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Bundle/EzPublishRestBundle/Tests/EventListener/CsrfListenerTest.php, eZ/Publish/Core/MVC/Symfony/Controller/SecurityController.php, eZ/Publish/Core/REST/Server/Controller/User.php
> https://jira.ez.no/browse/EZP-24476
=> Fix EZP-24476: Refactor CSRF token generation in Security login form

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
In #1300 updating comments was forgotten.
=> Fix EZP-24535: Added comments for ezimage_field parameters

eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
> https://jira.ez.no/browse/EZP-24568
=> Fix EZP-24568: Remove InvalidArgumentException when position of a FieldDefinition is 0

doc/specifications/proposed/named_queries/developer_documentation.md
> [EZP-24556](http://jira.ez.no/browse/EZP-24556)
> Status: ready for merge
This is meant to establish the developer documentation for the Named Queries feature. Once complete, the technical specifications + development can be started.
=> EZP-24556: Named queries developer doc

eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php, eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/5
=> EZP-24649: Solr: Index Locations as nested documents of Content

eZ/Publish/Core/Pagination/Pagerfanta/LocationSearchHitAdapter.php, eZ/Publish/Core/Search/Elasticsearch/Content/Handler.php, eZ/Publish/Core/Search/Legacy/Content/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Search/Legacy/Content/Handler.php, eZ/Publish/Core/Search/Legacy/Content/Location/Gateway.php, eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/ExceptionConversion.php, eZ/Publish/SPI/Search/Handler.php
JIRA: https://jira.ez.no/browse/EZP-24673
=> EZP-24673: Implement languageFilter for Location Legacy Search Engine

eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
JIRA: https://jira.ez.no/browse/EZP-24686
Cross-siteaccess links using multisite (content tree root) do not work correctly when the target siteaccess has a root location in a different translation that of the current site.
The fix is to make sure to load the target SA root location's path with respect to its language list.
=> Fix EZP-24686: Multisite cross SA links to different languages

composer.json, composer.lock
It seems we forgot to update composer.json :smile:
=> Removed ezpublish-legacy as dev dependency + updated deps

eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/Command/ElasticsearchCreateIndexCommand.php, eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php, eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml, eZ/Bundle/PlatformInstallerBundle/src/Resources/config_templates/clean/ezpublish.yml
=> EZP-24745: Make SolrBundle ready for release

.travis.yml, doc/specifications/rest/REST-API-V2.rst, eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Authentication.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/EzRest.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Views.php, eZ/Bundle/EzPublishRestBundle/Features/Views/query.feature, eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml, eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml, eZ/Publish/Core/REST/Client/Input/Parser/Content.php, eZ/Publish/Core/REST/Client/Input/Parser/SearchHit.php, eZ/Publish/Core/REST/Client/Input/Parser/View.php, eZ/Publish/Core/REST/Client/Input/Parser/ViewResult.php, eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/ViewInput.php, eZ/Publish/Core/REST/Client/Tests/Input/Parser/ContentTest.php, eZ/Publish/Core/REST/Client/Values/Content/Content.php, eZ/Publish/Core/REST/Client/Values/Content/VersionInfo.php, eZ/Publish/Core/REST/Client/Values/View.php, eZ/Publish/Core/REST/Client/Values/ViewInput.php, eZ/Publish/Core/REST/Client/Values/ViewResult.php, eZ/Publish/Core/REST/Common/FieldTypeProcessor/ImageProcessor.php
> Story: https://jira.ez.no/browse/EZP-24773
> Status: WIP, behat scenario works
Implements a [Behat Scenario for REST /views](https://github.com/ezsystems/ezpublish-kernel/blob/ezp24671-rest_views_bdd/eZ/Bundle/EzPublishRestBundle/Features/Views/query.feature) (only ContentQuery for now).
=> Behat tests for REST Views

.travis.yml, bin/.travis/prepare_rest_functional_tests.sh, eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTypeTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/RootTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/TrashTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/UrlAliasTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/UserTest.php, eZ/Publish/Core/REST/Server/Controller/Content.php, phpunit-functional-rest.xml, phpunit.xml
> Status: done
> JIRA: [EZP-24772](https://jira.ez.no/browse/EZP-24772)
=> Fix and automate existing REST functional tests

eZ/Publish/API/Repository/Values/ContentType/ContentTypeGroupCreateStruct.php, eZ/Publish/API/Repository/Values/ContentType/ContentTypeGroupStruct.php, eZ/Publish/API/Repository/Values/ContentType/ContentTypeGroupUpdateStruct.php
> https://jira.ez.no/browse/EZP-24454
=> EZP-24454: Added common base for ContentTypeGroupCreateStruct / ContentTypeGroupUpdateStruct

eZ/Publish/Core/REST/Server/Controller/User.php
JIRA: https://jira.ez.no/browse/EZP-24753
=> Fix EZP-24753: non-admin load user on login to PlatformUI

eZ/Publish/API/Repository/Tests/FieldType/SearchableUrl.php, eZ/Publish/API/Repository/Tests/FieldType/UrlIntegrationTest.php, eZ/Publish/Core/FieldType/Url/SearchField.php, eZ/Publish/Core/settings/indexable_fieldtypes.yml, eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml
This implements `Indexable` definition for `Url` field type.
Indexed data:
1. `value_url`, the URL
2. `value_id`, stored URL ID
3. `value_text`, linked text
=> Implement EZP-24816: Indexable for Url field type

eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.pt.xlf
This PR extends the EZP-24793 - Make Repository exceptions translatable story to include the Portuguese translation
=> Added Portuguese translation to the repository exceptions

eZ/Publish/Core/REST/Common/Input/Dispatcher.php, eZ/Publish/Core/REST/Common/Input/ParsingDispatcher.php, eZ/Publish/Core/REST/Common/Tests/Input/DispatcherTest.php, eZ/Publish/Core/REST/Common/Tests/Input/ParsingDispatcherTest.php
> Fixes EZP-24877: Error listing subitems on PlatformUI on Firefox
Covered by unit test (as well as version).
=> Ignore other parameters in REST content-type

eZ/Publish/API/Repository/Values/User/PolicyCreateStruct.php, eZ/Publish/API/Repository/Values/User/PolicyStruct.php, eZ/Publish/API/Repository/Values/User/PolicyUpdateStruct.php
> https://jira.ez.no/browse/EZP-24711
=> EZP-24711: Added common base for PolicyCreateStruct / PolicyUpdateStruct

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
This PR resolves https://jira.ez.no/browse/EZP-24902
Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/23
This only adds indexing integration test for the bug solved by https://github.com/ezsystems/ezplatform-solr-search-engine/pull/23.
The test if expected to fail and the pass when tested against the fix in the Solr repo.
=> Fix EZP-24902: Document is not indexed for translation

eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php, eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php
Contains what @emodric did on view `ViewControllerListener` (#1444), with the unit test fix.
=> Fix BC issues with deprecated location view controller and fallback to content view controller

eZ/Publish/API/Repository/Tests/FieldType/CountryIntegrationTest.php, eZ/Publish/API/Repository/Tests/FieldType/SearchMultivaluedBaseIntegrationTest.php, eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php, eZ/Publish/API/Repository/Tests/SearchServiceTest.php, eZ/Publish/Core/FieldType/Country/SearchField.php, eZ/Publish/Core/settings/indexable_fieldtypes.yml
This PR resolves https://jira.ez.no/browse/EZP-24904
Complete country data is now indexed, including country names, IDC and Alpha2 and Alpha3 codes.
=> Implement EZP-24904: improve indexable for Country field type

eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
> Implements [EZP-24932](https://jira.ez.no/browse/EZP-24932) (subtask of [EZP-24869](https://jira.ez.no/browse/EZP-24869))
=> Added locationId param to _ez_content_view route

doc/bc/changes-6.0.md, doc/specifications/security/permissions/policies_extensibility.md, eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/PoliciesConfigBuilder.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Security/PolicyProvider/PoliciesConfigBuilderTest.php, eZ/Publish/Core/Repository/Repository.php, eZ/Publish/Core/Repository/RoleService.php, eZ/Publish/Core/Repository/Tests/Service/Mock/RoleTest.php
> https://jira.ez.no/browse/EZP-24955
This PR just injects policies that are being provided by policy providers into the Repository.
Tests have been updated accordingly.
=> Fix EZP-24955: Dynamically inject limitation map into RoleService

.travis.yml, eZ/Bundle/EzPublishCoreBundle/EventListener/ExceptionListener.php, eZ/Bundle/EzPublishCoreBundle/Features/Context/ExceptionContext.php, eZ/Bundle/EzPublishCoreBundle/Features/Exception/unauthorized_login_form.feature, eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ExceptionListenerTest.php, eZ/Bundle/EzPublishCoreBundle/behat.yml, eZ/Bundle/EzPublishRestBundle/EventListener/ResponseListener.php, eZ/Bundle/PlatformBehatBundle/Controller/ExceptionController.php, eZ/Bundle/PlatformBehatBundle/DependencyInjection/EzPlatformBehatExtension.php, eZ/Bundle/PlatformBehatBundle/Resources/config/routing.yml, eZ/Bundle/PlatformBehatBundle/Resources/config/services.yml
> Fixes https://jira.ez.no/browse/EZP-24975 
For a detailled explanation of the issue and the solution, see https://jira.ez.no/browse/EZP-24975.
=> Fixed login form not showing on Unauthorized repository exception

doc/bc/changes-6.0.md, eZ/Bundle/EzPublishCoreBundle/Controller/PageController.php, eZ/Bundle/EzPublishCoreBundle/EventListener/BlockCacheResponseListener.php, eZ/Bundle/EzPublishCoreBundle/EventListener/BlockValidContentInfoItemsListener.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml, eZ/Publish/Core/MVC/Symfony/Controller/PageController.php, eZ/Publish/Core/MVC/Symfony/View/Builder/BlockViewBuilder.php, eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/Block/ValidItems.php
> Repeat of #1457
This PR refactors page controller to use the View API.
It also adds block cache response listener and view parameters injection listeners.
=> Page controller refactor

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml, eZ/Publish/Core/Limitation/SiteAccessLimitationType.php, eZ/Publish/Core/Limitation/Tests/SiteAccessLimitationTypeTest.php, eZ/Publish/Core/settings/roles.yml, eZ/Publish/Core/settings/settings.yml
> https://jira.ez.no/browse/EZP-25010
=> Fix EZP-25010: SiteAccessLimitationType should only accept values from existing SiteAccesses

eZ/Publish/API/Repository/Values/Content/Location.php
Path is an array and not a string
=> Fix wrong phpdoc type location->path

.travis.yml, bin/.travis/prepare_unittest.sh
Will adjust for beta tags once they are out before this is merged.
=> [Travis] (Re-)Add testing for Symfony 2.8

eZ/Publish/API/Repository/Values/Content/ContentCreateStruct.php, eZ/Publish/API/Repository/Values/Content/ContentStruct.php, eZ/Publish/API/Repository/Values/Content/ContentUpdateStruct.php, eZ/Publish/Core/Repository/Values/Content/ContentUpdateStruct.php
> https://jira.ez.no/browse/EZP-25100
=> EZP-25100: Added common base for ContentCreateStruct / ContentUpdateStruct

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Link to Jira task: https://jira.ez.no/browse/EZP-25114
=> EZP-25114: Allows setting CSS custom class name for the ezimage field

eZ/Bundle/PlatformInstallerBundle/src/Installer/DbBasedInstaller.php
Link to Jira task: https://jira.ez.no/browse/EZP-25140
=> EZP-25140: Add the possibility to override files when copying configuration files

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
> Fixes https://jira.ez.no/browse/EZP-25124
=> EZP-25124: Removed demo references in post install instructions

composer.lock, eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/Core/Repository/ContentService.php, eZ/Publish/Core/Repository/Helper/DomainMapper.php
> Fixes http://jira.ez.no/browse/EZP-25152
Change logic to only include always avaiable when no other language exists.
( Changes logic introduced in 5d32579 )
=> EZP-25152: Fields in main language always included on always available content

eZ/Publish/API/Repository/SectionService.php, eZ/Publish/API/Repository/Tests/SectionServiceTest.php, eZ/Publish/Core/Persistence/Cache/SectionHandler.php, eZ/Publish/Core/Persistence/Cache/Tests/SectionHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway.php, eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/ExceptionConversion.php, eZ/Publish/Core/Persistence/Legacy/Content/Section/Handler.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/Section/Gateway/DoctrineDatabaseTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/Section/SectionHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/User/Gateway/DoctrineDatabaseTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/Gateway/DoctrineDatabaseTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/User/_fixtures/roles.php, eZ/Publish/Core/REST/Client/SectionService.php, eZ/Publish/Core/Repository/SectionService.php, eZ/Publish/Core/SignalSlot/SectionService.php, eZ/Publish/Core/SignalSlot/Tests/SectionServiceTest.php, eZ/Publish/SPI/Persistence/Content/Section/Handler.php
> Fixes https://jira.ez.no/browse/EZP-23733
> Also requires https://github.com/ezsystems/PlatformUIBundle/pull/415
Adds method for counting policies using section in limitations.
=> Fix EZP-23733: The delete button in section view/list should be disabled if the section can not be removed

doc/specifications/io/legacy_dfs_cluster.md, eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php, eZ/Bundle/EzPublishCoreBundle/Features/Console/console.feature, eZ/Bundle/EzPublishCoreBundle/Features/Context/ConsoleContext.php, eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
Needed for https://github.com/ezsystems/ezplatform/pull/70
=> Rename application folder from 'ezpublish' to 'app'

eZ/Publish/API/Repository/Tests/SearchServiceTest.php, eZ/Publish/API/Repository/Tests/_fixtures/Elasticsearch/FieldRelation.php, eZ/Publish/API/Repository/Tests/_fixtures/Elasticsearch/FieldRelationAll.php, eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FieldRelation.php, eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FieldRelationAll.php, eZ/Publish/API/Repository/Tests/_fixtures/Solr/FieldRelation.php, eZ/Publish/API/Repository/Tests/_fixtures/Solr/FieldRelationAll.php
Needed to verify: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/31
=> [Integration] Add Coverage for FieldRelation Criterion

eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php
> http://jira.ez.no/browse/EZP-25111
=> EZP-25111: Deprecated ViewController location actions

doc/specifications/rest/REST-API-V2.rst
There some errors in the doc file that cause github not to display it properly. This issue fixes it.
=> fixed REST reStructuredText doc

eZ/Bundle/PlatformInstallerBundle/src/Resources/config_templates/common/ezpublish_dev.yml, eZ/Bundle/PlatformInstallerBundle/src/Resources/config_templates/common/ezpublish_prod.yml
These two files are not needed anymore. This pr deletes them
ping @andrerom @bdunogier
=> Remove no more needed config templates

.travis.yml, bin/.travis/prepare_unittest.sh, eZ/Bundle/EzPublishCoreBundle/Routing/DefaultRouter.php, eZ/Bundle/EzPublishCoreBundle/Tests/Routing/DefaultRouterTest.php, eZ/Publish/Core/MVC/Symfony/Routing/ChainRouter.php, eZ/Publish/Core/MVC/Symfony/Routing/Generator.php, eZ/Publish/Core/MVC/Symfony/Routing/Tests/GeneratorTest.php, eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasRouterTest.php, eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php
See https://jira.ez.no/browse/EZP-25279
=> Fix EZP-25279: DefaultRouter tests incorrectly for ABSOLUTE_URL

doc/bc/changes-6.1.md, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php, eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php, eZ/Bundle/PlatformInstallerBundle/src/Installer/Installer.php
https://jira.ez.no/browse/EZP-25369
Depends on var_dir setting in base: https://github.com/ezsystems/ezplatform/pull/80
=> EZP-25369: Remove configuration from installers

doc/specifications/rest/REST-API-V2.rst, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestLocation.php, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestTrashItem.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestLocationTest.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestTrashItemTest.php
https://jira.ez.no/browse/EZP-25380
=> EZP-25380: REST Add ContentInfo to TrashItem

doc/specifications/rich_text/ezdocbook.md
JIRA: https://jira.ez.no/browse/EZP-25115
This adds an overview of RichText implementation.
=> EZP-25115: XmlText to RichText migration

eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng, eZ/Publish/Core/FieldType/Tests/RichText/Validator/DocbookTest.php
Same as https://github.com/ezsystems/ezpublish-kernel/pull/1572
Just to let Travis execute tests on master.
=> EZP-25448: RichText field does not accept element with 2 classes

bin/.travis/prepare_unittest.sh, eZ/Publish/Core/MVC/Symfony/View/ContentView.php, eZ/Publish/Core/MVC/Symfony/View/Tests/ContentViewTest.php, eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php
> status: ready to be merged
> Fixes http://jira.ez.no/browse/EZP-25294 on master
Master merge of https://github.com/ezsystems/ezpublish-kernel/pull/1581
Fixes [EZP-25294](http://jira.ez.no/browse/EZP-25294) (null location in content view templates). Also contains improvements to the `prepare_unittests.sh` script for solr.
=> Merge #1581 to master

eZ/Bundle/EzPublishCoreBundle/Resources/config/fos_http_cache.yml
Fix regression caused by EZP-25204 , JIRA: https://jira.ez.no/browse/EZP-25476
This takes #1582 by @wizhippo, rebased to / PR against 6.1
ping @bdunogier @andrerom
=> Fix EZP-25476: Return User hash headers vary to default

data/cleandata.sql
**JIRA ticket related:** https://jira.ez.no/browse/EZP-25522
=> EZP-25522: User is not able to get variation of his profile image

doc/specifications/rest/REST-API-V2.rst, eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php, eZ/Publish/Core/REST/Server/Controller/Role.php
> Fixes https://jira.ez.no/browse/EZP-25516
Also remove draftByRoleId and policiesByRoleDraft routes, let the Role REST controller deal with role IDs as if there were no draft IDs.
=> Fix EZP-25516: Update REST spec with role draft features, fix inconsistencies

eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Authentication.php
> Re-post of #1614 against 6.1
=> BDD: improved feedback on session creation errors

eZ/Publish/API/Repository/Tests/FieldType/PageIntegrationTest.php, eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/PageConverter.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/PageTest.php, eZ/Publish/SPI/Tests/FieldType/PageIntegrationTest.php
https://jira.ez.no/browse/EZP-25413
=> Page FieldType custom attributes write support

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
See https://github.com/sensiolabs/SensioDistributionBundle/commit/964a56e855acac38d4a81920b3a86543f7e8492f
=> EZP-25720: Update type hint to use the proper event class

eZ/Publish/Core/FieldType/Tests/FieldTypeMockTest.php
Related to JIRA ticket: 
https://jira.ez.no/browse/EZP-25831
I think that this PR is some how urgent because wihtout this all of our pull request on travis for php version 7 are failing.
=> EZP-25831: Fix php 7 tests.

doc/specifications/io/legacy_dfs_cluster.md
=> Fix wrong example for Legacy DFS cluster config

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php, eZ/Publish/Core/Search/Common/Slot/UpdateLocation.php, eZ/Publish/Core/settings/search_engines/slots.yml
https://jira.ez.no/browse/EZP-25835
There were no signals fired after location update so we need to implement those to handle reindexing well.
=> EZP-25835: Reindex location on update

doc/specifications/rest/REST-API-V2.rst, doc/specifications/rest/xsd/Content.xsd, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php
> Implements [EZP-25842](https://jira.ez.no/browse/EZP-25842)
Not much to add. Value object visitor unit test and specifications have been updated.
=> EZP-25842: Added current version number to REST content info

eZ/Publish/Core/REST/Server/Input/Parser/Criterion/UserMetadata.php, eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/UserMetadataTest.php
> Implements https://jira.ez.no/browse/EZP-25777
> Based on https://github.com/ezsystems/ezpublish-kernel/pull/1650 by @Nattfarinn
Adds a unit test to @Nattfarinn's criterion handler.
=> EZP-25777 UserMetadata criterion handling in REST Views

.travis.yml, bin/.travis/composer-auth.json, bin/.travis/prepare_behat.sh, bin/.travis/prepare_rest_functional_tests.sh, bin/.travis/prepare_unittest.sh, eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
> Depends on https://github.com/ezsystems/ezplatform/pull/119
To:
- Improve speed, especially on anything involving mysql
- move to use docker containers for functional tests, to:
- to avoid having to create complex custom scripts yet again, just for travis
- so we can run tests locally as well soon
=> [Travis] Change to use trusty env for testing

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
https://jira.ez.no/browse/EZP-25915
On bundle changes when switching branches, triggered when loading container when trying to clear cache.
This will need change in ezplatform `composer.json` to take advantage of this.
=> EZP-25915: Avoid RunTimeException on composer update/install

.travis.yml
Ref: https://github.com/ezsystems/ezplatform/commit/987a9dc6ab0e6f455dbdf34640f82e8ec9fcab11
Merging once travis agrees to unblock other PR's.
=> [Travis] Adjust docker use after simplification done on ezplatform repo.

.travis.yml, bin/.travis/prepare_unittest.sh, eZ/Publish/API/Repository/Tests/Regression/EnvTest.php, eZ/Publish/API/Repository/Tests/SetupFactory.php, eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php, eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/SetupFactory.php, eZ/Publish/Core/settings/containerBuilder.php, eZ/Publish/Core/settings/storage_engines/cache.yml
Status: **WIP**
Context: *To try to figure out why a behat test is failing with Redis: https://github.com/ezsystems/ezplatform/pull/123*
=> [Travis] Run one integration test with Redis to verify integrity

Readme.md
Minor, text-only changes to improve the README copy.
=> Grammatical and spelling corrections

data/cleandata.sql
Changed default link URLs to point to our new documentation.
=> URLs updated

.travis.yml
Elapsed time for unit tests on PHP7:
- Uncached:  2 min 33 sec
- Cached   : 1 min 47 sec
=> [Travis] Enable cache of composer packages

eZ/Publish/API/Repository/ContentService.php, eZ/Publish/API/Repository/UserService.php, eZ/Publish/Core/Repository/ContentService.php, eZ/Publish/Core/Repository/UserService.php, eZ/Publish/Core/Search/Common/Slot/DeleteContent.php, eZ/Publish/Core/Search/Common/Slot/DeleteUser.php, eZ/Publish/Core/Search/Common/Slot/DeleteUserGroup.php, eZ/Publish/Core/Search/Common/Slot/DeleteVersion.php, eZ/Publish/Core/Search/Common/Slot/Trash.php, eZ/Publish/Core/Search/Elasticsearch/Content/Handler.php, eZ/Publish/Core/SignalSlot/ContentService.php, eZ/Publish/Core/SignalSlot/Signal/ContentService/DeleteContentSignal.php, eZ/Publish/Core/SignalSlot/Signal/TrashService/TrashSignal.php, eZ/Publish/Core/SignalSlot/Signal/UserService/DeleteUserGroupSignal.php, eZ/Publish/Core/SignalSlot/Signal/UserService/DeleteUserSignal.php, eZ/Publish/Core/SignalSlot/TrashService.php, eZ/Publish/Core/SignalSlot/UserService.php
Issue: https://jira.ez.no/browse/EZP-26186
Todo:
- ~~Add additional integration tests~~ Moved to https://jira.ez.no/browse/EZP-26219
=> EZP-26186: Some signals are not correctly sent leaving Solr index out of sync

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
Ommits coverage for DeleteUser[Group] for backport as it will cause issues for dependnecies for solrBundle 1.0.
=> EZP-26186: Add integration tests for cases solved in #1759 for 6.3

eZ/Publish/API/Repository/Tests/SearchServiceTest.php, eZ/Publish/Core/Search/Elasticsearch/Content/CriterionVisitor/FullText.php
This PR resolves https://jira.ez.no/browse/EZP-26141
https://github.com/ezsystems/ezpublish-kernel/pull/1770 reopened against `6.3`
=> EZP-26141: Search appears to conduct some form of 'OR' search not and 'AND' search

eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
> Fixes [EZP-26356](http://jira.ez.no/browse/EZP-26356)
=> Fix EZP-26356: exception in rest parser exception handling

eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Exception.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ContentFieldValidationExceptionTest.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ExceptionTest.php
> Implements EZP-26472
Adds previous exceptions to ErrorMessage responses. Multiple level of previous are supported, and will be nested.
Before:
```
{
"ErrorMessage": {
"_media-type": "application\/vnd.ez.api.ErrorMessage+json",
"errorCode": 500,
"errorMessage": "Internal Server Error",
"errorDescription": "A DBAL error occured while writing var\/site\/storage\/images\/4\/8\/3\/0\/384-1-eng-GB\/thumb_IMG_3164_1024.jpg",
"trace": "#0 \/Users\/bdunogier\/ezplatform\/vendor\/ezsystems\/ezpublish-kernel\/eZ\/Publish\/Core\/IO\/IOService.php(131): eZ\\Publish\\Core\\IO\\IOMetadataHandler\\LegacyDFSCluster->create(Object(eZ\\Publish\\SPI\\IO\\BinaryFileCreateStruct))\n#1 \/Users\/bdunogier\/ezplatform\/app\/cache\/dev\/appDevDebugProjectContainer.php(46018): …
```
=> Added previous exception to the REST exception output

eZ/Publish/Core/REST/Server/Controller/Content.php
> Fixes [EZP-26445](http://jira.ez.no/browse/EZP-26445)
Disables HTTP cache on versions list and on draft versions.
=> Disabled HTTP caching on REST content draft load

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php, eZ/Publish/API/Repository/SearchService.php, eZ/Publish/API/Repository/SearchServiceSortClause.php, eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php, eZ/Publish/Core/Repository/LocationService.php, eZ/Publish/Core/Repository/Mapper/Readme.md, eZ/Publish/Core/Repository/Mapper/SortClauseMapper.php, eZ/Publish/Core/Repository/Repository.php, eZ/Publish/Core/Repository/SearchService.php, eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php, eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php, eZ/Publish/Core/Repository/UserService.php, eZ/Publish/Core/SignalSlot/SearchService.php, eZ/Publish/Core/settings/repository.yml
Implementation of the idee from https://github.com/ezsystems/ezpublish-kernel/pull/1634
JIRA: https://jira.ez.no/browse/EZP-26528
=> EZP-26528: SortClauseMapper for LocationService / UserService

eZ/Bundle/EzPublishDebugBundle/Collector/SiteAccessCollector.php, eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml, eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/siteaccess/panel.html.twig, eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/siteaccess/toolbar.html.twig
> [EZP-26375](https://jira.ez.no/browse/EZP-26375)
=> Implement EZP-26375: Add siteaccess collector to debug toolbar

doc/specifications/misc/query_types.md, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
> [EZP-26628](https://jira.ez.no/browse/EZP-26628)
Allow any QueryType class to be registered as a new instance by specifying the 'alias' tag attribute.
A typical use-case would be when a QueryType uses a location id (location children) or content type identifier from a container parameter
```yaml
parameters:
app.query_type.latest_content.class: AppBundle\QueryType\LatestContent
services:
app.query_type.latest_articles:
class: '%app.query_type.latest_content.class%'
arguments:
- '%app.content_type_identifiers.article%'
tags:
- {name: ezpublish.query_type, alias: latest_articles}
app.query_type.latest_blog_posts:
class: '%app.query_type.latest_content.class%'
arguments:
- '%app.content_type_identifiers.blog_post%'
tags:
- {name: ezpublish.query_type, alias: latest_blog_posts}
```
It makes …
=> Implemented QueryType override

eZ/Publish/Core/IO/Exception/InvalidBinaryAbsolutePathException.php, eZ/Publish/Core/IO/Exception/InvalidBinaryFileIdException.php, eZ/Publish/Core/IO/Exception/InvalidBinaryPrefixException.php, eZ/Publish/Core/IO/IOService.php, eZ/Publish/Core/IO/TolerantIOService.php, eZ/Publish/Core/IO/UrlDecorator/Prefix.php
Attempt to fix comments by @bdunogier in #1834.
=> EZP-26683: Make IO exceptions more user friendly, take i18n

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
This will alow me to style https://jira.ez.no/browse/EZP-26662
=> EZP-26647: add css class on field definition settings for design

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php, eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php, eZ/Publish/Core/Search/Elasticsearch/Content/Mapper/StandardMapper.php
This PR resolves https://jira.ez.no/browse/EZP-26707
Only tests here, should pass when https://github.com/ezsystems/ezplatform-solr-search-engine/pull/74 is merged to master.
=> EZP-26707: Search with Solr does not respect isSearchable setting of fields

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Publish/Core/REST/Common/FieldTypeProcessor/BaseRelationProcessor.php, eZ/Publish/Core/REST/Common/FieldTypeProcessor/RelationListProcessor.php, eZ/Publish/Core/REST/Common/FieldTypeProcessor/RelationProcessor.php, eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RelationListProcessorTest.php, eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RelationProcessorTest.php
https://jira.ez.no/browse/EZP-24994
=> EZP-24994: Fix "Default Location" for REST API

bin/.travis/prepare_behat.sh, composer.json
https://github.com/ezsystems/PlatformUIBundle/pull/755
=> Make sure to checkout the correct ezplatform branch to run behat tests

.travis.yml, bin/.travis/prepare_unittest.sh
_if this does not work, try to downgrade composer to 1.2.2 on travis_
=> [Travis] Try to get Solr dependnecy to resolve

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
...when they have the same name and the same parent
=> Fix EZP-26742: allow concurrent creation of many contents

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
This PR resolves https://jira.ez.no/browse/EZP-26756
Related PR: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/80
FieldRelation is not handled in Location search when using Solr search engine.
=> EZP-26756: FieldRelation is not handled in Solr Location search

eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
This simply enables full text search tests for Legacy search engine.
=> Enable full text field type tests for Legacy engine

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php, eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php, eZ/Bundle/EzPublishCoreBundle/Tests/Translation/GlobCollectorTest.php, eZ/Bundle/EzPublishCoreBundle/Translation/Collector.php, eZ/Bundle/EzPublishCoreBundle/Translation/GlobCollector.php
Jira : https://jira.ez.no/browse/EZP-26835
Add TranslationPass to load every ezplatform translation files into translator.
Translation package will be present as composer dependencies with this pattern : 'vendor/ezplatform-i18n-[locale]
Unit test
=> EZP-26835 : add TranslationPass to load every ezplatform translation

eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineIndexerFactory.php
Jira : https://jira.ez.no/browse/EZP-26835
Remove @note from phpdoc
=> EZP-26835 : fix @note phpdoc (breaks translation extraction)

data/mysql/dfs_schema.sql, eZ/Bundle/PlatformInstallerBundle/src/Installer/CleanInstaller.php
> [EZP-26482](https://jira.ez.no/browse/EZP-26482)
=> Fix EZP-26482: add ezdfsfile to MySQL schema.sql

eZ/Publish/Core/FieldType/DateAndTime/Type.php
Suggestion @glye, feel free to rebase / squash this into your commit if you pull this in.
=> [PR of PR] Fix api doc on DateTime FieldType

eZ/Publish/Core/Repository/Values/ContentType/ContentType.php
JIRA: https://jira.ez.no/browse/EZP-26903
=> Fix EZP-26903: ContentType::getDescription incorrect usage of isset() function

bin/extract-translations.sh, eZ/Bundle/EzPublishCoreBundle/Resources/translations/fieldtypes.en.xlf, eZ/Bundle/EzPublishCoreBundle/Resources/translations/messages.en.xlf, eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
Jira: https://jira.ez.no/browse/EZP-26835
Simplify sed command to clean file reference + make path relative
+ fix fieldtypes source
=> EZP-26835 : Fix file reference in extract translations + update files

eZ/Bundle/EzPublishCoreBundle/Resources/translations/fielddefinition.en.xlf, eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
Jira : https://jira.ez.no/browse/EZP-26699
Translate field definition blocks
After this PR is merge, todo : synchronize ezplatform-18n
=> EZP-26699 : translate fielddefinition

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/AsseticPass.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FragmentPass.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RouterPass.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SecurityPass.php, eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/session.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml, eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml, eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml, eZ/Publish/Core/settings/storage_engines/legacy/language.yml
review ping @bdunogier @alongosz @Nattfarinn
=> [Symfony 3.x] Fixes for Symfony 3 compatibility

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Publish/API/Repository/Tests/ContentServiceTest.php
> Issue: https://jira.ez.no/browse/EZP-26988
> Followup on https://github.com/ezsystems/ezpublish-kernel/pull/1905
=> [Sf3.x][YML] EZP-26988: Remove use of router.class parameter

eZ/Bundle/EzPublishCoreBundle/FieldType/Page/PageService.php
jira : https://jira.ez.no/browse/EZP-26967 for 6.7
Missing statement for 'UnauthorizedException' in PageService.php
=> EZP-26967: Missing statement in PageService.php

eZ/Bundle/EzPublishCoreBundle/FieldType/Page/PageService.php
jira: https://jira.ez.no/browse/EZP-26967
=> EZP-26967: Missing statement in PageService.php 6.8

eZ/Bundle/EzPublishCoreBundle/FieldType/Page/PageService.php
jira: https://jira.ez.no/browse/EZP-26967
=> EZP-26967: Missing statement in PageService.php (master)

eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
=> Ran CS fixer.

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
Small improvement to try to give some better hints on how to resolve issues when using installer.
For instance the typical case where people try to install demo on clean or opposite.
=> EZP-27256: Installer could be more helpful on errors

eZ/Publish/API/Repository/Tests/Common/FacetedSearchProvider.php, eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php, eZ/Publish/API/Repository/Tests/SearchServiceTest.php
Will be marked as incomplete until: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/91
=> EZP-27327: Add Integration testing of Facets on Location Search

doc/bc/changes-6.10.md, eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php, eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/MapperTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_content_from_rows_result.php, eZ/Publish/Core/Repository/Helper/DomainMapper.php, eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php, eZ/Publish/SPI/Persistence/Content/VersionInfo.php
> Issue: https://jira.ez.no/browse/EZP-27420
=> EZP-27420: Use language code's over id's for SPI VersionInfo

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Publish/Core/REST/Common/FieldTypeProcessor/UserProcessor.php
**Ticket:** https://jira.ez.no/browse/EZP-27399
=> EZP-27399: Prevent password hash being returned in by rest

eZ/Publish/API/composer.json, eZ/Publish/SPI/composer.json
The split script should be updated to include the 7.0 branch (and the same files updated on the 7.0 branch as well).
=> Updated API and SPI composer.json

eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php, eZ/Publish/API/Repository/Values/Content/VersionInfo.php, eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php, eZ/Publish/Core/MVC/Symfony/FieldType/RichText/Renderer.php, eZ/Publish/Core/REST/Server/Controller/Content.php, eZ/Publish/Core/Repository/ContentService.php, eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php, eZ/Publish/Core/Repository/Tests/Values/Content/VersionInfoTest.php
=> EZP-27473: Add methods to allow checking of version statuses

eZ/Publish/Core/Repository/Tests/Values/User/UserGroupTest.php, eZ/Publish/Core/Repository/Tests/Values/User/UserTest.php, eZ/Publish/Core/Repository/Values/User/User.php, eZ/Publish/Core/Repository/Values/User/UserGroup.php
Some cleanup on user properties in regards to how internal properties are handled.
=> Minor User & UserGroup properties fixes

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/js_routing.yml, eZ/Bundle/EzPublishCoreBundle/Routing/JsRouting/ExposedRoutesExtractor.php
> https://jira.ez.no/browse/EZP-27359
=> EZP-27359: Fully integrate FOSJsRoutingBundle

eZ/Publish/Core/settings/fieldtypes.yml, eZ/Publish/Core/settings/indexable_fieldtypes.yml
> Issue: https://jira.ez.no/browse/EZP-27601
=> EZP-27601: Solr Indexing fails on legacy field types registered as "Null Types"

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml, eZ/Publish/Core/REST/Server/Input/Parser/Criterion.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/ContentTypeParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/CriterionParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/DateRangeParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/FieldParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/FieldRangeParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/LocationParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/SectionParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/TermParser.php, eZ/Publish/Core/REST/Server/Input/Parser/FacetBuilder/UserParser.php, eZ/Publish/Core/REST/Server/Input/Parser/Query.php, eZ/Publish/Core/REST/Server/Tests/Input/Parser/FacetBuilder/FacetBuilderBaseTest.php, eZ/Publish/Core/REST/Server/Tests/Input/Parser/FacetBuilder/FacetBuilderParserTest.php
Ticket related: https://jira.ez.no/browse/EZP-27295
ToDo:
=> EZP-27295: Add support for Search facets in REST API

eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/Core/Persistence/Cache/ContentHandler.php, eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
=> [7.0][Cache] Invalidate version list on new draft

eZ/Bundle/EzPublishCoreBundle/Routing/DefaultRouter.php
JIRA: https://jira.ez.no/browse/EZP-27652
=> Fix EZP-27652: Router have wrong context after language switcher link

eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php
Fixing deprecation notices in `ViewController` as they are inconsistent.
=> Added deprecation doc of already deprecated view actions

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php, eZ/Publish/Core/Search/Common/Slot/RemoveTranslation.php, eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml, eZ/Publish/Core/settings/search_engines/legacy/slots.yml
Implements [EZP-27712](https://jira.ez.no/browse/EZP-27712)
----
This PR adds search slot reindexing content on `RemoveTranslationSignal` added in #2031
**TODO**:
=> EZP-27712: As a Developer I want Search to handle RemoveTranslationSignal

eZ/Publish/API/Repository/Tests/BaseTest.php
|   |  |
| ------------- | ------------- |
| Target branch  | **master**  |
| Related PR  | ezsystems/ezplatform-solr-search-engine#103  |
As the result of a discussion in the ezsystems/ezplatform-solr-search-engine#103 PR, there's no need to refactor anything in this package.
This PR includes minor exception message improvement when `SetupFactory` is missing.
**TODO**:
- ~Align SolrBundle SetupFactory FQCN references with changes from ezsystems/ezplatform-solr-search-engine#103~
- ~Discuss backporting this to `6.7`~
=> EZP-27916: Improved exception message on missing SetupFactory

bin/.travis/prepare_unittest.sh, eZ/Publish/API/Repository/Tests/SearchServiceFulltextTest.php, eZ/Publish/API/Repository/Values/Content/Query/Criterion/FullText.php, phpunit-integration-legacy-solr.xml
Kernel counterpart of https://github.com/ezsystems/ezplatform-solr-search-engine/pull/95
=>  EZP-26806: Improve fulltext search query syntax

doc/specifications/rest/REST-API-V2.rst, eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml, eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php, eZ/Publish/Core/REST/Server/Controller/Content.php, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/VersionInfo.php, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/VersionTranslationInfo.php, eZ/Publish/Core/REST/Server/Values/VersionTranslationInfo.php
|  |  |
| --- | --- |
| Status:  | **Ready for a review**  |
| Target branch: | [master](https://github.com/ezsystems/ezpublish-kernel/tree/master) |
| PAPI PR:    | #2081 |
| REST endpoint: | `/content/objects/<ID>/versions/<versionNo>/translations/<languageCode>` |
| HTTP method: | `DELETE` |
This PR implements REST endpoint which allows deleting Translation, specified by language code, from a Content Object Version **Draft**.
After review and many considerations, the final version of this REST endpoint simply does the same thing as PHP API - removes Translation from a previously prepared Draft.
Constraints:
- REST API Consumer has to create Draft prior to passing it to this endpoint.
- If the removed Translation is the main one, REST API Consumer MUST update it to another one prior to …
=> EZP-27864: As a REST Consumer I want to remove translation from a single Version

composer.json
This PR sets branch-alias to `6.13.x-dev`
=> [Composer] Set master to 6.13.x-dev

eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php, eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php, eZ/Publish/Core/Persistence/Cache/Tests/ObjectStateHandlerTest.php
> https://jira.ez.no/browse/EZP-28148
ping @gggeek 
Yes the test fails without the fix ;)
=> EZP-28148: Fix regression on loading all State (group) cache not getting update

eZ/Publish/API/Repository/Tests/TrashServiceTest.php
Small fix from https://github.com/ezsystems/ezpublish-kernel/pull/2146
=> Removed unused User 'use'

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
On request of @DavidLiedle on Slack.
=> Update welcome message performance URL

eZ/Publish/Core/Repository/ContentService.php
https://jira.ez.no/browse/EZP-28319
=> EZP-28319: Take into consideration subtree limits in loadReverseRelations

doc/bc/changes-6.13.md, eZ/Bundle/EzPublishCoreBundle/Resources/config/storage_engines.yml, eZ/Publish/Core/Persistence/Database/DatabaseHandler.php, eZ/Publish/Core/Persistence/Database/DeleteQuery.php, eZ/Publish/Core/Persistence/Database/Expression.php, eZ/Publish/Core/Persistence/Database/InsertQuery.php, eZ/Publish/Core/Persistence/Database/Query.php, eZ/Publish/Core/Persistence/Database/QueryException.php, eZ/Publish/Core/Persistence/Database/SelectQuery.php, eZ/Publish/Core/Persistence/Database/UpdateQuery.php, eZ/Publish/Core/Persistence/Doctrine/AbstractDoctrineQuery.php, eZ/Publish/Core/Persistence/Doctrine/ConnectionHandler.php, eZ/Publish/Core/Persistence/Doctrine/DeleteDoctrineQuery.php, eZ/Publish/Core/Persistence/Doctrine/DoctrineExpression.php, eZ/Publish/Core/Persistence/Doctrine/InsertDoctrineQuery.php, eZ/Publish/Core/Persistence/Doctrine/SelectDoctrineQuery.php, eZ/Publish/Core/Persistence/Doctrine/SubselectDoctrineQuery.php, eZ/Publish/Core/Persistence/Doctrine/UpdateDoctrineQuery.php, eZ/Publish/Core/settings/storage_engines/common.yml
=> [BC] Deprecate Zeta Database abstraction layer

eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php, eZ/Publish/Core/Persistence/Cache/URLHandler.php
> JIRA: https://jira.ez.no/browse/EZP-28480
SPI cache for URL Handler in 7.0
=> EZP-28480: SPI cache for URL Handler in 7.0

composer.json, eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/URLHandlerPass.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/UrlChecker.php, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php, eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/url_checker.yml, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/URLHandlerPassTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/URLChecker/URLCheckerTest.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/AbstractURLHandler.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/HTTPHandler.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/MailToHandler.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/URLChecker.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/URLCheckerInterface.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/URLHandlerInterface.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/URLHandlerRegistry.php, eZ/Bundle/EzPublishCoreBundle/URLChecker/URLHandlerRegistryInterface.php
> JIRA: https://jira.ez.no/browse/EZP-28505
This PR contains impl. of command to validate external links.
=> EZP-28505: As a Maintainer I want command to validate external URLs

eZ/Publish/Core/Persistence/Cache/UserHandler.php
jira issue: https://jira.ez.no/browse/EZP-28695
=> EZP-28695: update cache key to support email address as username

eZ/Publish/API/Repository/Tests/LocationServiceTest.php, eZ/Publish/Core/Repository/Helper/DomainMapper.php, eZ/Publish/Core/Repository/LocationService.php
> JIRA: https://jira.ez.no/browse/EZP-28665
This PR defines and adds a validation of minimum and maximum value for location priority as `<-2147483648;2147483647>`
> 2. Add new Content Object under root Content Object.
> 3. In the Platform UI, navigate to the root Content Object.
> 4. In the Sub-items list, change the priority of the previously created Content Object to 999999999999999999999999999999999999999999999999999999999999 and confirm. 
> 5. Backend will return response with status 500 "Internal Server Error" (details in JIRA ticket)
=> EZP-28665: Validation of the location priority range

bootstrap.php, composer.json, eZ/Bundle/EzPublishCoreBundle/Tests/Translation/GlobCollectorTest.php, eZ/Publish/API/Repository/Tests/Regression/EZP22958SearchSubtreePathstringFormatTest.php, eZ/Publish/API/Repository/Tests/Values/User/Limitation/ObjectStateLimitationTest.php, eZ/Publish/API/Repository/Tests/Values/User/Limitation/OwnerLimitationTest.php, phpunit-functional-rest.xml, phpunit-integration-legacy-elasticsearch.xml, phpunit-integration-legacy-solr.xml, phpunit-integration-legacy.xml, phpunit-integration-rest-json.xml, phpunit-integration-rest-xml.xml, phpunit.xml
This PR enables PHPUnit v6 support for this repo.
=> PHPUnit v6 support

eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php, eZ/Publish/Core/Repository/Tests/Service/Mock/NameSchemaTest.php, eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionsCriterionHandlerTest.php, eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
Updated class constants in:
* DomainMapperTest
* NameSchemaTest
* PermissionsCriterionHandlerTest
* UserTest
=> Class constants in Core\Repository tests part 2

.github/pull_request_template.md
|   |   |
| ------------------ | ------------------ |
| **Target branch** | `6.7`, `6.13`, `7.0` and `master` |
This Pull Request adds a GitHub Pull Request template which would be used for every new PR. 
It follows [this doc](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and it's done in a similar way like the ezsystems/ezplatform-admin-ui#95 with changes specific to `ezpublish-kernel`.
**TODO**:
=> [GitHub] Added Pull Request template

eZ/Bundle/EzPublishIOBundle/DependencyInjection/Configuration.php, eZ/Bundle/EzPublishIOBundle/Tests/DependencyInjection/ConfigurationFactory/BinarydataHandler/FlysystemTest.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Authentication.php, eZ/Publish/API/Repository/Tests/URLServiceAuthorizationTest.php, eZ/Publish/API/Repository/Tests/URLServiceTest.php, eZ/Publish/API/Repository/Tests/UserServiceTest.php, eZ/Publish/Core/Base/ServiceContainer.php, eZ/Publish/Core/FieldType/Image/IO/Legacy.php, eZ/Publish/Core/FieldType/Page/Value.php, eZ/Publish/Core/FieldType/Tests/AuthorTest.php, eZ/Publish/Core/FieldType/Tests/PageTest.php, eZ/Publish/Core/MVC/Symfony/View/Builder/ParametersFilter/RequestAttributes.php, eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/ValueObjectsIds.php, eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/TimeConverter.php, eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php, eZ/Publish/Core/REST/Common/Input/ParsingDispatcher.php, eZ/Publish/Core/REST/Common/Tests/Output/ValueObjectVisitorBaseTest.php, eZ/Publish/Core/REST/Server/Controller.php, eZ/Publish/Core/Repository/TrashService.php, eZ/Publish/Core/Repository/UserService.php, eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
Minor code tweaks:
- dead code
- mkdir race condition
- sprintf pattern fix
- random API usage tweaks
=> SCA with Php Inspections (EA Ultimate)

doc/specifications/rest/REST-API-V2.rst, eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/LocationTest.php, eZ/Publish/Core/REST/Server/Controller/Location.php
| **JIRA issue**     | [EZP-28801](https://jira.ez.no/browse/EZP-28801)
| **Doc needed**     | no, specification update included in PR
This PR allows translating URL alias into a location with urlAlias parameter provided.
**TODO**:
=> EZP-28801: As a REST consumer, I want to get the location that matches an URL alias

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php, eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php, eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler/Keyword.php, eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
| **JIRA issue**     | [EZP-28843](https://jira.ez.no/browse/EZP-28843)
This is bugfix / Improvement for https://github.com/ezsystems/ezpublish-kernel/pull/2239
**TODO**:
=> EZP-28843: As a Developer I want SQL Search by Field to use ezkeyword Ext. Storage

eZ/Publish/Core/Persistence/Cache/ContentHandler.php, eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
| **JIRA issue**     | [EZP-28853](https://jira.ez.no/browse/EZP-28853)
`VersionInfo` object from persistence is not cached in persistent cache on eZ kernel 6.x.
We use `ContentService::loadVersionInfoById` intensively, which has a result of generating a large volume of uncached database queries, on larger sites thousands of them which slows down the site considerably.
This PR adds `VersionInfo` to persistence cache and triggers clearing said cache in relevant places.
**Note 1**
When merging from `6.7` to `6.13`, relevant cache clear …
=> EZP-28853: Add VersionInfo to persistence cache

composer.json, eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php, eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
| **JIRA issue**     | none
| **Bug/Improvement**| Improvement
| **Target version** |`master`
This PR enables install of PHPUnit v7.
=> Use PHPUnit v7

eZ/Publish/Core/FieldType/Tests/UserTest.php, eZ/Publish/Core/FieldType/User/Type.php, eZ/Publish/Core/settings/fieldtypes.yml, eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
| **JIRA issue**     | [EZP-28902](https://jira.ez.no/browse/EZP-28902)
| **Related PR** | ezsystems/repository-forms#224
**TODO**:
=> EZP-28902: Creating a user with existing username results in Internal Server Error.

eZ/Bundle/EzPublishRestBundle/Routing/OptionsLoader/Mapper.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/HttpOptionsTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Routing/OptionsLoader/MapperTest.php, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Options.php
| **JIRA issue**     | [EZP-28962](https://jira.ez.no/browse/EZP-28962)
| **Related PR** | ezsystems/ezplatform#279
| **Target version** | `7.1`
| **Tests pass**     | yes, but require ezsystems/ezplatform#279
This PR fixes REST Controller name set for OPTIONS method.
**TODO**:
=> EZP-28962: Fixed REST OPTIONS Controller name

eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php, eZ/Publish/Core/Persistence/Cache/TrashHandler.php
| **JIRA issue**     | [EZP-28680](https://jira.ez.no/browse/EZP-28680)
**TODO**:
=> EZP-28680: Error 500 after restoring related item in another location

eZ/Bundle/EzPublishDebugBundle/Twig/DebugTemplate.php
| **JIRA issue**     | No need?
| **Target version** | `6.x`/`7.x`
When using eZ Design Engine, sometimes it is very hard to find which templates are exactly used to render the page, since only logical name is displayed in HTML output.
This changes the output to display the real path to the used template.
Before:
After:
**TODO**:
=> Display real template names in debug output

eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
| **JIRA issue**     | [EZP-29077](https://jira.ez.no/browse/EZP-29077)
After EZP-28143 it could be, that searches in sudo closure use cached permissions from non sudo user.
**TODO**:
=> Fix EZP-29077: CachedPermissionService doesn't consider sudo

eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php, eZ/Publish/API/Repository/Tests/SearchServiceTest.php, eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/Field.php
| **JIRA issue**     | [EZP-28863](https://jira.ez.no/browse/EZP-28863)
Not sure if should target master or 7.x, it is bugfix but for relatively new feature.
**TODO**:
=> EZP-28863: REST search error for searching fields with the same name

eZ/Bundle/EzPublishCoreBundle/Command/CopySubtreeCommand.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
| **JIRA issue**     | [EZP-29062](https://jira.ez.no/browse/EZP-29062)
**TODO**:
=> EZP-29062: Implemented ezplatform:copy-subtree command

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
we need a database to `ezplatform:install`
=> Installer - create database if it does not exist

composer.json, eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ImaginePass.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
| **Bug/Improvement**| yes?
Bumps Liip Imagine Bundle to v2 which has proper support for Symfony 3.x/4.x
=> Bump Liip Imagine Bundle to 2.0

doc/specifications/rest/REST-API-V2.rst, eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml, eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml, eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/BookmarkTest.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php, eZ/Publish/Core/REST/Server/Controller/Bookmark.php, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/BookmarkList.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/BookmarkListTest.php, eZ/Publish/Core/REST/Server/Values/BookmarkList.php
| **JIRA issue**     | [EZP-29147](https://jira.ez.no/browse/EZP-29147)
**TODO**:
=> EZP-29147: As a developer, I want a REST API to manage bookmarks

eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/Location.php
JIRA: https://jira.ez.no/browse/EZP-28789
=> Fix EZP-28789: Warning in LocationId Matcher if Content has no Location

eZ/Publish/Core/Repository/SiteAccessAware/NotificationService.php, eZ/Publish/Core/Repository/SiteAccessAware/Repository.php, eZ/Publish/Core/settings/repository/siteaccessaware.yml
| **JIRA issue**     | [EZP-29340](https://jira.ez.no/browse/EZP-29340)
| **Bug**| yes
**TODO**:
=> EZP-29340: Added NotificationService as a part of SiteAccessAware Repository layer

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
Update welcome text to:
1. reflect the composer script alias for install
2. reflect simplifications on install text
=> [Composer] Update create-project welcome text

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ImaginePass.php, eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php, eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php, eZ/Publish/API/Repository/Tests/LocationServiceTest.php, eZ/Publish/Core/FieldType/Country/Value.php, eZ/Publish/Core/FieldType/Date/Type.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElement2Test.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Notification/Gateway/DoctrineDatabaseTest.php, eZ/Publish/Core/Repository/ContentService.php
Php Inspections (EA Ultimate): new findings
=> [minor] SCA

eZ/Publish/Core/Persistence/Legacy/Notification/Gateway/DoctrineDatabase.php
| **JIRA issue**     | [EZP-29447](https://jira.ez.no/browse/EZP-29447)
**TODO**:
=> EZP-29447: Fix number of pending notifications for current user

eZ/Publish/API/Repository/Tests/RoleServiceTest.php, eZ/Publish/Core/Persistence/Cache/UserHandler.php
| **JIRA issue**     | [EZP-29083](https://jira.ez.no/browse/EZP-29083)
| **Target version** | `7.2` 
Cache related to role-assignment wasn't invalidated when editing policies list.
**TODO**:
=> EZP-29083: Error after trying to delete role assignment

eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
| **JIRA issue**     | [EZP-29536](https://jira.ez.no/browse/EZP-29536)
This is a PR with the same code as in https://github.com/ezsystems/ezpublish-kernel/pull/2424, which has been merged too early.
=> Test case for ContentViewBuilder

eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
| **JIRA issue**     | [EZP-29581](https://jira.ez.no/browse/EZP-29581)
Currently, to clear image variation caches, one must clear the entire cache, since the caches for variations are not tagged.
This adds various tags to image variation cache items to be able to clear them on demand.
**TODO**:
=> EZP-29581: Add cache tags to image variation cache

eZ/Bundle/EzPublishCoreBundle/Resources/translations/fieldtypes.en.xlf
| **JIRA issue**     | [EZP-29684](https://jira.ez.no/browse/EZP-29684)
[https://github.com/ezsystems/ezplatform-admin-ui/pull/654](https://github.com/ezsystems/ezplatform-admin-ui/pull/654)
[https://github.com/ezsystems/repository-forms/pulls](https://github.com/ezsystems/repository-forms/pulls)
**TODO**:
=> EZP-29684: Remove the hyphen from the "E-mail" in whole application

eZ/Publish/Core/Repository/ContentService.php
| **JIRA issue**     | [EZP-29695](https://jira.ez.no/browse/EZP-29695)
| **Target version** | `6.x`/`7.x`
**TODO**:
=> EZP-29695: Option "Default content availability" on content types not working

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php
| **Target version** | 7.2+
Needed for eZ Commerce, could also be used by EE.
**TODO**:
=> [Composer] Allow welcome message to be customized by project

eZ/Publish/Core/Repository/Helper/DomainMapper.php
**JIRA issue**: https://jira.ez.no/browse/EZP-29790
Done in code as there is no index on attribute.position table, and just joining will probably be slow in itself.
=> EZP-29790: [Integration tests] Sort fields to get rid of random Postgres failures

doc/bc/changes-7.4.md, eZ/Publish/API/Repository/ContentTypeService.php, eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php, eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php, eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php, eZ/Publish/Core/REST/Client/ContentTypeService.php, eZ/Publish/Core/Repository/ContentTypeService.php, eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php, eZ/Publish/Core/SignalSlot/ContentTypeService.php, eZ/Publish/Core/SignalSlot/Signal/ContentTypeService/RemoveContentTypeDraftTranslationSignal.php, eZ/Publish/Core/SignalSlot/Tests/ContentTypeServiceTest.php, eZ/Publish/SPI/Persistence/Content/Type/Handler.php
| **JIRA issue**     | [EZP-29788](https://jira.ez.no/browse/EZP-29788)
**TODO**:
=> EZP-29788: As a developer, I want to delete content type translation

eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml, eZ/Publish/Core/MVC/Symfony/Locale/Tests/UserLanguagePreferenceProviderTest.php, eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProvider.php, eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProviderInterface.php, eZ/Publish/Core/Repository/Values/MultiLanguageDescriptionTrait.php, eZ/Publish/Core/Repository/Values/MultiLanguageNameTrait.php
| **JIRA issue**     | [EZP-29932](https://jira.ez.no/browse/EZP-29932)
**TODO**:
=> EZP-29932: As a Developer I want list of Languages based on User's browser settings

eZ/Publish/Core/Base/Exceptions/InvalidArgumentType.php
| **JIRA issue**     | [EZP-30122](https://jira.ez.no/browse/EZP-30122)
Exception message is so not meaningful
**TODO**:
=> EZP-30122: Fix missing argumentName parameter in InvalidArgumentType exception

eZ/Publish/Core/Base/Exceptions/UnauthorizedException.php
| **JIRA issue**     | [EZP-30118](https://jira.ez.no/browse/EZP-30118)
| **Bug/Improvement**| Bug
| **Target version** | `6.7`, `6.13`, `7.3`, `7.4`, `master`
**TODO**:
=> EZP-30118: Fix typo in UnauthorizedException message

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/SortClauseTest.php
| **JIRA issue**     | [EZP-30146](https://jira.ez.no/browse/EZP-30146)
| **Target version** | `7.3`
**TODO**:
=> EZP-30146: Added missing LocationId SortClause REST Input Parser

eZ/Publish/API/Repository/Values/ContentType/FieldDefinition.php
Working with phpstan , i found this issue.
=> Missing type in @property-read documentation

eZ/Publish/Core/MVC/Symfony/FieldType/ImageAsset/ParameterProvider.php, eZ/Publish/Core/MVC/Symfony/FieldType/Tests/ImageAsset/ParameterProviderTest.php
| **JIRA issue**     | [EZP-30202](https://jira.ez.no/browse/EZP-30202)
**TODO**:
=> EZP-30202: Error to preview / publish content item with empty Image Asset field

eZ/Publish/API/Repository/Tests/RoleServiceTest.php, eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php, eZ/Publish/Core/Persistence/Cache/UserHandler.php
| **JIRA issue**     | [EZP-30322](https://jira.ez.no/browse/EZP-30322)
| **Bug**| yes
**TODO**:
=> EZP-30322: Fix list of users assigned to Role is not updated

eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php, eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage/Gateway/DoctrineStorage.php, eZ/Publish/Core/FieldType/Media/MediaStorage/Gateway/DoctrineStorage.php
| **JIRA issue**     | [EZP-30331](https://jira.ez.no/browse/EZP-30331)
| **Target version** | `7.3` 
Note for QA:
Please check save content before publishing, as there was bug with in in the past and that changes part of solution.
**TODO**:
=> EZP-30331: Cannot edit ezmedia properties after publishing

eZ/Publish/API/Repository/Tests/TrashServiceTest.php, eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php, eZ/Publish/Core/Persistence/Cache/TrashHandler.php
| **JIRA issue**     | [EZP-30314](https://jira.ez.no/browse/EZP-30314)
| **Target version** | `7.4`
**TODO**:
=> EZP-30314: Content is cached even after deletion

eZ/Publish/API/Repository/Values/Content/Location.php, eZ/Publish/Core/Repository/Helper/DomainMapper.php
| **JIRA issue**     | [EZP-30229](https://jira.ez.no/browse/EZP-30229) (Alternative approach)
**TODO**:
=> EZP-30229: Track original state of Location::$hidden

eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php, eZ/Publish/Core/Persistence/Legacy/Content/Handler.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php, eZ/Publish/Core/settings/storage_engines/legacy/content.yml
| **JIRA issue**     | [EZP-29694](https://jira.ez.no/browse/EZP-29694)
| **Required by** | ezsystems/ezplatform-admin-ui#950
Done as a part of fixing draft conflict version, to keep same behavior as in ezpublish.
**TODO**:
=> EZP-29694: Copied translations from published version to draft

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
| **Target version** | `7.5`+
This PR:
**TODO**:
=> [Tests] Fixed failing hide/reveal Content integration tests

eZ/Bundle/EzPublishCoreBundle/Features/Context/ConsoleContext.php, eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentPreviewContext.php, eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Authentication.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/ContentTypeGroup.php, eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/EzRest.php, eZ/Bundle/EzPublishRestBundle/behat_suites.yml
| **JIRA issue**     | https://jira.ez.no/browse/EZP-29858
| **Bug/Improvement**| n/a
| **New feature**    | n/a
| **Target version** | kernel 8.0 / eZ Platform 3.0
| **BC breaks**      | 1) new parameter in RestContext constructor 2) removed bits of unused code/Steps
Depends on: https://github.com/ezsystems/BehatBundle/pull/76
This is Stage 1 - adapting the tests to changes made in BehatBundle. Removing the dependency on EzContext and its traits.
Stage 2 (planned for 3.0) is moving PlatformBehatBundle and Behat parts of EzPublishRest bundle out of this repository, most likely to BehatBundle. 
TODO:
1) ~~Remove TMP commits before merging~~ - done
=> EZP-29858: Adjust tests for BehatBundle refactoring

eZ/Publish/Core/Search/Common/FieldRegistry.php
| **JIRA issue**     | [EZP-30458](https://jira.ez.no/browse/EZP-30458)
Added more descriptive exception message when implementation of `\eZ\Publish\SPI\FieldType\Indexable` is missing
**TODO**:
=> EZP-30458: Added more descriptive exception message

eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
| **JIRA issue**     | [EZP-29470](https://jira.ez.no/browse/EZP-29470)
Bug 🐛 / missing from #2407, as cache misses when there are exceptions where not tracked.
**TODO**:
=> EZP-29470: As a dev I also want cache miss trace of NotFound objects

eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/ContentLimitationsMixIntegrationTest.php, eZ/Publish/Core/Limitation/ContentTypeLimitationType.php, eZ/Publish/Core/Limitation/LocationLimitationType.php, eZ/Publish/Core/Limitation/ParentContentTypeLimitationType.php, eZ/Publish/Core/Limitation/ParentDepthLimitationType.php, eZ/Publish/Core/Limitation/ParentOwnerLimitationType.php, eZ/Publish/Core/Limitation/ParentUserGroupLimitationType.php, eZ/Publish/Core/Limitation/SubtreeLimitationType.php, eZ/Publish/Core/Limitation/Tests/ContentTypeLimitationTypeTest.php, eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php, eZ/Publish/SPI/Limitation/Target/Version.php, eZ/Publish/SPI/Tests/Limitation/Target/Builder/VersionBuilderTest.php
| **JIRA issue**     | [EZP-30470](https://jira.ez.no/browse/EZP-30470)
| **Required by** | ezsystems/ezplatform-admin-ui#987
**TODO**:
=> EZP-30470: Improved filtering Content Types and Languages based on permissions

eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/Core/Persistence/Tests/TransformationProcessor/_fixtures/transformations/latin.tr, eZ/Publish/Core/Persistence/Tests/TransformationProcessor/_fixtures/transformations/latin.tr.result
| **JIRA issue**     | [EZP-30548](https://jira.ez.no/browse/EZP-30548)
Added romanian special characters to TransformationProcessor.
**Todo**:
=> EZP-30548: Added support for Romanian special characters

eZ/Publish/Core/REST/Client/ContentService.php, eZ/Publish/Core/SignalSlot/ContentService.php, eZ/Publish/Core/SignalSlot/Signal/ContentService/AddTranslationInfoSignal.php, eZ/Publish/Core/SignalSlot/Signal/ContentService/TranslateVersionSignal.php
More in JIRA issue: [EZP-30585](https://jira.ez.no/browse/EZP-30585)
=> EZP-30585: Dropped unused translation methods from inner ContentService

eZ/Publish/Core/Event/Content/BeforePublishVersionEvent.php, eZ/Publish/Core/Event/Content/PublishVersionEvent.php, eZ/Publish/Core/Event/ContentService.php, eZ/Publish/Core/Event/Tests/ContentServiceTest.php
| **JIRA issue**     | [EZP-30616](https://jira.ez.no/browse/EZP-30616)
**TODO**:
=> EZP-30616: Fixed missing parameter in PublishVersion Events

eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
| **JIRA issue**     | No need to
Small typo discovered while running the script to extract translations. i don't think we need a jira isssue here, but let me know if you do. 
ping @glye @andrerom @adamwojs
=> fixed annotation typo y the persistence cache collector file

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php, eZ/Bundle/EzPublishCoreBundle/EventListener/User/DeleteUserListener.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml, eZ/Publish/API/Repository/ContentTypeService.php, eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php, eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php, eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php, eZ/Publish/Core/REST/Client/ContentTypeService.php, eZ/Publish/Core/Repository/ContentTypeService.php, eZ/Publish/Core/Repository/Repository.php, eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php, eZ/Publish/Core/Repository/Slot/User/DeleteUser.php, eZ/Publish/Core/SignalSlot/ContentTypeService.php, eZ/Publish/Core/settings/containerBuilder.php, eZ/Publish/Core/settings/slot.yml, eZ/Publish/SPI/Persistence/Content/Type/DeleteByParamsStruct.php, eZ/Publish/SPI/Persistence/Content/Type/Handler.php, eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php, eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
| **JIRA issue**     | [EZP-30725](https://jira.ez.no/browse/EZP-30725)
Added slot that delete content type drafts of removed user
**TODO**:
=> EZP-30725: Added slot that delete content type drafts of removed user

data/update/mysql/dbupdate-7.5.2-to-7.5.3.sql, data/update/postgres/dbupdate-7.5.2-to-7.5.3.sql
| **JIRA issue**     | [EZP-30725](https://jira.ez.no/browse/EZP-30725)
Adds some SQLs that remove from existing DB, drafts of non-existing users
**TODO**:
=> EZP-30725: Added db upgrade script for CT drafts cleanup

eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php, eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php
| **JIRA issue**     | [EZP-30544](https://jira.ez.no/browse/EZP-30544)
| **Target version** |  `master` 
This removes another dependency on HttpCacheBundle.
related:
https://github.com/ezsystems/ezplatform-http-cache/pull/94
**TODO**:
=> EZP-30544: Use configurable user hash header name

doc/specifications/rest/REST-API-V2.rst
=> Added X-Siteaccess specification for REST doc

eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php, eZ/Publish/Core/FieldType/Tests/UserTest.php, eZ/Publish/Core/FieldType/User/Type.php, eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
| **JIRA issue**     | [EZP-30966](https://jira.ez.no/browse/EZP-30966)
**TODO**:
=> EZP-30966: Fixed notice "Undefined index: PasswordTTL" while updating ezuser field definition using PAPI

eZ/Bundle/EzPublishCoreBundle/SiteAccess/MatcherBuilder.php, eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistry.php, eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistryInterface.php, eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/MatcherBuilderTest.php, eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
| **JIRA issue**     | [EZP-30974](https://jira.ez.no/browse/EZP-30974)
**TODO**:
=> EZP-30974: Fixed outstanding PHPUnit warnings

eZ/Publish/Core/IO/IOMetadataHandler.php, eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php, eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
Some more discovered typos.
**TODO**:
=> EZP-30985: Fix typos reported as deprecations

eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
=> Refactored Exception Conversion Content Gateway to use multi catch

composer.json
| **Target version** | `master` for features
Added conflict with phpunit/phpunit v8.4.0 due to https://github.com/sebastianbergmann/phpunit/issues/3879
**TODO**:
=> Added conflict with phpunit/phpunit 8.4.0

.travis.yml
Bumped Solr version to test on to `7.7`.
**TODO**:
=> [Travis] Updated Solr version in test matrix 

doc/bc/changes-8.0.md, eZ/Bundle/EzPublishCoreBundle/Controller.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml, eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
Removes some deprecation messages and fixes some typos that were reported as deprecations.
**TODO**:
=> EZP-30985: Refactored Core Controller, provided FQCN-named alias for GlobalHelper, replaced deprecated param provider service tag

eZ/Publish/API/Repository/ObjectStateService.php, eZ/Publish/API/Repository/Values/ObjectState/ObjectStateGroup.php, eZ/Publish/Core/Event/ObjectStateService.php, eZ/Publish/Core/Event/Tests/ObjectStateServiceTest.php, eZ/Publish/Core/Repository/ObjectStateService.php, eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/ObjectStateServiceTest.php, eZ/Publish/SPI/Repository/Decorator/ObjectStateServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/ObjectStateServiceDecoratorTest.php
| **JIRA issue**     | [EZP-30827](https://jira.ez.no/browse/EZP-30827)
| **BC breaks**      | yes!
This PR introduces strict types for the `\eZ\Publish\API\Repository\ObjectStateService`
**TODO**:
=> EZP-30827: Introduced strict types for ObjectStateService

eZ/Publish/Core/Base/Exceptions/DatabaseException.php, eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
Generic exceptions such as RuntimeException should never be thrown. 
**TODO**:
=> Added DatabaseException to replace RuntimeException occurrence in Gateway class

eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
=> Refactored Location's Exception Conversion

eZ/Publish/Core/Persistence/Legacy/Bookmark/Gateway/ExceptionConversion.php
=> Bookmark exception conversion

eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/ExceptionConversion.php
=> Refactored Language's Exception Conversion to use multi catch

eZ/Publish/API/Repository/SearchService.php, eZ/Publish/Core/Repository/SearchService.php, eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/SearchServiceTest.php, eZ/Publish/SPI/Repository/Decorator/SearchServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/SearchServiceDecoratorTest.php, eZ/Publish/SPI/Search/Capable.php
| **JIRA issue**     | [EZP-31094](https://jira.ez.no/browse/EZP-31094)
This PR introduces strict types for the `\eZ\Publish\API\Repository\SearchService`
**TODO**:
=> EZP-31094: Introduced strict types for SearchService

eZ/Publish/API/Repository/TrashService.php, eZ/Publish/Core/Event/TrashService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/TrashServiceTest.php, eZ/Publish/Core/Repository/SiteAccessAware/TrashService.php, eZ/Publish/Core/Repository/TrashService.php, eZ/Publish/SPI/Repository/Decorator/TrashServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/TrashServiceDecoratorTest.php
| **JIRA issue**     | [EZP-31093](https://jira.ez.no/browse/EZP-31093)
| **Target version** |  `master` 
This PR introduces strict types for the` \eZ\Publish\API\Repository\TrashService`
**TODO**:
=> EZP-31093: Introduced strict types for TrashService

eZ/Publish/API/Repository/FieldTypeService.php, eZ/Publish/Core/Helper/Tests/FieldHelperTest.php, eZ/Publish/Core/Repository/FieldTypeService.php, eZ/Publish/SPI/Repository/Decorator/FieldTypeServiceDecorator.php
| **JIRA issue**     | [EZP-31095](https://jira.ez.no/browse/EZP-31095)
This PR introduces strict types for the `\eZ\Publish\API\Repository\FieldTypeService`
**TODO**:
=> EZP-31095: Introduced strict types for FieldTypeService

eZ/Publish/API/Repository/URLWildcardService.php, eZ/Publish/Core/Event/URLWildcardService.php, eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php, eZ/Publish/Core/Repository/URLWildcardService.php, eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/URLWildcardServiceDecoratorTest.php
| **JIRA issue**     | [EZP-31098](https://jira.ez.no/browse/EZP-31098)
This PR introduces strict types for the` \eZ\Publish\API\Repository\URLWildcardService`
**TODO**:
=> EZP-31098: Introduced strict types for URLWildcardService

eZ/Publish/API/Repository/SectionService.php, eZ/Publish/Core/Event/SectionService.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php, eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php, eZ/Publish/Core/Repository/SectionService.php, eZ/Publish/Core/Repository/SiteAccessAware/SectionService.php, eZ/Publish/SPI/Repository/Decorator/SectionServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/SectionServiceDecoratorTest.php
| **JIRA issue**     | [EZP-31030](https://jira.ez.no/browse/EZP-31030)
This PR introduces strict types for the `\eZ\Publish\API\Repository\SectionService`.
**TODO**:
=> EZP-31030: Introduced strict types for SectionService

doc/upgrade/7.5.md, eZ/Publish/API/Repository/ContentService.php, eZ/Publish/API/Repository/Events/Content/BeforeCreateContentDraftEvent.php, eZ/Publish/API/Repository/Events/Content/CreateContentDraftEvent.php, eZ/Publish/API/Repository/Tests/ContentServiceTest.php, eZ/Publish/Core/Event/ContentService.php, eZ/Publish/Core/Persistence/Cache/ContentHandler.php, eZ/Publish/Core/Persistence/Legacy/Content/Handler.php, eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php, eZ/Publish/Core/Repository/ContentService.php, eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php, eZ/Publish/SPI/Persistence/Content/Handler.php, eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
| **JIRA issue**     | [EZP-30936](https://jira.ez.no/browse/EZP-30936)
**TODO**:
=> [DO NOT MERGE] EZP 30936: Travis run

doc/bc/changes-8.0.md, eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
=> Removed `*.class` parameters from routing configuration

eZ/Publish/API/Repository/Tests/BaseURLServiceTest.php, eZ/Publish/API/Repository/Tests/URLServiceTest.php, eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
| **JIRA issue**     | [EZP-31059](https://jira.ez.no/browse/EZP-31059)
Failed build: https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/612484652?utm_medium=notification&utm_source=github_status
**TODO**:
=> EZP-31059: Limited URL Search Results to unique entries only

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml, eZ/Publish/Core/MVC/Symfony/SiteAccess.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Provider/StaticSiteAccessProvider.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessService.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessServiceInterface.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Provider/ChainSiteAccessProviderTest.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php, eZ/Publish/Core/MVC/Symfony/SiteAccessGroup.php
| **JIRA issue**     | [EZP-EZP-31193](https://jira.ez.no/browse/EZP-31193)
**TODO**:
=> EZP-31193: Added information about Site Access groups to the Site Access

eZ/Publish/Core/FieldType/Float/Type.php
| **JIRA issue**     | [EZP-28900](https://jira.ez.no/browse/EZP-28900)
| **Target version** |`7.5`
see https://github.com/ezsystems/repository-forms/pull/325
**TODO**:
=> EZP-28900: Improved fromHash function in FloatType to return correct  float value

data/update/mysql/dbupdate-7.5.3-to-8.0.0.sql, data/update/mysql/dbupdate-7.5.latest-to-8.0.0.sql, data/update/postgres/dbupdate-7.5.3-to-8.0.0.sql, data/update/postgres/dbupdate-7.5.latest-to-8.0.0.sql
| **Target version** | `master (8.0.0@dev)` for eZ Platform 3.0.0
To prepare for eZ Platform 3.0.0-beta4 release I've merged upgrade scripts targeted for 8.0.0 into the one, named `dbupdate-7.5.latest-to-8.0.0.sql`.
**TODO**:
=> Merged database upgrade scripts for 8.0.0

.travis.yml, eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php
| **JIRA issue**     | [EZP-XXXXX](https://jira.ez.no/browse/EZP-XXXXX)
| **New feature**    | yes/no
| **Target version** | `6.x`/`7.x` for bug fixes or improvements _(on existing features)_, `master` for features
| **BC breaks**      | yes/no
**TODO**:
=> [DON'T MERGE] Test merge

Readme.md
Kernel Readme update consisting of: link update, name update, text proofreading.
=> [Doc] Updated README

eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/MapperTest.php, eZ/Publish/Core/Persistence/Legacy/UserPreference/Mapper.php
…ymfony bugfix) / added protection for unexpected tags
| **JIRA issue**     | [EZP-31297](https://jira.ez.no/browse/EZP-31297)
| **Target version** | `7.x` for bug fixes or improvements _(on existing features)_, `master` for features
Resolve ticket issue (Added additional protection in Mapper for unexpected tags)
**TODO**:
=> EZP-31297: Narrowed user preferences values to the available list (added additional tags protection for read)

eZ/Publish/API/Repository/Tests/UserServiceTest.php
| **JIRA issue**     | [EZP-29574](https://jira.ez.no/browse/EZP-29574)
| **Target version** | 7.5
**TODO**:
=> EZP-29574: Increased token time life to prevent token expired before end test

eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/MapperTest.php, eZ/Publish/Core/Persistence/Legacy/UserPreference/Mapper.php
Fix for https://github.com/ezsystems/ezpublish-kernel/pull/2926/files#diff-23a658e7ce8e018db83a092cf671159eR45
( https://jira.ez.no/browse/EZP-31297 )
Please test also switching the date formats in user preferences
**TODO**:
=> Fix - Removed clearing from tags in low-level code

.travis.yml, eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf, eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Exception.php, eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ExceptionTest.php
| **JIRA issue**     | [EZP-31298](https://jira.ez.no/browse/EZP-31298)
| **Bug**| yes
**TODO**:
=> Backported #2945 "EZP-31298: Made non verbose exception messages in REST responses"

eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
Test fix for https://github.com/ezsystems/ezpublish-kernel/pull/2940 
Tests for ezplatform-solr-search-engine passed:
=> EZP-31299: Fixed tests after merge #2940

eZ/Publish/Core/settings/tests/integration_legacy.yml, eZ/Publish/Core/settings/tests/integration_legacy_core.yml
=> Fixed Unit tests for 6.13 branch

eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php, eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
=> EZP-31299: [Tests] Added missing language mask to initial test data

eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ChainConfigResolverTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ConfigResolverTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolverTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolverTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolverTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolverTest.php
=> Added ChainConfigResolver tests

eZ/Publish/API/Repository/UserService.php, eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php, eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php, eZ/Publish/Core/REST/Client/UserService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php, eZ/Publish/Core/Repository/SiteAccessAware/UserService.php, eZ/Publish/Core/Repository/UserService.php, eZ/Publish/Core/SignalSlot/UserService.php
| **JIRA issue**     | [EZP-31079](https://jira.ez.no/browse/EZP-31079)
Method will be removed in `8.0`. Ref PR: https://github.com/ezsystems/ezpublish-kernel/pull/2944
**TODO**:
=> EZP-31079: Deprecated loadUserByCredentials

eZ/Publish/API/Repository/Repository.php, eZ/Publish/Core/Event/Repository.php, eZ/Publish/Core/Repository/Repository.php, eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
| **JIRA issue**     | [EZP-31481](https://jira.ez.no/browse/EZP-31481)
This PR introduces strict types for the `\eZ\Publish\API\Repository\Repository`
**TODO**:
=> EZP-31481: Introduced strict types for Repository

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
| **JIRA issue**     | [EZP-31487](https://jira.ez.no/browse/EZP-31487)
Please check if you even get error described in ticket, I use our docker setup with freshly build containers.
**TODO**:
=> EZP-31487: Escaped install command

eZ/Publish/API/Repository/LocationService.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Templating/Tests/GlobalHelperTest.php, eZ/Publish/Core/Repository/LocationService.php, eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php, eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php, eZ/Publish/SPI/Repository/Decorator/LocationServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/LocationServiceDecoratorTest.php
| **JIRA issue**     | [EZP-31448](https://jira.ez.no/browse/EZP-31448)
This PR introduces strict types for the `\eZ\Publish\API\Repository\LocationService`
**TODO**:
=> EZP-31448: Introduced strict types for LocationService

eZ/Publish/API/Repository/UserService.php, eZ/Publish/Core/Event/UserService.php, eZ/Publish/Core/Persistence/Legacy/User/Mapper.php, eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php, eZ/Publish/Core/Repository/SiteAccessAware/UserService.php, eZ/Publish/Core/Repository/UserService.php, eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php, eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
| **JIRA issue**     | [EZP-31469](https://jira.ez.no/browse/EZP-31469)
This PR introduces strict types for the \eZ\Publish\API\Repository\UserService
**TODO**:
=> EZP-31469: Introduced strict types for UserService

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php, eZ/Bundle/EzPublishCoreBundle/Resources/config/query_types.yml, eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
| **JIRA issue**     | [EZP-31506](https://jira.ez.no/browse/EZP-31506)
Deprecated `ezpublish.query_type` tag in favour of `ezplatform.query_type`. 
**TODO**:
=> EZP-31506: Deprecated `ezpublish.query_type` tag in favour of `ezplatform.query_type`

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml, eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php, eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
| **JIRA issue**     | [EZP-31490](https://jira.ez.no/browse/EZP-31490)
**TODO**:
=> EZP-31490: Added multilingual content route

eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
| **JIRA issue**     | [EZP-31499](https://jira.ez.no/browse/EZP-31499)
Follow up https://github.com/ezsystems/ezpublish-kernel/pull/3000. Fixed unclosed "(" in embed_inline.html.twig 
**TODO**:
=> EZP-31499: Fixed unclosed "(" in embed_inline.html.twig

eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway.php, eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php, eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/LegacyStorage.php
| **JIRA issue**     | [EZP-31129](https://jira.ez.no/browse/EZP-31129)
| **Target version** | 7.5
Depended on: https://github.com/ezsystems/ezplatform-richtext/pull/109
**TODO**:
=> EZP-31129: Added optional parameter to unlinkURL to better delete unused links

eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/ViewMatcherRegistryTest.php, eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/SiteAccessMatcherRegistryTest.php, eZ/Publish/Core/IO/Tests/MetadataHandler/ImageSizeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeGroupTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/LocationTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentLocationTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/RemoteTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/SectionTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/MultipleValuedTest.php, eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/UrlAliasTest.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Provider/ChainSiteAccessProviderTest.php, eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php, eZ/Publish/Core/Pagination/Tests/AdapterFactory/SearchHitAdapterFactoryTest.php, eZ/Publish/Core/Persistence/Cache/Tests/BookmarkHandlerTest.php, eZ/Publish/Core/Persistence/Cache/Tests/NotificationHandlerTest.php, eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php, eZ/Publish/Core/Persistence/Cache/Tests/UrlWildcardHandlerTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Update/Handler/DoctrineDatabaseTest.php, eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php, eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecLexerTest.php, eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecParserTest.php
| **JIRA issue**     | [EZP-31560](https://jira.ez.no/browse/EZP-31560)
| **Target version** | `master` (merge up of #3021)
This is the preview of a merge up of #3021 into `master`.
Merge up with changes relevant for `master` (44c1d7703005b4db447e084d529adc1439bf90fe).
**TODO**:
=> [Fast Forward MERGE] EZP-31560: [Tests] Fixed namespaces not following PSR
