ezsystems/ezpublish-kernel

eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishLegacyBundle/Tests/Controller/PreviewControllerTest.php
eZ/Publish/Core/Helper/ContentPreviewHelper.php
eZ/Publish/Core/Helper/PreviewLocationProvider.php
eZ/Publish/Core/Helper/Tests/ContentPreviewHelperTest.php
eZ/Publish/Core/Helper/Tests/PreviewLocationProviderTest.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php

> [EZP-23784](https://jira.ez.no/browse/EZP-23784)
Improves the Location draft passed on to the preview template when previewing the first version of a Content. This draft does not have an id (it is set to null), but has the real parent location id and depth.
Moved the location part out of `eZ\Publish\Core\Helpers\ContentPreviewHelper` to `eZ\Publish\Core\Helper\PreviewLocationProvider`. Using the API + SPI, the provider will either return the content's main location (API), or a fake location based on the content's parent location (SPI, uses eznodeassignment inside persistence).

EZP-23784: Refactored preview location handling

---

eZ/Bundle/EzPublishRestBundle/Features/ContentTypeGroup/list.feature
eZ/Bundle/EzPublishRestBundle/Features/ContentTypeGroup/read.feature
eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Authentication.php

JIRA: https://jira.ez.no/browse/EZP-23848
Fix failing BDD tests due to wrong expectation of `HTTP 401: Not Authorized` response with anonymous.
In fact, this is the response for any and ALL requests if http basic auth is used, and no user is provided,
however, this is outside the scope of existing tests (ContentTypeGroup read/list).
For the purpose of existing REST api tests, `anonymous` user is used. 
In this case, the queries are allowed and return valid results (ContentTypeGroup/list)
Nitpick:  
The `Given I do not have permissions` sentence actually equals `Given I have "anonymous" permissions`.

Fix EZP-23848: [BDD] don't expect HTTP 401 in REST API with anonymous

---

doc/specifications/debug/data_collectors.md
eZ/Bundle/EzPublishDebugBundle/Collector/EzPublishCoreCollector.php
eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
eZ/Bundle/EzPublishDebugBundle/Collector/TemplateDebugInfo.php
eZ/Bundle/EzPublishDebugBundle/Collector/TemplatesDataCollector.php
eZ/Bundle/EzPublishDebugBundle/DependencyInjection/Compiler/DataCollectorPass.php
eZ/Bundle/EzPublishDebugBundle/EzPublishDebugBundle.php
eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/layout.html.twig
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/panel.html.twig
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/toolbar.html.twig
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/templates/panel.html.twig
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/templates/toolbar.html.twig
eZ/Bundle/EzPublishDebugBundle/Tests/Collector/EzPublishCoreCollectorTest.php
eZ/Bundle/EzPublishDebugBundle/Tests/DependencyInjection/Compiler/DataCollectorPassTest.php
eZ/Bundle/EzPublishLegacyBundle/Collector/LegacyTemplatesCollector.php
eZ/Bundle/EzPublishLegacyBundle/Collector/TemplateDebugInfo.php
eZ/Bundle/EzPublishLegacyBundle/DependencyInjection/EzPublishLegacyExtension.php
eZ/Bundle/EzPublishLegacyBundle/Resources/config/debug.yml
eZ/Bundle/EzPublishLegacyBundle/Resources/views/Profiler/templates/panel.html.twig
eZ/Bundle/EzPublishLegacyBundle/Resources/views/Profiler/templates/toolbar.html.twig

> https://jira.ez.no/browse/EZP-23864
This patch decouples legacy data collector from core.
It adds an extension point allowing to add custom *eZ collectors* (i.e. meant to be displayed in
webprofiler under eZ toolbar/panel).
Symfony profiler let any bundle register *data collectors* and displayed collected data in the web profiler toolbar
and debug panel. eZ has its own data collector.
As of v6.0, it is possible to display custom collected data under eZ toolbar / panel.
The main data collector has been splitted into several dedicated ones and now only aggregates data collected by
registered sub-collectors.
Following data collectors are part of `EzPublishDebugBundle`:
* `PersistenceCacheCollector`: Collects information on persistence cache (aka SPI cache) efficiency (hits/miss).
* …

Fix EZP-23864: Fix coupling with legacy in debug bundle

---

eZ/Bundle/EzPublishRestBundle/CorsOptions/RestProvider.php

Otherwise the 'allowed_methods' previously set by \Nelmio\CorsBundle\Options\ConfigProvider in \Nelmio\CorsBundle\Options\Resolver::getOptions will be overwritten with value of $return['allow_methods'] due to array_merge()
At least on my setup ;)

EZP-23889: RestProvider must check that is_rest_request is true

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Compound.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/HostElement.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Regex.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/URIElement.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Compound/CompoundAndTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Compound/CompoundOrTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostElementTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElement2Test.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElementTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIRegexTest.php

> https://jira.ez.no/browse/EZP-23834
Cause of ESIs not being shareable amon pages (within the same SiteAccess) was the presence of SimplifiedRequest object, containing current `pathinfo`, which is most of the time not really needed.
This PR makes SiteAccess matchers not serializing the inner request when being serialized (done when generating ESI URL).

Fix EZP-23834: Cached ESI can not be shared among pages because of inner request

---

doc/specifications/security/multiple_user_providers.md

JIRA: https://jira.ez.no/browse/EZP-23902
With the sync with Symfony-standard 2.5 (see EZP-23494 / https://github.com/ezsystems/ezpublish-platform/commit/0cd0fc3cfac574ce9cb429772522fdc6ba835304 ) the ```encoders``` key has been removed from ```security.yml```, along with alternate providers.
The documentation/example should include the encoder as it is necessary.

Fix EZP-23902: update multiple user providers doc security.yml example

---

eZ/Publish/Core/Persistence/Solr/Slot/MoveSubtree.php
eZ/Publish/Core/Persistence/Solr/Slot/MoveUserGroup.php

This PR resolves issue https://jira.ez.no/browse/EZP-23403
It turned out `MoveSubtree` slot also need to be fixed, as it was reindexing all Locations of the Content in the moved subtree, while only moved Locations needed reindexing.
`MoveUserGroup` slot is fixed by extending `MoveSubtree` slot and using its implementation.
Testing: manual testing
Followup: remove UserService::moveUserGroup() method: https://jira.ez.no/browse/EZP-23699

Fix EZP-23403: Fix implementation of Persistence\Solr\Slot\MoveUserGroup slot

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Compound.php

> https://jira.ez.no/browse/EZP-23923
In compound SiteAccess matchers, it's not needed to keep defined config during serialization. Keeping it can lead to very long URLs for subrequests, potentially exceeding 2048 characters, which make Hinclude requests hardly usable.

Fix EZP-23923: ESI/Hinclude URI too long with Compound siteaccess matcher

---

composer.json
eZ/Bundle/EzPublishCoreBundle/HttpCache.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SymfonyCache/UserContextSubscriber.php

> https://jira.ez.no/browse/EZP-23930
This PR fixes the [BC break introduced in FOSHttpCacheBundle 1.2.0](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/CHANGELOG.md#120).
Also bumps FOSHttpCacheBundle requirement to `~1.2` (composer update needed).
Should unblock https://github.com/ezsystems/ezpublish-community/pull/223 and https://github.com/ezsystems/ezpublish-community/pull/224
**Important**:
* Only affects Symfony reverse proxy
* New maintenance sub-releases needed: `2014.11.8`, `2015.01.1`, `5.4.1.1`

Fix EZP-23930: Adapt HttpCache to comply FOSHttpCacheBundle 1.2

---

eZ/Bundle/EzPublishRestBundle/ApiLoader/Factory.php
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/REST/Common/FieldTypeProcessor/MediaProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/BinaryInputProcessorTest.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/MediaProcessorTest.php

JIRA: https://jira.ez.no/browse/EZP-23837 (discovered while implementing the Media field edit view in PlatformUI https://jira.ez.no/browse/EZP-23813)
It's impossible to update the value of a Media field using the REST API. It seems like it's because unlike for BinaryFile and Image, the Media field type processor does not extend the BinaryInputProcessor (which takes care of creating a file on the disk with the data provided in the REST update struct).
Note: for now, this is a very rough patch just to let me work on EZP-23813 and to see which tests it breaks :)
manual for now

Fix EZP-23837: Impossible to set the value of a Media field

---

eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/Handler.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/Location/Handler.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/Mapper/StandardMapper.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/MapperInterface.php
eZ/Publish/Core/settings/storage_engines/legacy_elasticsearch.yml

This PR implements https://jira.ez.no/browse/EZP-23562
This breaks Mapper implementation into a abstract `Mapper` and `Standard` implementation, in order to make custom implementations dispatchable.
`mapContentLocation()` is renamed to `mapLocation()` as more appropriate.

EZP-23562: Elasticsearch: make Mapper dispatchable

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Values/Content/Query/CustomFieldInterface.php
eZ/Publish/API/Repository/Values/Content/Query/SortClause/Field.php
eZ/Publish/Core/FieldType/Country/SearchField.php
eZ/Publish/Core/FieldType/Integer/SearchField.php
eZ/Publish/Core/FieldType/MapLocation/SearchField.php
eZ/Publish/Core/FieldType/Price/SearchField.php
eZ/Publish/Core/FieldType/TextLine/SearchField.php
eZ/Publish/Core/FieldType/Unindexed.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/CriterionVisitor/Field.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/CriterionVisitor/Field/FieldIn.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/CriterionVisitor/Field/FieldRange.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/CriterionVisitor/Field/MapLocationDistanceRange.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/CriterionVisitor/FullText.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/FieldMap.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/SortClauseVisitor/Field/Field.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/SortClauseVisitor/Field/MapLocationDistance.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/SortClauseVisitor/FieldBase.php
eZ/Publish/Core/Persistence/Elasticsearch/Tests/Content/Search/FieldMapTest.php
eZ/Publish/Core/Persistence/Elasticsearch/Tests/TestCase.php
eZ/Publish/Core/settings/storage_engines/elasticsearch/criterion_visitors_content.yml
eZ/Publish/Core/settings/storage_engines/elasticsearch/sort_clause_visitors_content.yml
eZ/Publish/SPI/FieldType/Indexable.php

This PR resolves issue https://jira.ez.no/browse/EZP-23465
Current implementation of field mapping does not cover several use-cases:
1. In case the FieldType indexes multiple fields, no way is provided to select particular field for search and sort
Indexable FieldType interface provides a way to index single field data in multiple fields. Currently we use this in the case of MapLocation FieldType, where both address and geo point is indexed. At the moment MapLocationDistance criterion and sort clause discriminate on the field to use through its type (see `eZ\Publish\SPI\Persistence\Content\Search\FieldType\*`). This mechanism can be ambiguous if multiple fields of the same type are defined. MapLocation address is not searchable with Field criterion nor sortable with Field sort clause, as …

Implement EZP-23465: Elasticsearch: refactor FieldMap implementation for caching and multiple fields support

---

eZ/Publish/Core/Persistence/Cache/Handler.php
eZ/Publish/Core/Persistence/Cache/LocationSearchHandler.php
eZ/Publish/Core/Persistence/Cache/SearchHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/PersistenceHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/SearchHandlerTest.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/Handler.php
eZ/Publish/Core/Persistence/Elasticsearch/Content/Search/Location/Handler.php
eZ/Publish/Core/Persistence/Elasticsearch/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Search/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Search/Location/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Search/MainHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater.php
eZ/Publish/Core/Persistence/Legacy/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/HandlerTest.php
eZ/Publish/Core/Persistence/Solr/Content/Search/Handler.php
eZ/Publish/Core/Persistence/Solr/Content/Search/Location/Handler.php
eZ/Publish/Core/Persistence/Solr/Handler.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/SPI/Persistence/Handler.php
eZ/Publish/SPI/Search/Content/Handler.php
eZ/Publish/SPI/Search/Content/Location/Handler.php
eZ/Publish/SPI/Search/Handler.php

This PR resolves https://jira.ez.no/browse/EZP-23966, a sub-task for https://jira.ez.no/browse/EZP-23940
Followup: https://jira.ez.no/browse/EZP-23967
This introduces main Search Engine Handler, moving Content and Location search handler namespaces down.
Main Search Engine Handler interface implementations will be put in use in the followup.

Fix EZP-23966: SPI: Introduce main handler for Search Engines

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml

A small fix missing in merged https://github.com/ezsystems/ezpublish-kernel/pull/1170
This adds `ezpublish.spi.search_handler` to container configuration in EzPublishCoreBundle.

EZP-23967: fix container: configure search handler in EzPublishCoreBundle

---

eZ/Bundle/EzPublishCoreBundle/Converter/ContentParamConverter.php
eZ/Bundle/EzPublishCoreBundle/Converter/LocationParamConverter.php
eZ/Bundle/EzPublishCoreBundle/Converter/RepositoryParamConverter.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Converter/AbstractParamConverterTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Converter/ContentParamConverterTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Converter/LocationParamConverterTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php

Link: https://jira.ez.no/browse/EZP-21998
*Please review the test carefully as I am not used to write them* :)
Implements @ParamConverter for `Location` and `Content`
See symfony doc: http://symfony.com/doc/2.3/bundles/SensioFrameworkExtraBundle/annotations/converters.html
Unit test and manual on DemoBundle ( see https://github.com/ezsystems/DemoBundle/pull/129 )

EZP-21998: Implement @ParamConverter in controllers

---

eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php

In https://github.com/ezsystems/ezpublish-kernel/commit/1f2d9b23555cb2a90bf4aebcbe0ab58a15930745 compiler passes have been moved but use statements needed to be updated.
Opening a PR

Fix use after the move of compiler passes

---

eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RequestEventListenerTest.php

> [EZP-23966](https://jira.ez.no/browse/EZP-23996)
> Sub-task of [EZP-23964](https://jira.ez.no/browse/EZP-23994)
> Related to ezsystems/LegacyBridge#7
Removes the Legacy Setup event listener, [moved to legacy-bridge](https://github.com/ezsystems/LegacyBridge/pull/7).

EZP-23996: Moved legacy setup event to legacy-bridge

---

doc/upgrade/6.0.md
eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/UpdateSortKeysCommand.php
eZ/Bundle/EzPublishMigrationBundle/EzPublishMigrationBundle.php

This PR resolves https://jira.ez.no/browse/EZP-23924
When fixing sort key field type bugs we did not always provide update scripts, leaving the database in inconsistent state. This could result in incorrect matches when using search.
This implements the cleanup script that will check if fields of given field type have correct sort key, and update it if needed.

EZP-23924: Empty sort_key_string should be fixed to prevent failures

---

eZ/Publish/Core/MVC/Symfony/Security/Tests/User/ProviderTest.php
eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php

> https://jira.ez.no/browse/EZP-23971
When reloading security token from the session, repository user is not refreshed correctly (i.e. not re-fetched). Consequence is that if the user is modified in the backend (e.g. e-mail changed or user deleted), it's not reflected for the currently logged in user.
This patch fixes it. 
If user isn't found, a `UsernameNotFoundException` will be thrown, allowing [Symfony `ContextListener`](https://github.com/symfony/symfony/blob/2.6/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L148-L181) (firewall listener loading security info from the session) to reset the security token and kick the user out.

Fix EZP-23971: If a user is removed while logged in, session for that user will throw an exception

---

eZ/Publish/Core/Base/Tests/Container/Compiler/Search/Legacy/CriterionFieldValueHandlerRegistryPassTest.php
eZ/Publish/Core/Base/Tests/Container/Compiler/Search/Legacy/SortClauseConverterPassTest.php
eZ/Publish/Core/Base/Tests/Container/Compiler/Search/SignalSlotPassTest.php
eZ/Publish/Core/Base/Tests/Container/Compiler/Search/Solr/AggregateSortClauseVisitorPassTest.php
eZ/Publish/Core/Search/Common/Slot/CreateLocation.php
eZ/Publish/Core/settings/search_engines/elasticsearch/criterion_visitors_content.yml
eZ/Publish/Core/settings/search_engines/elasticsearch/criterion_visitors_location.yml
eZ/Publish/Core/settings/search_engines/solr/criterion_visitors.yml

This PR resolves https://jira.ez.no/browse/EZP-23940
Just some minor cleanup found after all the PRs.
One fix worth of notice is CreateLocation slot change. This was fixed for Elasticsearch, but when Slots were made common, the Solr implementation was kept by mistake. There is no need to index all Content's Locations when Locations is created. If Locations are sub-documents of Content,  `contentSearchHandler()->indexContent()` with re-index Content with it's sub-documents (both ES and Solr), if Location is also indexed separately then `locationSearchHandler()->indexLocation()` will take care of it (only ES, Solr implementation is empty).
TL; DR: slots should not have to know how data is structured in a particular engine, this is handled by concrete indexing implementation.

EZP-23940: Cleanup (Decouple search handlers from Persistence)

---

eZ/Bundle/EzPublishCoreBundle/EventListener/IndexRequestListener.php
eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/IndexRequestListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RequestEventListenerTest.php

JIRA: https://jira.ez.no/browse/EZP-23978
Split IndexRequest into its own event listener, so that it can be overridden/disabled by LegacyBridge
(see #1165)

EZP-23978: Split Index RequestEventListener service.

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Values/Content/Query.php
eZ/Publish/API/Repository/Values/Content/Search/SearchResult.php
eZ/Publish/Core/Search/Legacy/Content/Gateway.php
eZ/Publish/Core/Search/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Search/Legacy/Content/Handler.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/ExceptionConversion.php
eZ/Publish/Core/Search/Legacy/Content/Location/Handler.php

https://jira.ez.no/browse/EZP-24047
see: http://share.ez.no/forums/ez-publish-5-platform/about-searchservice-and-count-queries
Test ping @crevillo, using  ~~$fieldFilters['perform_extra_count'] = false~~ `$query->performCount = false`

EZP-24047: Allow skipping count query when using SearchService against db

---

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php

Change welcome text to make sure directory permissions are mentioned, default example of install is using demo-clean and that it more clearly states it is and example.

Tweak install text to reflect demo-clean install

---

eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/AddField.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentUpdater/Action/AddFieldTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentUpdater/Action/RemoveFieldTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentUpdaterTest.php
eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
eZ/Publish/Core/settings/search_engines/solr/criterion_visitors.yml
eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php

This PR resolves https://jira.ez.no/browse/EZP-23941
First part of the issue, required to implement the field map on the ContentType handler.
`ContentUpdater` service, used by ContentType handler to update Content instances when FieldDefinition is added or removed was using search handler to find Content instances of a specific ContentType.
This would create a circular dependency and therefore needed to be removed. Search handler is here replaced by new method in Content gateway `getContentIdsByType()`.
Additionally a bug in `ContentUpdater` is fixed, where added Field ids were not retained across versions and external storages were not notified for store/delete for all necessary versions.

EZP-23941: Move field map to storage 1/2

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
eZ/Publish/Core/Search/Common/FieldNameResolver.php
eZ/Publish/Core/Search/Elasticsearch/Content/SortClauseVisitor/Field/Field.php
eZ/Publish/Core/Search/Elasticsearch/Content/SortClauseVisitor/Field/MapLocationDistance.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseConverter.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Field.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/MapLocationDistance.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/SectionName.php
eZ/Publish/Core/Search/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/Location/HandlerSortTest.php
eZ/Publish/Core/Search/Solr/Content/SortClauseVisitor/MapLocationDistance.php
eZ/Publish/Core/Search/Tests/FieldNameResolverTest.php
eZ/Publish/Core/settings/search_engines/legacy.yml
eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
eZ/Publish/SPI/Persistence/Content/Type/Handler.php
phpunit.xml

This PR resolves https://jira.ez.no/browse/EZP-23941
This adds `getFieldMap()` method to the ContentType handler.
The method is added to the interface and implemented in all handler implementations: Cache storage, Legacy storage, memory caching implementation in Legacy storage. 
It returns field map data in the form:
```php
array(
"<ContentType identifier>" => array(
"<FieldDefinition identifier>" => array(
"field_definition_id" => "<FieldDefinition id>",
"field_type_identifier" => "<FieldType identifier>",
),
...
),
...
)
```
This data is used by search implementations to map Field criteria and sort clauses to the field in the index backend or storage.
Legacy Search Engine allowed sorting on the data of the fields that are not searchable, for example template_look/title (`ezsetting` …

EZP-23941: Move field map to storage 2/2

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

This PR resolves https://jira.ez.no/browse/EZP-21721
Originally reported problem was about empty XmlText field being rendered as empty internal XML format, ie:
```xml
<?xml version="1.0" encoding="utf-8"?>
<section xmlns:image="http://ez.no/namespaces/ezpublish3/image/" xmlns:xhtml="http://ez.no/namespaces/ezpublish3/xhtml/" xmlns:custom="http://ez.no/namespaces/ezpublish3/custom/"/>
```
The problem was coming from `simple_block_field` and `simple_inline_field` blocks, where Twig's `default` filter was incorrectly used for a case when variable was not defined.
This filter returns passed default value if tested value is [not defined **or empty**](http://twig.sensiolabs.org/doc/filters/default.html). That could not work correctly as what is considered empty by Twig could be a correct result …

Fix EZP-21721: Displaying an empty XMLText field outputs eZXML

---

bootstrap.php

Fixes https://jira.ez.no/browse/EZP-24093
If you do a ezpublish-community install and then you run ezpublish-kernel you'll probably go to your vendor/ezsystems/ezpublish-kernel folder and do what install doc says
* Enter directory cd ezpublish-kernel
* Get Composer using curl curl -s http://getcomposer.org/installer | php
* Install dev dependencies: php composer.phar install --prefer-dist --dev
* Copy config.php-DEVELOPMENT cp config.php-DEVELOPMENT config.php
* Execute phpunit -vc phpunit*.xml with one of:
...
But actually in these case i'm getting an error
```
PHP Fatal error:  Class 'Matthias\SymfonyDependencyInjectionTest\PhpUnit\AbstractCompilerPassTestCase' not found in /home/carlos/ezpublish-community/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Base/Tests/Container/Compiler/Fi …
```

Fix: EZP-24093 Fatal Error running ezpublish-kernel tests inside an ezcommunity install

---

eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
eZ/Publish/Core/FieldType/Image/ImageStorage.php
eZ/Publish/Core/IO/TolerantIOService.php
eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php

> Implements [EZP-23788](https://jira.ez.no/browse/EZP-23788)
This changes the Image FieldType's external storage handler, to make it accept a reference to an existing image as the `ImageValue::$id` property.
Long story long, this was kind of possible in the initial version, but it depended on `id` (formerly named `path`) referencing both the stored file or the input file, which caused a lot of issues. In 5.2, `path` was reserved for the stored path, and `inputUri` was added for the input file. In 5.4, `path` was renamed to `id`, and became more of an internal field.
I believe that allowing to use `id` to reference an existing file makes sense. We might wanna be careful with what happens if an Image's FieldValue is re-used for another field. It was taken into account, but I'm not entirely …

EZP-23788: accept existing file when updating images

---

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/REST/Common/FieldTypeProcessor/RichTextProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RichTextProcessorTest.php

This PR resolves https://jira.ez.no/browse/EZP-24078
For REST access this adds the value in XHTML5 editing format alongside the value in internal format.
This is acheved thorugh standard REST extension point -- FieldTypeProcessor, by overriding default implementation of `postProcessValueHash` method, so that injected converter is used to convert internal format to the desired format, which is then added to the output hash.
The value will then be avialable over REST under `xhtml5edit` key, like:
```xml
<fieldValue>
<value key="xml">&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ezxhtml="http://ez.no/xmlns/ezpublish/docbook/xhtml" xmlns:ezcustom="http://ez.no/xmlns/ezpublish/docbook/custom" …
```

EZP-23078: As a UI developer, I want to have access to an HTML5 version of the RichText fields

---

eZ/Publish/Core/FieldType/Page/Type.php
eZ/Publish/Core/FieldType/Tests/PageTest.php

This PR resolves https://jira.ez.no/browse/EZP-24106
This overrides default `FieldType::isEmptyValue()` implementation for `Page` field type.
The check is now similar to what is done in Legacy Stack datatype, see https://github.com/ezsystems/ezflow-ls-extension/blob/master/datatypes/ezpage/ezpagetype.php#L184.
Note that this ignores `Page::$layout` property when checking if the value is empty. This means `Page` field type value can be non-empty, but have no content to display in the templates. Handling this properly would require introducing something like `hasContent()`. Suggestions on how to handle this are wellcome.
1. https://jira.ez.no/browse/EZP-24183: FieldType::isEmptyValue( $value ) should check $value type

Fix EZP-24106: ez_is_field_empty does not work for a Page field

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
eZ/Publish/Core/Helper/ContentPreviewHelper.php
eZ/Publish/Core/Helper/Tests/ContentPreviewHelperTest.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php

> https://jira.ez.no/browse/EZP-24053
> https://jira.ez.no/browse/EZP-24052
This issue was due to an incomplete implementation of legacy website toolbar (handling preview was missing).
This PR ensures that:
* Content preview route is only used with Http GET (POST will be used by legacy to publish or go back to editing).
* One can easily check if preview is active and retrieve previewed content/location.
ContentPreviewHelper is now used to check if preview is active and to get previewed content/location since as of Symfony 2.4, request attributes from the master request are not passed to sub-requests any more. Furthermore, it's cleaner to be able to get this information through a dedicated service instead of request attributes.
LegacyBridge related PR: …

Fix EZP-24053: Preview locks content object, and cause version edit conflict

---

doc/bc/changes-5.3.md
doc/bc/changes-5.4.md
doc/bc/changes-6.0.md
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FullText.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/Location/HandlerTest.php

TL;DR; FullText was hardcoded to disable search on phrases that exists in more then 20 content objects..
See issue for details: https://jira.ez.no/browse/EZP-24213
*Approach: In original discussion with @pspanja I suggested exposing a spiContentHandler->getTotalCount() method to provide total count and cache it in SPI cache. I have initial work on that, however ended up just caching it locally on FullTextHandler as that turned out to much simpler and a count query is compared to everything else we do here very fast. If someone see some immediate value also other places in having spiContentHandler->getTotalCount() I can re add it, or do it as followup.*

EZP-24213: FullText stopWordThreshold should be percentage of content count

---

eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/ContentTypeIdentifier.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/Field.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldBase.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldRelation.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/MapLocationDistance.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/Location/HandlerSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/Location/HandlerTest.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml

This PR resolves: https://jira.ez.no/browse/EZP-24206
Since decoupling search from persistence, search engine uses cached implementation of storage engine. Initially that was used to implement cached map of searchable fields, which (in Legacy Search Engine) was used to get required field information in Field sort clause handler. This employs the similar approach on two other places:
1. `ContentTypeIdentifier` criterion handler - uses cached storage to find ContentType id from identifier and. Doing that simplifies the generated query, avoiding one sub-query.
2. `Field` criterion handler - uses previously implemented searchable field map to build a map of searchable fields for a given field target. This avoids one separate database query per Field criterion used.
- limited …

EZP-24206: As a Developer I want faster search, using spi cache & indexed columns

---

.travis.yml

Also:
- change to use include matrix option for easier reading
- change hhvm to use nightly builds as well, and skip integration tests for now as they "pass"*
- change to use symfony  2.7@dev instead of 2.6@beta to make sure we test against 2.7 already 
_* Besides https://github.com/facebook/hhvm/issues/4476<del>, for unit tests we are mainly blocked by https://github.com/facebook/hhvm/issues/5134</del>_

[Travis] Run unit tests on PHP 7.0 nightly builds

---

eZ/Publish/API/Repository/Tests/FieldType/IntegerIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/TextLineIntegrationTest.php
eZ/Publish/Core/Search/Elasticsearch/Content/CriterionVisitor/Field/FieldRange.php
eZ/Publish/Core/Search/Solr/Content/CriterionVisitor/Field/FieldRange.php

This PR resolves https://jira.ez.no/browse/EZP-21794
This implements field type integration test framework for search with Field criterion and Field sort clause.
In order to get it working for a specific field type, concrete test needs to extend the base one, implementing two abstract methods:
* `getSearchValueA()`
* `getSearchValueB()`
These provide distinct valid field type input values, which will be used to create two test Content objects.
Field criterion will be tested on these Content objects, for each supported operator, combined with `LogicalNot` criterion.
Field sort clause will be tested in ascending and descending sorting order.
Same set of tests will be executed for each type of search (Content search, Location search), and in case of a criterion separately for a filtering and …

Implement EZP-21794: integration test framework for Search with Field criterion and sort clause

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Search/Solr/Content/Handler.php

This PR resolves https://jira.ez.no/browse/EZP-24215
The issue was discovered while using content service copyContent method.
During the copying, the content's mainLocationId is set to 0, and location service checks for null.
Steps to reproduce:
```php
$oldLocation = $locationService->loadLocation( $locationId );
$locationCreateStruct = $locationService->newLocationCreateStruct( $newLocationParentId );
$copiedContent = $contentService->copyContent( $oldLocation->contentInfo, $locationCreateStruct );
var_dump( $contentService->loadContentInfo( $copiedContent->id ) );
```
MainLocationId is set to 0 in dumped content info
This PR proposes the fix for this.
Casting main location id to int in Content Mapper should happen only if main location id is not null, and copyContent method in Content …

Fix EZP-24215: CopyContent method returns content with 0 as its main location id

---

bin/.travis/prepare_unittest.sh

Failure in https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/59236460#L107 seems to be a temporary problem, as it did not appear on re-running https://github.com/ezsystems/ezpublish-kernel/pull/1235.
This adds `composer self-update` to `bin/.travis/prepare_unittest.sh` script, so that problems caused by outdated composer version are avoided. See https://github.com/ezsystems/ezpublish-kernel-ee/pull/65 for more details (caret operator it this case, as described at https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-).

[Travis] execute composer self-update

---

doc/bc/changes-6.0.md
eZ/Publish/API/Repository/ContentTypeService.php
eZ/Publish/API/Repository/Tests/BaseNonRedundantFieldSetTest.php
eZ/Publish/Core/FieldType/Tests/TextLineTest.php
eZ/Publish/Core/FieldType/TextLine/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/TextLine.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php
eZ/Publish/Core/REST/Client/ContentTypeService.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentTypeBase.php
eZ/Publish/Core/SignalSlot/ContentTypeService.php

> https://jira.ez.no/browse/EZP-24253
Modifications to allow flexible implementation of ContentType forms.

EZP-24253: Implement framework for ContentType creation

---

eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/FilterConfiguration.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/FilterConfigurationTest.php

JIRA: https://jira.ez.no/browse/EZP-24279
Problem: for existing image variations, it is not possible to define liip_imagine settings.
While it may be possible to introduce new semantic config options, the settings under `liip_imagine` configuration block should also apply.
This does that, making possible to define settings such as `jpeg_quality` (or future settings) for existing variations.
(see also https://jira.ez.no/browse/EZP-24167 - Image variations JPEG quality)

Fix EZP-24279: use defined liip_imagine variation settings

---

doc/bc/changes-5.3.md
doc/bc/changes-5.4.md
doc/bc/changes-6.0.md
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/SignalSlot/ContentService.php

This PR resolves https://jira.ez.no/browse/EZP-24268
This defines and implements throwing `BadStateException` when using `ContentService::deleteVersion()` to delete Content's last version.
In this case `ContentService::deleteContent()` should be used instead.

Fix EZP-24268: deleting the last version of the Content should not be allowed

---

eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/FloatIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchableFloat.php
eZ/Publish/Core/FieldType/Float/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/FieldValueMapper/FloatMapper.php
eZ/Publish/Core/Search/Elasticsearch/Content/Resources/mappings/content.json
eZ/Publish/Core/Search/Solr/Content/FieldValueMapper/FloatMapper.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/search_engines/elasticsearch/field_value_mappers.yml
eZ/Publish/Core/settings/search_engines/solr/field_value_mappers.yml
eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml
eZ/Publish/Core/settings/tests/integration_legacy_solr.yml

This PR resolves https://jira.ez.no/browse/EZP-24266
This implements `Indexable` definition for `Float` field type.
The field type is not searchable in Legacy engine, because the implementation uses sort keys (int and string), but will be searchable with Solr and Elasticsearch engines. For the purpose of testing test field type that defines the original field type as searchable is implemented, also ContentType service tests needed to be adapted.

Implement EZP-24266: Indexable Float field type

---

eZ/Publish/API/Repository/Tests/BaseContentTypeServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchableTextBlock.php
eZ/Publish/API/Repository/Tests/FieldType/TextBlockIntegrationTest.php
eZ/Publish/Core/FieldType/Integer/SearchField.php
eZ/Publish/Core/FieldType/TextBlock/SearchField.php
eZ/Publish/Core/FieldType/TextBlock/Type.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentTypeBase.php
eZ/Publish/Core/Search/Solr/Content/CriterionVisitor.php
eZ/Publish/Core/Search/Solr/Content/CriterionVisitor/Field/FieldIn.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24269
This implements `Indexable` definition for `TextBlock` field type.
The field type was incorrectly defined as searchable, while it is not searchable in Legacy Search Engine.
That is here fixed, and for the purpose of testing test field type that defines the original field type as searchable is implemented. Also, ContentType service tests needed to be adapted.
Solr's base `CriterionVisitor` now implements `prepareValue()` method, which is used to convert and escape the search target value to the proper Solr representation. This will be further employed in next sub-tasks.

Implement EZP-24269: Indexable TextBlock field type

---

eZ/Publish/API/Repository/Tests/FieldType/CheckboxIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/Core/FieldType/Checkbox/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/FieldValueMapper/MultipleBooleanMapper.php
eZ/Publish/Core/Search/Solr/Content/FieldValueMapper/MultipleBooleanMapper.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24274
This implements `Indexable` definition for `Checkbox` field type.
Since Legacy Search Engine stores boolean value as integer (0/1), this required dedicated methods to provide Field search target value in the field type integration tests. These default to the Field creation value, and should be overridden as needed.
Solr's base `CriterionVisitor` now implements `prepareValue()` method, which is used to convert and escape the search target value to the proper Solr representation.
In multiple boolean value mappers a case when since boolean value is given is fixed.

Implement EZP-24274: Indexable Checkbox field type

---

eZ/Publish/API/Repository/Tests/FieldType/DateAndTimeIntegrationTest.php
eZ/Publish/Core/FieldType/DateAndTime/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/Resources/mappings/content.json
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24271
This implements `Indexable` definition for `DateAndTime` field type.
Tests account for Legacy Search Engine storing field type's values as integer timestamps.

Implement EZP-24271: Indexable DateAndTime field type

---

eZ/Publish/API/Repository/Tests/FieldType/EmailAddressIntegrationTest.php
eZ/Publish/Core/FieldType/EmailAddress/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24273
This implements `Indexable` definition for `EmailAddress` field type.

Implement EZP-24273: Indexable EmailAddress field type

---

eZ/Publish/API/Repository/Tests/FieldType/FileSearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchableImage.php
eZ/Publish/API/Repository/Tests/SetupFactory/LegacyElasticsearch.php
eZ/Publish/API/Repository/Tests/SetupFactory/LegacySolr.php
eZ/Publish/Core/FieldType/Image/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/CriterionVisitor/Field/FieldRange.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml
eZ/Publish/Core/settings/tests/integration_legacy_solr.yml

This PR resolves https://jira.ez.no/browse/EZP-24275
Additionally to the file name, which is the default value used by Field criterion and sort clause, Image field type also indexes alternative text and file size. These can be targeted by using `CustomFieldInterface:: setCustomField()` method. Test framework is here refactored to allow testing of these custom fields. However this is a bit awkward, and calls for a refactoring to make testing simpler for the new implementations.
Since not all searchable field types have Indexable definition implemented, this required `FileSearchBaseIntegrationTest`. This is temporary and will be removed when all searchable field types are covered.
Dedicated methods to provide Field search target value was …

Implement EZP-24275: Indexable Image field type

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

https://jira.ez.no/browse/EZP-24158
Reproduced with ezpublish-docker VM.
*Context: This was the parts I skipped when I first added cache clearing by copying what CacheClearing command is doing, part still skipped is cache warmup. Maybe we could rather just reuse the cache clearing command here, afaik there is a way to do that but I don't remember how and I think I remember it being rather hackish looking but might be wrong.*

Fix EZP-24158: Need to clear cache manually after platform install

---

eZ/Publish/API/Repository/Tests/FieldType/BinaryFileIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/Core/FieldType/BinaryFile/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24314

Implement EZP-24314: Indexable BinaryFile field type

---

eZ/Publish/API/Repository/Tests/FieldType/TimeIntegrationTest.php
eZ/Publish/Core/FieldType/Time/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24272
This implements `Indexable` definition for `Time` field type. Time value is indexed as integer (time of day as number of seconds).
Note that providing integer field value is interpreted a giving a timestamp, so field type's value object is constructed directly. This required dedicated methods to provide Field search target value in the field type integration tests (implemented in previous sub-tasks).

Implement EZP-24272: Indexable Time field type

---

eZ/Publish/API/Repository/Tests/FieldType/DateIntegrationTest.php
eZ/Publish/Core/FieldType/Date/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This PR resolves https://jira.ez.no/browse/EZP-24270
This implements `Indexable` definition for `Date` field type. Date value is indexed as integer (timestamp with time of day at 0).

Implement EZP-24270: Indexable Date field type

---

eZ/Publish/API/Repository/FieldType.php
eZ/Publish/Core/FieldType/Tests/APIFieldTypeTest.php
eZ/Publish/Core/REST/Client/FieldType.php
eZ/Publish/Core/Repository/Values/ContentType/FieldType.php

> https://jira.ez.no/browse/EZP-24347
Added following public method to `eZ\Publish\API\Repository\FieldType`:
* `validateValue()`
* `validateValidatorConfiguration()`
* `validateFieldSettings()`
They're just proxies to internal SPI FieldType (the real one).
This makes it possible to do validation from outside the repository (e.g. using Symfony Validation component)

Fix EZP-24347: Expose FieldType validation from API

---

doc/bc/changes-6.0.md
doc/specifications/rest/REST-API-V2.rst
eZ/Publish/API/Repository/LocationService.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018LanguageTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018ObjectStateTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018VisibilityTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/UserService.php
eZ/Publish/API/Repository/Values/Content/Query.php
eZ/Publish/Core/REST/Client/LocationService.php
eZ/Publish/Core/REST/Client/UserService.php
eZ/Publish/Core/REST/Server/Controller/Location.php
eZ/Publish/Core/REST/Server/Controller/User.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/Search/Elasticsearch/Content/Gateway/Native.php
eZ/Publish/Core/Search/Legacy/Content/Gateway.php
eZ/Publish/Core/Search/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/Location/HandlerTest.php
eZ/Publish/Core/Search/Solr/Content/Gateway/Native.php
eZ/Publish/Core/Search/Solr/Content/Location/Gateway/Native.php
eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/Tests/UserServiceTest.php
eZ/Publish/Core/SignalSlot/UserService.php

This PR resolves https://jira.ez.no/browse/EZP-23405
This removes the option for returning unlimited number of search hits.
While this worked with relational database (Legacy Search Engine), Solr and Elasticsearch were never made to provide for this. Using big number to fake unlimited (`1073741824` for Legacy Search Engine) routinely causes OOM exceptions with Solr and Elasticsearch.
Solr and Elasticsearch were made to work with returning relatively small number of hits, providing paging/scrolling for the case when full set is required.
This removes `null` as an alias for unlimited in `Query` objects, and also in methods that rely on search:
* LocationService::loadLocationChildren()
* UserService:: loadSubUserGroups()
* UserService:: loadUserGroupsOfUser()
* UserService:: …

Fix EZP-23405: remove unlimited search hits option

---

eZ/Publish/Core/FieldType/Integer/Type.php
eZ/Publish/Core/FieldType/Tests/IntegerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/Integer.php

Default values must be null, not false. Required for https://github.com/ezsystems/repository-forms/pull/10
Thanks @lolautruche
https://jira.ez.no/browse/EZP-24397

Fix EZP-24397: Implement FieldDefinition form mapper for ezinteger

---

eZ/Publish/Core/REST/Server/Controller/Location.php
eZ/Publish/Core/REST/Server/Controller/Trash.php
eZ/Publish/Core/REST/Server/Controller/User.php

> https://jira.ez.no/browse/EZP-24374
Some location hrefs have a double `/`. This should ensure that they're gone.
none

EZP-24374: Fixed double slashes in REST location path

---

doc/specifications/proposed/content_download/content_download.md
eZ/Bundle/EzPublishCoreBundle/EventListener/ContentDownloadRouteReferenceListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ContentDownloadRouteReferenceListenerTest.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadController.php
eZ/Publish/Core/MVC/Symfony/Routing/RouteReference.php

> http://jira.ez.no/browse/EZP-23550
> [specifications](https://github.com/ezsystems/ezpublish-kernel/blob/ezp23550-content_download/doc/specifications/proposed/content_download/content_download.md)

EZP-23550: Implement content/download

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml

https://jira.ez.no/browse/EZP-24427
Constructor for the controller needs a third param
ping @bdunogier @andrerom @lolautruche

EZP-24227: Missing Translation Helper in Content Download service definition

---

.travis.yml
bootstrap.php
config.php-DEVELOPMENT

This is based by what's done in SensioDistributionBundle:
https://github.com/sensiolabs/SensioDistributionBundle/commit/0db645c7e01286d7ca8fa79b61539f6aa644b25c
Deprecation errors should not block tests.

Silence deprecation notices with Symfony 2.7

---

eZ/Publish/Core/FieldType/Tests/XmlText/Converter/Html5Test.php
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/001-title.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/002-para.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/003-section.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/004-sectionNested.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/005-emphasis.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/006-emphasisStrong.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/007-emphasisUnderlined.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/012-literallayout.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/013-anchor.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/014-link.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/019-emphasisStrikedthrough.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/020-blockquote.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/021-titleImplicitLevels.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/026-tableTitles.xml
eZ/Publish/Core/FieldType/Tests/XmlText/Converter/_fixtures/html5/output/108-expandTable.xml
eZ/Publish/Core/FieldType/XmlText/Input/Resources/stylesheets/eZXml2Html5_core.xsl

[WIP] 
----
Fixes: https://jira.ez.no/browse/EZP-23846
Found this issue in the tracker. I'm experiencing it too. As said there, seems to be caused by the anchors added when trasforming ```header```
I did some manually tests and found that deleting name attribute makes the warning dissapear. 
I deleted name because [is not supported by html5](http://www.w3schools.com/tags/att_a_name.asp). My worry is if this name could be needed for anything else. (old browsers or whatever).   
Let me know if you find this workaround as a good solution and if so, i could add some test.
ping @pspanja @lolautruche @andrerom 
Edit: Tests will need to be updated as they expect name attribute in the anchors.

EZP-23846: Fix XSLTProcessor::transformToXml(): ID eztoc_1_1 already defined

---

eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php

JIRA: https://jira.ez.no/browse/EZP-24399
When generating cross-siteaccess links, the destination root location should be taken into account (so the path prefix is removed from the url).
Note: 
This does NOT (yet) modify the variables on the "fallback" section as it may be reverted, see https://github.com/ezsystems/ezpublish-kernel/pull/1259
TODO:

Fix EZP-24399: Cross-siteaccess links do not take tree_root into account

---

doc/bc/changes-6.0.md
eZ/Bundle/EzPublishCoreBundle/Console/Application.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SiteAccessListenerTest.php

> https://jira.ez.no/browse/EZP-24459
Follow-up of #1221.
After investigation, it is actually not necessary to *fix* ContentPreview since the previewed SiteAccess is already correctly handled, as the content preview is rendered through a sub-request. In this regard, SiteAccess match done normally (not limited to master request).

Fix EZP-24459: SiteAccess should not be a synchronized service any more

---

composer.json

https://jira.ez.no/browse/EZP-24484
Proxy manager needs to be updated to 1.0 so we can skip disallowing newer versions of Zend Stdllib that does not have this problem.
Fix for master, 5.3 and 5.4 to avoid the conflict below:

Update ProxyManager to avoid conflict with Zend Stdlib

---

eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Publish/Core/Base/Container/ApiLoader/FieldTypeCollectionFactory.php
eZ/Publish/Core/Base/Container/Compiler/FieldTypeCollectionPass.php

> https://jira.ez.no/browse/EZP-24440
FieldTypeCollectionFactory now also have a list of FieldTypes that are **not** using NullFieldType

Fix EZP-24440: Filter FieldType selection in ContentType edition

---

composer.json

This change will allow to use `~6.0@dev` as dependency instead of hardcoding `dev-master`.
The same needs to be done in other packages (e.g. repository-forms, demobundle...)
Ping @andrerom @bdunogier @pspanja @glye

Added 6.0.x alias to dev-master

---

eZ/Publish/Core/FieldType/Page/Type.php

Need to allow empty value, when the field type is first added to the content type.
Required for FieldDefinition form mapper for ezpage: https://github.com/ezsystems/repository-forms/pull/23
https://jira.ez.no/browse/EZP-24444

Fix EZP-24444: Implement FieldDefinition form mapper for ezpage

---

eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/Tests/RichTextTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RichTextConverter.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/RichTextProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RichTextProcessorTest.php
eZ/Publish/SPI/Tests/FieldType/RichTextIntegrationTest.php

Removed tag preset field type setting, as discussed in https://github.com/ezsystems/repository-forms/pull/21
https://jira.ez.no/browse/EZP-24449

Fix EZP-24449: Implement FieldDefinition form mapper for RichText

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml

Two minor changes to RichText field type:
1. fixed incorrect `docbook` to `xhtml5edit` stylesheet configuration, causing incorrect namespace on the conversion result.
2. disabled validation of `xhtml5edit` input
Reported in https://github.com/ezsystems/PlatformUIBundle/pull/235.

RichText: disable xhtml5edit input validation and fix conversion stylesheet configuration

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ComplexSettingsPass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ConfigResolverParameterPass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ComplexSettings/ComplexSettingValueResolver.php
eZ/Bundle/EzPublishCoreBundle/EventListener/DynamicSettingsListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ComplexSettingsPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ConfigResolverParameterPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ComplexSettings/ComplexSettingValueResolverTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/DynamicSettingsListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/Stubs/FooServiceInterface.php

> https://jira.ez.no/browse/EZP-24458
This PR removes usage of *fake* services to inject dynamic settings using factories.
Instead, usage of ExpressionLanguage component is introduced.
This allows to remove usage of a hack (fake services) and of a Symfony deprecated feature (synchronized services).

Fix EZP-24458: Refactor dynamic settings injection

---

eZ/Publish/Core/FieldType/Image/Type.php
eZ/Publish/Core/FieldType/Tests/ImageTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php

Flipped byte/megabyte conversion in the converter, this seems to have been backwards originally.
Edit: I reverted this flip. It's not backwards, it's just that ezimage is meant to have the max file size in bytes, not MB.
What remains of the fix is to use `null` rather than `false`, same as for binaryfile and media.
Requirement for ezimage form mapper: https://github.com/ezsystems/repository-forms/pull/24
https://jira.ez.no/browse/EZP-24442

Fix EZP-24442: Implement FieldDefinition form mapper for ezimage

---

eZ/Publish/Core/Search/Solr/Content/DocumentMapper/NativeDocumentMapper.php
eZ/Publish/Core/Search/Solr/Content/Resources/schema.xml
eZ/Publish/Core/settings/search_engines/solr/criterion_visitors.yml

This PR resolves sub-task https://jira.ez.no/browse/EZP-24486
Schema is changed to index to fulltext `text` field over proxy field `*_fulltext_t`, which is not indexed nor stored, but is copied to it.
Location index now does not index to `text` field by omitting `*_fulltext_t` fields and not registering `FullText` criterion.

Implement: EZP-24486: Disable FullText search for LocationSearch

---

doc/bc/changes-6.0.md
doc/specifications/proposed/content_download/content_download.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/BinaryContentDownloadPass.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ContentDownloadRouteReferenceListener.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Publish/API/Repository/Tests/FieldType/BinaryFileIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/MediaIntegrationTest.php
eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
eZ/Publish/Core/FieldType/Tests/BinaryFileTest.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadController.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadRedirectionController.php
eZ/Publish/Core/MVC/Symfony/FieldType/BinaryBase/ContentDownloadUrlGenerator.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/BinaryProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/BinaryProcessorTest.php
eZ/Publish/Core/settings/fieldtype_external_storages.yml
eZ/Publish/SPI/Tests/FieldType/BinaryFileIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/MediaIntegrationTest.php

> Alternative for #1299 
> [EZP-24468](http://jira.ez.no/browse/EZP-24468)
With this approach, we use a different route for REST content/download urls. That route is based on the fieldId instead of the fieldDefIdentifier, but does a permanent redirect to fieldDefIdentifier.
This has several advantages:
- since REST doesn't know about siteaccesses/languages mapping, we can take care of that part when redirecting
- it allows us to store this REST content/download URI into the SPI cache, and avoid putting a field Def Identifier there (even though it actually is there in every field, in the Version)
- it separates layers better, even if it is not perfect

EZP-24468: expose content/download url over REST 

---

doc/specifications/proposed/named_queries/index.md

Review ping @bdunogier, @pspanja.
BD: As you mentioned we could support dynamic parameters on Persisted Queries, I added a section on that as I think it will to easily break down. And while I did not go into it in details, I kind of view Named Queries *(like you seem to do from spec also)* as being two parts: a factory; The Type; aka Query Type, and the corresponding Value; __potentially__ the Query object it returns as a result. While Persisted Queries is just a Value, no factories involved. Except maybe for structs like newContentQueryCreateStruct(), which will for the most part look like a Query Value but w/o limit and offset for instance. But unsure if that first with how you see things? *side: hmm, maybe I should just do a proposed spec to make it more clear* :P

[Spec] Added clarifications on Persisted Queries

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

- Avoid the width="" and the height=""
- Allow to force a height and a width manually (useful for handling the different screen densities)

Fix EZP-24535: Avoid empty width/height and allow to force them

---

eZ/Publish/Core/IO/Tests/TolerantIOServiceTest.php
eZ/Publish/Core/IO/TolerantIOService.php

A simple fix and test for what I believe is a bug in the TolerantIOService. The bug causes wrong URIs to be rendered in img src attributes when the image does not exist on the filesystem, e.g. without the standard "images" prefix. That becomes a problem when the view is cached with that wrong img URI and the image is then added at the correct path afterwards.
No jira issue because it wouldn't let me register.
Issue: https://jira.ez.no/browse/EZP-24548

Fix EZP-24548: [API/IO] Wrong image url prefix when image is not found

---

eZ/Publish/Core/Search/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/Handler.php

Optimize sorted search queries by about 50%.
Sorting should not be required when just counting the results. Skipping the sort part of this query reduces the overall runtime for field sorted queries to the SPI by almost 50%.

Fix EZP-24539: Avoid expensive sorting sql when not needed in Search

---

eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/contentobjects.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_content_from_rows.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_content_from_rows_result.php

issue: https://jira.ez.no/browse/EZP-24499
The SQL in Legacy Content GateWay QueryBuilder has a query which does not correctly filter out the languages we are not interested in, leading mysql to transfer way to many rows *(160k reported in issue)* for the data we need. This causes a lot of unneeded processing making it slow on both mysql and php side. It also causes unneeded network transfer and memory use on server, client and php side, causing memory limit issues in worst cases like the once reported.
Contains two commits:
- fix for fixtures, 25c7cb0b6f9c1b7bcb1a3aa8b8cf07ca4b50a409 introduced issue as it was lacking name table and using wrong language_id for eng-GB, fixing this to be closer to real database caused the issue reported here to be detected by the tests. …

EZP-24499: loading Content with many languages & attributes & locations leads to high memory usage

---

eZ/Publish/Core/Helper/PreviewLocationProvider.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php

issue: https://jira.ez.no/browse/EZP-23784
Just a small enhancement to what was done in #1113 to:
- adds a somewhat correct pathString
- cleans up the code a bit to mainly throw NotImplemented when Content has no locations
Intend to backport this and #1113 to 5.4 for the customer that has some issues around this to see if it solves their problem, or not.
review ping @bdunogier @lolautruche

Fix EZP-23784: Improve Location handling in preview part 2

---

eZ/Publish/Core/REST/Server/Controller/User.php

> Fixes https://jira.ez.no/browse/EZP-24564
Makes sure that the REST User Controller sets the UserSession's CSRF token as a string and not an object.

EZP-24564: REST UserSession expects csrf as string

---

doc/bc/changes-6.0.md
eZ/Publish/Core/FieldType/Float/Type.php
eZ/Publish/Core/FieldType/Tests/FloatTest.php
eZ/Publish/Core/FieldType/Tests/FloatValueValidatorTest.php
eZ/Publish/Core/FieldType/Validator.php
eZ/Publish/Core/FieldType/Validator/FloatValueValidator.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/FloatConverter.php

> https://jira.ez.no/browse/EZP-24533
To be compatible with Symfony Form component and NumberToLocalizedStringTransformer, we **must not** use `false` as default values, and prefer `null` instead.

Fix EZP-24533: Float FieldType has wrong default validator values

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php

JIRA: https://jira.ez.no/browse/EZP-24562
When using `urlalias_iri` legacy transformation group, url aliases can be created with single/quotes, for example.
Symfony's RoutingExtension for twig, which implements `{{ path() }}`, has it's own method for determining wether an url is potentially unsafe, in which case it can be html-encoded.
However, this is not compatible with eZ Publish's simple `path(location)` . ref:
https://github.com/symfony/TwigBridge/blob/master/Extension/RoutingExtension.php#L75
In the UrlAliasGenerator, manually replace potentially unsafe characters with their url-encoded counterpart (not html-encoded, so that it is always a valid url)

Fix EZP-24562: quotes in urlAlias cause twig's path() to break html

---

eZ/Publish/Core/Search/Solr/Content/Location/SortClauseVisitor/DateModified.php
eZ/Publish/Core/Search/Solr/Content/SortClauseVisitor/Aggregate.php
eZ/Publish/Core/Search/Solr/Content/SortClauseVisitor/DateModified.php
eZ/Publish/Core/settings/search_engines/solr/sort_clause_visitors.yml

> Review dependency graph
> * https://github.com/ezsystems/ezpublish-kernel/pull/1305 Main languages core
>  * https://github.com/ezsystems/ezpublish-kernel/pull/1322 Multicore tests
>    * https://github.com/ezsystems/ezpublish-kernel/pull/1326 Complete CustomField support
>       * https://github.com/ezsystems/ezpublish-kernel/pull/1327 Extract CoreFilter service
>       * https://github.com/ezsystems/ezpublish-kernel/pull/1333 Indexable Selection
>          * https://github.com/ezsystems/ezpublish-kernel/pull/1334 Indexable RelationList
> * **https://github.com/ezsystems/ezpublish-kernel/pull/1329 DateModified sort clause**
This implements Content Search visitor for `DateModified` sort clause. Tests are already present, but were skipped without the implementation.
Additionally this …

Fix EZP-24557: Solr search engine: DateModified sort clause is not supported with Content Search

---

eZ/Publish/API/Repository/Tests/FieldType/RelationListIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/RelationSearchMultivaluedBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchMultivaluedBaseIntegrationTest.php
eZ/Publish/Core/FieldType/RelationList/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This implements `Indexable` definition for `RelationList` field type.
Only a list of related Content IDs is indexed.

EZP-24573: Implement Indexable interface for RelationList

---

eZ/Bundle/EzPublishCoreBundle/Console/Application.php

> https://jira.ez.no/browse/EZP-24598
Make sure console commands update the scope with the siteaccess so dynamic settings are updated as expected.

Fix EZP-24598: Dynamic settings that depend on siteaccess in Console commands do not work correctly

---

eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
eZ/Publish/Core/FieldType/Url/UrlStorage.php

This PR fixes https://jira.ez.no/browse/EZP-24083.
The issue is present when creating and/or updating content with empty ezurl field type.
In that case we end up with multiple entries in the database with url set to null and the same md5 hash.
I have added a simple check to prevent this from happening, which is consistent with behavior in the legacy stack.

EZP-24083 do not save empty url

---

eZ/Bundle/PlatformInstallerBundle/src/Resources/config_templates/clean/ezpublish.yml

Exemple of failure: That is impossible ( in DEV mode ) to edit a Content Type.
It works in PROD (because the Notice is not triggered) 
but 
https://github.com/ezsystems/PlatformUIBundle/blob/master/Controller/ContentTypeController.php#L150
The array is still empty..
```
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined offset: 0" at wwwroot/vendor/ezsystems/platform-ui-bundle/Controller/ContentTypeController.php line 150 
```

Fix EZP-24614: "default" is not a siteaccess. Fix a configResolver failure

---

eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php

The role updating code in the Doctrine layer tries to read the row count after doing the update query. Updates have no result rows, so it always fails with a NotFoundException. Fix is simple: Don't do it. (Verified by comparing with content type code.)
https://jira.ez.no/browse/EZP-24698

Fix EZP-24698: Role update leads to NotFoundException

---

eZ/Publish/Core/Search/Common/Slot/AbstractSubtree.php
eZ/Publish/Core/Search/Common/Slot/HideLocation.php
eZ/Publish/Core/Search/Common/Slot/MoveSubtree.php
eZ/Publish/Core/Search/Common/Slot/MoveUserGroup.php
eZ/Publish/Core/Search/Common/Slot/UnhideLocation.php

> ##### This PR resolves https://jira.ez.no/browse/EZP-24704
> ##### Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/10
`HideLocation` and `UnhideLocation` search engine slots are fixed so that the whole subtree is reindexed. Reindexing everything is a bit of an overkill, since it should not be required to reindex sub-subtrees where the root Location is already hidden.
That behavior should be revisited in the future, and is maybe another argument in favor of internal storage-based simplified search engine, which would here enable much simpler loading of data for reindexing.

EZP-24704: Solr: Implement native result extractor

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestLocation.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestLocationRootNodeTest.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestLocationTest.php

> Story: https://jira.ez.no/browse/EZP-24672
> Status: missing test updates
Also contains a variable factoring in one file. The main change is that the RestLlocation also renders the ContentInfo object from the Location's properties.

EZP-24672: Added ContentInfo to REST Location

---

eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
eZ/Publish/API/Repository/Tests/_fixtures/Elasticsearch/CustomFieldBetween.php
eZ/Publish/API/Repository/Tests/_fixtures/Solr/CustomFieldBetween.php
eZ/Publish/API/Repository/Values/Content/Search/SearchHit.php

Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/12
One of the remaining points from the workshop.
Initially the idea was for this to be plural (an array of strings), containing the array of matched language codes. Since we can't achieve that ATM the property is kept as string.

Renamed SearchHit::$contentTranslation to $matchedTranslation

---

eZ/Bundle/EzPublishCoreBundle/FieldType/Page/PageService.php

JIRA: https://jira.ez.no/browse/EZP-24618
When loading block items content, an unauthorized exception prevents the whole block from being displayed.
This causes the "offending" item to be ignored (not displayed).

Fix EZP-24618: Error displaying page block if block item is unauth.

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchMultivaluedBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018LanguageTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018ObjectStateTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP20018VisibilityTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP21069Test.php
eZ/Publish/API/Repository/Tests/Regression/EZP21906SearchOneContentMultipleLocationsTest.php
eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php

Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/13
This adds call to the `SearchHandler::commit()` method for all tests that create or modify Content/Locations and require them to be available for search.
Since quite some non-search implementation uses search internally, this also exposes all of those, that is it exposes the places where asynchronous/delayed nature of indexing gets in the way of "optimal" behavior.
While I think this way of calling `SearchHandler::commit()` to make data available for tests is justified for `SearchService::find*` methods, the behavior is hard to explain on other places, like `LocationService::loadLocationChildren()`, `TrashService::recover()`, `UserService::moveUserGroup()` and others.
For these I propose implementing …

Implement commit() instead of setCommit()

---

.travis.yml
eZ/Publish/Core/Repository/UserService.php

This PR resolves https://jira.ez.no/browse/EZP-23242
Blocks https://jira.ez.no/browse/EZP-24718
This replaces Content search with Location search in UserService.
Existing tests apply.
Additionally Travis parameters for Solr integration tests are updated.

EZP-23242: UserService uses Content search instead of Location search

---

doc/bc/changes-6.0.md
eZ/Publish/API/Repository/LocationService.php
eZ/Publish/API/Repository/UserService.php
eZ/Publish/API/Repository/Values/Content/Query.php
eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php
eZ/Publish/Core/Pagination/Tests/LocationSearchHitAdapterTest.php
eZ/Publish/Core/REST/Client/LocationService.php
eZ/Publish/Core/REST/Client/UserService.php
eZ/Publish/Core/REST/Server/Controller/Location.php
eZ/Publish/Core/REST/Server/Controller/User.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/UserService.php

This PR resolves https://jira.ez.no/browse/EZP-24720
This increases default search limit value from 10 to 25.
That is done to limit impact of backporting removal of unlimited search hits option in https://jira.ez.no/browse/EZP-23405 to 5.4.

EZP-24720: increase default search limit value from 10 to 25

---

doc/bc/changes-5.4.md
doc/bc/changes-6.0.md
eZ/Publish/API/Repository/Values/Content/Search/SearchHit.php

This adds BC notes for:
* Introduction of `SearchHit::$matchedTranslation`
* removal of deprecated criteria and sort clauses

Missing BC notes

---

doc/bc/changes-6.0.md
eZ/Publish/API/Repository/Tests/Regression/EZP21906SearchOneContentMultipleLocationsTest.php
eZ/Publish/API/Repository/Tests/Regression/EZP22958SearchSubtreePathstringFormatTest.php
eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Values/Content/Query.php
eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php

This removes deprecated (5.2) virtual property `$criterion` on the API Query class.
The property was mapped to concrete `$query` property.

Removed deprecated Query::$criterion

---

eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/XmlTextConverter.php

Fixes `Setting 'tagPreset' is of unknown tag preset` in PlatformUI
`tagPreset` is stored in dataText2 while an int is expected by the FieldType. This PR fixes the inconsistency.

Fixed tagPreset setting consistency in XmlTextConverter

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessor.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessorTest.php

References behave differently in PHP 7 and calls to
`call_user_func_array()` now must have explicit references when passing
arguments (not variables assigned by reference).
See [reported PHP bug](https://bugs.php.net/bug.php?id=70379).
Tests should have broken but they did not because of a issue in
`testMapConfigClosure()`.
*Important*: There is *no change on the behavior*. We only avoid a warning from being triggered.

[PHP 7] Fixed reference issue in ConfigurationProcessor

---

.travis.yml
composer.lock

Don't allow PHP 7.0 to fail anymore, *and* move several tests over to it to put more emphasis on 7.0 testing *(..and get some speed up of travis runs as a bonus)*.
Tests moved-to/enabled on 7.0:
- unit
- behat
- solr
- elastic search

Full PHP 7.0 testing

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php

JIRA ticket related: https://jira.ez.no/browse/EZP-24750
Reason: missing ownerId for fake ContentInfo
BTW: nice hack and only 1.5yr old TODO

fix: call to /api/ezp/v2/content/locations/1 caused server error

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/_fixtures/urlaliases_location_iri.php

> Fixes https://jira.ez.no/browse/EZP-24737
> Status: code ready, tests not updated yet
Uses `mb_strtolower()` when hasing UrlAlias parts to md5.

Use mbstring on string ops on UrlAlias

---

eZ/Publish/API/Repository/Values/Content/SectionCreateStruct.php
eZ/Publish/API/Repository/Values/Content/SectionStruct.php
eZ/Publish/API/Repository/Values/Content/SectionUpdateStruct.php

This helps a lot form management (`data_class` option) / validation config (FQCN based).
See implementation for sections at https://github.com/ezsystems/repository-forms/pull/37
This PR also introduces 2 new interfaces: `CreateStruct` and `UpdateStruct`, mostly for type hint/check.
This change is completely BC and is applicable to most (maybe all) structs defined in the Repository.

Add common base for Section create/update structs

---

eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/SignalSlot/Repository.php

When using sudo method in repository with signal slot wrapper activated, final closure call does not use the signal slot repository as a param, instead it uses core implementation.

EZP-24759: Repository sudo method does not use signal slot repo

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

JIRA: https://jira.ez.no/browse/EZP-24705
Whitespace between tags is removed when displaying xmltext content. For example:
`<p><emphasize>em</emphasize> <strong>strong</strong></p>`
is displayed instead as:
`<p><emphasize>em</emphasize><strong>strong</strong></p>`
The source of the problem seems to be twig's `{% spaceless %}`:
> Use the spaceless tag to remove whitespace between HTML tags, not whitespace within HTML tags > or whitespace in plain text:
The behavior, however, is to also remove spaces between __inner__ html tags.
render the `'simple_block_field'` outside of the spaceless tag, as well as it's `field_value` output.

Fix EZP-24705: whitespace between tags is removed on display.

---

doc/bc/changes-6.0.md
doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/EventListener/RequestListener.php
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Bundle/EzPublishRestBundle/Tests/EventListener/RequestListenerTest.php
eZ/Publish/Core/REST/Common/Input/Dispatcher.php
eZ/Publish/Core/REST/Common/Input/ParsingDispatcher.php
eZ/Publish/Core/REST/Common/Tests/Input/ParsingDispatcherTest.php
eZ/Publish/Core/REST/Server/Controller/Content.php
eZ/Publish/Core/REST/Server/Controller/Views.php
eZ/Publish/Core/REST/Server/Input/Parser/ContentQuery.php
eZ/Publish/Core/REST/Server/Input/Parser/LocationQuery.php
eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Input/Parser/ViewInputOneDotOne.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Location.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestExecutedView.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Root.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/ViewInputOneDotOneTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/ViewInputTest.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestExecutedViewTest.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RootTest.php

> Implements https://jira.ez.no/browse/EZP-24671
Adds handling of versions in Input parsing dispatcher. The input_parser service tag has an optional 'version' attribute. 
The ViewInput input parser has two classes, one for 1.0, one for 1.1. The one for 1.0 is the one used until now. The other one accepts either LocationQuery and ContentQuery.
The OutputVisitor for an ExecutedView has been modified to accept Content, Location or ContentInfo. ContentInfo search isn't implemented yet (see Controller method).

EZP-24672: Implemented LocationSearch in REST

---

eZ/Publish/Core/MVC/Symfony/Cache/Http/FOSPurgeClient.php

JIRA: https://jira.ez.no/browse/EZP-24755
FOSHttpCacheBundle has a listener on kernel terminate event which issues a flush() call, however legacy ajax requests through ezjscore (and other places such as scripts, etc) terminate execution before this event.
This ensures that a call to flush() is always performed.

Fix EZP-24755: (FOS) Http cache not purged if execution terminates

---

eZ/Bundle/EzPublishCoreBundle/EventListener/ExceptionListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml

Purpose is to automatically convert exceptions coming from the Repository to appropriate HTTP exception, expected by Symfony.
Converts:
* `eZ\Publish\API\Repository\Exceptions\NotFoundException` => `Symfony\Component\HttpKernel\Exception\NotFoundHttpException`
* `eZ\Publish\API\Repository\Exceptions\UnauthorizedException` => `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException`
* `\eZ\Publish\API\Repository\Exceptions\ForbiddenException` => `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException`
Please note that this only occurs using HTTP, not console.
As for REST, a similar listener is already in place, with a higher priority.

Implemented generic ExceptionListener

---

.travis.yml
composer.json
eZ/Bundle/EzPublishCoreBundle/Features/Console/console.feature
eZ/Bundle/EzPublishCoreBundle/Features/Context/ConsoleContext.php
eZ/Bundle/PlatformBehatBundle/Command/TestSiteaccessCommand.php
eZ/Bundle/PlatformBehatBundle/EzPlatformBehatBundle.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config_templates/clean/ezpublish.yml

> Story: [EZP-24774](https://jira.ez.no/browse/EZP-24774)
> Related pull-requests: ezsystems/BehatBundle#32, ezsystems/ezplatform#38
Tests that the siteaccess is correctly matched with and without the `--siteaccess` parameter.
Adds a `mobile` siteaccess to the `clean` installer so that we have a valid scenario for testing.

BDD: console siteaccess matching

---

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/FieldType/Float/Type.php
eZ/Publish/Core/FieldType/Tests/FloatTest.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/FloatProcessor.php

The float fieldtype value checking was missing a step for checking if the value was an integer
PR resolves: https://jira.ez.no/browse/EZP-24038

EZP-24038: Float field does not accept an integer as input

---

eZ/Publish/API/Repository/Tests/FieldType/AuthorIntegrationTest.php
eZ/Publish/Core/FieldType/Author/SearchField.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml

This implements `Indexable` definition for `Author` field type.
Indexed data:
1. `name`, a list of author names
2. `id`, a list of author IDs
3. `email`, a list of author emails
3. `count`, number of authors
4. `sort_value`, list of author names concatenated with `-` and used for sorting

EZP-24582: implement Indexable for Author field type

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/AncestorContent.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/AncestorLocation.php
eZ/Publish/API/Repository/Tests/_fixtures/Solr/AncestorContent.php
eZ/Publish/API/Repository/Tests/_fixtures/Solr/AncestorLocation.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/Ancestor.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/Ancestor.php
eZ/Publish/Core/Search/Legacy/Content/Gateway/CriterionHandler/Ancestor.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/CriterionHandler/Ancestor.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_content.yml
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_location.yml

This PR resolves https://jira.ez.no/browse/EZP-24804
Review together with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/19
This implements `Ancestor` criterion, accepting Location path string(s) as value.

Implement EZP-24804: Ancestor criterion

---

doc/bc/changes-6.0.md
eZ/Publish/Core/FieldType/Tests/XmlText/Gateway/LegacyStorageTest.php
eZ/Publish/Core/FieldType/Tests/XmlTextTest.php
eZ/Publish/Core/FieldType/XmlText/Type.php
eZ/Publish/Core/FieldType/XmlText/Value.php
eZ/Publish/Core/FieldType/XmlText/XmlTextStorage/Gateway/LegacyStorage.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/XmlTextConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/XmlTextTest.php
eZ/Publish/SPI/Persistence/Content/FieldValue.php
eZ/Publish/SPI/Persistence/ValueObject.php
eZ/Publish/SPI/Tests/FieldType/XmlTextIntegrationTest.php

As discussed with @kore, storage engines should not be aware of high level representation of XML field type, that is DOMDocument.
Todo:

EZP-24832: Remove DOMDocument handling from legacy converters

---

eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml

Exceptions happening when querying the REST WS always output debug traces, even when kernel.debug is explicitly set to false.
Fix this by making it depend on kernel.debug.
https://jira.ez.no/browse/EZP-24827

Fix EZP-24827: REST: exceptions always output debug traces

---

eZ/Publish/API/Repository/Tests/FieldType/AuthorIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/FloatIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/IntegerIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/SelectionIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/TextBlockIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/TextLineIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/UrlIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/XmlTextIntegrationTest.php
eZ/Publish/Core/FieldType/Author/SearchField.php
eZ/Publish/Core/FieldType/Country/SearchField.php
eZ/Publish/Core/FieldType/Float/SearchField.php
eZ/Publish/Core/FieldType/Integer/SearchField.php
eZ/Publish/Core/FieldType/MapLocation/SearchField.php
eZ/Publish/Core/FieldType/Price/SearchField.php
eZ/Publish/Core/FieldType/Relation/SearchField.php
eZ/Publish/Core/FieldType/RichText/SearchField.php
eZ/Publish/Core/FieldType/Selection/SearchField.php
eZ/Publish/Core/FieldType/TextBlock/SearchField.php
eZ/Publish/Core/FieldType/TextLine/SearchField.php
eZ/Publish/Core/FieldType/Url/SearchField.php
eZ/Publish/Core/FieldType/XmlText/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/FieldValueMapper/MultipleStringMapper.php
eZ/Publish/Core/Search/Elasticsearch/Content/FieldValueMapper/StringMapper.php
eZ/Publish/Core/Search/Elasticsearch/Content/Mapper/StandardMapper.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/search_engines/common.yml
eZ/Publish/SPI/Search/FieldType/FullTextField.php

> #### This PR resolves https://jira.ez.no/browse/EZP-23247
> #### Review with https://github.com/ezsystems/ezplatform-solr-search-engine/pull/21
This implements `Indexable`s for `XmlText` and `RichText` field types.
Previously these were handled by `TextLine` implementation of `Indexable`.
Implementing this properly required separately indexing field type value as string field and as full text field.
String field indexes shortened variant of the field value, while full text field indexes complete text content of the field value. This is achieved by using new SPI search field type `FullText`. Fields of this type, in both Solr and Elasticsearch, are not stored, but instead copied to the real full text field.
This gives better control of what goes into full text index than was the case …

Implement EZP-23247: missing field type Indexable definitions

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
phpunit-integration-legacy-elasticsearch.xml
phpunit-integration-legacy-solr.xml
phpunit-integration-legacy.xml

This PR resolves https://jira.ez.no/browse/EZP-24294
The reported issue was apparently resolved since reported, this adds new test case testing data indexing on a search engine. For now only creating a Location and moving a subtree is tested, as was reported in the issue. More will be added later.

EZP-24294: Search not working correctly after decoupling from Persistence

---

eZ/Publish/Core/FieldType/XmlText/XmlTextStorage/Gateway/LegacyStorage.php

JIRA ticket related: https://jira.ez.no/browse/EZP-24779
**Issue:**
The problem appears if (for some unknown reason, ie. failed import from 3rd party system) there's no url link in database for content.
**Output:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ErrorMessage media-type="application/vnd.ez.api.ErrorMessage+xml">
<errorCode>500</errorCode>
<errorMessage>Internal Server Error</errorMessage>
<errorDescription>Notice: Undefined offset: 14179</errorDescription>
<trace>#0 /var/www/amnh/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldType/XmlText/XmlTextStorage/Gateway/LegacyStorage.php(95): Symfony\Component\Debug\ErrorHandler-&gt;handleError(8, 'Undefined offse...', '/var/www/amnh/v...', 95, Array)
#1 /var/www/amnh/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/FieldTyp …
```

EZP-24779 Fix undefined index when url link does no longer exist in DB

---

eZ/Publish/Core/Repository/Helper/DomainMapper.php

This PR resolves https://jira.ez.no/browse/EZP-24867
It appears when SPI has more fields than current content type definition

Fix EZP-24867: undefined offset when trying to build object from SPI

---

doc/specifications/security/policies_extensibility.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigBuilderInterface.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ContainerConfigBuilder.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/PoliciesConfigBuilder.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/PolicyProviderInterface.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/RepositoryPolicyProvider.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/YamlPolicyProvider.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/policies.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/policies1.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/policies2.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Security/PolicyProvider/PoliciesConfigBuilderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Security/PolicyProvider/YamlPolicyProviderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Stub/StubPolicyProvider.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Stub/StubYamlPolicyProvider.php
eZ/Publish/Core/settings/roles.yml

> https://jira.ez.no/browse/EZP-24862
This patch makes it possible for any bundle to expose available policies checkable against repository with a user. It introduces the concept of `PolicyProvider` which can be added to EzPublishCoreBundle's DIC extension.
A `PolicyProvider` is an object providing a hash containing declared modules, functions and limitations.
* Each policy provider provides a collection of permission *modules*.
* Each module can provide *functions* (e.g. "content/read": "content" is the module, "read" is the function)
* Each function can provide a collection of limitations.
Limitations need to be implemented as *limitation types* and declared as services (already in place).
```php
namespace Acme\FooBundle\AcmeFooBundle\Security;
use …
```

Fix EZP-24862: Expose available repository policies

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php
eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/User.php
eZ/Bundle/EzPublishRestBundle/Features/User/load_users.feature
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/UserTest.php
eZ/Publish/Core/REST/Client/Input/Parser/UserList.php
eZ/Publish/Core/REST/Client/Input/Parser/UserRefList.php
eZ/Publish/Core/REST/Server/Controller/User.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/OK.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Root.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RootTest.php
eZ/Publish/Core/REST/Server/Values/OK.php

> Implements [EZP-24820](https://jira.ez.no/browse/EZP-24820)
Adds support for `login` and `email` query parameters on `GET /user/users`. Will return the user(s) matching the criteria. While login might only return one user, email might return several if non unique emails are allowed.
Also adds support for `HEAD` requests on the same resource. In that case, it will either respond with a `200` (yes, there is content matching the filter) or `404` (couldn't find anything). It doesn't differenciate between no permissions and no content.
Testing is done via behat, with a scenario for each filtering method. This required adding (primitive) Input Parsers for `UserList` and `UserRefList`.

REST: verify existence of users by login or email

---

eZ/Publish/Core/MVC/Symfony/Cache/Http/FOSPurgeClient.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/FOSPurgeClientTest.php

JIRA: https://jira.ez.no/browse/EZP-24854
When issue http cache (varnish) purge requests, a regex is used with multiple location Ids.
The problem is that the regex is matching all locations that __contain__ the value, for example, banning location 2 will also ban 12, 20, 21.
vcl ref: ` ban("obj.http.X-Location-Id ~ " + req.http.X-Location-Id);`
https://github.com/ezsystems/ezplatform/blob/master/doc/varnish/vcl/varnish4.vcl#L116
Fix by making sure that location __is__ one of the requested (starts/ends with provided value)
Manual

Fix EZP-24854: http cache purge bans wrong/additional location ids

---

eZ/Publish/Core/REST/Common/Input/Handler/Xml.php

The REST XML Input Parser can't distinguish if a one item list is a unique item or a list. The test was failing while the feature was working since this affects the parser, only used in tests.

REST: Marked UserList.User as a forced list item

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/Tests/RichTextTest.php
eZ/Publish/Core/settings/fieldtype_services.yml
eZ/Publish/Core/settings/fieldtypes.yml
eZ/Publish/SPI/Tests/FieldType/RichTextIntegrationTest.php

This resolves https://jira.ez.no/browse/EZP-24423
RichText was using the same validator dispatcher to validate both the input value and the result of conversion to the internal format.
This makes internal format validator a separate dependency. Method `validate()` is now implemented, using internal format validator to validate the value in the internal format, either provided as such or converted from one of the input formats.
Also, input validator dispatcher is made optional.

Fix EZP-24423: RichText input validation

---

doc/specifications/proposed/named_queries/developer_documentation.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Stub/QueryTypeBundle/QueryType/TestQueryType.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Stub/QueryTypeBundle/QueryTypeBundle.php
eZ/Publish/Core/QueryType/ArrayQueryTypeRegistry.php
eZ/Publish/Core/QueryType/OptionsResolverBasedQueryType.php
eZ/Publish/Core/QueryType/QueryType.php
eZ/Publish/Core/QueryType/QueryTypeRegistry.php

> Story: https://jira.ez.no/browse/EZP-24623
The namespace is `eZ/Publish/Core/QueryType`.
Contains:
- The `QueryType` interface,
- `OptionsResolverBasedQueryType` abstract class,
- The `QueryTypeRegistry`,
- The compiler pass that registers services tagged as `ezpublish.query_type` with the Registry.

EZP-24623: Implemented QueryType API

---

eZ/Publish/Core/settings/search_engines/common.yml

This PR resolves https://jira.ez.no/browse/EZP-24294
The problem was search Slots were not configured when using the Repository in Symfony context.
Fixed by adding `slots.yml` to `common.yml`, as common for all search engines.

Fix EZP-24294: Search Not working correctly after decoupling from Persistence

---

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml

> Fixes https://jira.ez.no/browse/EZP-24910
It is used by many REST services, and some FieldTypeProcessors may depend on core repository services. Injecting those in a request listener, like the UserContentGateway from PlatformUIBundle, will initialize some settings (vardir) too early.
It materializes as invalid BinaryFileId exceptions unless the vardir is defined in the `default` scope.

Made REST FieldTypeProcessor registry lazy

---

eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php
eZ/Publish/Core/Persistence/Legacy/User/Handler.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
eZ/Publish/SPI/Persistence/User/Handler.php

> https://jira.ez.no/browse/EZP-24912
Now the previous role is correctly removed in favor of the role draft, which becomes the *published* role.
The same `roleId` is also kept (like for ContentTypes).

Fix EZP-24912: Publishing a role draft doesn't remove previous published role

---

eZ/Publish/API/Repository/RoleService.php
eZ/Publish/Core/Persistence/Legacy/User/Handler.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
eZ/Publish/Core/REST/Client/RoleService.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/Core/SignalSlot/RoleService.php
eZ/Publish/Core/SignalSlot/Tests/RoleServiceTest.php

> https://jira.ez.no/browse/EZP-24913
API has been updated to accept `PolicyDraft` object and gateway was also updated to stop discriminate policy draft vs regular policy removal.

Fix EZP-24913: Cannot remove a policy from a RoleDraft

---

eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php

> See https://jira.ez.no/browse/EZP-24897
When a `locationId` is passed to the view controller, this adds the Location object to the request attributes. It makes it possible to typehint the Location object instead of the locationId scalar. This should make preview of first versions of a location work in much more cases.
Tested by changing `DemoController::showBlogPostAction` to expect `Location $location` instead of `$locationId`. Before the change, previewing the first draft of a blog post would generate a fatal error. After the change it works as expected.

Added 'location' to locationView request attributes

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php

This PR fixes couple of issues with the new `_ez_content_view` route:
1) `ezpublish.controller.content` service does not exist, `ez_content` must be used instead. Additionally, when using the service notation here, `Action` should not be appended to action name. Thus, correct controller reference is `ez_content:viewContent`
2) `/content/view/{contentId}/{language}` route path clashes with legacy `/content/view/full/42` URLs. In order to avoid that, route path was renamed to `/view/content/{contentId}/{language}`.
3) The route was missing the `viewType` and `layout` parameters, which means that something like `/view/content/42/eng-GB` was failing with `Controller "eZ\Publish\Core\MVC\Symfony\Controller\Content\ViewController::viewContent()" requires that you provide a value for the …

Fix _ez_content_view route controller and allow fallback to legacy /content/view/full/42

---

eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php

After #1425, when no custom controller is specified in location view rules, they should automatically be converted to content view override rules. This is implemented in https://github.com/ezsystems/ezpublish-kernel/commit/e18b76458981c55fe1bc1618eb023f1f3de3a596.
However, since ContentView config parser is registered *after* LocationView config parser (which handles the conversion), and `$config` variable is passed around by value instead of by reference, ContentView parser just undos everything LocationView parser did in relation to automatic conversion.
Since LocationView provider also removes the rules it converted, the system is left without rules used to render the location/content view.
This makes sure LocationView parser is registered after ContentView parser, so conversion will …

Fix automatic conversion of location view rules to content view rules

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ViewProvidersPass.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ConfigScopeListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConfigScopeListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/Stubs/ViewProvider.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Event/APIContentExceptionEvent.php
eZ/Publish/Core/MVC/Symfony/View/CustomLocationControllerChecker.php
eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php

1) Template renderer needs special handling if template identifier is a closure
2) Dispatch `MVCEvents::PRE_CONTENT_VIEW` event prior to rendering the template, just as view manager did
3) Fix interface name in `APIContentExceptionEvent`

Fixes to controller refactoring

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/EmbedObjectParameters.php

Event handler that injects `$params['objectParameters']` as a standalone variable into view.

Add injector to inject embed objectParameters variable into template

---

eZ/Bundle/EzPublishCoreBundle/EventListener/CacheViewResponseListener.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ViewRendererListener.php
eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

This PR fixes two small issues:
1) Replicates all ViewController functionality in ContentViewBuilder and fixes typos
2) Again, same as in ViewController, if the response is not modified, ViewRendererListener should not render the content and X-Location-Id should not be set.

Fixes to view refactoring

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/BaseTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/022-embed.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/023-embedInline.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/027-linkedEmbed.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/028-linkedEmbedInline.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/001-embedContent.docbook.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/001-embedContent.xhtml5.edit.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/002-embedInlineContent.docbook.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/002-embedInlineContent.xhtml5.edit.xml

This PR resolves https://jira.ez.no/browse/EZP-24951
Conversion stylesheet for converting from XHTML5 edit format to the internal format was converting embed element's text content, which is in the case of edit format a div or span element. This was causing the validation of the converted result to fail when the source element contained text content.
The problem is fixed by applying conversion only on non-text children of the embed elements.
Additionally fixed: using `data-href` instead of just `href` on embed elements in XHTML5 edit format.

Fix EZP-24951: embed element's text content is converted from XHTML5 edit format

---

eZ/Bundle/EzPublishCoreBundle/behat.yml
eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php
eZ/Bundle/EzPublishRestBundle/behat.yml

> See ezsystems/ezplatform#55
In addition to moving the rest & core behat suites from ezplatform to ezpublish-kernel, this PR also changes the RestContext so that it gets the configured URL from Mink instead of re-declaring it in each suite.
This should make it possible to a) simplify the rest context arguments (format + driver should be sufficient) b) customize the base uri (including for REST) using the [`BEHAT_CONFIG` environment variable](http://docs.behat.org/en/v3.0/guides/6.profiles.html#environment-variable-behat-params).
Example:
```bash
export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "https://ez.loc/"}}}'
./bin/behat --profile=rest --suite=fullJson
```

BDD: config import + rest config

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

Title says it all :)
Eliminates the possiblity that you have  view with location that does not belong to content.

Throw exception if loaded location does not belong to content

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Publish/Core/Helper/ContentPreviewHelper.php
eZ/Publish/Core/Helper/Tests/ContentPreviewHelperTest.php

> JIRA issue: https://jira.ez.no/browse/EZP-24982
When previewing content in a siteaccess which is matched with URI type matching (e.g. http://example.com/cro), generated links loose their URI part.
The siteaccess is correctly set to preview subrequest, but not the info that it's an URI type matched siteaccess, which means that URLs can't be generated correctly.

Fix EZP-24982: Generating links when previewing content in siteaccess with URI matching does not work

---

eZ/Publish/API/Repository/RoleService.php
eZ/Publish/Core/REST/Client/RoleService.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/Core/SignalSlot/RoleService.php

> https://jira.ez.no/browse/EZP-24956
Added missing implementation, roughly identical to deprecated `RoleService::updatePolicy()`

Fix EZP-24956: Implement RoleService::updatePolicyByRoleDraft()

---

doc/specifications/config/semantic_configuration_integration.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php

This PR resolves https://jira.ez.no/browse/EZP-24999
The goal is to be able to define semantic configuration and default settings from external bundle, that will be available under standard `ezpublish` configuration root and subject to resolving (ConfigResolver).
This is achieved through two new methods in Core bundle extension, intended to be called from bundle's `build()` method:
* `addConfigParser()`
* `addDefaultSettings()`
Default settings could probably work if imported into standard `ezpublish.yml`, however this approach does not require manual configuration.

Implement EZP-24999: As a bundle developer I want to use standard ezpublish semantic configuration

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml

Hey guys,
I think that is a typo, but what a typo! It triggers the new name schema. That works... but it was impossible again to purge the variations..and it messes up the cluster...
You owe me a beer for that one ;-)
++

The ezpublish.image_alias.variation_path_generator should be use here

---

eZ/Publish/Core/IO/Tests/IOServiceTest.php
eZ/Publish/Core/Search/Tests/FieldNameResolverTest.php

Fixed broken covers statements so that code coverage generation works again. Otherwise PHPUnit will just abort test execution at each broken statement.

Fixed broken covers statements

---

eZ/Bundle/EzPublishCoreBundle/EventListener/CacheViewResponseListener.php

Previously, if you wanted to modify shared max age in your custom controller, you would do it directly in `Response` object that `ez_content:view(Location|Content)` returned.
Now, since setting shared max age is done in `CacheViewResponseListener` which subscribes to `KernelEvents::RESPONSE` event, it is not possible to set the custom shared max age in your controllers as it will be overwritten.
This makes sure shared max age is set only if not set previously in the response.
Similar thing is already done with `X-Location-Id` header which is set only if it was not set before (third `false` param in https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/EventListener/CacheViewResponseListener.php#L65).

Add the ability to set shared max age in custom controllers

---

eZ/Publish/API/Repository/Tests/FieldType/BinaryFileIntegrationTest.php

This makes tests less fragile as it removes the need to override test method that other tests depend on in order to skip the tests for specific search engine.
See https://github.com/ezsystems/ezpublish-kernel/pull/1483

Fixed tests: Use dedicated method for checking search engine support

---

eZ/Publish/API/Repository/Tests/FieldType/FileSearchBaseIntegrationTest.php
eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php

> Fix for https://jira.ez.no/browse/EZP-24959
Makes sure that a null fieldValue will delete stored data.

Fix EZP-24959: binary field data isn't removed

---

eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
eZ/Publish/SPI/Tests/FieldType/BinaryFileIntegrationTest.php

> JIRA: https://jira.ez.no/browse/EZP-25039
The PR makes sure that both `id` and `mimeType`, if provided in the update data, are ignored. The mimeType is generated from the filepath instead.
This also rewrites a bit the store method to be clearer.

EZP-25039: Updating a BinaryFile field with a different mimetype will fail

---

eZ/Publish/Core/Repository/RoleService.php

Since we changed back to the old style of role versioning, a role draft does not have the same id as the published version. Instead we have to check the `originalId` of the draft. ~~This was not exposed in the API - added here order to fix the bug.~~ We check this using SPI roles, which know about the originalId.
https://jira.ez.no/browse/EZP-24939

Fix EZP-24939: Updating a role to the same name raises a notification error

---

eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php

> JIRA issue: https://jira.ez.no/browse/EZP-25032
I have a custom provider which uses a custom user class with DOES NOT extend `eZ\Publish\Core\MVC\Symfony\Security\User` class, but it DOES implement `eZ\Publish\Core\MVC\Symfony\Security\UserInterface`.
Since I want to use eZ repository to check for user authentication, this combination is not possible since eZ Publish `RepositoryAuthenticationProvider` explicitly checks if user is an instance of `eZ\Publish\Core\MVC\Symfony\Security\User` class instead of checking for `eZ\Publish\Core\MVC\Symfony\Security\UserInterface`.
This PR changes the provider to use the interface rather than the concrete implementation of User class.

Fix EZP-25032: Repository authentication provider cannot be used with custom user classes

---

eZ/Publish/Core/FieldType/Image/ImageStorage.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/BinaryInputProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/BinaryInputProcessorTest.php
eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php

> Fixes https://jira.ez.no/browse/EZP-24922
There are two issues here:
PlatformUI re-uses the current Image Field Value when updating a field, the id is always passed. Since the id was checked before the inputUri, the inputUri was always ignored. Doing so shouldn't prevent the file from being updated, since it is a calculated value. 
The PR makes sure that `inputUri` has precedence over `id` if both are given. This behaviour is covered by the integration test update.
The processor was creating the file from `data`, and passing this file as `path`, a property that is now deprecated. It has been changed to use `inputUri`, and the test was updated.
The SPI test doesn't cover this, as it belongs to the REST layer.
The behaviour has been tested on PlatformUI, by …

EZP-24922: Image file can't be updated over REST

---

eZ/Bundle/EzPublishRestBundle/Features/Content/user_content.feature
eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php
eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/EzRest.php
eZ/Bundle/EzPublishRestBundle/Features/Context/UserContentContext.php
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Bundle/EzPublishRestBundle/behat.yml
eZ/Publish/Core/REST/Client/Input/Parser/ErrorMessage.php
eZ/Publish/Core/REST/Client/Input/Parser/Version.php
eZ/Publish/Core/REST/Client/Input/Parser/VersionInfo.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/ContentTypeCreateStruct.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/LocationCreateStruct.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/RestContentCreateStruct.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/VersionUpdate.php
eZ/Publish/Core/REST/Client/Tests/Input/Parser/BadStateExceptionTest.php
eZ/Publish/Core/REST/Client/Tests/Input/Parser/InvalidArgumentExceptionTest.php
eZ/Publish/Core/REST/Client/Tests/Input/Parser/NotFoundExceptionTest.php
eZ/Publish/Core/REST/Client/Tests/Input/Parser/VersionInfoTest.php
eZ/Publish/Core/REST/Client/Tests/Output/ValueObjectVisitor/LocationCreateStructTest.php
eZ/Publish/Core/REST/Client/Values/Content/Content.php
eZ/Publish/Core/REST/Client/Values/Content/VersionUpdate.php
eZ/Publish/Core/REST/Client/Values/ErrorMessage.php
eZ/Publish/Core/REST/Server/Values/RestContentCreateStruct.php

> Testing branch for https://github.com/ezsystems/PlatformUIBundle/pull/401
> See BDD @ https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/87190070#L944
> Ready for review
Adds coverage for creation of users with the REST Content API (instead of the User API).
Would belong to PlatformUIBundle, but since PlatformUI is installed in the kernel, and we have the REST test infrastructure, it is acceptable I think to have it in here.
Some of the REST Client (only used by rest afaik) parsers/visitors were returning REST ids (`/path/to/resource/id`) while the ones in the Server namespace use "normal" ids. I'm not 100% sure about the change, but to the best of my knowledge, it does work fine.
The error improvement changes two things:
- the parser doesn't _throw_ exceptions anymore, it returns …

[BDD] PlatformUI User/Content controller

---

eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml

Seems to be a error in eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml which makes it impossible to change ez_io.metadata_handler because it will be instantiated as a binarydata handler

Fixed ezpublish.core.io.metadata_handler.flysystem service to be instantiated from correct class

---

eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/User/Mapper.php

> https://jira.ez.no/browse/EZP-25079
Related PRs: https://github.com/ezsystems/repository-forms/pull/57 / https://github.com/ezsystems/PlatformUIBundle/pull/426
Legacy storage engine: This ensures that all policies inside a RoleDraft (`ezrole_version !== 0`) is a PolicyDraft (i.e. has `originalId !== null`), including when a new policy is added to the role draft.
Before, when adding a policy to a role draft, the new policy was not considered as a draft since it didn't have any reference from an existing policy (`ezpolicy_original_id`). Result was that we ended with a RoleDraft object having mixed PolicyDraft and Policy objects.
Now `originalId` is filled with the newly created policy's ID.

Fix EZP-25079: When saving a new policy draft module/function choice is lost

---

eZ/Publish/Core/REST/Common/Input/ParserTools.php
eZ/Publish/Core/REST/Common/Tests/Input/ParserToolsTest.php

JIRA: https://jira.ez.no/browse/EZP-25093
when using the REST API with a JSON input, you are forced to use boolean as string (ie `"false"` or `"true"`) which is a bit stupid given you can put real boolean values in JSON.
This patch improves the REST parser tools to be a bit smarter on that.
(This was discovered in https://github.com/ezsystems/PlatformUIBundle/pull/431 / https://github.com/ezsystems/ez-js-rest-client/pull/68 / [EZP-25091](https://jira.ez.no/browse/EZP-25091))
manual tests for EZP-25091 (and added unit tests, just waiting for Travis to run them).

Fix EZP-25093: REST API does not accept real boolean value as input

---

eZ/Publish/API/Repository/Values/Content/ContentCreateStruct.php
eZ/Publish/API/Repository/Values/Content/LocationCreateStruct.php
eZ/Publish/API/Repository/Values/ContentType/ContentTypeCreateStruct.php
eZ/Publish/API/Repository/Values/ContentType/FieldDefinitionCreateStruct.php
eZ/Publish/API/Repository/Values/ObjectState/ObjectStateCreateStruct.php
eZ/Publish/API/Repository/Values/ObjectState/ObjectStateGroupCreateStruct.php
eZ/Publish/API/Repository/Values/User/UserCreateStruct.php
eZ/Publish/Core/FieldType/Image/Value.php

> https://jira.ez.no/browse/EZP-25100
These tags are actually useless and are not taken into account by PHPDoc.
Problem is they conflict with Symfony (well actually Doctrine) annotation reader, used by Validation component.
They lead to exceptions like:
```
[Semantical Error] The annotation "@required" in property 
eZ\Publish\API\Repository\Values\Content\ContentCreateStruct::$contentType was never imported. 
Did you maybe forget to add a "use" statement for this annotation
```

EZP-25100: Removed @required doc tags on value objects properties

---

eZ/Publish/Core/REST/Server/Input/Parser/ContentUpdate.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/ContentUpdateTest.php

> Fixes https://jira.ez.no/browse/EZP-24901
The location id path string wasn't converted to a numerical id. Leftover from the initial implementation. The test has been updated, but I haven't tested it in real life.

Fix EZP-24901: error in REST location id parsing

---

.travis.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/block/block.html.twig

> Fixes bugs that slipped through in #1496 / EZP-25121

Fixes for EZP-25121

---

eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php

Quick fix to allow legacy bridge tests that error out to run.
They depend on this test class but can't access the property.
See: https://github.com/ezsystems/LegacyBridge/pull/43

Mark test property as protected to allow legacy bridge tests to run

---

eZ/Publish/Core/FieldType/Selection/Type.php
eZ/Publish/Core/FieldType/Tests/SelectionTest.php

> Part of https://jira.ez.no/browse/EZP-25002
> Other PRs for this: https://github.com/ezsystems/repository-forms/pull/56 and https://github.com/ezsystems/PlatformUIBundle/pull/417
Require at least one selection option in order to validate the field type settings.

Fix EZP-25002: Unable to add more options to ezselection field type

---

eZ/Publish/API/Repository/Values/Content/Content.php
eZ/Publish/Core/REST/Client/Values/User/User.php
eZ/Publish/Core/REST/Client/Values/User/UserGroup.php
eZ/Publish/Core/Repository/Values/Content/Content.php
eZ/Publish/Core/Repository/Values/User/User.php
eZ/Publish/Core/Repository/Values/User/UserGroup.php

Issue: https://jira.ez.no/browse/EZP-25041
User and UserGroup do not implement getField method, which in turn means they can not be used with translation and field helper, nor can the ez_field_value and ez_render_field be used directly on User/UserGroup (only on their 'content' property, accessed via magic method).
As they can be used however with ez_render_name, for example, and considering they do extend abstract 'content' class, it would make sense for them to behave in the same way the Content itself does.
This PR moves getField method to abstract class Content and implements it in User and UserGroup.

EZP-25041 implement getField method on User and UserGroup

---

eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestExecutedView.php

> Implements https://jira.ez.no/browse/EZP-25151
Adds `count`, with the total results count, to the Result node.
Also adds `time`, `timedOut` and `maxScore`, as per [specs](https://github.com/ezsystems/ezpublish-kernel/blob/master/doc/specifications/rest/REST-API-V2.rst#L7464-L7467).

EZP-25151: total count in REST search results

---

eZ/Publish/Core/FieldType/RichText/Normalizer/DocumentTypeDefinition.php
eZ/Publish/Core/FieldType/Tests/RichText/Normalizer/DocumentTypeDefinitionTest.php

> Fixes https://jira.ez.no/browse/EZP-24732
The normalization done on input XML in #1489 wasn't applied if the XML didn't include an XML declaration tag. PlatformUI doesn't include it.
According to @dpobel, it is optional in XML 1.0 (and according to what I've read online.
- Updated unit test
- Manual test with [damien's script](https://github.com/dpobel/TestCommandsBundle/blob/master/Command/CreateRichTextEntitiesCommand.php)
- Manual CURL test on create content
- Manual PlatformUI test

EZP-24732: run normalization even if no XML declaration

---

eZ/Publish/Core/FieldType/Selection/Type.php
eZ/Publish/Core/FieldType/Tests/SelectionTest.php

> Fixes https://jira.ez.no/browse/EZP-25178
> Regression from https://jira.ez.no/browse/EZP-25002
The validator requires at least one option to pass, which makes sense, but since the validator also runs when the field type is added, before the user has had a chance to add any options, it fails here. (If we're going to have this check we need to run it in a different way.)

Fix EZP-25178: Adding a "selection" field to a content type raises an error

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php

Fix coverage tests added in https://github.com/ezsystems/ezpublish-kernel/pull/1531
This is essentially calling SOLR's `commit()` after publishing content, otherwise search results will be wrong/empty.
Used to verify: ezsystems/ezplatform-solr-search-engine#31

[Integration] Fix FieldRelation Criterion coverage tests

---

data/update/mysql/unstable/dbupdate-6.0.0rc1-to-6.0.1rc1.sql
data/update/postgres/unstable/dbupdate-6.0.0rc1-to-6.0.1rc1.sql
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php

Legacy SE did not handle hidden state at all, adding that.

EZP-24467: Location visibility on move when new parent is hidden/invisible

---

data/cleandata.sql

Fixes https://jira.ez.no/browse/EZP-25275
This pr removes to policies from the cleandata.sql file so they don't appear in the platfrom ui interface. 
Second part of this will be added to legacy-bridge.
Tasks
---------

EZP-25275: Remove unneeded policies from platform clean install

---

composer.json

- Updated ezpublish-kernel package description
- Removed legacy-dir extra param
- Changed dev-master branch alias 6.1.x-dev

[composer.json] description, branch-alias, and legacy config

---

.travis.yml

Should make Travis test 2.8.0 (the previous line led to an error, since inline aliasing requires an exact version number).

[travis] Fixed Sf 2.8 in the test matrix

---

eZ/Publish/Core/FieldType/RichText/Converter/Xslt.php

Link to Jira task: https://jira.ez.no/browse/EZP-25068
This fix was originally proposed by @gggeek in https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/4
I can confirm that it fixes XSLT issue on Windows file system with RichText field type.

EZP-25068: XSLT warning on windows for rich text fields

---

.travis.yml
bin/.travis/prepare_unittest.sh

Travis was using the  sf version from the composer.lock instead of the newly required version.  This requires and updates to the correct version regardless of the lock file.

Fix travis composer require for alternate sf version

---

.travis.yml
composer.json
composer.lock

Update to tst Symfony 2.8 by default , and bump php requirements while at it to avoid conflicts and align for planned bump next year.
Flysystem needs a bump to 1.0 as well, but as it changes a bit *(and breaks tests)* I'll leave that for @bdunogier.

[Composer] Re allow symfony 2.8 for testing

---

eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fos_http_cache.yml

…ward requests.
JIRA: https://jira.ez.no/browse/EZP-25204
When performing internal request forwards (such as using a non-default `index_page` as described in the JIRA issue), FOSHttpCache will add headers to the `Vary:` response header.
This happens because it will not find the `user_hash_header` , so will add what is defined in `user_identifier_headers` : `Cookie` and `Authentication` by default.
Ref: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/EventListener/UserContextSubscriber.php#L134
The suggested approach is to: 
1. add the user-hash header to the forwarded request if it is already set, and
2. (optional) remove 'Cookie' from the `user_identifier_headers` config, as ezp kernel implements and uses its own user-hash generator, and the cookie vary should be added …

Fix EZP-25204: FosHttpCache sets 'Vary:Cookie' for forward requests.

---

doc/specifications/template/ez_functions.md
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/content_functions/ez_field.test
eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php

Link: https://jira.ez.no/browse/EZP-25329
As the ticket mentions, this adds a simple twig helper function that returns the whole Field so that it can be used for example for ez_image_alias().
I tried seeing whether I should write some tests for this, but I'm not sure. Same goes for the documentation, should I extend that as well?
Example of how this could be used in combination with ez_image_alias:
```
{% set thumb_image_variation = ez_image_alias( ez_translated_field( content, "image" ), content.versionInfo, "gallerythumbnail" ) %}
```

Implement EZP-25329: getTranslatedField twig helper function

---

eZ/Publish/API/Repository/ContentTypeService.php
eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
eZ/Publish/Core/REST/Client/ContentTypeService.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/SignalSlot/ContentTypeService.php
eZ/Publish/Core/SignalSlot/Tests/ContentTypeServiceTest.php

> Fixes https://jira.ez.no/browse/EZP-24848
> Also requires https://github.com/ezsystems/PlatformUIBundle/pull/479
Adds a count method to check for existing content, used with CT delete buttons.

Fix EZP-24848: Content Type removal does not take into account Contents in the trash

---

eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ImageExtension.php

This PR fixes https://jira.ez.no/browse/EZP-25149 by catching an exception raised in `vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php` when an image could not created from the input, e.g. when the source file is invalid.

EZP-25149: Catch a yet uncaught exception in ez_image_alias

---

data/cleandata.sql

Update to use the final place for the technical documentation, also only point to space when pointing to front page to avoid issues if frontpage is renamed.

Update eZ Platform doc url

---

eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SiteAccessListenerTest.php
eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php

JIRA: https://jira.ez.no/browse/EZP-25171
When I copy a URL with ViewParameters in Firefox. The Url will be UTF8 encoded. So the brackets are %28 and %29
E.g.: http://www.example.tld/site/(param)/value -> http://www.example.tld/site/%28param%29/value
The new stack can now not match the route and give it to the legacy. There it can be matched.
When I look in the code I see, that the rawurldecode function has been used only for the semanticPathinfo:
https://github.com/ezsystems/ezpublish-kernel/blob/2267c6e903c38b027b3b97e2901ccf0923bcbbad/eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php#L126
In legacy it works because of:
https://github.com/ezsystems/ezpublish-legacy/blob/e6c912113a8cee636070d2ac1fcbd308f713b97e/lib/ezutils/classes/ezuri.php#L224

Fix EZP-25171: UTF8 Encoded ViewParameters are not matched

---

doc/bc/changes-6.0.md
eZ/Publish/API/Repository/Values/Content/ContentInfo.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentBase.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php

Issue: https://jira.ez.no/browse/EZP-25377
When publishing existing content (creating new version) with the PAPI, the publication date of the content gets the current datetime, same as modification date. While modification date behavior is correct, the publish date of the content should remain unchanged to reflect the original (first) publish date of the content.
Publishing from legacy administration does just that - changes only modification date.
To reproduce:
- load content
- create draft
- modify content with updatestruct
- publish new draft
Expected outcome: original content and republished content have the same publishedDate but different modificationDate.
Actual outcome: republished content has different publishedDate than original content.
I have added the regression test, but …

EZP-25377 fix republish modifying publication date

---

eZ/Publish/Core/FieldType/Tests/TextLineTest.php
eZ/Publish/Core/FieldType/TextLine/Type.php
eZ/Publish/Core/FieldType/Validator/StringLengthValidator.php

Fixes https://jira.ez.no/browse/EZP-25342
Related pr https://github.com/ezsystems/repository-forms/pull/66 even is not mandatory to merge one before the other. 
ping @bdunogier @andrerom @lolautruche

Fix EZP-25432 In Textline fieldtype, is being permitted the "Minimum length" and "Maximum length" to have negative values

---

doc/bc/changes-6.1.md
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/HostElement.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/URIElement.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostElementTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElement2Test.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElementTest.php

JIRA: https://jira.ez.no/browse/EZP-25337
This replaces #1476
The problem is that configuration parser always creates arrays out of the matcher settings, which URIElement and HostElement did not take into account see https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php#L217: 
```
// Value passed to the matcher should always be an array.
// If value is not an array, we transform it to a hash, with 'value' as key.
```
The tests still passed because an int was used for the constructor, with the proposed fix no changes should be necessary.

Fix EZP-25337: URIElement SA matcher wrong value

---

composer.json

Need to accept `ezsystems/behat-bundle` 6.2 (dependencies injection support), even though it is not used by the kernel yet.

[dependencies] be more flexible on behat-bundle

---

eZ/Publish/Core/Repository/Helper/FieldTypeRegistry.php
eZ/Publish/Core/Repository/Tests/Helper/FieldTypeRegistryTest.php

Small fix in `Repository\Helper\FieldTypeRegistry`.
This did not register on integration tests because PHPUnit will first run field type tests (as configured by `<directory>`), so when FieldTypeService tests run all field types will already be initialised in container and faulty code will not be reached.

Fixed: do not return single field type

---

eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php

https://jira.ez.no/browse/EZP-25454
Fixes:
```
[PDOException]                                                                                           
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'sort_key_string' at row 1
```

EZP-25454: Limit sort key string to avoid strict errors on MySQL 5.7

---

eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
eZ/Publish/Core/FieldType/Tests/RichText/Validator/DocbookTest.php

JIRA: https://jira.ez.no/browse/EZP-25448 (and https://jira.ez.no/browse/EZP-25028)
While working on https://github.com/ezsystems/PlatformUIBundle/pull/510, I found that the RichText field does not accept element with 2 (or more) classes. This patch fixes that issue by changing the `ezpublish.rng` schema so that the `ezxhtml:class` accepts any `CDATA` (see `class` attribute definition in the XHTML1 DTD https://www.w3.org/TR/xhtml1/dtds.html#a_dtd_XHTML-1.0-Strict and http://relaxng.org/tutorial-20011203.html#IDA0FYR)
This also fixes EZP-25028 because thanks to this schema change, `ezxhtml:class` class also be empty.
unit tests + manual test in https://github.com/ezsystems/PlatformUIBundle/pull/510

EZP-25448: RichText field does not accept element with 2 classes

---

bin/.travis/prepare_unittest.sh
eZ/Publish/Core/MVC/Symfony/View/ContentView.php
eZ/Publish/Core/MVC/Symfony/View/Tests/ContentViewTest.php
eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php

> Fixes http://jira.ez.no/browse/EZP-25294 and https://jira.ez.no/browse/EZP-25470
> Replaces #1542
Fixes a fatal error that occurs when an item  is viewed as an embed. The `location` is set to null instead of not being set at all. This prevents the variable from being set if there is no location, as [suggested by @andrerom](https://github.com/ezsystems/ezpublish-kernel/pull/1542#issuecomment-169713854).
This should be okay. If a location is being viewed, the variable will be set. If a content is being viewed, users do not expect the variable to exist.
Also fixes the solr integration test failure ([EZP-25470](https://jira.ez.no/browse/EZP-25470)) in pull-requests against 6.1.

Fix EZP-25294: do not set the location if there isn't one

---

eZ/Publish/Core/Limitation/Tests/SubtreeLimitationTypeTest.php
eZ/Publish/Core/Repository/Values/Content/Query/Criterion/PermissionSubtree.php
eZ/Publish/Core/Search/Elasticsearch/Content/CriterionVisitor/SubtreeIn.php
eZ/Publish/Core/Search/Elasticsearch/Content/Location/CriterionVisitor/SubtreeIn.php
eZ/Publish/Core/Search/Legacy/Content/Location/Gateway/CriterionHandler/Subtree.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_content.yml

https://jira.ez.no/browse/EZP-25334
This replaces https://github.com/ezsystems/ezplatform-solr-search-engine/pull/34 by undoing e30d1de5c3ccefa563dc6760dd376199db4b2e4f that was done as part of #912.
Review ping @pspanja, input on how we can test to make sure right handler is used with Legacy SE? And should probably also find a way to cover subtree limitation on content and location search to make sure integration works.
Test ping @harmstyler

EZP-25334: Missing PermissionSubtree Criterion Visitor on Solr

---

data/update/mysql/unstable/dbupdate-6.1.0-to-6.2.0rc1.sql
data/update/postgres/unstable/dbupdate-6.1.0-to-6.2.0rc1.sql

Also better document the issues that can turn up as part of the schema change.
ping @crevillo @emodric

EZP-19123: Missing SQL to copy ezuser.login to login_normalized

---

bin/.travis/prepare_unittest.sh

Assuming that this might be the issue causing #1388 to fail now on mysql.

[Travis] Make sure UTF8 is always used for test databases

---

eZ/Publish/Core/FieldType/Tests/TimeTest.php
eZ/Publish/Core/FieldType/Time/Type.php

Link: https://jira.ez.no/browse/EZP-25375
In order to fix this issue I first created a PR on the PlatformUIBundle https://github.com/ezsystems/PlatformUIBundle/pull/501
Then I ran into the kernel bug on the Time FieldType. I had to override the `isEmptyValue()` to take care of the specificity of the `Value` of the Time FieldType.
Trying to unit test this bug, I ran into an Assert bug on type comparison, which was hiding the actual bug. Fixing the unit test bug led into revealing other FieldType bugs (TextLine, TextBlock and Email) which will be dealt with in https://jira.ez.no/browse/EZP-25424.
Unit test and manual test on Time field.

Fix EZP-25375: Error when setting 00:00 on Time FieldType

---

eZ/Publish/Core/REST/Server/Controller/User.php

When CSRF protection is disabled with `framework.csrf_protection.enabled` flag set to false, site crashes with an exception about missing `security.csrf.token_manager` service.
Required by: https://github.com/ezsystems/PlatformUIBundle/pull/515

EZP-25482: Do not use CSRF token manager if not available

---

eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php

This fixes a possible discrepancy in published/modifed dates when publishing content.
This was discovered after some unrelated tests ran in Netgen variant of ezpublish-kernel 2014.12: https://travis-ci.org/netgen/ezpublish-kernel/jobs/111418231 and failed at random times. This looks like a possible solution to that failing test. In any case, the fix doesn't hurt and is "more correct" :)

EZP-25377: Fix possible timing issues and discrepancies in published/modified dates

---

eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Publish/Core/REST/Server/Controller/Role.php

> Fixes https://jira.ez.no/browse/EZP-24830
Implements REST methods for new role draft functionality:
NB: For `testCreateRoleDraft()` we have to pass RoleInput-XML even though this is not actually used in the controller. It's a POST, so we have to send some kind of document. Could we send an empty XML doc instead, or something more elegant?
NB2: BD found that we have inadvertently broken BC half a year ago, this is corrected here by ensuring that `createRole` defaults to publishing the role. To return a draft instead (the currently preferred way) pass "publish=false".
NB3: Should the REST API doc be updated now? Or a new V3 created?
https://github.com/ezsystems/ezpublish-kernel/blob/master/doc/specifications/rest/REST-API-V2.rst#user-management

Fix EZP-24830: REST methods for role drafts

---

eZ/Publish/Core/Limitation/OwnerLimitationType.php
eZ/Publish/Core/Limitation/ParentOwnerLimitationType.php

**JIRA ticket related:** https://jira.ez.no/browse/EZP-25522
It would allow use of `Owner`: `self` limitation that would give user access to its own user content object.
Ie: 
The problem could be resolved by setting proper roles and limitations from UI without additional backend work.
It still require giving group access to `/1/5/X` location and careful set of editing permissions so editor would not be able to modify other users.

EZP-25522: User is not able to get variation of his profile image

---

composer.json
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
eZ/Publish/Core/Helper/FieldsGroups/RepositoryConfigFieldsGroupsListFactory.php
eZ/Publish/Core/Helper/Tests/FieldsGroups/ArrayTranslatorFieldsGroupsListTest.php
eZ/Publish/Core/Helper/Tests/FieldsGroups/RepositoryConfigFieldsGroupsListFactoryTest.php

> Implements http://jira.ez.no/browse/EZP-25376
> Version change: adds a new feature, bumps master to `6.3.x-dev`
New settings are added to define available content fields groups identifiers for a repository:
```
ezpublish:
repositories:
default:
fields_groups:
list: ["content", "metadata"]
default: "content"
```
The entries are groups identifiers.
An `@ezpublish.fields_groups.list` service gives access to the values.
It uses an `ArrayTranslator` implementation of the newly added `FieldsGroupsList` interface. It is constructed by `@ezpublish.fields_groups.list.repository_settings_factory`, a `RepositoryConfigFieldsGroupsListFactory`, that reads settings using `@ezpublish.api.repository_configuration_provider`

EZP-25376: Settings based fields groups implementation

---

eZ/Bundle/EzPublishCoreBundle/Fragment/FragmentListenerFactory.php
eZ/Bundle/EzPublishCoreBundle/Tests/Fragment/FragmentListenerFactoryTest.php

> Re-opening of #1588 against `6.2` branch
> Fixes https://jira.ez.no/browse/EZP-25475
Amended a cosmetic fix as well as unit tests update.
Can be merged when Travis passes, as #1588 had enough +1 already.

Fix EZP-25475: no request under CLI in FragmentListenerFactory

---

.travis.yml
bin/.travis/prepare_behat.sh
eZ/Bundle/EzPublishCoreBundle/Features/Content/content_preview.feature
eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentPreviewContext.php
eZ/Bundle/EzPublishCoreBundle/behat_suites.yml
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php

> Re-post of #1604 onto `6.1`
> Fixes http://jira.ez.no/browse/EZP-25460
`/content/versionview` works by forwarding a ContentView internal request with a pre-loaded content, in the requested version. The `PreviewController` is only setting `location`, not `content`. The ContentViewBuilder loads the Content item based on parameters, using the published version by default.
The `[travis]` commit removes quotes around the tags. Having those caused problems (when used through env vars) and prevented behat from finding any scenario.
BDD that fails on Travis for this particular case.

EZP-25460: draft preview shows published version

---

composer.json

This is a temporary solution for 6.1 (and possibly 6.0) branch, in case #1601 is not intended to be backported.
This limits FOS HTTP Cache bundle to version 1.3.6 which does not cause the issue described in https://jira.ez.no/browse/EZP-25533

EZP-25533: Temporary limit FOS HTTP Cache bundle to <= 1.3.6

---

doc/behat/README.md
eZ/Bundle/PlatformBehatBundle/Context/Argument/AnnotationArgumentResolver.php
eZ/Bundle/PlatformBehatBundle/Resources/config/services.yml
eZ/Bundle/PlatformBehatBundle/ServiceContainer/EzBehatExtension.php

As decided BehatBundle is to be deprecated and separated between the kernel and platformUI bundle. The idea is to make the Behat easier to maintain, having less repo dependencies should help releases and versions also.
This PR moves the EzBehatExtension and AnnotationArgumentResolver into the kernel. This is used to inject into behat the necessary services. Since this is to be used by most contexts it should be in the kernel.
Related PRs:
* Behat browser context #1585
* Add RepositoryContext trait #1584
* Deprecate Behat classes https://github.com/ezsystems/BehatBundle/pull/48

[POC - Behat] Add EzBehatExtension and ArgumentResolver

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Publish/Core/REST/Server/Controller/Role.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/PublishedRole.php
eZ/Publish/Core/REST/Server/Values/PublishedRole.php

> Fixes https://jira.ez.no/browse/EZP-25610
Role draft publishing currently returns HTTP 201 Created. This is wrong, it should be used only for newly created resources. Content publishing returns HTTP 204 No Content, we should do the same for roles.
This fixes the return value, and updates the test and api doc.

Fix EZP-25610: Publishing a role draft with REST should return HTTP 204

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Publish/Core/REST/Server/Input/Parser/Limitation/PathStringRouteBasedLimitationParser.php
eZ/Publish/Core/REST/Server/Input/Parser/Limitation/RouteBasedLimitationParser.php
eZ/Publish/Core/REST/Server/Input/Parser/RoleAssignInput.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Limitation/PathStringRouteBasedLimitationParserTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Limitation/RouteBasedLimitationParserTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/RoleAssignInputTest.php

> Fixes REST blocker https://jira.ez.no/browse/EZP-25539
REST limitation values reference another value object, depending on the limitation type (section, etc).
The spec says that those references are expected to be hrefs (`/content/sections/2`), but the current implementation uses raw ids (`2`).
This PR fixes it by introducing LimitationValue parsers for `Section` and `Subtree` (limitation types supported by `RoleAssignment` with limitation). They both use a `RouteBasedLimitationParser`, that parses the limitation value id using the router.

Fixed href parsing in REST limitation value

---

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php

Issue: https://jira.ez.no/browse/EZP-23445
Target: **6.3** *(contains deprecations and changes)*
1. With Symfony_ENV being now used most other places as of [eZ Platform 1.0](https://github.com/ezsystems/ezplatform/pull/70), it now makes sense to take it into account here as well.
2. Get rid of the question, behave more like other commands, and use ezpublish-asset-dump-env for bc but deprecate with a error saying use of Symfony_ENV is preferred.

EZP-23445: Take SYMFONY_ENV into account in asset dump composer scripts

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Repository/LocationService.php

Issue: https://jira.ez.no/browse/EZP-25648
Should be allowed to update a location with the same remote id, as it won't produce a duplicate.

EZP-25648: Allow location update with same remoteId

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/CacheFactory.php
eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
eZ/Bundle/EzPublishCoreBundle/ApiLoader/StorageConnectionFactory.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php
eZ/Bundle/EzPublishCoreBundle/Matcher/BlockMatcherFactory.php
eZ/Bundle/EzPublishCoreBundle/Matcher/ContentMatcherFactory.php
eZ/Bundle/EzPublishCoreBundle/Matcher/LocationMatcherFactory.php
eZ/Bundle/EzPublishCoreBundle/Matcher/ServiceAwareMatcherFactory.php
eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/ApiLoader/ElasticsearchEngineFactory.php
eZ/Bundle/EzPublishIOBundle/ApiLoader/HandlerFactory.php
eZ/Bundle/EzPublishIOBundle/DependencyInjection/ConfigurationFactory.php
eZ/Bundle/EzPublishIOBundle/DependencyInjection/ConfigurationFactory/Flysystem.php
eZ/Bundle/EzPublishLegacySearchEngineBundle/ApiLoader/ConnectionFactory.php
eZ/Publish/Core/Base/Container/ApiLoader/FieldTypeCollectionFactory.php
eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Base/Container/ApiLoader/Storage/ExternalStorageRegistryFactory.php
eZ/Publish/Core/MVC/Symfony/Controller/Controller.php
eZ/Publish/Core/REST/Server/Controller.php

> Implements https://jira.ez.no/browse/EZP-25335
Replaces usage of abstract `ContainerAware` with the `ContainerAwareTrait`.

Fix EZP-25335: Use ContainerAwareTrait instead for sf 2.8+ support

---

doc/specifications/security/authentication_symfony.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/full.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/pagelayout.html.twig
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/ViewbaseLayout.php

Here's another try to solve this. In this case i create a new `pagelayout.html.twig` template and a new param in `templating.yml` file. i called it `ezpublish.pagelayout`. Better naming suggestions are very welcomed :). 
The `full.html.twig`extends that new `viewBaseLayout`.
One concern about this is what if the user tries something like 
```twig
{{ render( controller( "ez_content:viewAction", {'contentId': contentId, 'viewType': 'full', 'noLayout': 1} ) ) }}
```
In this case, shouldn't we modify full template to check if ```noLayout``` is true or false?
ping @andrerom @emodric @bdunogier

EZP-25627 provide default layout template allowing show sf toolbar

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/HttpCachePass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/IO.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/HttpCachePassTest.php

> https://jira.ez.no/browse/EZP-25098
Fixes an issue with Symfony 2.8+ when container is being compiled just before a regular request. This issue was introduced by the new Twig cache warmer, which loads Twig context and its extensions. Some of them depend indirectly on the `ConfigResolver`, while there is no SiteAccess context yet (cache warming occurs just after container compilation).
The fix consists in marking the affected services as lazy.
I also removed a unused call to the config resolver in IO config parser (separate commit).
IMHO this should also be backported to 5.4 in order to make it compatible with Symfony 2.8

Fix EZP-25098: [Symfony 2.8] First load doesn't load the configuration

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/SlugConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/SlugConverterTest.php

> Fix https://jira.ez.no/browse/EZP-25623
This adds tests to https://github.com/ezsystems/ezpublish-kernel/pull/1624 by @clash82, and extends the fix to `urlalias_compat`.
Changes:
- `urlalias`: As described in issue, commas are now removed instead of being converted to dots
- *NB: After this fix, exclamation marks are no longer removed!* Is this correct? (Answering myself: Yes, I think this is correct. Before and after the fix, the underlying `cleanupText()` by itself would keep the `!`. But `convert()` would remove it, because it would convert it to a dot, which would in turn be removed by `cleanupText()`. So if it is correct to *not* convert the `!`, then it should not be removed either.)
- `urlalias_iri`: No change, not affected by issue
- `urlalias_compat`: …

Fix EZP-25623: Wrong content object URL path after content update

---

eZ/Bundle/EzPublishRestBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishRestBundle/DependencyInjection/EzPublishRestExtension.php
eZ/Bundle/EzPublishRestBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RootTest.php
eZ/Publish/Core/REST/Common/Values/Resource.php
eZ/Publish/Core/REST/Common/Values/Root.php
eZ/Publish/Core/REST/Server/Controller/Root.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Root.php
eZ/Publish/Core/REST/Server/Service/ExpressionRouterRootResourceBuilder.php
eZ/Publish/Core/REST/Server/Service/RootResourceBuilderInterface.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RootTest.php

> JIRA: https://jira.ez.no/browse/EZP-25613
This adds the ability to add resources in the rest root so rest consumers can discover them. For example you can register the resource and use the capi auto discovery to find the uri for the resource.
To add a resource a bundle would add the resource using the PrependExtensionInterface and pre-pending the new resource to the config.

[WIP] EZP-25613 Add a way to register resources with the rest root

---

doc/behat/README.md
eZ/Bundle/PlatformBehatBundle/Context/RepositoryContext.php

As decided BehatBundle is to be deprecated and separated between the kernel and platformUI bundle. The idea is to make the Behat easier to maintain, having less repo dependencies should help releases and versions also.
This PR moves the RepositoryContext trait into the kernel. This is trait contains all the methods related to the repo . Since this is to be used by any contexts that need the repo it should be in the kernel to be easily included and not duplicate.
Related PRs:
* Behat browser context #1585
* Add EzBehatExtension and ArgumentResolver #1586
* Deprecate Behat classes https://github.com/ezsystems/BehatBundle/pull/48

[POC - Behat] Add RepositoryContext trait

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/URI.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterMapURITest.php

> Reopening of #1555 by @Simounet against 6.1
Adds test + a fix for the mirror case (`/foo` => `/`).

EZP-25453: improve root uri handling in Map\URI siteaccess matcher

---

eZ/Bundle/PlatformBehatBundle/Resources/config/services.yml

JIra: https://jira.ez.no/browse/EZP-25761
AnnotationArgumentResolver fails in php7 because it is being executed after Symfony2Extension's ArgumentResolver (which creates actual parameter instances).
The problem only happens in php7 because both services have the same priority and sort has a different behavior from php5.
The fix is to tag the service with a higher priority.

Fix EZP-25761: Increase annotation argument resolver priority

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/URI.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterMapURITest.php

JIRA: https://jira.ez.no/browse/EZP-25783
Currently when using `Map\URI` siteaccess matcher the matching fails if the URI has utf8 characters,
while this should be possible (and was in legacy).
This resolves the problem by making sure the matcher map key is not urlencoded 
(`"Äpfel"` != `"%C3%84pfel"` )
TODO:

Fix EZP-25783: URI SiteAccess matching fails with utf8

---

eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

Fixes: https://jira.ez.no/browse/EZP-25717
> Status: TBD
Some status information, for more please watch discussion in #1639.
>So after a long time of investigation, because there were a lot of incosistency with my test behavior (once it worked, and the other time it wasn't) i got an conclusion that the methods are missbehaving on top of how many times there where called.
>So the problem is how many times we hit the ->lookup('/path') method, why?
> 1. The first call loads an urlAlias, and stores it in cache#stash_default#ez_spi#urlalias#url#media.
> 2. The second call, loads from cache cache#stash_default#ez_spi#urlalias#url#media and loads urlPath from persistence mechanism and stores to the cache the alias with cache#stash_default#ez_spi#urlalias#0-62933a2951ef01f4eafd9bdf4d3cd2f0# ID!! …

EZP-25717: Fix all alias types cleaning

---

eZ/Publish/Core/IO/Tests/UrlDecorator/AbsolutePrefixTest.php
eZ/Publish/Core/IO/UrlDecorator/AbsolutePrefix.php

This change allows the usage of absolute urls like
`//static.example.com`
without them being turned into relative urls.

Fix to support urls with ommited schemes.

---

composer.json
composer.lock

Bump to (0.5) to:
- avoid issues with PHP 5.3 Stash legacy Session compat layer when doing composer install --optimize-autoload *(which is usable now on PHP 5.6+ as of Composer 1.1)*
- have a version fully tested in PHP7
- more bug fixes
*Not bumping to 0.6 here as it breaks a lot of things, so it's a bit bigger effort.*
*Side: Loosened requirements for StashBundle in https://github.com/ezsystems/ezplatform/commit/6e630756175d2ad5e0859914aef2afe306ae67d3*

[Composer] Bump Stash Bundle version

---

eZ/Publish/Core/Search/Common/FieldNameResolver.php
eZ/Publish/Core/Search/Tests/FieldNameResolverTest.php

Issue: https://jira.ez.no/browse/EZP-25309
1. This changes the approach from https://github.com/ezsystems/ezpublish-kernel/pull/1551 to return [search field types](https://github.com/ezsystems/ezpublish-kernel/tree/master/eZ/Publish/SPI/Search/FieldType) per field name, instead of field type's Indexable implementation. 
2. For custom fields we now return null, as it is impossible to resolve field type in a programatic way. This means if custom field types are used (by CustomFieldCriterion and custom field interfaces implemented by the field criterion), that the value provided to Criterion needs to be of correct type (and for the custom field value being indexed).

EZP-25309: Fix for hardcoded custom fields search field names

---

eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

Fixes: https://jira.ez.no/browse/EZP-25773
Added due to feature request in #1646

EZP-25773: Cache warmup for urlAlias object

---

composer.json

Reverts ezsystems/ezpublish-kernel#1659
realized this will cause issues if someone updates composer lock on php 7, as 2.0 only support 7.

Revert "[Composer] Bump Proxy manager support"

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Publish/Core/REST/Server/Input/Parser/Criterion.php
eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Input/Parser/SortClause/DataKeyValueObjectClass.php
eZ/Publish/Core/REST/Server/Input/Parser/SortClause/GenericDataKey.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/SortClause/DataKeyValueObjectClassTest.php

> Implements https://jira.ez.no/browse/EZP-24315
Continues on the work from @Nattfarinn in https://github.com/ezsystems/ezpublish-kernel/pull/1651 - Thank you!

Fix EZP-24315: Add support for sorting in REST Views

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Publish/Core/REST/Server/Input/Parser/Criterion.php
eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Input/Parser/SortClause/GenericDataKey.php

**JIRA Ticket related**: https://jira.ez.no/browse/EZP-24315
Example of use (JSON):
```json
{
"ViewInput": {
"identifier": "FilterArticleByOwnerIdExample",
"Query": {
"Criteria": {
"ContentTypeIdentifierCriterion": "article"
},
"SortClauses": {
"DatePublished": "ascending"
},
"limit": "10",
"offset": "0"
}
}
}
```
**Important**: Implementing every single missing SortClause parser is not part of it.

EZP-24315: Handling SortClauses is missing in REST Views (ie. DatePublished)

---

composer.json

Because of change done in 9bbde1ad6cab84b213feb1934a0f88a939f09926, caused by break in https://github.com/sensiolabs/SensioDistributionBundle/commit/4fd740b02261672cc4e41a78791af35935424b7f, we need to require higher version of `sensio/distribution-bundle` to avoid error if this is installed with older version of `sensio/distribution-bundle`.
4.0 is same as 3.0 branch but besides ACME bundle code generation stuff, so technically we should be able to support both. 5.0 branch seems to be more for when we switch to Symfony 3.x.
Doing this to avoid further User painted himself into a corner issues, as found [here](https://jira.ez.no/browse/EZP-25774), once 9bbde1ad6cab84b213feb1934a0f88a939f09926 is out in more EE releases and people do composer update on their own.

[Composer] Bump requirements for sensio/distribution-bundle

---

eZ/Publish/Core/REST/Server/Input/Parser/Limitation/PathStringRouteBasedLimitationParser.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Limitation/PathStringRouteBasedLimitationParserTest.php

> Fix https://jira.ez.no/browse/EZP-25817
Ensures that the `_href` ends with a slash, being tolerant of PlatformUI not doing this (yet), to avoid breaking things.
The master fix will throw an exception, requiring a fix in PlatformUI: https://github.com/ezsystems/ezpublish-kernel/pull/1671

Fix EZP-25817: Invalid subtree path when assigning role with subtree limitation

---

eZ/Publish/API/Repository/Tests/FieldType/RelationBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/Core/Base/Exceptions/ContentFieldValidationException.php
eZ/Publish/Core/FieldType/RichText/Type.php

Make sure to take all tag variants of embed and link into account.
@pspanja Is this correct? From other tests it seemed to be what should be looked for at this stage.
As for embed => ezembed, as far as I understood it getRelations are performed after the input value transformations are done, so it should indeed always be docbook tag names we should expect here, right?
Otherwise: Found several more @todos about embeds, is something missing on embeds as far as you know?
Review ping @bdunogier, @pspanja @alongosz

EZP-25849: Content embedded within RichText not available via Relations

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml

> Fixes [EZP-25907](https://jira.ez.no/browse/EZP-25907)
> Unblocks ezsystems/PlatformUIBundle#622
Implements missing basic sort clauses.

Missing REST sort clauses

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_image.html.twig
eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

> Status: work in progress
> Fixes http://jira.ez.no/browse/EZP-25875
Renders embedded images using a dedicated template.
- Adds a default view configuration that matches embed images by content type identifier. The list of content-types is configurable.
- Adds a default, configurable, `EzPublishCoreBundle:default:content/embed_image.html.twig` template. It displays the first filled image field of the embedded content, using the variation configured in the embed.
- Adds an `ez_first_filled_image_field` twig function that, given a  content, returns the identifier of the first image field that is not empty.
There are two main customization use-cases:
Customizing which content types are considered as images, and rendered as such, is done by setting the …

EZP-25875: embed image view

---

doc/specifications/rest/REST-API-V2.rst
doc/specifications/rest/xsd/View.xsd
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml

Updates the XSD schemas forgotten when SortClauses were implemented in REST (#1687, #1677)
Also changes the definition of sort clause services to match the Symfony standards (lowercase services). Other services will have to be fixed as well, but it will take a bit of effort in order not to break BC.

Update REST SortClauses XSD schemas

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml

Title says it all.
The service definition wasn't correctly indented, and the service not defined at all.

Fix EZP-25929: incorrect DateModified REST SortClause definition

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/text_linked.html.twig

The ezobjectrelation_field template block uses the 'text_linked' view for the related content's sub-request. Since it is not defined by default, rendering fails.
This fixes it by defining a default `content_view` rule for the `text_linked` view type. The template can be customized, like other default view templates, using a container parameter:
```
parameters:
ezplatform.default_view_templates.content.text_linked: "content/view/text_linked.html.twig"
```

Fix EZP-25559: Added missing text_linked default view template

---

eZ/Publish/Core/IO/IOMetadataHandler/Flysystem.php
eZ/Publish/Core/IO/Tests/IOMetadataHandler/FlysystemTest.php

> Fixes https://jira.ez.no/browse/EZP-25937
> Reboot of #1611 by @ostark
In some cases `$info['timestamp']` is not defined, e.g if 'LastModified' is not set for an S3 object:
https://github.com/thephpleague/flysystem/blob/0.5.12/src/Adapter/AwsS3.php#L486.
Changes from #1611:
- Unit test added
- CS fixed
- Added JIRA issue

Fix EZP-25937: Undefined index timestamp when using Adapter/AwsS3

---

eZ/Publish/Core/MVC/Exception/NoViewTemplateException.php
eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php
eZ/Publish/Core/MVC/Symfony/View/Tests/Renderer/TemplateRendererTest.php

> Implements [EZP-25940](http://jira.ez.no/browse/EZP-25940)
When a view is rendered without a template being set, the error message is not informative enough:
```
An exception has been thrown during the rendering of a template ("Unable to find template """)
```
This changes the message as follows:
```
An exception has been thrown during the rendering of a template ("No view template was set to render the view with the 'text_linked' view type. Check your view configuration.")
```
Also adds a unit test to `TemplateRenderer`, that cover both a standard `render()` and a `render()` without a template.

EZP-25940: Improve error when rendering a view without a template

---

eZ/Publish/Core/Base/Container/ApiLoader/FieldTypeNameableCollectionFactory.php

`FieldTypeNameableCollectionFactory` was introduced at the same time than deprecated `ContainerAware` usage was removed, and still uses it.
Changes it to use `ContainerAwareInterface` + the trait.

Fix EZP-25984: FieldTypeNameableCollectionFactory uses ContainerAware

---

bin/.travis/prepare_unittest.sh
eZ/Publish/API/Repository/Tests/Values/User/Limitation/ParentDepthLimitationTest.php
eZ/Publish/Core/Limitation/ParentDepthLimitationType.php
eZ/Publish/Core/Limitation/Tests/ParentDepthLimitationTypeTest.php

This PR resolves https://jira.ez.no/browse/EZP-25280
As described in the comment on the issue, the problem comes from missing Location on publishing the first Content draft. Solution is similar to what was already done for [`LocationLimitationType`](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Limitation/LocationLimitationType.php#L142).
Added failing/fixed integration test and missing unit tests.

Fix EZP-25280: ParentDepth Limitation fails on content creation

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/BasicContentContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentTypeContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/FieldTypeContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/RoleContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/UserContext.php

In order to deprecate `BehatBundle` repository some Contexts will be moved into the kernel.
Making the Contexts `classes` and not `traits` (as some of them still are in BehatBundle) should improve the overall flexibility and maintainability of the code.
One if the main objectives is to use this Contexts with other Bundles BDD, such as PlatformUI, running each behat suite with the various needed Contexts instead of one with everything.
PS: this PR contains a lot of code but it has already been reviewed before, the code was just moved basically.

[Behat] Add BasicContent, ContentType, Field, Role and User Contexts

---

eZ/Bundle/EzPublishRestBundle/behat_suites.yml

@bdunogier / @miguelcleverti seem to be missing to get more specs to run with xml suite, but this and more is maybe fixed in #1654?

[Behat] Add missing config for UserContentContext

---

composer.json
composer.lock
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/IO.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishIOBundle/DependencyInjection/Factory/LocalAdapterFactory.php
eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php

> Implements [EZP-25676](https://jira.ez.no/browse/EZP-25676)
This updates the league/flysystem dependency to 1.0, and adds configuration for permissions of generated files.
The default values are `0755` for directories, and `0644` for files.
The values can be customized with siteaccess aware semantic config:
```
ezpublish:
system:
default:
io:
permissions:
files: 0750
directories: 0640
```

Updated flysystem dependency to ^1.0

---

eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php

Aim: get skipped tests down to 0 for Solr so we can enable fail on skipped to get rid of this^ black spot in our testing matrix.
^ *from time to time tests are skipped by mistake, including depends issues, and we don't detect it until we do an effort on it.*

[Integration] Reduce skipped tests

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed.html.twig

Ezobjectrelationlist on the front end won't generate the links to the add objects, however in Platform UI they appear correctly
Steps: 
1. Add Content with a Ezobjectrelationlist and some objects related
2. Send for publishing
3. Verify in Platform UI that the links to the related objects are present and they work
4. Access to the Content in the frontend. The objects names are present but the links are missing

EZP-26015 - Ezobjectrelationlist on the frontend misses the links to the objects

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php

> Fixes [EZP-26106](https://jira.ez.no/browse/EZP-26106) and [EZP-26086](https://jira.ez.no/browse/EZP-26086)
If a QueryType is tagged with `ezpublish.query_type`, it will be skipped (using the class name) by the convention registration.
The "class" parameter will be correctly interpreted to the actual value in order to retrieve the QueryType's name with the static call.
Both cases are covered by the QueryTypePass's unit test.

Query type pass fixes

---

eZ/Bundle/EzPublishRestBundle/EventListener/RequestListener.php
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Bundle/EzPublishRestBundle/Tests/EventListener/RequestListenerTest.php

**JIRA ticket related:** https://jira.ez.no/browse/EZP-26080
Currently `RequestListener` forces developers to use predefined REST prefix for every REST call (it's `/api/ezp/v2` by default) even if custom REST actions are not `ezp` nor `v2`.
Proposed solution is to match prefix with pattern `/api/{name}/v{version}/` and allow to prefix (and version) custom REST routes, without BC break.
`{name}` - only letters (upper and lowercase), digits, underscore and dash
`{version}` - up to two-level version number (for example `1`, `2` but also `1.5`)

EZP-26080: Can't register REST routes with different prefix

---

eZ/Bundle/EzPublishRestBundle/DependencyInjection/Compiler/OutputVisitorPass.php
eZ/Bundle/EzPublishRestBundle/Tests/DependencyInjection/Compiler/OutputVisitorPassTest.php

**JIRA ticket related**: https://jira.ez.no/browse/EZP-26110
You can define custom output visitors and tag it (`name: ezpublish_rest.output.visitor, regexps: something`) but it won't work with current implementation unless you load your bundle before `new eZ\Bundle\EzPublishRestBundle\EzPublishRestBundle(),` (and this way sucks). It's because of order of output visitors passed to compiler pass while kernel configuration contains Pokemon "gotta catch'em all" regexp `(^.*/.*$)` so it always return `application/vnd.ez.api...` regardless of visitors and generators registered after that one.
**Solution**: Proposed solution is to implement `priority` tag attribute similar to ones used in Symfony event listeners or cache warmers with default `0` in case of missing attribute.
**Example of use**: …

EZP-26110: Can register custom OutputVisitor but can't set its priority

---

eZ/Publish/API/Repository/Tests/FieldType/FileBaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/FileSearchBaseIntegrationTest.php
eZ/Publish/Core/IO/IOService.php
eZ/Publish/Core/IO/TolerantIOService.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/LocationAwareStore.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/LocationAwareStoreTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/URIElement.php

Status: **Ready for review**
To move forward with #1724 we need to fix some errors revealed while running CI tests on Windows.
**TODO**:

EZP-25942: Fix errors specific to Microsoft Windows operating system

---

eZ/Bundle/EzPublishRestBundle/Features/Context/RestContext.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Publish/Core/REST/Client/Exceptions/ServerException.php
eZ/Publish/Core/REST/Client/Input/Parser/ErrorMessage.php
eZ/Publish/Core/REST/Client/Values/ErrorMessage.php

Makes sure exception from server is shown in test output by passing it on.
Note: As always server need to run in debug mode to provide file, line and trace info *(Not included in REST response in prod for security reasons)*.

[Tests] Provide more debug info on Functional test server failures

---

.travis.yml
composer.json
composer.lock
eZ/Publish/Core/Persistence/Cache/CacheServiceDecorator.php
eZ/Publish/Core/Persistence/Cache/Tests/Helpers/IntegrationTestCacheServiceDecorator.php

Using Stash bundle v0.6 is not safe* without the following fixes, adding this to 6.5 and not 6.4 as stash api changed.
\* Number of integration test failures before fixes on cache decorator _(effectively all)_:
```
FAILURES!
Tests: 972, Assertions: 430, Errors: 587, Failures: 100, Skipped: 7979, Incomplete: 6.
```

[Stash] Update to Stash Bundle v0.6

---

appveyor.yml

This PR solves [EZP-25942](https://jira.ez.no/browse/EZP-25942) introducing [AppVeyor](https://appveyor.com/) (continuous integration tool for Windows) project file.
Sample PR presenting working integration: [alongosz/ezpublish-kernel/pull/1](https://github.com/alongosz/ezpublish-kernel/pull/1).
**TODO**:

EZP-25942: As a Maintainer I want Continuous Integration on Windows so we can move towards better supporting it

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/slot.yml
eZ/Publish/Core/MVC/Symfony/Cache/GatewayCachePurger.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/InstantCachePurger.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/LocalPurgeClient.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/DeleteContentSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/DeleteLocationSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/PurgeAllHttpCacheSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/PurgeForContentHttpCacheSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/RecoverSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/TrashSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/PurgeClientInterface.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/InstantCachePurgerTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/AbstractPurgeForContentSlotTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/DeleteContentSlotTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/RecoverSlotTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/TrashSlotTest.php
eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/DeleteLocationSignal.php
eZ/Publish/Core/SignalSlot/Signal/TrashService/RecoverSignal.php
eZ/Publish/Core/SignalSlot/Signal/TrashService/TrashSignal.php
eZ/Publish/Core/SignalSlot/TrashService.php

In theory fixes:
- http://jira.ez.no/browse/EZP-25003
- https://jira.ez.no/browse/EZP-24621
- https://jira.ez.no/browse/EZP-24944
- https://jira.ez.no/browse/EZP-26107
Changes:
- Adds TrashSlot and RecoverSlot
- Adds affected parentLocation on Trash and DeleteLocation signal, pass this to purge function
- Adds affected contentId on Recover signal so cache clearing can clear relevant cache.
Also done but can be moved to other PR if needed:
- Avoid exception on DeleteContent signal  by purging all cache *(for now, afaik UI exposes Trash so should not be to common)* as we don't have affected locations atm, end solution is multi tag and just clear content id related tags as a later follow up feature.
- Some cleanup on argument name for purge().
- ~~See if REST functional tests actually use …

EZP-25003: clear HTTP cache when trashing and recovering content

---

eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/REST/Client/HttpClient/ConnectionException.php
eZ/Publish/Core/REST/Client/Input/Parser/ErrorMessage.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/ViewInput.php
eZ/Publish/Core/REST/Client/Values/ErrorMessage.php
eZ/Publish/Core/REST/Server/Controller/Content.php
eZ/Publish/Core/REST/Server/Exceptions/ContentFieldValidationException.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ContentFieldValidationException.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ContentFieldValidationExceptionTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentBase.php
eZ/Publish/Core/Repository/Tests/Service/Integration/UserBase.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php

> Implement https://jira.ez.no/browse/EZP-24853
Treat "required field is missing" errors the same as field validation errors, so that both can be dealt with at the same time. Meaning that `ContentValidationException` is no longer thrown on content create/update, only a `ContentFieldValidationException` containing all errors. ~~`ContentFieldValidationException` now extends `ContentValidationException`, to avoid API change.~~ (reverted)
The errors are structured as below. Note: There may be more than one error per field, so that's an array. It's currently not indexing by fielddef identifier as requested, but rather by fielddef ID, since that's what we get from the core `ContentFieldValidationException`. The `type` is what is given by …

Ezp24853 enhance rest when failing save create draft

---

composer.json
composer.lock

Status: **Proof of Concept**
Although `v5.0` seems to be more for Symfony `3` due to directory structure changes, it should work with Symfony `2.8`.
It would allow us to get rid of very long deprecation warning in web apps log files in order to fully solve [EZP-26128](https://jira.ez.no/browse/EZP-26128).
This PR was created to test and discuss if it is possible.

[PoC] [Composer] EZP-26128: Bump requirements for sensio/distribution-bundle to v5.0

---

bin/.travis/prepare_behat.sh
eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php

> Fixes http://jira.ez.no/browse/EZP-26188
> Required by #1726
Merges global twig variables into the context in the `ez_render_*` helpers.
To test, use either app or `ezpublish` variables in `content_edit.html.twig`. Without the patch, an error about a missing variable is thrown.

Fix EZP-26188: Add twig globals to fields templates

---

doc/specifications/rest/REST-API-V2.rst
eZ/Publish/Core/REST/Server/Controller/Location.php

Link: https://jira.ez.no/browse/EZP-26116
When deleting an object with more than one location using REST, a 500 error is thrown because `$trashItem` is `null`.
It is supposed to be `null` as it is the expected result from the API (no object has been deleted but only one of its location, no trashitem has been created). https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/TrashService.php#L113
It is safe regarding BC as before it crashed and now it doesn't.
Manual test.

Fix EZP-26116: Error trashing an object with multiple locations

---

.travis.yml
composer.json
composer.lock
eZ/Bundle/EzPublishCoreBundle/EventListener/DynamicSettingsListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/DynamicSettingsListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/LocaleListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php

Adds fixes to get tests to pass with Symfony 3.x, this is just one step towards later provide full Symfony 3.0 support scheduled for eZ Platform 2.0 *(no date yet, but after 1.x LTS is made in December is the goal)*.
Followup:
- ~~Update FosHttpCache to get rid of Guzzle 3 dependency *(Guzzle is downgraded from v3.9.3 to v3.8.1 by Composer here because it is needed by version of FosHttpCache we use and since that version of Guzzle and earlier wrongly does not specify Symfony version requirement)*~~ *Actually not solved in FosHttpCache at all yet as master, aka 2.0 is not out, so more of an issue for them to solve.*
- PHPUnit-bridge: https://github.com/ezsystems/ezpublish-kernel/pull/1754
- Setup Behat testing with Symfony 3 at some point, but we probably need to change dir layout first …

[Composer] Add kernel support for Symfony 3.0

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Router.php

JIRA: https://jira.ez.no/browse/EZP-25913
When using SiteAccess Router (or a service that depends on it) in a console command ('cli' siteaccess) a notice is thrown (siteAccess property is not matched/set).
Fix: just check the property first.

EZP-25913: notice in SiteAccess\Router in console command

---

eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SiteAccessListenerTest.php

JIRA: https://jira.ez.no/browse/EZP-26149
When using an URI string such as `/(p1)/v1//v2` , SiteAccessListener tries to identify the name of the second view parameter:
```php
// We extract it + the value from the following segment (next element in $vpSegments array)
if ($vpSegments[$i]{0} === '(') {
```
If it is an empty string, a PHP notice is generated (Uninitialized string offset: 0).
This skips the process for empty viewParameter segments

Fix EZP-26149: PHP notice when using empty view parameter name

---

eZ/Publish/Core/settings/search_engines/slots.yml

Assumed (wrongly) that Platform UI was not using UserService for things like delete, so missed this one.

EZP-26228: Backport missing user slot config for EZP-26186

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php

> https://jira.ez.no/browse/EZP-26125
When trying to generate the URL for content which does not have any of the translations specified for current siteaccess and is not always available, the following error is thrown:
```
Some mandatory parameters are missing ("language") to generate a URL for route "_ez_content_view"
```
The most common reason why this happens (and hardest to debug) is when a content embeds or links to another content which does not have proper translations.
In case of such content, internal route is used to generate the URL to the content, but language cannot be reliably provided to the route. This removes the `language` parameter from the internal route in order not to crash the page. IMO, I'd rather have an internal link showing up than internal server error showing …

EZP-26125: Missing language parameter when generating _ez_content_view route

---

composer.json
composer.lock

> Fixes http://jira.ez.no/browse/EZP-25533
> Replaces #1601 
> **Requires https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/289** _and_ a new tag of it
Removes the version restriction set on friendsofsymfony/http-cache-bundle. Sets the 1.3 requirement to 1.3.8 (not yet released).

EZP-25533: removed http-cache-bundle version restriction

---

bin/.travis/prepare_behat.sh
eZ/Bundle/EzPublishRestBundle/EventListener/CsrfListener.php
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Bundle/EzPublishRestBundle/Tests/EventListener/CsrfListenerTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTypeTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Publish/Core/REST/Server/Controller/User.php

> Relates to [EZP-26179](https://jira.ez.no/browse/EZP-26179) / [ezsystems/platform-ui-bundle#668](https://github.com/ezsystems/PlatformUIBundle/pull/668#issuecomment-243796772)
> Implements [EZP-26720](https://jira.ez.no/browse/EZP-26270) (use session auth in REST functional tests)
> Fixes [EZP-25038](https://jira.ez.no/browse/EZP-25038) (error when logging in with REST if a session was started before)
According to the specifications, `/api/ezp/v2/user/sessions/<id>/refresh` must throw a 404 if the session doesn't exist / has expired.
Because of the CSRF token check in the CsrfListener, a 401 is thrown because the csrf token verification fails, as the session has expired, and we don't have a stored token anymore.
This changes the CsrfListener to skip this route, and explicitly checks in …

Fix EZP-26179: REST session refresh must throw a 404 if session has expired

---

doc/specifications/rest/REST-API-V2.rst
doc/specifications/rest/xsd/ErrorMessage.xsd

> Fixes https://jira.ez.no/browse/EZP-26239
Adds `errorDetails` to the schema.
This reminds me of something...

Fix EZP-26239: Missing update of REST-API-V2.rst about validation

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php

This PR resolves https://jira.ez.no/browse/EZP-26344
When URL alias is published, it is checked against a list of reserved words, in order to avoid the conflict with app modules.
This is done before URL alias name is converter/sluggified, so it is possible that a reserved name will be published.
Example: `claß` checked against reserved `class` will not match, but it's later converted/sluggified and published as `class`.
Follow up: https://jira.ez.no/browse/EZP-26345

EZP-26344: Publishing URL alias does not always respect reserved names

---

eZ/Bundle/EzPublishRestBundle/Features/Context/RestClient/BuzzDriver.php
eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/REST/Server/Controller/SessionController.php
eZ/Publish/Core/REST/Server/Controller/User.php

> Implements [EZP-26179](http://jira.ez.no/browse/EZP-26329)
> Refactoring of the changes from https://github.com/ezsystems/ezpublish-kernel/pull/1769
Delete, create and refresh session actions are deprecated in the User controller,
and moved to a new one, SessionController.
The REST functional tests now cover most of the session interactions, and passed without any issue. The code was moved as is from the updated one in the User controller, and Container calls changed to injected properties.

Refactored session rest actions to their own controller (EZP-26329)

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/LanguageAwareTestCase.php
eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
eZ/Publish/Core/settings/search_engines/legacy/services.yml

Status: **Ready for a review**
JIRA issue: [EZP-26219](https://jira.ez.no/browse/EZP-26219)

EZP-26219: Add Integration test coverage to verify search index after operations affecting it

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Search/Common/Slot/AssignSection.php
eZ/Publish/Core/Search/Common/Slot/SwapLocation.php
eZ/Publish/Core/Search/Common/Slot/UpdateContentMetadata.php
eZ/Publish/Core/settings/search_engines/slots.yml

Status: **Ready for a review**
This is a `v6.4` backport of #1776, related to JIRA issue [EZP-26219](https://jira.ez.no/browse/EZP-26219).
This PR adds some missing Search Engine slots for Signals affecting Search Engine Index.
**TODO**:

EZP-26219: Add missing Slots for Signals affecting Search Engine Index

---

eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php

Issue: https://jira.ez.no/browse/EZP-26342
Replaces #1788 _(for now does not retain invalid data on purpose in db, we'll need to look at that as a separate feature as it affects to many things)_
In addition work that was done on adding validation to field relations in a generic way was moved to #1796.

EZP-26342: Don't throw during on relation list data issue when creating drafts

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/full.html.twig
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php

Jira: https://jira.ez.no/browse/EZP-26281
Missing language in full.html.twig for PreviewController
This fix corrects problem of missing language in full.html.twig for PreviewController.
In full.html.twig is used eZ\Publish\Core\Repository\Values\Content\Content method getFieldsByLanguage without $languageCode parameter.
When we use this template in other languages than mainLanguageCode, method getFieldsByLanguage is returned empty array.

EZP-26281 Missing language in full.html.twig for PreviewController

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTypeTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
eZ/Publish/Core/REST/Server/Controller/ContentType.php
eZ/Publish/SPI/Persistence/Content/Type/Handler.php

> Status: **Ready for a review**
> Fixes: [EZP-26277](https://jira.ez.no/browse/EZP-26277)
> Backported to: `6.4`
This PR shortens generated identifiers of content type copies.
Instead of:
`copy_of_<identifier>_<remoteId>`
now we have:
`cpy_<identifier>_<remoteId>`
Also, `<remoteId>` is no longer a `md5` hash but a `sha1` hash shortened to 7 chars. We can't get rid of `<remoteId>` in copied content type identifier because it would be impossible to copy content type several times.
Another possible approaches:
- Make database identifier field longer than 50 chars - as suggested in JIRA issue description. However AFAIK performance of `varchar` varies between DBMS-es and should be tested on large databases (about 2 mln of Content Objects).
- Force API Consumer to specify copied content …

EZP-26277: Content type copies generated identifiers are too long

---

eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/REST/Common/FieldTypeProcessor/BaseRelationProcessor.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/RelationListProcessor.php
eZ/Publish/Core/REST/Common/FieldTypeProcessor/RelationProcessor.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RelationListProcessorTest.php
eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/RelationProcessorTest.php

> Implements [EZP-23000](http://jira.ez.no/browse/EZP-23000)
Uses the `postProcessValueHash()` method of the `RelationProcessor` and `RelationListProcessor`.
These links aren't really "complete" from an HATEOAS perspective, as they're missing the media-type. Full relation data must be taken from the `Relations` node, using the href + field def identifier to identify the matching `Relation` node.
```
<fieldValue>
<value key="destinationContentId">42</value>
<value key="destinationContentHref">/api/ezp/v2/content/objects/42</value>
</fieldValue>
```
```
<fieldValue>
<value key="destinationContentIds">
<value>42</value>
<value>300</value>
</value>
<value key="destinationContentHrefs">
<value>/api/ezp/v2/content/objects/42</value>
<value>/api/ezp/v2/content/objects/300</value>
</value> …
```

EZP-23000: Add destination content href to Relation(List) REST value

---

data/cleandata.sql

> https://jira.ez.no/browse/EZP-26412
Largest content ID is 51, but `ezcobj_state_link` table references IDs 52, 54 and 56, which causes create content operation to crash for content which gets those IDs.

Fix EZP-26412: Query error when publishing content on clean eZ Platform install

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Search/Common/Slot/UpdateContentMetadata.php

> Status: **Ready for a review**
> Fixes: [EZS-1009](https://jira.ez.no/browse/EZS-1009)
Use case: sending for a review applies to drafts and it triggers `UpdateContentMetadataSignal`. `UpdateContentMetadata` Search Slot introduced in #1779 should ignore drafts.
Looking from the Kernel side - it is possible to update Content Metadata for drafts, so Search Slot should check if content is published before trying to index it.
**TODO**:

EZS-1009: Send for review does not work for draft version

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_inline.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_inline.html.twig

> https://jira.ez.no/browse/EZP-26243
By default, the embed templates in rich text field type render the entire page. This is something we never want, so this disables the behaviour.
Ofcourse, the specific embed template which user overrides still can control this by not honoring the `noLayout` flag, but by default, the layout should be disabled.

Fix EZP-26243: Default embed templates in rich text field type render the whole page

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/Helper/ContentInfoLocationLoader.php
eZ/Publish/Core/Helper/ContentInfoLocationLoader/SudoMainLocationLoader.php
eZ/Publish/Core/Helper/Tests/ContentInfoLocationLoader/SudoMainLocationLoaderTest.php
eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

> Fixes [EZP-26381](https://jira.ez.no/browse/EZP-26381)
Makes the `ContentViewBuilder` load the main Location if none was asked / provided as an argument.
Fixes display of relation field values, as they use a ContentView with the `text_linked` view type, and the template only generates a link to the related content if a location is provided.
An alternative fix would be to use the content and mainLocationId as arguments in the text_linked template (tested works as well):
```
<a href="{{ path( "ez_urlalias", {"locationId": content.contentInfo.mainLocationId} ) }}">{{ content_name }}</a>
```
But I believe that there is nothing wrong with making the main location available.

ContentViewBuilder will load the main location if none was asked

---

eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadRedirectionController.php

Link: https://jira.ez.no/browse/EZP-25918
When a file (`content/download`) is requested using REST, information regarding the file is computed in order to call the generic download route. Then a redirect is made.
The issue here is that the redirect is permanent `HTTP 301`. So the web browser stores it. If the file is later modified, the browser will use its redirection cache and call the old URL, so information won't be computed and the user will get an outdated file.
The patch changes the type of redirection to a non permanent one `HTTP 302`.
Manual tests

Fix EZP-25918: Download redirect code should not be permanent

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Views.php
eZ/Bundle/EzPublishRestBundle/Features/Views/query.feature
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/Criterion/ContentTypeIdentifier.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/Query.php
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/ViewInput.php
eZ/Publish/Core/REST/Client/Values/ViewInput.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/ContentTypeIdentifier.php
eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestExecutedView.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestExecutedViewTest.php

> Implements [EZP-26326](http://jira.ez.no/browse/EZP-26326)
> Status: ready for review.
`Criteria` is deprecated in favour of `Filter`.
This also integrates basic Criterion testing to the REST behat suite. This implies improvements to the Query ValueObjectVisitor, as well as base work for CriterionVisitors. Those are used to build REST payloads based on value objects. _As a bonus, they can also be used by the REST client :)_

EZP-26326: Implement Filter and Query REST Query parameters

---

doc/bc/changes-6.5.md
eZ/Publish/Core/FieldType/Tests/IntegerValueValidatorTest.php
eZ/Publish/Core/FieldType/Validator/IntegerValueValidator.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/IntegerConverter.php

JIRA: https://jira.ez.no/browse/EZP-26382
Replaces #1792
This changes the `Integer` Field Type validator default from `false` to `null`, using the same logic as was done in eb5bbcdac288e3e1 for Float, but still allowing deprecated `false` value to be used.
No change to `Core/FieldType/Integer/Type.php` is needed as it was already done in cfd038a5991f7366

Fix EZP-26382: ContentType Draft sets IntegerValueValidator min/max to 0

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/TreeHandler.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/SPI/Persistence/Content/Handler.php

> Issue: https://jira.ez.no/browse/EZP-26539
Since 3d063d909bb4a69c3d3b8c1d076a921ccc6a80d0, ordering is done by storage engines.
Besides refactoring for removing unneeded code, this will be needed in order for version list to be able to be paged in the future.

EZP-26539: Move versionList() ordering logic down to SPI

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Search/Legacy/Content/FullTextValue.php
eZ/Publish/Core/Search/Legacy/Content/Mapper/FullTextMapper.php
eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Repository/SearchIndex.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml

> Fixes: [EZP-26499](https://jira.ez.no/browse/EZP-26499)
This PR fixes `WordIndexer` to exclude any word boundary, not just spaces.
As a side fix, a proper identifier (string) is inserted into `ezsearch_object_word_link` table instead of field id.
**TODO**:

EZP-26499: Search index - better word boundaries detection

---

eZ/Publish/API/Repository/Tests/Regression/EZP26367UrlAliasHistoryRedirectLoopTest.php
eZ/Publish/API/Repository/Values/Content/URLAlias.php
eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

This PR resolves https://jira.ez.no/browse/EZP-26367
This seems to be a design limitation.
`UrlAlias` is identified by composite key `parent-text_md5`, which is defined on a single path element. It can be loaded both by `reverseLookup(Location $location)` and `lookup($path)`. The latter means it's history state for `UrlAlias` is ambiguous as it depends not only on the end path element/Location, but possible on the elements/Locations above as well. For example, history parts are marked with bold style:
- Location 1
- /one/**two** (history: true)
- /one/three (history: false)
- Location 2
- /**two**/three (history: true)
- /four/three (history: false)
And so on.
The problem here is we use same object (`UrlAlias`) for two different things, lookup and reverse lookup. Some years ago I proposed …

EZP-26367: Renaming parent leads to redirect loop

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FullText.php

> Fixes #1814, related to [EZP-26499](https://jira.ez.no/browse/EZP-26499)
> Component: Legacy/SQL Search Engine
PR #1814 introduced change to `WordIndexer` splitting phrase to be indexed not only by white spaces, but also by word boundaries. 
To properly search using phrases with word boundaries (e.g. `Folder1.`) this change also needs to be reflected on the Legacy/SQL Search Engine `FullText` Criterion Handler.
**TODO**:

EZP-26499: Fix word boundaries detection in SQL Search Engine FullText Criterion Handler

---

eZ/Publish/API/Repository/Tests/Values/User/Limitation/RolePolicyLimitationTest.php
eZ/Publish/Core/Repository/PermissionsCriterionHandler.php
eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionsCriterionHandlerTest.php

> Fixes: [EZP-26476](https://jira.ez.no/browse/EZP-26476)
> Alternative to: #1819
> Backport: `6.6`
This PR revisits #1819 using simple one-line fix provided by @pspanja.
~`Criterion\MatchAll` is added for policies without limitations when creating `PermissionCriterion`.~
**TODO**:

EZP-26476: [fix v2] Wider roles being ignored if you define more restrictive roles

---

.travis.yml
eZ/Bundle/EzPublishRestBundle/Features/Context/SubContext/Views.php
eZ/Bundle/EzPublishRestBundle/Features/Views/query.feature
eZ/Publish/Core/REST/Client/Output/ValueObjectVisitor/Criterion/ContentTypeIdentifier.php

Fixes array handling in the ContentTypeIdentifierCriterion value object visitor, used by behat to serialize a Query into a REST payload.

Fixed REST views behat scenario

---

eZ/Bundle/EzPublishIOBundle/BinaryStreamResponse.php

JIRA: https://jira.ez.no/browse/EZP-26554
Using a non-ascii filename will result in an exception, as Symfony's `ResponseHeaderBag` checks the value but  does not automatically convert it.
This means that the `setContentDisposition()` function must perform this conversion, at least if no fallbakc is provided, according to the doc:
> * @ param string $filenameFallback A fallback filename, containing only ASCII characters. Defaults to an automatically encoded filename

Fix EZP-26554: download filename fallback must be ASCII in Content-Disposition

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

> [EZP-26666](http://jira.ez.no/browse/EZP-26666)
FieldType settings display in content type editing. Missing because RichText was implemented after the feature.
No options are exposed, as the `numRows` supported by the FieldType (like TextBlock) isn't implemented, and is planned for removal.

Added RichText fielddefinition_setting blocks

---

.travis.yml
composer.json

As discussed with some we want to bump PHP requirements for the LTS.
This has been communicated over some time on the requirements already:
https://doc.ez.no/pages/viewpage.action?pageId=31429536
Main arguments:
- To be able to start to take advantage of [PHP 5.6 features](http://php.net/manual/en/migration56.new-features.php)
- Including class constant expressions/arrays, and Variadic functions / Argument unpacking.
- PHP 5.5 is EOL since 21 Jul 2016, and hence won't be relevant for the support period of the LTS
- All supported platforms by now have access to PHP 5.6 packages or higher.
PHP 5.6 is the closest you get to a PHP LTS, and is supported by PHP until 31 Dec 2018, and most likely further by distros.

[Composer] Drop PHP 5.5 support for 1.7LTS

---

eZ/Publish/Core/IO/Exception/InvalidBinaryFileIdException.php
eZ/Publish/Core/IO/IOService.php
eZ/Publish/Core/IO/TolerantIOService.php
eZ/Publish/Core/IO/UrlDecorator/Prefix.php

> Issue: https://jira.ez.no/browse/EZP-26683
To avoid cryptic IO exceptions when upgrading and merging in wrong var_dir settings or otherwise miss configuring this setting.
Solves:
- `$message` containing important context information, not being passed on to string given to user
- add context information on prefix exceptions

EZP-26683: Make IO exceptions more use friendly

---

eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Input/Parser/ViewInput.php
eZ/Publish/Core/REST/Server/Input/Parser/ViewInputOneDotOne.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/QueryParserTest.php

> [EZP-26702](http://jira.ez.no/browse/EZP-26702)
Ping @StephaneDiot for testing.
Added a unit test for the Query InputParser.

EZP-26702: made sure an empty Filter/Criteria doesn't generate an empty LogicalAnd

---

eZ/Publish/Core/Helper/Tests/TranslationHelperTest.php
eZ/Publish/Core/Helper/TranslationHelper.php

This PR resolves https://jira.ez.no/browse/EZP-26706
When resolving translated `Content` name from `ContentInfo`, `TranslationHelper` will unnecessarily load `Content` in all languages, while only `VersionInfo` is needed. Depending on how much this is used and how many languages a `Content` has, this can be quite a drain on the resources.

EZP-26706: Resolve translated name from VersionInfo

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/Exception/InvalidSearchEngineIndexer.php
eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineIndexerFactory.php
eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RegisterSearchEngineIndexerPass.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/ApiLoader/ElasticsearchEngineFactory.php
eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/DependencyInjection/EzPublishElasticsearchSearchEngineExtension.php
eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/Resources/config/services.yml
eZ/Publish/Core/Search/Common/Indexer.php
eZ/Publish/Core/Search/Elasticsearch/Content/Handler.php
eZ/Publish/Core/Search/Elasticsearch/Content/Indexer.php
eZ/Publish/Core/Search/Legacy/Content/Indexer.php
eZ/Publish/Core/settings/containerBuilder.php
eZ/Publish/Core/settings/search_engines/common.yml
eZ/Publish/Core/settings/search_engines/elasticsearch.yml
eZ/Publish/Core/settings/search_engines/legacy.yml
eZ/Publish/Core/settings/tests/common.yml
eZ/Publish/SPI/Search/Handler.php
eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php

> Status: **Ready for a review**.
> Implements: [EZP-26098](https://jira.ez.no/browse/EZP-26098).
This PR adds generic `ezplatform:reindex` command able to recreate Search Engine Index for any Search Engine extending Search Engine Indexer Service.
The Service should be tagged as `ezpublish.searchEngineIndexer` with an alias corresponding to a specific search engine (legacy, solr, elasticsearch).
**TODO**:
_Note: This PR was rebased, removing any code related to previous approach. Old code is available [here](https://github.com/ezsystems/ezpublish-kernel/compare/master...alongosz:ezp-26098-backup-20160926)._

EZP-26098: Add generic command to recreate search engine index

---

eZ/Publish/API/Repository/ContentTypeService.php
eZ/Publish/API/Repository/Tests/Regression/EZP26551DeleteContentTypeDraftTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/SPI/Persistence/Content/Type/Handler.php

This PR resolves https://jira.ez.no/browse/EZP-26551
This fixes the issue by deleting both draft and define (published) ContentType when calling `ContentTypeService::deleteContentType($contentType)` with argument not being an instance of `ContentTypeDraft`. When calling the method with an instance of `ContentTypeDraft`, only the draft will be deleted, which is the same behavior as before.
`NotFound` exception is removed from SPI `ContentTypeHandler::delete($contentTypeId, $status)`. That approach is the same as taken in https://github.com/ezsystems/ezpublish-kernel/pull/1133.
We should eventually switch to use `PDO::MYSQL_ATTR_FOUND_ROWS` and fix this problem for good, but that's maybe something we'll want to do with kernel version 7. For more info on that part see:
- …

Fix EZP-26551: Content type draft not deleted when content type is

---

eZ/Publish/Core/MVC/Symfony/Translation/CatalogueMapperFileWriter.php

> [EZP-26733](https://jira.ez.no/browse/EZP-26733)
Tested on PlatformUI, works as expected.

Fix EZP-26733: keep the desc attribute when mapping translation catalogs

---

eZ/Bundle/EzPublishElasticsearchSearchEngineBundle/Command/ElasticsearchCreateIndexCommand.php
eZ/Bundle/EzPublishLegacySearchEngineBundle/Command/CreateIndexCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php

> Follow-up on [EZP-26098](https://jira.ez.no/browse/EZP-26098)
This PR deprecates Search Engine-specific indexing commands in favor of `ezplatform:reindex` generic command introduced in #1738.
**TODO**:

EZP-26098: Deprecate SearchEngine-specific indexing commands

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

https://jira.ez.no/browse/EZP-26719
This is the first PR to fix the Jira EZP-26719.
Fonctionnaly this PR won't change anything, it's just replacing the deprecated method so I will be able to implement a view matcher in platfom UI
Manually
Can be tested after this one :https://github.com/ezsystems/PlatformUIBundle/pull/732
Just go on a content type view page with a content having a relation or relatiolist field with a defaut location set

EZP-26719 : use ez_content:ViewAction instead of deprecated viewLocation

---

eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php
eZ/Publish/Core/FieldType/Keyword/SearchField.php
eZ/Publish/Core/FieldType/Keyword/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/KeywordConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/KeywordTest.php
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
eZ/Publish/SPI/Tests/FieldType/KeywordIntegrationTest.php

This PR resolves https://jira.ez.no/browse/EZP-26705
this implements `Indexable` for the `Keyword` field type + integration tests.

EZP-26075: Keyword field type not indexed by Solr Search Engine

---

.travis.yml
eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/REST/Common/Tests/Output/Generator/FieldTypeHashGeneratorBaseTest.php
eZ/Publish/Core/REST/Common/Tests/Output/Generator/_fixtures/Json_FieldTypeHashGeneratorTest__testGenerateFloatValue.out
eZ/Publish/Core/Repository/Tests/Service/Integration/Base.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentTypeBase.php

Given PHP 7.1 is entering RC state we should start to have some testing
of it in place for v1.6 (16.10) release.
Float rounding issue in REST, seems something is causing rounding to behave strangly.
Change in 7.1: https://wiki.php.net/rfc/precise_float_value
23.424242424242424242  _Orignal_
23.424242424242  _Expected (according to PHPUnit on PHP 7.1)_
23.424242424242426 _Actual (according to PHPUnit on PHP 7.1), notice the strange rounding_
```
1) eZ\Publish\Core\REST\Common\Tests\Output\Generator\Json\FieldTypeHashGeneratorTest::testGenerateFloatValue
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-{"Field":{"fieldValue":23.424242424242}}
+{"Field":{"fieldValue":23.424242424242426}}
/home/travis/build/ezsystems/ezpublish-kernel/eZ/Publish/Core/REST/Common/T …
```

[PHP] Add testing of PHP 7.1 and adjust tests

---

eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php
eZ/Publish/Core/FieldType/Keyword/SearchField.php

This is additional fix for https://jira.ez.no/browse/EZP-26705
Adds indexing full text data (keywords) + integration tests.

EZP-26705: Keyword field type indexes full text data

---

eZ/Publish/API/Repository/Tests/Regression/PureNegativeQueryTest.php

This PR resolves https://jira.ez.no/browse/EZP-26774
Counterpart on the Solr search engine: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/81
This adds tests to expose a potentially unhandled "pure negative" query.
Quoting [Solr FAQ](https://wiki.apache.org/solr/FAQ#Why_does_.27foo_AND_-baz.27_match_docs.2C_but_.27foo_AND_.28-bar.29.27_doesn.27t_.3F):
> Boolean queries must have at least one "positive" expression (ie; MUST or SHOULD) in order to match. Solr tries to help with this, and if asked to execute a BooleanQuery that does contains only negatived clauses _at the topmost level_, it adds a match all docs query (ie: *:*)
>
> If the top level BoolenQuery contains somewhere inside of it a nested BooleanQuery which contains only negated clauses, that nested query will …

EZP-26774: Add regression test for pure negative query handling

---

.travis.yml

Travis UnitTest preparation fails randomly due to composers high memory consumption. It's recommended by Composer troubleshooting to run it with disabled `memory_limit` in such situations.
Example test fails:
- https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/184229805#L357
- https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/184218885#L359
Composer troubleshooting:
- https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

Fix composer "memory exhausted" during Travis UnitTest preparation

---

eZ/Publish/Core/QueryType/QueryParameterContentViewQueryTypeMapper.php

https://jira.ez.no/browse/EZP-26777
In confguration we can add an array of 'excluded_content_types' on query parameters for a content view.
Here is a sample configuration : 
```yaml
content_view:
full:
home:
controller: ez_query:LocationQueryAction
params:
query:
query_type: AppBundle:Children
parameters:
parent_location_id: 2
excluded_content_types:
- layout
- article
```
The results is an error in QueryParameterContentViewQueryTypeMapper::evaluateExpression because an array is passed instead of a string.

EZP-26777: Allow injecting arrays as a QueryTypes parameters

---

.travis.yml
eZ/Publish/API/Repository/Tests/SearchServiceTest.php

This PR resolves https://jira.ez.no/browse/EZP-26775
`ezplatform-solr-search-engine` counterpart: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/83

 EZP-26775: supported Solr backend v6

---

data/update/mysql/dbupdate-6.7.0-to-6.8.0.sql
data/update/postgres/dbupdate-6.7.0-to-6.8.0.sql
eZ/Bundle/EzPublishCoreBundle/Resources/config/policies.yml
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php

> Status: **Ready for a review**
> Implements: [EZP-26070](https://jira.ez.no/browse/EZP-26070)
This PR implements in a very simple way [EZP-26070](https://jira.ez.no/browse/EZP-26070) just by adding new `content/publish` policy. Policies `content/edit` and `content/create` are meant for drafts.
Note: To be able to publish content, at least `content/read`, `content/versionread` and `content/edit` is required as well. We might consider `content/publish` policy to implicitly mean also all other required but I'm not a big fan of this as it would complicate permission system itself and require more extensive changes.
**TODO**:

EZP-26070: PHP API support for new Publish permission

---

composer.json

> https://jira.ez.no/browse/EZP-26843
This limits Twig to 1.x, since JMS Translation bundle is not compatible with 2.0. JMS Translation bundle itself doesn't limit the constraint to 1.x, and seems that is half abandoned since no work was done on it in 5 months.

EZP-26843: Limit Twig to 1.x due to 2.0 incompatibility with JMS Translation bundle

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/ContentBase.php
eZ/Publish/Core/SignalSlot/ContentService.php

> Issue: https://jira.ez.no/browse/EZP-26831
When creating content the expected behavior would be that alwaysAvailable is set by default from the contentType.

EZP-26831 Make newContentCreateStruct respect ContentType defaultAlwaysAvailable

---

eZ/Publish/Core/REST/Server/Controller/SessionController.php

Jira : https://jira.ez.no/browse/EZP-26794
Clear unauthorized user authentication if they don't have acces to remove siteaccess unwanted exception
Trying to login using a user whose user group has no assigned role
- Create a user group - Group1
- Under Group1, create a user - user1 _(don't assign any role to Group1)_
- Try to login in admin interface using the user1
- We are unable to do so, because of a "401 - unauthorized" - ok once again
- Right after, try to login as admin
-> i should work
composer require ezsystems/ezpublish-kernel:dev-EZP-26794-unable-to-login

EZP-26794 : unable to login in backend

---

eZ/Bundle/EzPublishCoreBundle/Translation/GlobCollector.php

The path to translation packages was wrong, with `ezsystems` as a vendor instead of `ezplatform-i18n`.

Fixed path to vendor/ezplatform-i18n

---

eZ/Bundle/EzPublishCoreBundle/Tests/Routing/UrlAliasRouterTest.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasRouterTest.php
eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php

As the location is already set in the parameters the routerlistener will add the location to the request attributes

Remove redundant setting of locationId attribute

---

eZ/Bundle/EzPublishCoreBundle/EventSubscriber/CrowdinRequestLocaleSubscriber.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventSubscriber/CrowdinRequestLocaleSubscriberTest.php

> [EZP-26828](http://jira.ez.no/browse/EZP-26828)
> Related to https://github.com/ezsystems/PlatformUIBundle/pull/773 and https://github.com/ezsystems/ezplatform/pull/154
If an `ez_in_context_translation` cookie is set with any value, the request's accept-language
is set, using an event subscriber, to ach-UG, the pseudo-locale used by crowdin.
When the locale is ach-UG, the javascript that adds the in-context overlay is loaded.
One way is to open the development console (right click, inspect) and run these lines:
- enable: `document.cookie='ez_in_context_translation=1;path=/;'; location.reload();`
- disable: `document.cookie='ez_in_context_translation=;expires=Mon, 05 Jul 2000 00:00:00 GMT;path=/;'; location.reload();`
An alternative is to create two bookmarks, with the following links:
- …

EZP-26828: Added in-context translation EventSubscriber

---

composer.json

While testing JMS Translation Bundle 2.0 support with Twig 2.1, I got an exception `Cannot bind closure to scope of internal class stdClass`. It turns out this is due to older version of `ocramius/proxy-manager` which does not support PHP 7 correctly.
There is no breaking changes in kernel with Proxy Manager 2.x as far as I can see.

Allow installation of ocramius/proxy-manager ^2.0

---

eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php

Introduced in #1781. Legacy handler, phpdoc on interface as seen inline, and parameters passed in repository are done in the "right order".
Todo:

EZP-26882: Location swap in some cases not clearing right UrlAlias cache

---

eZ/Publish/Core/FieldType/DateAndTime/Type.php
eZ/Publish/Core/FieldType/Tests/DateAndTimeTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/DateAndTimeTest.php

> Fixes https://jira.ez.no/browse/EZP-26791
> Status: Ready to merge
Field definitions can be cached by Stash. When a DateAndTime is set to default to either the current time or an offset of the current time, this is saved as a timestamp which is cached and can go stale.
This adds a `timestring` to the default value hash the DateAndTimeConverter makes. This contains the time or offset in a string parseable by PHPs DateTime class, which the DateAndTime Type can use when converting with `fromHash()`. The existing timestamp is kept, and will work as before.

Fix EZP-26791: Default value "Current datetime" for ezdatetime is wrongly cached

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

> [EZP-26902](https://jira.ez.no/browse/EZP-26902)
The size is entered and stored in megabytes, but the fielddefinition settings template presents it as bytes.

Fix EZP-26902: Binary files max file size in content type view has wrong unit

---

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php

> Issue: https://jira.ez.no/browse/EZP-26957
I'm not sure this belongs here, but for the time being it feels like we should stress tuning setup on Platform including promoting PHP 7 usage. /cc @bdunogier @DavidLiedle _(note: this is master so effectively 1.8 and up where we do technically support PHP 7.1)_
Another reason for adding this is because the one on dumping autoload can not be done automatic yet: https://github.com/ezsystems/ezplatform/commit/bb2a3135ba5050143db82efb39aff3f20d2884e8
Todo:

[Doc] EZP-26957: Add performance tips in welcome message

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

The parameter will likly instead be set using the env() feature of Symfony 3.2+,
so we should not use global parameters that are _maybe_ defined in meta repo in bundles.
Bonus: We can consier removing index data in our sql dump files.
Downside: There will now be a re index performed even with legacy storage engine.

EZP-26988: Remove use of hardcoded search_engine param

---

eZ/Publish/Core/FieldType/Tests/DateAndTimeTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php

> Fixes https://jira.ez.no/browse/EZP-27022
> Ready for review
https://jira.ez.no/browse/EZP-26791 introduced a timestring (like "now", or "1 day, 2 hours") as the way to delay the initialisation of the datetime value until when you're creating it, rather than when the content type cache was last cleared (which was the bug).
This fails for DEFAULT_CURRENT_DATE_ADJUSTED because the adjustment is calculated by taking current time, adding the DateInterval, and comparing the resulting time with the original as timestamps, before making a timestring out of it. But timestamps do not care about DST (daylight savings time), so this will in some cases lead to off-by-one-hour bugs.
The fix is to instead format the timestring as containing all the properties of the DateInterval (years, months, days, …

EZP-27022: "Current date adjusted" fails on DST

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/Tests/RichTextTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RichTextConverter.php
eZ/Publish/SPI/Tests/FieldType/RichTextIntegrationTest.php

> Fixes [EZP-25007](https://jira.ez.no/browse/EZP-25007)
This PR removes `numRows` setting from the `RichText` Field Type and is required for changes in 
[repository-forms#112](https://github.com/ezsystems/repository-forms/pull/112) to work.
**TODO**:

EZP-25007: "Number of text rows in the editor" should be removed from RichText fieldtype

---

eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler/Collection.php

A small fix where LIKE clause wildcards (`%`, `_`) were not escaped when handling `CONTAINS` operator in Legacy search engine.

Escape LIKE wildcards when used for CONTAINS operator

---

eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php
eZ/Publish/Core/FieldType/Keyword/KeywordStorage.php
eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/LegacyStorage.php

> Fixes: [EZP-23912](https://jira.ez.no/browse/EZP-23912)
> Backport: **6.7**
This PR fixes the bug which occurs when updating `ezkeyword` field with an empty keyword list (keyword list is not affected).
**TODO**:
*Note: as a separate task this test should be moved to `BaseIntegrationTest` parent class with proper fixes for `ezuser` field (out of scope of this PR)*.

EZP-23912: Impossible to empty a Keyword field

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/024-template.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/025-templateInline.xml

> Issue: https://jira.ez.no/browse/EZP-26838
Changes custom tag representation in xhtml5edit _(our custom xhtml5 format used by editor)_ from:
```xml
<eztemplate data-ezname="factoidbox" class="templateClass3" data-ezalign="center">
<ezcontent>It is widely known that the bistable multivibrator hums z's in the middle octave key of E.</ezcontent>
</eztemplate>
<eztemplateinline data-ezname="strikedthrough">
<ezcontent>text</ezcontent>
</eztemplateinline>
```
To:
```xml
<div data-ezelement="eztemplate" data-ezname="factoidbox" class="templateClass3" data-ezalign="center">
<div data-ezelement="ezcontent">It is widely known that the bistable multivibrator hums z's in the middle octave key of E.</div>
</div>
<span data-ezelement="eztemplateinline" data-ezname="strikedthrough">
<span …
```

EZP-26838: Change representation of custom tags in xhtml5edit format

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Router.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterTest.php

> https://jira.ez.no/browse/EZP-26949
`SiteAccess\Router::matchByName()` should return default SiteAccess when
no SiteAccess could be matched, instead of `null`.
Otherwise this is not aligned to what `match()` does.
Yes, I know, I'm the one who introduced this bug :blush: :octocat:

Fix EZP-26949: SiteAccess reverse match doesn't work with default SiteAccess

---

eZ/Publish/Core/FieldType/Tests/DateAndTimeTest.php

Ref: https://travis-ci.com/ezsystems/ezpublish-kernel-ee/jobs/66407749
Still works locally, but fails on Travis. Testing an approach that doesn't use timestamps, similar to https://github.com/ezsystems/ezpublish-kernel/pull/1916

DateAndTimeTest::testFromHash fails occasionally on Travis

---

eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php
eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/LegacyStorage.php

> Fixes [EZP-27014](https://jira.ez.no/browse/EZP-27014)
> Status: **Work in progress**
Creating Content Object with `ezkeyword` field filled with keyword differing only by case, results in all keywords being appended, e.g. "Foo, foo".
**TODO**:

EZP-27014: 'ezkeyword' data not saved properly

---

eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/Readme.rst
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/schematron/sch2xsl.sh

It seems that `Readme.rst` on generating XSLT stylesheet from the Schematron schema files needs to be improved.

[Doc] Improve DocBook Schematron README

---

eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RequestEventListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Routing/UrlAliasRouterTest.php
eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php

> Fixes [EZP-26961](https://jira.ez.no/browse/EZP-26961)
|Q|A|
|---|---|
|Target branch|6.7|
|Unit tests|yes|
|Backward compatible|yes|
When a content has been renamed, the redirection emitted by the UrlAliasRouter must contain the X-Location-Id header. This adds the location id as a request attribute when the redirect URLAlias is found, and adds the header to the Response in the RequestListener.

Fix EZP-26961: No X-Location-Id header in redirections

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/Core/Repository/ContentService.php

> Issue: https://jira.ez.no/browse/EZP-27125
Minor optimization to avoid having to do a SPI lookup to get current version number.

EZP-27125: Take current version from ContentInfo if not set in loadContentByContentInfo()

---

eZ/Publish/API/Repository/Tests/FieldType/DateIntegrationTest.php
eZ/Publish/Core/FieldType/Date/SearchField.php
eZ/Publish/Core/FieldType/Date/Value.php
eZ/Publish/Core/FieldType/Tests/DateTest.php

Link: https://jira.ez.no/browse/EZP-25276
When the server's timezone is not UTC, the date won't be retrieved properly.
Timestamps are stored in UTC timezone, if you are in a timezone starting with  `-`, the date retrieved will be the day before. 
For example: 03/27/2017
- Stored as `03/27/2017 00:00:00` (as a timestamp)
- Was retrieved in a server configured to use New York's time as `03/27/2017 00:00:00` minus 6 hours so the day before: `03/26/2017 18:00:00` (as a timestamp)
This patch makes sure date are retrieved as UTC. It is based on the DateAndTime behavior: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/FieldType/DateAndTime/Value.php#L71
Manual test on platformUI and update of unit test.

Fix EZP-25276: Different timezones on server/local env changes the inserted date

---

eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/026-tableTitles.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/010-htmlInformaltable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/011-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/018-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/024-template.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/026-tableTitles.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/010-htmlInformaltable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/011-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/018-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/026-tableTitles.xml

> Issue: https://jira.ez.no/browse/EZP-26976
Related to PlatformUI fix: https://github.com/ezsystems/PlatformUIBundle/pull/817
"BC":
- This changes xhtml5 edit & ouput formats to _always_ return tbody in tables, and optionally also thead/tfoot if present.
Todo:

EZP-26976: Add RichText xhtml5 support for thead & tfoot

---

doc/specifications/siteaccess/siteaccess_aware_configuration.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessConfigurationFilter.php

> [EZP-27115](http://jira.ez.no/browse/EZP-27115)
Allows bundles to add a `SiteAccessConfigurationFilter`, that gets to filter the siteaccess configuration array before it is applied:
```php
// MyBundle.php
$extension = $container->getExtension('ezpublish');
$extension->addSiteAccessConfigurationFilter(new MyFilter());
// MyFilter.php
function filter($configuration)
{
$configuration['list'][] = 'foo';
$configuration['groups']['site_group'][] = 'foo';
return $configuration;
}
```
Dynamically create admin siteaccess(es) for the Hybrid UI.
The `SiteAccessConfigurationFilter`, added by 3rd party bundles to the `ezpublish` extension, are provided to the CoreBundle's `Configuration`. They are iterated on in the `beforeNormalization()` method of the `siteaccess` configuration node.

Allow extensions to customize the siteaccess configuration

---

eZ/Publish/Core/Repository/Helper/NameSchemaService.php

> Issue: https://jira.ez.no/browse/EZP-26921
change substr to multi-byte substr (mb_substr). It fix problems with long cyrillic names
Closes #1899

EZP-26921: Name encoding issue when title exceeds max name length

---

eZ/Publish/Core/MVC/Symfony/Security/EventListener/SecurityListener.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/EventListener/SecurityListenerTest.php

| Q                | A
| ---------------- | -----
| JIRA      | [EZP-26970](http://jira.ez.no/browse/EZP-26970)
| Feature request? | no
| Tests | Updated unit tests |
| Target branch | 6.7
The SecurityListener must throw an `AuthenticationException` if the user isn't allowed, as it is what The AbstractAuthenticationListener will catch.

Fix EZP-26970: login no siteaccess login policy

---

eZ/Bundle/EzPublishCoreBundle/Imagine/BinaryLoader.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/BinaryLoaderTest.php

> [EZP-26914](http://jira.ez.no/browse/EZP-26914)
The command expects a path relative to the `storage/images` directory, but it is not documented anywhere, and the current message does not help:
```
php app/console liip:imagine:cache:resolve var/site/storage/images/7/4/2/0/247-1-eng-GB/test.jpg
[eZ\Publish\Core\IO\Exception\InvalidBinaryFileIdException]                        
Argument 'BinaryFile::id' is invalid: 'NULL' is wrong value in class 'BinaryFile'
```
This adds  a catch on the exception that indicates an invalid prefix, and a message that reminds this expectation:
```
php app/console liip:imagine:cache:resolve var/site/storage/images/7/4/2/0/247-1-eng-GB/test.jpg
[Liip\ImagineBundle\Exception\Binary\Loader\NotLoadableException] …
```

EZP-26914: Improve exception message from liip:imagine:resolve

---

doc/bc/changes-6.9.md

> Context:
> - Fix is to make sure type hint is on API and not Core: https://github.com/ezsystems/date-based-publisher/pull/18/files
> - Caused by: https://github.com/ezsystems/ezpublish-kernel/pull/1884
> - Affected service id’s:  @ezpublish.api.service.*
Changes documentation now brings more detail about what's done and how it may affect current installation.

EZP-25679: Document decoupling BC break

---

eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Publish/Core/FieldType/Image/ImageStorage.php
eZ/Publish/Core/REST/Server/Controller/BinaryContent.php

> Fixes [EZP-27151](https://jira.ez.no/browse/EZP-27151)
Adds the content version number to the `imageId` argument: `<contentId>-<fieldId>-<versionNumber>`. If none is provided, the route will still be valid, and will pick the currently published version (same behaviour as previous versions).
This part of the REST API clearly deserves a refactoring, but this bugfix isn't the right time for it :)
Tested manually...

Fix EZP-27151: Added version number to REST imageId

---

bin/extract-translations.sh
doc/specifications/image/variation_purging.md
eZ/Bundle/EzPublishCoreBundle/Features/Context/ConsoleContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/YamlConfigurationContext.php
eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php

> **Target branch**: `7.0`
This PR fixes for `v2` and `Kernel 7.0` hardcoded Symfony console script path to `bin/console`.
Suggestions how to parametrize this instead of hardcoding are welcomed, but for now I decided it would be an overkill.
Main reason behind this is that reindexing called by `ezplatform:install` crashes each time I try to test it :)

[Sf 3.x] Fix Symfony console script path

---

.travis.yml
appveyor.yml
eZ/Bundle/EzPublishIOBundle/Tests/EventListener/StreamFileListenerTest.php

[CI] Force Sf 3.x requirement to test with latest version

---

composer.json

> https://jira.ez.no/browse/EZP-27279
JMS Translation Bundle as of v1.3.2 supports Twig 2.0 (https://github.com/schmittjoh/JMSTranslationBundle/pull/439).
Made against `6.7`, since original PR that limited Twig to 1.x (#1877) was also against this branch.

EZP-27279: Remove Twig 1.x version constraint

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

> [EZP-27237](https://jira.ez.no/browse/EZP-27237)
The `ContentViewBuilder` will load the Content differently depending if the View is an embed one or not. That logic was reversed, and `loadEmbedContent()` was used to load content for regular views, and `loadContent()` for embed views.
Tested manually.

Fix EZP-27237: fixed wrong content loading logic in ContentViewBuilder

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml

> https://jira.ez.no/browse/EZP-27308
Non strict service references are not used any more, and service names will become case sensitive in later Symfony versions.

EZP-27308: Remove deprecated usage of Symfony services

---

eZ/Bundle/EzPublishDebugBundle/Twig/DebugTemplate.php

> https://jira.ez.no/browse/EZP-27290
Starting with https://github.com/symfony/symfony/commit/eddecbd112c13eadac6533b39287205b90430a21 and in combination with legacy eZ templates, when an exception happens (even a silenced deprecation notice, which is converted to an exception) while rendering the template, one gets a message `Cannot instantiate abstract class eZ\Bundle\EzPublishDebugBundle\Twig\DebugTemplate` in the log, which ultimately breaks the profiler.
The issue comes from https://github.com/symfony/symfony/blob/master/src/Symfony/Component/VarDumper/Caster/ExceptionCaster.php#L201-L202, which presumes that every subclass of `Twig_Template` is instantiable.
Haven't found other way to solve this other than this. The fix is also compatible with Twig 2.0 (for when we enable it again …

EZP-27290: Remove abstract on DebugTemplate to fix dumping logs in profiler

---

eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetContentType.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetContentTypeMinCount.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetContentTypeMinLimit.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetFieldRegexp.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetFieldRegexpSortCount.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetFieldRegexpSortTerm.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetFieldSimple.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetSection.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetTerm.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/FacetUser.php
eZ/Publish/API/Repository/Values/Content/Query.php
eZ/Publish/Core/Search/Legacy/Content/Handler.php

> Issue: https://jira.ez.no/browse/EZP-27296
Adapt Legach Search engine and clarify API doc.
This is done to avoid consumer code having to check what searc henigne is in use and conditionally
apply facet builders.
Integration tests before this change:
```
Tests: 6157, Assertions: 10137, Skipped: 4927, Incomplete: 6.
```
After change 20 of the skipped became incomplete, and by generating fixtures for the expected behaviour we now have:
```
Tests: 6157, Assertions: 10157, Skipped: 4907, Incomplete: 6.
```

EZP-27296: Ignore facetBuilders in LegacySE, don't throw

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

> Issue: https://jira.ez.no/browse/EZP-26068 _(& https://jira.ez.no/browse/EZP-26555)_
> _Use of GMap blocked now since Google started requiring api key, this blocks use on tutorial, (..)._
Solves:
- maps now broken as api key is now required
- does not load script several times in case there are several gmap fields
- exposes scrollwheel parameter to be able to disable it on the map
replaces #1726

EZP-26068: Fix broken Google  Maps, adopt google maps APIs v3

---

eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php

Based on usage of function BaseIntegrationTest::getHandler(), for example here:
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/SPI/Tests/FieldType/AuthorIntegrationTest.php#L59
The first parameter should be instance of \eZ\Publish\SPI\FieldType\FieldType instead of \eZ\Publish\SPI\Persistence\FieldType.

[PHPDoc] Fix PHPDoc on BaseIntegrationTest::getHandler()

---

eZ/Publish/Core/MVC/Symfony/Security/ReferenceUserInterface.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/UserTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/UserWrappedTest.php
eZ/Publish/Core/MVC/Symfony/Security/User.php
eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php
eZ/Publish/Core/MVC/Symfony/Security/UserInterface.php
eZ/Publish/Core/MVC/Symfony/Security/UserWrapped.php
eZ/Publish/Core/REST/Server/Security/RestAuthenticator.php
eZ/Publish/Core/REST/Server/Tests/Security/RestSessionBasedAuthenticatorTest.php

> JIRA:  https://jira.ez.no/browse/EZP-24852
As we anyway always refresh APIUser on load, this changes our symfony User to not serialize APIUser to session anymore to reduce size of session being serialized back and forth.
On top of that make sure WrappedUser does not get self or User injected to avoid possibility of wrong use and bloated session value.

EZP-24852: Add UserReference support in Authentication/User providers

---

eZ/Publish/Core/MVC/Symfony/View/BaseView.php

> https://jira.ez.no/browse/EZP-27331
When using the view system, it is now possible to add arbitrary parameters. 
However it is currently possible to *replace* an existing one as `BaseView::addParameters()` uses `+= ` assignment and does not expose a setter.
Thus, if a key in `$parameters` already exists in `$this->parameters`, it is ignored.
Issue reference for EzCoreExtraBundle: https://github.com/lolautruche/EzCoreExtraBundle/issues/23
This patch replaces `+=` by `array_replace()`, like in Symfony `ParameterBag`.

Fix EZP-27331: Cannot override view parameters

---

eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php

> Fixes [EZP-26164](https://jira.ez.no/browse/EZP-26164)
When a Binary Field is saved with external data, but doesn't have a mimeType defined, gets it from the IOService using the stored file. Covers the case where a Field Value is copied from another translation and left untouched.

Fix EZP-26164: error saving a binary field copied translation

---

eZ/Bundle/EzPublishRestBundle/DependencyInjection/EzPublishRestExtension.php

> JIRA: [EZP-27349](https://jira.ez.no/browse/EZP-27349)
> Required by ezsystems/hybrid-platform-ui#2
**Must be merged to master, not 7.0**
Marks REST routes as non-siteaccess aware so that they aren't prefixed with the siteaccess when generating a link using the UrlGenerator.
Can be tested by generating any REST URL using the UrlGenerator (from a twig template for instance):
```
{{ path( 'ezpublish_rest_loadLocation', {'locationPath': location.pathString|trim('/')} ) }}
```
Without this patch, the current siteaccess will be prefixed before the REST URL, and it won't work as expected.

[REST] Made routes non-siteaccess-aware

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/settings/search_engines/legacy/slots.yml

> Fixes [EZP-27250](https://jira.ez.no/browse/EZP-27250)
> Branch: **6.7**
Legacy/SQL Search engine is missing Search Slots related to User Field Type (`ezuser`), so when user is added, reindexing is required to be able to search for that user. This PR fixes this issue.
Please note that search applies only to Content Fields (First name, Last name), not login.
**TODO**:

EZP-27250: Fulltext search not working on "User" content

---

eZ/Publish/Core/Search/Common/FieldValueMapper/MultipleStringMapper.php
eZ/Publish/Core/Search/Common/FieldValueMapper/StringMapper.php

Required by https://github.com/ezsystems/ezplatform-solr-search-engine/pull/90
Makes `TextField` search field type valued mapped as multivalued string.
Multivalued field is stored same as a single value, but with extra "spacing" between the single values/tokens. This prevents spurious phrase matches across single values, so it's actually desirable for the language analyzed field that `TextField` represents. See [doc about `positionIncrementGap`](https://cwiki.apache.org/confluence/display/solr/Field+Type+Definitions+and+Properties#FieldTypeDefinitionsandProperties-GeneralProperties).
Previously the multiple text values had to be concatenated and passed to the search `Field` as a single value. This enables passing an array of values. There should be no functional difference for the …

EZP-27280: Search field type TextField should be multivalued

---

eZ/Publish/API/Repository/Values/Content/Content.php
eZ/Publish/API/Repository/Values/Content/ContentInfo.php
eZ/Publish/API/Repository/Values/Content/Location.php
eZ/Publish/API/Repository/Values/Content/VersionInfo.php
eZ/Publish/API/Repository/Values/ContentType/ContentType.php
eZ/Publish/Core/Repository/Values/Content/Content.php
eZ/Publish/Core/Repository/Values/Content/VersionInfo.php

Second try to update PHPDoc
(first: https://github.com/ezsystems/ezpublish-kernel/pull/1981)
Like as title PHPDoc was outdated, it disturbed fast programming.
It's not all updates of PHPDoc. If this part will come out correct i will create next PR.
Now should be fine with this PR, 
@andrerom 
https://github.com/ezsystems/ezpublish-kernel/pull/1981#issuecomment-300290399
I really do not want to omit 'mixed -> string|int' but i did that.
In API VersionInfo class ids are marked as "int".

Some improvements on API PHPDoc to use more specific types

---

eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/field_rendering_functions/ez_render_field_exception.test

> [EZP-27368](https://jira.ez.no/browse/EZP-27368)
It's testing an exception thrown here:  https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php#L318.

EZP-27368: Add test for an exception in ez_render_field function

---

eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ISBNConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/ISBNTest.php

It fixes https://jira.ez.no/browse/EZP-24617
Method resulted with true in both dataInt values: 1 and 0

EZP-24617: Fixing toFieldDefinition method for ISBNConverter

---

eZ/Bundle/EzPublishRestBundle/Tests/DependencyInjection/Compiler/InputParserPassTest.php

InputParserPassTest [fails for Symfony 3.3](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/237480102#L704) because service ids will be case sensitive. To make it BC, let's change `UnitTest` to `unit_test`.
**TODO**:

[Sf 3.3] Make unit tests respect case sensitivity of service ids

---

composer.json
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php

>[EZP-27367](https://jira.ez.no/browse/EZP-27367)
Currently on failed test the function FileSystemTwigIntegrationTestCase::doIntegrationTest breaks with an error: 
> Error: Call to undefined method Twig_Loader_Chain::getSource()
It comes from the fact that function Twig_Loader_Chain::getSource() was deprecated in Twig version 1.27 and removed in version 2.0 in favor of Twig_Loader_Chain::getSourceContext(), which was introduced in version 1.27. I decided to go for a compability with version <1.27, so in this PR I am handling both cases.

EZP-27367: Update FileSystemTwigIntegrationTestCase::doIntegrationTest for Twig 2.*

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php

This is alternative version of #1988 I'm not sure which one is better so I'm opening two PR for reviewers to decide which one we should continue with.
It fixes https://jira.ez.no/browse/EZP-26608
**A bug**: Configuration is set that if there's no config related to list of fields groups coming from user it creates default list containing only content.
**Solution**: Changing contents of default list by adding reading value from parameter ezsettings.default.content.field_groups.list

EZP-26608 fixing default fields group list

---

eZ/Publish/Core/MVC/Symfony/Security/EventListener/SecurityListener.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/EventListener/SecurityListenerTest.php
eZ/Publish/Core/REST/Server/Controller/SessionController.php

**JIRA issue:** [https://jira.ez.no/browse/EZP-26794](https://jira.ez.no/browse/EZP-26794)
Related to @bdunogier solution described in PR #1944 `AbstractAuthenticationListener` should catch `AuthenticationException` and after that session token should be set to `null` by invoking `onFailure()`.
Maybe I’m wrong, but I think this solution is not working because `AuthenticationException` is thrown but can not be caught inside `AbstractAuthenticationListener::handle()` since `AbstractAuthenticationListener::requiresAuthentication()` returns `false`. 
Therefore `AbstractAuthenticationListener::onFailure()` is never called and session cookies stay kept in the browser. 
Exception is caught directly in `\eZ\Publish\Core\REST\Server\Controller\SessionController::createSessionAction()` and that is …

Fix-EZP-26794: Unable to login as admin after trying to login with an user which group as no role

---

eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/Core/FieldType/Date/SearchField.php
eZ/Publish/Core/Search/Elasticsearch/Content/FieldValueMapper/GeoLocationMapper.php

JIRA issue: [https://jira.ez.no/browse/EZP-27373](https://jira.ez.no/browse/EZP-27373)
If `Date` FieldType is used and **Searchable** setting is checked and also default value is set to **Empty** then it is impossible to save content without setting the value of this field. 
API returns an error as described in issue.

Fix-EZP-27373: Error when edit empty not required date

---

eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ImageExtension.php

> JIRA: -
This PR adds missing use statment of \InvalidArgumentException class in eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ImageExtension (used in line no. 71)

Missing import of \InvalidArgumentException class in ImageExtension

---

eZ/Publish/API/Repository/ObjectStateService.php
eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
eZ/Publish/API/Repository/Tests/_fixtures/generate-fixtures.php
eZ/Publish/API/Repository/Values/ObjectState/ObjectState.php
eZ/Publish/API/Repository/Values/ObjectState/ObjectStateGroup.php
eZ/Publish/Core/REST/Client/Input/Parser/ObjectState.php
eZ/Publish/Core/REST/Client/Input/Parser/ObjectStateGroup.php
eZ/Publish/Core/REST/Client/ObjectStateService.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ObjectStateGroupTest.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestObjectStateTest.php
eZ/Publish/Core/Repository/ObjectStateService.php
eZ/Publish/Core/Repository/Tests/Values/MultiLanguageTestTrait.php
eZ/Publish/Core/Repository/Tests/Values/ObjectState/ObjectStateGroupTest.php
eZ/Publish/Core/Repository/Tests/Values/ObjectState/ObjectStateTest.php
eZ/Publish/Core/Repository/Values/ObjectState/ObjectState.php
eZ/Publish/Core/Repository/Values/ObjectState/ObjectStateGroup.php
eZ/Publish/Core/SignalSlot/ObjectStateService.php
eZ/Publish/Core/SignalSlot/Tests/ObjectStateServiceTest.php

Part of [EZP-27428](https://jira.ez.no/browse/EZP-27428) implementation for #2002
----
**Target branch**: `language_match_api_logic`
This PR refactors ObjectState-related code to implement multi-language / unified logic introduced in #2002.
**TODO**:

EZP-27428: Implemented MultiLanguage logic for ObjectStateService

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

> JIRA: https://jira.ez.no/browse/EZP-26878
This PR fixes  "No default value" displayed in content type view for following cases: 
* ezinteger = 0
* ezfloat = 0.0
* ezisbn (any value)
* ezstring = '0'
Malfunctioning found by QA when https://github.com/ezsystems/repository-forms/pull/119 was tested.

EZP-26878: "No default value" in content type view for a default value in some cases

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php

> Issue: https://jira.ez.no/browse/EZP-27358
Fixes two issues found in the original work:
- Google maps key not injected into Platform UI	
- Google maps scrollWeel is internally a string, externally boolean
Todo:

EZP-27358: Google maps key & scrollWheel not correctly working

---

eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/API/Repository/Values/ContentType/FieldDefinition.php
eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
eZ/Publish/Core/Repository/Helper/NameSchemaService.php
eZ/Publish/Core/Repository/Values/ContentType/FieldDefinition.php

Part of [EZP-27428](https://jira.ez.no/browse/EZP-27428) implementation for #2002
----
**Target branch**: `language_match_api_logic`
This PR adds support (setting, usage, tests) for `FieldDefinition::$mainLanguageCode` property which was introduced in `MultiLanguageTrait`.
**TODO**:

EZP-27428: Added mainLanguageCode support to FieldDefinition

---

.travis.yml
eZ/Bundle/EzPublishRestBundle/Features/Content/user_content.feature

Backport fix related to [EZP-27399](https://jira.ez.no/browse/EZP-27399)
----
This PR backports #2015 to **6.7**

Backport EZP-27399: Tag failing Scenario as broken because of security issue fix

---

doc/specifications/io/io_migration_script.md
eZ/Bundle/EzPublishIOBundle/Command/MigrateFilesCommand.php
eZ/Bundle/EzPublishIOBundle/DependencyInjection/Compiler/MigrationFileListerPass.php
eZ/Bundle/EzPublishIOBundle/EzPublishIOBundle.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/BinaryFileLister.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileIterator/LegacyStorageFileIterator.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileIteratorInterface.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageBinaryFileRowReader.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageFileRowReader.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageMediaFileRowReader.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReaderInterface.php
eZ/Bundle/EzPublishIOBundle/Migration/FileLister/ImageFileLister.php
eZ/Bundle/EzPublishIOBundle/Migration/FileListerInterface.php
eZ/Bundle/EzPublishIOBundle/Migration/FileListerRegistry.php
eZ/Bundle/EzPublishIOBundle/Migration/FileListerRegistry/ConfigurableRegistry.php
eZ/Bundle/EzPublishIOBundle/Migration/FileMigrator/FileMigrator.php
eZ/Bundle/EzPublishIOBundle/Migration/FileMigratorInterface.php
eZ/Bundle/EzPublishIOBundle/Migration/MigrationHandler.php
eZ/Bundle/EzPublishIOBundle/Migration/MigrationHandlerInterface.php
eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml

> Implements https://jira.ez.no/browse/EZP-25946
> Ready for review
Migrates files from local storage to NFS/DFS cluster, and vice versa. (Theoretically, any Flysystem adapter should work.)
Adds a Command which validates from/to input and runs the migration in batches. Input options partially based on [legacy clusterize.php](https://github.com/ezsystems/ezpublish-legacy/blob/d76ce9824dabaceeefa77530c8c611e447d1b109/bin/php/clusterize.php) but made more generic. Meaning it's not just for clusterize/unclusterize, but also for migrating between e.g. NFS and AWS/S3.
`$ php app/console ezplatform:io:migrate-files --dry-run --from=default,default --to=dfs,nfs`
Same as https://github.com/ezsystems/ezpublish-kernel/pull/1825 but for 6.7, ensuring all tests pass.
Had to un-`final`-ise file lister …

EZP-25946: Procedure to migrate existing images/binaries to another IO adapter

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php

> https://jira.ez.no/browse/EZP-27490
This patch removes the exception when the main config parser is already instantiated as this is not necessary and blocks config:dump-reference command (at least using Symfony 3.3).

Fix EZP-27490: Exception when running config:dump-reference

---

eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
eZ/Publish/SPI/Persistence/Content/Field.php

Fixes [EZP-27441](https://jira.ez.no/browse/EZP-27441)
----
> Target branch: **6.7**
When Content with empty Image FT gets translated, `ImageConverter` and `ImageStorage` try to access unset properties.
This PR contains the fix for the actual, root cause of the error described in the issue which is shallow clone of `eZ\Publish\SPI\Persistence\Content\Field`.
When a Persistence Field [is copied before the update](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.3/eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php#L333), its `value` property, which is an object (`eZ\Publish\SPI\Persistence\Content\FieldValue`) gets copied as a reference. Thus `updateField` operates also directly on this object leaving it in unwanted state for the future creation of an empty field from a …

EZP-27441: Error when translate a content with no image

---

eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/Content.php
eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/ContentType.php
eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/Remote.php
eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Id/Section.php
eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/Identifier/Section.php

`ContentBased` matchers:
* Id/Content
* Id/ContentType
* Id/Remote
* Id/Section
* Identifier/Section
should in `match()` method check against `eZ\Publish\Core\MVC\Symfony\View\ContentValueView` interface, rather than `eZ\Publish\Core\MVC\Symfony\View\ContentView` which is concrete implementation.
[Jira](https://jira.ez.no/browse/EZP-27453)

EZP-27453: Match against ContentValueView and not ContentView

---

eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/field_rendering_functions/ez_render_fielddefinition_settings.test
eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php

> [EZP-27344](https://jira.ez.no/browse/EZP-27344)
#
Excerpt from the ticket above:
"Currently creating custom Field Type requires creating Twig file with settings block like this one from the tutorial: https://github.com/ezsystems/TweetFieldTypeBundle/blob/master/Resources/views/platformui/content_type/view/eztweet.html.twig. It is required regardless of whether developer wants to implement some custom settings or not. 
In my opinion, it shouldn't be required if there are no settings because it unnecessarily complicates the creation of simple Field Types. Also, it should be consistent with field_definition_edit Twig block and currently this block is not required if the developer doesn't want to implement something more advanced, like a validator."
I decided to go for catching an …

EZP-27344: Make declaration of twig "settings" block optional for custom Field Types

---

doc/specifications/proposed/translations/removal.md

Proposed specification for [EZP-27417](https://jira.ez.no/browse/EZP-27417)
---------------------
This PR specifies proposed PHP API changes which would allow removal of the translation from all the Content Object Versions.
Right now spec covers ~two~ one use case:
~1. Creating a new version (draft) of content object with the translation removed.~
2. Removing at once all the translations from all existing versions (with suggested usage).
The first use case got separated into another Story: [EZP-27508](https://jira.ez.no/browse/EZP-27508)
**TODO**:

[Spec] EZP-27417: As a Developer I want API to allow removal of the translation from all content object versions

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php

> https://jira.ez.no/browse/EZP-27510
This patch ensures that the ConfigResolver's default scope is always the SiteAccess name, unless otherwise provided.
Kind of relates to
https://github.com/ezsystems/ezpublish-kernel/pull/1440 by @wizhippo

Fix EZP-27510: ConfigResolver default scope is not updated when SiteAccess is matched

---

eZ/Publish/Core/IO/IOService.php

Tentative fix for https://jira.ez.no/browse/EZP-27553
Followup to "Fix broken LegacyDFSCluster::create()" https://github.com/ezsystems/ezpublish-kernel/commit/2b74e9df15620b98f45cd31ce25efc14f1de4569
~Currently no idea why this should fail in 1.10 when it works in 1.9.~ It fails in 1.9.1, same as 1.10, as the original fix was made in 1.9.1.

BinaryFileCreateStruct->mtime should be a DateTime

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php

JIRA: https://jira.ez.no/browse/EZP-27359
This reverts the *last minute* change done in https://github.com/ezsystems/ezpublish-kernel/pull/2025 (see https://github.com/ezsystems/ezpublish-kernel/commit/4afcf2a55465dc5d3eea085235e64fd31aab6823 / https://github.com/ezsystems/ezpublish-kernel/pull/2025#discussion_r123692900).
It seems at this stage, the extensions are not available (`$container->hasExtension('fos_js_routing')` is false, and `$container->getExtensions()` returns an empty array).
@emodric @lolautruche @bdunogier feel free to suggest something else, as long as we get `/admin` URIs in the Hybrid Platform UI, that's fine :)
manual tests

EZP-27359: Restore interface test to check if FOSJsRouting is there

---

.travis.yml

Fix failing behat tests by switching `SYMFONY_ENV` to `behat`
----
Travis recently updated Trusty, since then some behat scenarios [fail](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/246249820).
Behat scenarios fail when trying to perform `ezplatform:install`. However I think it's rather related to cache warmup.
The error and its stack trace:
`PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www" directory. in /var/www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:581
Stack trace:
#0 /var/www/vendor/ezsystems/ezplatform-design-engine/bundle/DependencyInjection/Compiler/PHPStormPass.php(48): Symfony\Component\Filesystem\Filesystem->dumpFile('/var/www/ide-tw...', '{"namespaces":[...')`
Possible …

[Travis] Switch SYMFONY_ENV to behat for scenarios on PHP 7.0

---

eZ/Bundle/EzPublishIOBundle/Migration/MigrationHandler.php

> Fixes https://jira.ez.no/browse/EZP-27564
> QA confirmed in origin issue: https://jira.ez.no/browse/EZP-25946
Follow-up to https://github.com/ezsystems/ezpublish-kernel/pull/1972/ as QA found it didn't work. The data handler factories are not set when calling MigrationHandler::setIODataHandlersByIdentifiers(), see https://github.com/ezsystems/ezpublish-kernel/blob/efafb63fe3442c14d6b5d90c9db9ef58839605b7/eZ/Bundle/EzPublishIOBundle/Migration/MigrationHandler.php#L54
This seems to be because of a fairly last minute change in the final-ness to solve a lazy-loading problem.
This experimentally solves it by un-final-ising the method. Not sure yet if kosher. ~If we do this, we may need to do the same for the logging methods as they might have the same problem~ They don't. Why? Beats me. 😖 …

Make MigrationHandler::setIODataHandlersByIdentifiers() not final

---

eZ/Publish/Core/FieldType/Image/IO/Legacy.php
eZ/Publish/Core/IO/TolerantIOService.php

This is a fix for https://jira.ez.no/browse/EZP-27551
After changes in EZP-26175, specifically in 1a5f7d7 method `loadBinaryFileByUri` is no longer throwing an `InvalidArgumentException` but returns `MissingBinaryFile` instead. This is a bug introduced in `5.4.10` release.
There are two issues with that:
1. You cannot construct `MissingBinaryFile` without an `id` property because it will throw an exception.
2. Method `loadBinaryFileByUri` will fallback to `draftIOService` only in case of `InvalidArgumentException` which is no longer a case.
Important note: this is just a quick fix for a fatal error. However this topic still requires some work, which turns out not to be so straigth forward, that's why I decided to split it into separate PRs. Images which are not uploaded (in content which …

EZP-27551 Proper handling of missing images

---

eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
eZ/Publish/Core/Repository/LocationService.php

> Issue: https://jira.ez.no/browse/EZP-27608
API docs actually says the returned locations should be filtered, so treating this as bug.
Todo:

EZP-27608: [API] loadLocations() does not filter on permissions

---

eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php

> [EZP-27511](https://jira.ez.no/browse/EZP-27511)
#
Moving the content from one section to another doesn't change the section. This behaviour was different in 5.x.
I noticed that Content/Location/Handler::copySubtree() function is updating the section when it is necessary, so I implemented that behaviour in Content/Location/Handler::move() function as well.
The change in Cache/LocationHandler::move() function comes from the fact that Cache/LocationHandler:setSectionForSubtree() function is clearing the content cache and as move() is now calling copySubtree(), it should be cleared there as well.

Fix EZP-27511: Content section not updated when moving content from one section to another

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

JIRA: https://jira.ez.no/browse/EZP-26764
min length Text line settings was missing. Also, fixed the string generated the adjusted datetime on DateAndTime settings.
manual tests

EZP-26764: Fix ContentType FieldDefinition settings views

---

eZ/Bundle/EzPublishCoreBundle/Resources/translations/fielddefinition.en.xlf
eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
eZ/Publish/Core/MVC/Symfony/Cache/Http/ContentPurger.php

JIRA: https://jira.ez.no/browse/EZP-26764
*Forward* port of #1949 to 6.10 branch:
* add translatable strings
* fixed a comment so that the translation extraction script works
* compared to #1949, the fix Date and Time adjust sentence is removed as this was already fixed when translatable strings was added

EZP-26764: Display min length validator configuration of Text Line Field Definition

---

eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/API/Repository/UserService.php
eZ/Publish/Core/REST/Client/UserService.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/SignalSlot/Tests/UserServiceTest.php
eZ/Publish/Core/SignalSlot/UserService.php

Implements [EZP-27509](https://jira.ez.no/browse/EZP-27509)
----
This PR adds prioritized languages list support to the `UserService::load*` methods.
**TODO**:
- ~Add prioritized languages list to `loadAnonymousUser` + add an integration test.~ // deprecated

EZP-27509: Improve UserService to load new translated API properties via prioritized languages list

---

eZ/Publish/SPI/FieldType/StorageGateway.php

This PR is a follow-up on #1906 and #1985 fixing PostgreSQL sequence names for `7.0`.
Notes for reviewers:
- If DBMS driver wrapper (e.g. Doctrine `MySqlPlatform`) does not support sequences, sequence name is ignored, so this is fine for MySQL.
- I couldn't reuse `eZ\Publish\Core\Persistence\Doctrine\ConnectionHandler\PostgresConnectionHandler::getSequenceName` because we aim to deprecate entire namespace and eventually remove it once we create Improved Storage Engine. Maybe then we'll find a better place for this method.
// side: @andrerom this bugfix is so simple I didn't feel a need for an issue, but I could create one if you wish :)

[PostgreSQL] Fix sequence naming for External Storage Gateways

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php

Fixes [EZP-27665](https://jira.ez.no/browse/EZP-27665)
----
This PR is a follow-up on #1682 and [EZP-19123](https://jira.ez.no/browse/EZP-19123) for PostgreSQL database.
While the fix applied there to the PostgreSQL schema:
`CREATE UNIQUE INDEX ezuser_login ON ezuser USING btree ((lower(login)));`
covers disallowing inserting login that differs only by case from an existing one, it doesn't solve querying for that login.
According to this doc:
https://www.postgresql.org/docs/current/static/indexes-expressional.html
to fully utilize the index mentioned above, we also need to use it in the query.
Ref.: [failing PostgreSQL integration test on Travis](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/253254086#L831).
Side note: SQLite is also case sensitive, so test also fails for it.
The …

EZP-27665: [PostgreSQL] Users with uppercase characters in login are not authorized

---

eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/LegacyStorage.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php

> JIRA: https://jira.ez.no/browse/EZP-27666
This PR change a type hints from `eZ\Publish\Core\IO\UrlRedecorator` into `eZ\Publish\Core\IO\UrlRedecoratorInterface` in the following services:
* `eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\ImageConverter`
* `eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\DoctrineStorage`
* `eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage`

EZP-27666: Services should depend upon UrlRedecoratorInterface instead of UrlRedecorator

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
eZ/Publish/API/Repository/Tests/FieldType/RelationIntegrationTest.php
eZ/Publish/Core/FieldType/Relation/Type.php
eZ/Publish/Core/FieldType/Tests/RelationTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationConverter.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/RelationTest.php
eZ/Publish/SPI/Tests/FieldType/RelationIntegrationTest.php

This PR adds allowed classes to single object relation field. @andrerom suggested this PR, which does the same for legacy:
https://github.com/ezsystems/ezpublish-legacy/pull/1201
This feature requires changes in 3 bundles, so I have 3 PRs. The other 2:
* https://github.com/ezsystems/PlatformUIBundle/pull/878
* https://github.com/ezsystems/repository-forms/pull/127
I made the storage of the settings in xml in the dataText5 field. It is compatible with the old way, but it drops that schema on the next save of the content type. So if someone has stuff in dataInt1 and dataInt2 cause of an upgrade, then those will work, but when someone saves the content type, then they will be emptied and converted to xml into dataText5.
I didnt include the `type` and `object_class` deprecated xml tags in …

EZP-24800 Support allowed classes limitation for object relation fields

---

eZ/Publish/API/Repository/Tests/Values/User/Limitation/ObjectStateLimitationTest.php
eZ/Publish/Core/Limitation/ObjectStateLimitationType.php
eZ/Publish/Core/Limitation/Tests/ObjectStateLimitationTypeTest.php
eZ/Publish/SPI/Limitation/Type.php

> [EZP-27528](https://jira.ez.no/browse/EZP-27528)
#
Excerpt from the JIRA:
> When using multiple StateGroup limitations in one policy they combine using the "or" relationship instead of the "and" one. This means only one of these limitations must apply in order for the policy to work. Other limitations combine using the "and" relationship.
I found out that all the StateGroup limitations from one policy are combined together and verified against the object states. This means only one match is required for all StateGroup limitations to pass.
In this PR I changed this behaviour to at first find out which StateGroups are used for the limitation and then try to match all of them separately against the object states. If at least one of them doesn't match, then the StateGroup limitation fails. …

Fix EZP-27528: Multiple StateGroup limitations in one policy combine with the "or" relationship instead of the "and" one

---

eZ/Publish/API/Repository/Tests/BaseContentServiceTest.php
eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php

Fixes [EZP-27097](https://jira.ez.no/browse/EZP-27097)
----
User authorized by Node (Location) Limitation policy on content/create and content/publish is unable to copy content to that location.

EZP-27097: Can't copy objects to an authorized location limited by policies

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Page.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Templates.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/Contextualizer.php

[EZP-27497](https://jira.ez.no/browse/EZP-27497)
One of our sites has about 100 siteaccesses.
In eZ Platform 1.7 the container class file has a file size of over 30 MB.
I think we could skip merging of settings when there are no group or siteaccess settings.
Then the settings in default and global scope should be enough.
If you also think so, I can create a issue for it.

Fix EZP-27497: Large container class file when there are many siteaccesses

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/slot.yml
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/RemoveTranslationSlot.php

Implements [EZP-27713](https://jira.ez.no/browse/EZP-27713)
----
This PR implements `RemoveTranslationSlot` in `eZ\Publish\Core\MVC\Symfony\Cache\Http` for HttpCache.
**Note**: for now please disregard TMP commits - just helpers to perform some tests.
**TODO**:

EZP-27713: As a Developer I want HttpCache to handle RemoveTranslationSignal

---

doc/specifications/translations/removal.md

Spec/Doc follow-up after [EZP-27712](https://jira.ez.no/browse/EZP-27712) and [EZP-27713](https://jira.ez.no/browse/EZP-27713)
----
The note in the spec is no longer valid since 
- ezsystems/ezpublish-kernel#2060
- ezsystems/ezplatform-solr-search-engine#98
- ezsystems/ezpublish-kernel#2062
- ezsystems/ezplatform-http-cache#13
got merged.
*Sorry, I forgot about that ;)*

[Spec] Aligned removeTranslation Spec after adding Slots

---

eZ/Publish/Core/Persistence/Legacy/Content/TreeHandler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/TreeHandlerTest.php

> JIRA: -
Method `eZ\Publish\Core\Persistence\Legacy\Content\TreeHandler::changeMainLocation` expects only two arguments, but four are passed when `changeMainLocation` method call in  `eZ\Publish\Core\Persistence\Legacy\Content\TreeHandler::removeSubtree`.

Too many parameters passed to changeMainLocation method call

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php

Fixes [EZP-27764](https://jira.ez.no/browse/EZP-27764)
----
This PR fixes the bug related to URL aliases not being updated after translation removal, discovered by @rpmsauron while testing [EZP-27713](https://jira.ez.no/browse/EZP-27713).
The database table `ezurlalias_ml` contains column `lang_mask` which also needs to be updated after translation removal.
I've identified two cases for which to apply the fix:
1. `ezurlalias_ml` row can contain URL alias related to only one language with or without `alwaysAvailable` bit. This occurs when field based on which URL alias is generated is different in the specific translation.
2.  `ezurlalias_ml` row can contain URL alias related to multiple languages basically when links don't differ.
Fix:
1. Update `lang_mask` by removing `languageId` of …

EZP-27764: Translation removal does not update language mask for URL alias

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_image.html.twig

`embed_image.html.twig` view should be responsible for handling missing `objectParameters` parameter because it's possible to render view without it *(e.g in case of Embed Block and Collection Block in EE)* and has a very specific default value.
Note: Contrary to the initial Jira issue description, problem exists independently of env or debug settings. It's just silent when debug is false as the Twig setting `twig.strict_variables` depends on the `%kernel.debug%` parameter.

EZEE-1716: Cannot render embedded ezimage in CollectionBlock Gallery View

---

eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/API/Repository/URLAliasService.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
eZ/Publish/Core/Repository/URLAliasService.php

> JIRA: https://jira.ez.no/browse/EZP-27773
This PR adds limitation for the depth level of URL alias in the `eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\Handler::lookup` method. Without it, some URLs are end up with the fallowing database error: 
```SQLSTATE[HY000]: General error: 1116 Too many tables; MariaDB can only use 61 tables in a join at ...```  (see JIRA issue for more details)
Try access the URL with more than 60 segments like:
`http://SOME_EZP_INSTALLATION/0/1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24/25/26/27/28/29/30/31/32/33/34/35/36/37/38/39/40/41/42/43/44/45/46/47/48/49/50/51/52/53/54/55/56/57/58/59/60/61/62/63/64/65/66/67/68/69/70/71/72/73/74/75/76/77/78/79/80/81/82/83/84/85/86/87/88/89/90/91/92/93/94/95/96/97/98/99`

EZP-27773: Validation of depth level of url alias in the Legacy UrlAlias Handler

---

eZ/Publish/Core/FieldType/Page/PageStorage/Gateway/DoctrineStorage.php

EZP-26885 in #1993 introduced a regression in page field type DoctrineStorage gateway
Missing alias on inner join and missing ':' in setting parameter

EZP-27800: Fix innerJoin on page doctrine gateway

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/ContentService.php

PHP `ContentService::removeTranslation` uses `content / delete` but the actual proper module / function name should be `content / remove`
Backported to `6.11` as this feature exists since `v6.11.0`
**TODO**:

EZP-27886: [PAPI] Wrong policy function name used by ContentService::removeTranslation

---

eZ/Publish/Core/FieldType/Tests/StringLengthValidatorTest.php
eZ/Publish/Core/FieldType/Tests/TextLineTest.php
eZ/Publish/Core/FieldType/TextLine/Type.php
eZ/Publish/Core/FieldType/Validator/StringLengthValidator.php

> JIRA: https://jira.ez.no/browse/EZP-27876
This PR replace `strlen` with `mb_strlen` in length validation of TextLine field value (users expects length as number of characters instead of number of bytes)

Fix EZP-27876: Replace strlen with mb_strlen in length validation of TextLine field value

---

eZ/Bundle/EzPublishCoreBundle/Command/RemoveContentTranslationCommand.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/ContentService.php

This PR improves experience of removing of a Translation from all Versions of a Content Object by:
The mentioned command takes care of:
- Removing Versions which have only one Translation, the one to be removed (note that risks involved with changing published Version or the last remaining are already handled by API by throwing an exception).
- Updating main Translation / Language if the one being removed is the main one. User gets interactive choice of main Language.
Command was named `remove-content-translation` to distinguish it from upcoming feature to remove Translation from a single Version.

EZP-27842: Improve process of Translation removal from all Versions

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml

> JIRA: https://jira.ez.no/browse/EZP-27791
This PR change the configuration of default router by adding _ez_user_hash to non siteaccess aware routes.
In the siteaccess matching configuration based on URI, the HTTP proxy is unable to get the proper user hash, because we cut off the siteacceess prefix from URI before router match the request. See JIRA issue for more information.

Fix EZP-27791: Mark "_ez_user_hash" route as non siteaccess aware by default

---

eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php

> Issue: https://jira.ez.no/browse/EZP-28008
Add cache clearing of remote id lookup of ContentInfo in updateMetadata() call.
Additionally remove unneeded cache warming in these cases as to make sure the 100% correct data retrieved on load is rather cached instead. In the case of `updateContent` it warms up content for all translations, however this might not even be used by the given setup if specific languages are always loaded. So reduce complexity here basically.

EZP-28008: Clear remote id cache on meta data updates & remove inaccurate cache warmers

---

doc/specifications/translations/removal.md
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/BaseContentServiceTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/SPI/Persistence/Content/Handler.php

This PR implements PHP API method:
```
ContentService::deleteTranslationFromDraft(VersionInfo $versionInfo, $languageCode);
```
which deletes the Translation specified by a language code from a Content Object Version Draft.
Related PRs:
- #2001 - initial discussions for similar feature removing Translation from the entire Content, naming introduced there will be changed according to [this conclusion](https://github.com/ezsystems/ezpublish-kernel/pull/2081#issuecomment-334177307)
- #2086 - REST endpoint using PHP API implemented by this PR.
Note: It's a responsibility of PHP API Consumer to first create Draft and then publish it after removing language. Moreover, if a Translation is the main one, it needs to be changed manually using `ContentService::updateContentMetadata` first.
**TODO**: …

EZP-27508: As a Developer I want an API that removes a translation from a version

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/030-emphasisStrikedthroughDeleted.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/030-emphasisStrikedthroughDeleted.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/030-emphasisStrikedthroughDeleted.xml

> Issue: https://jira.ez.no/browse/EZP-28044
Changes to the following mapping for these tags so we can support strikethrough in editor as well as also continue to support `<del>` which might be useful in the future.
- `<s>` => `<emphasis role="strikedthrough">` _(this was mapped to `<del>` before)_
- `<del>` => `<emphasis role="strikedthrough" revisionflag="deleted">`
This also means that the meaning of strikedthrough text already migrated from eZ Publish will now correctly be displayed as strike in the editor and view, instead of being converted to `<del>` which editor did not support and which has other meaning.
Todo:

EZP-28044: As an Developer I want support for striked text in RichText

---

eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/DoctrineStorage.php
eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php

This is a follow up on #2107 which aligns new code introduced in `6.11` with new `php-cs-fixer` settings merged into `6.7`.
It includes:
Note: `master` also requires such alignment for the file `eZ/Bundle/EzPublishCoreBundle/Command/RemoveContentTranslationCommand.php` present only on that branch.

[CS] Aligned code according to CS rules introduced by php-cs-fixer v2.7.1

---

eZ/Publish/API/Repository/SearchService.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/SignalSlot/SearchService.php

> Issue: https://jira.ez.no/browse/EZP-28083
Suggestion for how user might be able to detect if given search engine support advance full text capability.
Use case: eZ backend UI for knowing if it should show help text to user on the advance search features or not.
Todo:

EZP-28083: As a Developer I would need to detect capabilities of configured search engine

---

composer.json

It seems there are no breaking changes from 1.x to 2.x apart from bumping the PHP requirement to 7.0 (https://github.com/1up-lab/OneupFlysystemBundle/compare/1.14.0...2.0.0)
It would also allow using the version of bundle which has a same issue fixed as https://github.com/ezsystems/ezpublish-kernel/pull/2109

Allow FlySystem Bundle 2.0

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php

On Symfony 3.4, using `>cannotBeEmpty()` on concrete array nodes results in a `RuntimeException`:
```
->cannotBeEmpty() is not applicable to concrete nodes at path "ezpublish.system..http_cache"
```

Remove cannotBeEmpty as it is not applicable to concrete nodes in Symfony 3.4

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

When trying to install eZ Platform `2.0` today I've encountered the following error:
```
PHP Warning:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: require(var/cache/dev/ContainerD7xjza8/getSwiftmailer_EmailSender_ListenerService.php): failed to open stream: No such file or directory in var/cache/dev/ContainerD7xjza8/Container.php:3923
```
I'm not 100% sure, but it seems something changed in Sf 3.4 with regards to cache clearing.
I've found out that [EZP-24158](https://jira.ez.no/browse/EZP-24158) introduced this manual cache clearing in Installer due to some dev environment problems. 
I removed it and now installer works w/o errors. Also I don't get the error described in the original issue. 
AFAICS `$this->cacheClearer->clear($this->cacheDir);` should be …

[Installer] Removed manual cache clearing as it crashes on Sf 3.4

---

eZ/Publish/Core/Repository/UserService.php

> Fix https://jira.ez.no/browse/EZP-28147
> Work in progress
> Regression from https://github.com/ezsystems/ezpublish-kernel/pull/2095 (Well, sort of. This bug existed even before that, but since most used the default hash, it was not discovered until the default hash algorithm changed.)
`UserService::updateUser()` always sets the password hash type to the default value, regardless of whether the password is updated or not. So when editing a user whose hash type is not the default, and not updating the password, the hash and hash type will no longer match, and login will fail.
Fix by only updating the hash type when the password is updated.
TODO

EZP-28147: Updated user cannot log in

---

eZ/Publish/Core/Limitation/ObjectStateLimitationType.php
eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ObjectStateHandlerTest.php

> Issue: https://jira.ez.no/browse/EZP-28148
Cause: On installs with a lot of object states the system creates a lot of lookups for them, most notably during permission checks in Object States Limitation Type.
This takes one of the changes in SPI Cache from 7.0, changing from storing id's in cache to the full objects to avoid lookups in loops. 7.0 will be even faster thanks to Symfony Cache, however for now these two changes should hopefully help quite a bit.

EZP-28148: Object States Limitations perform a lot of lookups

---

eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

> JIRA: https://jira.ez.no/browse/EZP-28046
When the user modifies field which is part of the content name,  the URL alias cache should be also cleared for children locations. If the cache isn't cleared for children locations then renaming parent leads to redirect loop when accessing child location's old URL
> 2. Create new container object (e.g. Folder "My Folder").
> 3. Create new object inside this container (e.g. Image "My Image").
> 4. Navigate to both of them in the front office (http://example.com/My-Folder and http://example.com/My-Folder/My-Image).
> 5. Rename "My Folder" to "My Folder Modified".
> 6. Reload child's old URL in the frontoffice (e.g. http://example.com/My-Folder/My-Image).
> 7. Observe infinite redirect loop.

Fix EZP-28046: Renaming parent leads to redirect loop when accessing child location's old URL

---

eZ/Publish/Core/Repository/Helper/RelationProcessor.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php

> JIRA: https://jira.ez.no/browse/EZP-28045
This PR contains patch for `Trying to get property of non-object` after publishing content when previously relation field was removed from content type definition. 
> 1. Edit default Article ContentType
> 2. Add Single Relation or Multiple Relation field. Save and publish ContentType.
> 3. Create new Article. Set all required values and set relation to any allowed content.
> 4. Publish article.
> 5. Edit Article ContentType, remove Single Relation or Multiple Relation added previously.
> 6. Save and publish ContentType.
> 7. Go to Content, find your Article created in step 3. Edit article. You don't need to change anything. Click Publish.

EZP-28045: Cannot modify content after removing relation field from ContentType

---

data/update/mysql/dbupdate-6.11.0-to-6.12.0.sql
data/update/postgres/dbupdate-6.11.0-to-6.12.0.sql

> Issue: https://jira.ez.no/browse/EZP-28185
eZ Platform 1.12.0 ships with ezpublish-kernel 6.12, which allows using longer hashes for passwords in the future (See https://jira.ez.no/browse/EZP-24744). This requires a change to the DB schema.
Unlike previous schema changes, this is not included in the SQL files to update the schema. This PR adds the SQL files for MySQL and PostgreSQL from [the eZ Platform upgrade instructions](https://doc.ezplatform.com/en/1.12/releases/updating_ez_platform/#__code_12) under the `data/update` directory structure:
- data/update/mysql/dbupdate-6.11.0-to-6.12.0.sql
- data/update/postgres/dbupdate-6.11.0-to-6.12.0.sql

EZP-28185: Database update SQL missing from Kernel 6.12

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/slot.yml
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/CopySubtreeSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/CopySubtreeSlotTest.php

> JIRA: https://jira.ez.no/browse/EZP-28160
This PR adds a missing HTTP Cache purging after the subtree copying. Discovered while testing https://github.com/ezsystems/PlatformUIBundle/pull/893#issuecomment-340418960 
Similar to https://github.com/ezsystems/ezplatform-http-cache/pull/18
> 1. Create the following structure:
> a) Home/Folder A
> b) Home/Folder A/Folder B
> c) Home/Folder A/Folder B/Article
> 2. Copy subtree Folder B into Folder A
> 3. Copy subtree Folder B into Folder A again
> 4. Go to location view for Folder A
> 5. The pagination is broken (see attached screenshot) because childCount in response to GET /api/ezp/v2/content/location/X/Y is out of date.

EZP-28160: Added HTTP Cache purge after copying subtree

---

eZ/Publish/API/Repository/PermissionCriterionResolver.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
eZ/Publish/Core/Repository/Permission/PermissionCriterionResolver.php
eZ/Publish/Core/Repository/PermissionsCriterionHandler.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/Tests/Permission/CachedPermissionServiceTest.php
eZ/Publish/Core/Repository/Tests/Permission/PermissionCriterionResolverTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionsCriterionHandlerTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php

> Issue: https://jira.ez.no/browse/EZP-28143
Cause: For non admin users, the permissions system needs to generate a query based on limitations assigned to a user. If the permissions grow complex, or the system uses a lot of object states, this will become _very_ expensive.
However if we can detect when current user changes, we can cache this permission criteria in memory as it does not change very often. For safety measure we can have a low ttl to avoid this getting stale. If it does get stale the user being served might experience seeing permission exceptions if user has lost access to something which happens to be part of search result.
Alternative would be to cache this in cache pool, however in current 5.x/6.x design that would imply moving logic down to SPI, which would imply …

EZP-28143: getPermissionCriterion() should be cached per user

---

eZ/Publish/Core/MVC/Symfony/FieldType/RichText/Renderer.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RichText/RendererTest.php

> JIRA: https://jira.ez.no/browse/EZP-28123
This PR contains patch for exception `Cannot generate an UrlAlias route for content without main location` which is thrown when rendering richtext with an embedded object which is trashed. 
> 2. In the back-office, create new Folder Content Type under "eZ Platform" named "Test Folder".
> 3. In the Media/Files, create new File Content Type named "Test File".
> 4. Edit the "Test Folder". In the "Description" field, embed the "Test file" using the "+" and "Embed" buttons from the Rich Text Editor. Publish "Test Folder".
> 5. In the front-office, navigate to "/Test-Folder". Confirm that the embedded Content Object "Test file" is also displayed.
> 6. In the backoffice, navigate to "Media/Files/Test file" and …

EZP-28123: Embedded content throws exception after it is moved to trash

---

eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RichText/RendererTest.php

For RichText Renderer unit test we have to mock Core Repository instead of API Repository because API interface doesn't have `sudo` method which is being mocked.
I also fixed references to deprecated `getMock` along the way.
Though related to #2132 not back-porting to 6.7 as this change was introduced on merge to master due to PHPUnit 5.7 update

[Tests] RichText RendererTest: Fixed mocks to align with PHPUnit 5.7

---

eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/API/Repository/Values/User/User.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/Repository/Values/User/User.php

> Attempt at implementing https://jira.ez.no/browse/EZP-28158
> which is to add a test for https://jira.ez.no/browse/EZP-28147 aka. https://github.com/ezsystems/ezpublish-kernel/pull/2129
> Sent to QA

EZP-28158: Test for EZP-28147 Updated user cannot log in

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/HttpCachePass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/HttpCachePassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php

> Issue: https://jira.ez.no/browse/EZP-28243
1. Fixes so it is possible to use this setting as documented in semantic config help text.
2. Make it possible to add plugin system for ezplatform-http-cache in order to add Fasly support: https://github.com/ezsystems/ezplatform-http-cache/pull/19

EZP-28243: Purge type using service id does not work

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
eZ/Publish/Core/Search/Common/IncrementalIndexer.php
eZ/Publish/Core/Search/Legacy/Content/Indexer.php

> issue: https://jira.ez.no/browse/EZP-28176
As a Developer I want a indexing command which is:
- faster at indexing (parallel indexing)
- able to refresh parts of index (by date or content id)
- able to omit purging so index is gradually refreshed on running prod setup
- able to remove index items if no longer existing (when I provide content id's to index)
Todo:

EZP-28176: Support for parallel and selective indexing command

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
eZ/Bundle/EzPublishCoreBundle/EventListener/BackgroundIndexingTerminateListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/BackgroundIndexingTerminateListenerTest.php
eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/Core/Search/Common/BackgroundIndexer.php
eZ/Publish/Core/Search/Common/BackgroundIndexer/NullIndexer.php
eZ/Publish/Core/settings/repository.yml

Issue: https://jira.ez.no/browse/EZP-28177
Related:
- https://github.com/ezsystems/ezpublish-kernel/pull/2139 Parallel and selective indexing 
- https://github.com/ezsystems/ezpublish-kernel/pull/2126 getPermissionCriterion() cache
As a Developer I want a indexing command which is:
A Search service which is more tollerant of search index inconsitencies
Log of when this occures
Attempt to self heald (re- index or remove form index) in cases item is not published or removed
Todo:

EZP-28177: Tolerant and self healing Search service

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SecurityPass.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/SecurityPassTest.php
eZ/Publish/Core/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php

> Fix https://jira.ez.no/browse/EZP-27996
> Sent to QA
Symfony's `RememberMeAuthenticationProvider` does not set eZ's repository user (of course).
Fix: Add our own, which does.

EZP-27996: "Remember me" doesn't retrieve the current user from Repository

---

eZ/Publish/Core/IO/IOMetadataHandler/LegacyDFSCluster.php
eZ/Publish/Core/IO/Tests/IOMetadataHandler/LegacyDFSClusterTest.php

This PR fix command `liip:imagine:cache:remove --filters=filter_name` not removing metadata but only binary files.
short debug story for image alias "medium":
- IOVariationPurger::purge
```
$directory = "_aliases/$aliasName";
$this->io->deleteDirectory($directory);
// $directory = '_aliases/medium'
```
- IOService::deleteDirectory
```
$prefixedUri = $this->getPrefixedUri($path);
$this->metadataHandler->deleteDirectory($prefixedUri);
// $directory = 'images/_aliases/medium'
```
- LegacyDFSCluster::deleteDirectory
```
$stmt = $this->db->prepare('DELETE FROM ezdfsfile WHERE name LIKE ?');
$stmt->bindValue(1, rtrim($spiPath, '/') . '/%');
// $spiPath = 'images/_aliases/medium'
// sql: DELETE FROM ezdfsfile WHERE name LIKE "images/_aliases/medium/%"
// name in database: …
```

EZP-28203: image alias removal command not removing data from "ezdfsfile" table

---

eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/API/Repository/TrashService.php
eZ/Publish/Core/REST/Client/TrashService.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/Core/SignalSlot/TrashService.php

> Fix https://jira.ez.no/browse/EZP-25636
> Work in progress
> Also needs https://github.com/ezsystems/PlatformUIBundle/pull/921

EZP-25636: User can't access trash if 1+ items are not readable

---

doc/bc/changes-6.13.md
doc/specifications/translations/removal.md
eZ/Bundle/EzPublishCoreBundle/Command/DeleteContentTranslationCommand.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/slot.yml
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/DeleteTranslationSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/RemoveTranslationSlot.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Search/Common/Slot/DeleteTranslation.php
eZ/Publish/Core/Search/Common/Slot/RemoveTranslation.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Signal/ContentService/DeleteTranslationSignal.php
eZ/Publish/Core/SignalSlot/Signal/ContentService/RemoveTranslationSignal.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml
eZ/Publish/Core/settings/search_engines/legacy/slots.yml
eZ/Publish/SPI/Persistence/Content/Handler.php

This PR deprecates `ContentService::removeTranslation`  and introduces new name `ContentService::deleteTranslation` for this method to keep consistent naming in new stack.
**TODO**:

EZP-28028: As a Developer I want API removing Translations to use consistent naming

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Cache/Http/InstantCachePurgerTest.php
eZ/Publish/API/Repository/TrashService.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/InstantCachePurger.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/InstantCachePurgerTest.php
eZ/Publish/Core/REST/Client/TrashService.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/Core/SignalSlot/TrashService.php

> Fix https://jira.ez.no/browse/EZP-28048
> Ready for review
Editors who are allowed to trash content but don't have read access to trash, get an access denied message when trashing things (though the content is successfully trashed). Fix: Use sudo() to force it.

EZP-28048 Moving to trash shouldn't give error if you can't read items in trash

---

eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ObjectStateHandlerTest.php

> Issue : https://jira.ez.no/browse/EZP-28247
This clears the object state group cache when a new object state is created

EZP-28247: Creating an new object state does not clear the group cache

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

Issue caused by distinct added which does not like the order by, I guess we don't really need the order by so suggesting to remove it.

EZP-28176: Fix SQL error on indexing with --subtree argument
