eZ/Bundle/EzPublishRestBundle/Resources/config/security.yml
eZ/Publish/Core/REST/Server/Security/RestLogoutHandler.php
eZ/Publish/Core/REST/Server/Tests/Security/RestLogoutHandlerTest.php

JIRA issue: https://jira.ez.no/browse/EZP-28210
This PR improves `RestLogoutHandler` to make it able to remove session cookie even if `session.cookie_domain` and `session.cookie_path` is set.

EZP-28210: Logout not working when session cookie domain set

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Languages.php
eZ/Bundle/EzPublishDebugBundle/Collector/EzPublishCoreCollector.php
eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Publish/Core/settings/fieldtype_external_storages.yml

* Implements the `reset()` method in `EzPublishCoreCollector`
* Removes usage of case insensitive parameter names
* Replaces `cannotBeEmpty` with `requiresAtLeastOneElement` in `$languages$` semantic configuration.

Remove some deprecations on Symfony 3.4

---

doc/bc/changes-7.0.md
eZ/Publish/API/Repository/Tests/FieldType/TimeIntegrationTest.php
eZ/Publish/Core/FieldType/Tests/TimeTest.php
eZ/Publish/Core/FieldType/Time/Value.php

| Q | A |
|---|---|
| **Issue** | [EZP-28269](https://jira.ez.no/browse/EZP-28269) |
| **Related to** | #2158 |
| **Type** | Bug |
| **BC break** | yes |
| **Target branch** | `7.0` |
We've discovered inconsistent behavior of [`Time\Value::fromTimestamp`](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.6/eZ/Publish/Core/FieldType/Time/Value.php#L89-L90) with respect to [`DateAndTime\Value::fromTimestamp`](https://github.com/ezsystems/ezpublish-kernel/blob/v6.7.6/eZ/Publish/Core/FieldType/DateAndTime/Value.php#L71). The former one creates Time Value relying on PHP server timezone setting, while the latter - creates Value w/o timezone (or using UTC).
There is [a difference](http://php.net/manual/en/datetime.settimestamp.php#117238) in setting `\DateTime` value using constructor …

[7.0] EZP-28269: Fixed inconsistent creating of eztime fromTimestamp

---

doc/bc/changes-7.0.md
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

Q | A
-- | --
Issue | [EZP-28309](https://jira.ez.no/browse/EZP-28309)
Type | Bug
BC break | yes
Target branch | 7.0
The root of the problem is handling **number of seconds** as a timestamp in order to use date formatter to display time. This isn't ideal because `eztime`, according to the requirements **should not be** timezone-dependent. Anyway, using date formatter is accepted as long as you force `UTC` timezone to avoid adjusting time to match server's timezone. As far as I remember the same kind of fix was used in v1 (done by the javascript though).

[7.0] EZP-28309: Fixed twig template for eztime incorrectly parsing time value

---

eZ/Publish/API/Repository/LocationService.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/SignalSlot/LocationService.php

| ------------- | --------- |
| **JIRA issue** | [EZP-28316](https://jira.ez.no/browse/EZP-28316) |
| **Related to** | [EZP-28315](https://jira.ez.no/browse/EZP-28315) |
| **Type** | Improvement |
| **BC break**    | no |
| **Target version** | `6.13` |
| **PHP API** | `LocationService::loadParentLocationsForDraftContent` |
While working on v2 create draft, we've discovered missing feature on `LocationService` to allow loading assigned Location node(s) for newly created, not published Draft (usually to do it Content has to be published first).
There is already a method for that on Persistence Handlers layer in `eZ\Publish\SPI\Persistence\Content\Location\Handler::loadParentLocationsForDraftContent`, however it had been not exposed as `LocationService` API. This PR …

EZP-28316: [PAPI] As a Developer I want the API to get Locations for Draft

---

eZ/Bundle/PlatformInstallerBundle/src/Installer/CleanInstaller.php
eZ/Bundle/PlatformInstallerBundle/src/Installer/DbBasedInstaller.php

| Q | A |
|---|---|
| **Issue** | [EZP-28262](https://jira.ez.no/browse/EZP-28262) |
| **Related to** | #2153 and [EZP-24842](https://jira.ez.no/browse/EZP-24842) |
| **BC break** | no |
| **Target branch** | `master` |
This PR is `6.x` backport of #2153. It adds a wrapper for checking and getting DBMS-specific SQL files from `/data/` directory with possibility to reuse by custom Installers and replaces hardcoded `/vendor/ezsystems/ezpublish-kernel` path.
**TODO**:

[Installer] EZP-28262: Replaced hardcoded DBMS-specific SQL file paths

---

composer.json
eZ/Bundle/EzPublishRestBundle/Resources/config/security.yml
eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
eZ/Publish/Core/REST/Server/Controller/SessionController.php
eZ/Publish/Core/REST/Server/Security/CsrfTokenManager.php
eZ/Publish/Core/REST/Server/Tests/Security/CsrfTokenManagerTest.php

> JIRA: https://jira.ez.no/browse/EZP-28306
This patch fixes broken login to PlatformUI over https with Symfony 2.8.31. Cause of the problem was missed `namespace` prefix (introduced by https://github.com/symfony/symfony/pull/24992) in token id in  `\eZ\Publish\Core\REST\Server\Controller\SessionController::hasStoredCsrfToken`.

EZP-28306: Fixed missing namespace prefix in token id  when checking if CSRF token is stored

---

eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/CreateLocationSignal.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/HideLocationSignal.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/MoveSubtreeSignal.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/SwapLocationSignal.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/UnhideLocationSignal.php
eZ/Publish/Core/SignalSlot/Signal/LocationService/UpdateLocationSignal.php
eZ/Publish/Core/SignalSlot/Tests/LocationServiceTest.php

> Issue: https://jira.ez.no/browse/EZP-28326
Adds parent location to location based signals so cache system can use this, especially important on for instance Move where this info is lost afterwards.

EZP-28326: Improve Signals to contain affected parent locations

---

doc/specifications/translations/removal.md
eZ/Bundle/EzPublishCoreBundle/Command/DeleteContentTranslationCommand.php
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/SignalSlot/ContentService.php

PHP API deleteTranslation improvement on handling single-Translation Version
----
| Q | A |
|---|---|
| **Issue** | [EZP-28271](https://jira.ez.no/browse/EZP-28271) |
| **Type** | Improvement |
| **BC break** | no, deleteTranslation appeared in `6.13` |
| **Target branch** | `6.x` |
This PR improves PHP API `ContentService::deleteTranslation` to handle a case when a Translation being deleted exists as a single Translation for non-published Versions.
**TODO**:

EZP-28271: Changed ContentService::deleteTranslation() to remove versions that only exist in that language

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/xsd/Version.xsd
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Values/Content/Field.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Version.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/VersionTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php

| --- | --- |
| **JIRA issue** | [EZP-28253](https://jira.ez.no/browse/EZP-28253), [EZP-28276](https://jira.ez.no/browse/EZP-28276) |
| **Type** | Improvement |
| **Target version** | `6.13` |
This PR implements two related stories, introducing:
- on PHP API level, to `eZ\Publish\API\Repository\Values\Content\Field` a property `typeIdentifier` which contains Field Type identifier (`ezstring`, `ezdate`, etc.)
- on REST API level this new propery value for Version response at `//Version/VersionInfo/Fields/field/typeIdentifier`.
**TODO**:

EZP-28253: [REST] As a frontend developer I would like to get information about field type in the CurrentVersion object

---

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php

Now that we require PHP 7.1 and have greatly improved performance of backend placing hinst on performance tuning does not need to take space here anymore.
Besides that:
- updated to use dev, with symfony 3 builtin server is only available in dev by default
- update to use `/admin` url for backend
- somewhat simplified the text a bit
Open question:

[7.0] Update & Simplify install instructions

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Publish/Core/FieldType/RichText/InternalLinkValidator.php
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/Tests/RichText/InternalLinkValidatorTest.php
eZ/Publish/Core/settings/fieldtype_services.yml
eZ/Publish/Core/settings/fieldtypes.yml

> JIRA: https://jira.ez.no/browse/EZP-28174
This PR adds validation of `ezlocation://` and `ezcontent://` links on the the richtext field type definition level. 
Currently, if link target does not exist the `NotFound` with message `Could not find 'location' with identifier '63'` exception is thrown  (https://github.com/ezsystems/ezpublish-kernel/blob/6.7/eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php#L84) when content relations are processed
> 1. Create new Article (or another ContentType object which has RichText filed) for e.g. Article A,
> 2. Create the second content object, for e.g. Article B. Let's assume, that this article has LocationId 63.
> 3. Edit Article A, in RichText editor, add some paragraph with text, select few words and click on add URL …

EZP-28174: Validation of ezlocation:// and ezcontent:// links in the richtext field type

---

.travis.yml
doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php
eZ/Bundle/PlatformBehatBundle/Command/CreateLanguageCommand.php
eZ/Publish/Core/REST/Server/Controller/Content.php

REST endpoint for deleting Translation from all Versions
----
|---|---|
| **Status** | Ready for a review |
| **Issue** | [EZP-27752](https://jira.ez.no/browse/EZP-27752) |
| **REST API** | `DELETE /content/objects/<ID>/translations/<languageCode>` |
| **Target version** | `6.13` |
This PR implements REST API endpoint for PHP API `ContentService::deleteTranslation` which removes a Translation given by the language code from all the Versions of a Content item.
**TODO**:

EZP-27752: As a REST Consumer I want to remove translation from all Versions

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

> issue: https://jira.ez.no/browse/EZP-28176
When _(by default when you have more than 50 items in db)_ running indexing in parallel, the first process would fail as there was a missing return on the php path function after the method was refactored during later stages of the PR work.

EZP-28176: missing return on php path crashing first indexing process

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

> issue: https://jira.ez.no/browse/EZP-28176
As proposed in #2173, change behaviour for 1.7LTS to be more conservative, by disabling `processes` by default, and let it support `auto` as option for picking number of CPU cores -1 as value.
Two commits here:
- Add `auto` option as the default one, + some formating fixes
- Change default to `1` for 1.7LTS

EZP-28176: Add 'auto' option on processes, & change default to disabled for 1.7LTS

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Tests/Functional/xsd/Version.xsd
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Values/Content/Field.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Version.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/VersionTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php

| --- | --- |
| **Status** | Ready for a review |
| **JIRA issue** | [EZP-28337](https://jira.ez.no/browse/EZP-28337) |
| **Related to** | #2168 |
| **Alternative to** | #2175 |
| **BC break**   | no, still within the scope of `6.13` |
| **Type** | Improvement |
| **Target version** | `6.13` |
This PR aligns naming convention introduced in #2168 with other parts of the system by renaming
`eZ\Publish\API\Repository\Values\Content\Field::$typeIdentifier`
to `fieldTypeIdentifer`.
There are two major issues with my push to strictly follow DDD:
1) We have a lot of overlapping names, so distinguishing between them is good for a developer.
2) Trying to align other parts of the system with proper naming convention proved to be risky and covered too wide of a scope, see …

EZP-28337: As a Developer I want API Field Type properties to use consistent naming

---

doc/bc/changes-6.13.md
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/API/Repository/Values/User/User.php
eZ/Publish/Core/Repository/UserService.php

> Fix https://jira.ez.no/browse/EZP-28214 for new stack
> For legacy, see https://github.com/ezsystems/ezpublish-legacy/pull/1334
> Sent to QA
Invalid password hash type should not be silently ignored, and we should not default to MD5.
Fix: Throw an exception if an invalid password hash type is specified.

EZP-28214: Password hash silently defaults to MD5

---

eZ/Publish/Core/Repository/ContentService.php

Hey,
Solves this old chestnut:
```php
try {
$contentService->loadContentByRemoteId("ATOTALLYLEGITREMOTEID", ['eng-GB'], 12345678);
} catch (\Exception $e) {
print $e->getMessage();
}
```
Where the remote ID doesn't exist.
`"Could not find 'Content' with identifier 'array (   'remoteId' => 1024,   'languages' =>    array (     0 => 'eng-GB',   ),   'versionNo' => 12345678, )"`

fix(): NotFoundException suggests it loads an id by remoteId.

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

> Issue: https://jira.ez.no/browse/EZP-28449
Solves:
- incompatibility with Symfony 3.4
- having to write to app/cache on install _(if setup with redis/memcached that is uneasier)_
- Actually clearing the cache relevant for install and indexer, even when setup with redis/memcached
@emodric I did not target 6.7 here to be on the safe side, is that a problem? _(if so you'll need to report issue for 6.7)_

EZP-28449: [Installer] Clear cache pool and not whole symfony cache on install

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php

| ------------ | ---------- |
| **Status** | Ready for a review |
| **JIRA issue** | [EZP-28375](https://jira.ez.no/browse/EZP-28375) |
| **Related to** | #2166 |
| **Target version** | `6.7` |
| **BC break** | no |
| **Tests pass** | yes |
This PR backports REST Functional tests fixes done for #2166 to `6.7`.
**TODO**

EZP-28375: Improved REST Functional Tests

---

eZ/Publish/API/Repository/Tests/FieldType/RelationListIntegrationTest.php
eZ/Publish/Core/FieldType/Relation/Type.php
eZ/Publish/Core/FieldType/Relation/Value.php
eZ/Publish/Core/FieldType/RelationList/Type.php
eZ/Publish/Core/FieldType/Tests/RelationListTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/RelationListConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/RelationListTest.php
eZ/Publish/SPI/Tests/FieldType/RelationListIntegrationTest.php

> JIRA: https://jira.ez.no/browse/EZP-28410
Adds selection limit to `ezobjectrelationlist` as there is an ongoing process od merging relation fieldtypes. This is the first step which allows to use `ezobjectrelationlist` the same way as `ezobjectrelation`.

EZP-28410: Add selection limit setting to ezobjectrelationlist fieldtype

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/policies.yml

https://jira.ez.no/browse/EZP-28470

EZP-28470: Allow state limitation on manage_locations

---

composer.json

We're integrating some libs that use CMF Routing 2.0, so this would help.
It seems there are no breaking changes between 2.0 and 1.x: https://github.com/symfony-cmf/Routing/compare/2.0...1.3

Allow symfony-cmf/routing 2.0

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/LocationView.php

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-28506
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes, no, maybe
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Implementation is different from [documentation](https://doc.ezplatform.com/en/1.12/guide/siteaccess/#scope). Currently, for View matching `default` acts as the most important scope instead of fallback.

EZP-28506: Defining a frontend template overrides the backend content view

---

eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php

| ------------ | ---------- |
| **Status** | Ready for a review |
| **JIRA issue** | [EZP-28510](https://jira.ez.no/browse/EZP-28510) |
| **Target version** | 7.0 |
| **BC break** | no |
| **Bug fix** | yes |
This PR presents one possible approach to refresh list of Content Types for Content Type Group after publishing Content Type.
The reason for the failure is that when list for group is tagged, new Content Type is not published yet, so not included in tags.
We were able to reproduce this behavior only when Content Type has `ezobjectrelation` or `ezobjectrelationlist` field types, because these are the only field types that requires loading list of content types (see [`AbstractRelationFormMapper::getContentTypesHash`](https://github.com/ezsystems/repository-forms/bl …

EZP-28510: ContentType list for Group is not refreshed after publishing ContentType

---

eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php

I missed integration test failure when checking final solution for #2185
The cache key prefix that is supposed to be used is `'ez-content-type-list-by-group-'`.
Sorry! :sob: 
// cc @andrerom @lserwatka

EZP-28510: Fixed wrong cache key name used in #2185 fix

---

.travis.yml
bin/.travis/prepare_behat.sh
composer.json
doc/bc/changes-7.0.md
eZ/Bundle/EzPublishRestBundle/Features/Content/user_content.feature
eZ/Publish/API/Repository/Tests/Regression/EnvTest.php

| ------------ | ---------- |
| **Status** | Work in progress |
| **JIRA issue** | [EZP-28375](https://jira.ez.no/browse/EZP-28375) |
| **Target version** | `7.0` |
| **BC break** | yes, for automated tests |
| **Tests pass** | [yes](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/313433466) |
This PR along with its counterpart, ezsystems/ezplatform#232, enables running tests that require running eZ Platform installation using docker container (that includes behat and REST functional tests).
**TODO**

EZP-28375: As a Maintainer I want CI to run tests on behat environment of eZ Platform v2 - part 1

---

.travis.yml
bin/.travis/prepare_behat.sh

This is an attempt to make temporarily disabled tests that require Docker containers setup to pass.
**TODO**:

EZP-28375: Enabled tests running inside Docker container

---

eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

> Issue: https://jira.ez.no/browse/EZP-28290
ping @emodric

EZP-28290: Invalid cache key on url ezjscore_call_ezjscnode::subtree::2

---

eZ/Publish/Core/FieldType/Image/IO/Legacy.php
eZ/Publish/Core/FieldType/Tests/Image/IO/LegacyTest.php

> Fix https://jira.ez.no/browse/EZP-28281
> Sent to QA
> (Forward port from 5.4)
The Image type fails to take drafts properly into account.

EZP-28281: Image is not displayed when previewing unpublished content

---

eZ/Publish/Core/FieldType/Date/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/DateTest.php

> JIRA: https://jira.ez.no/browse/EZP-28513
Current date populated as the default value for Date field type should be the absolute value (not related to the default server timezone). Otherwise, it some cases the value will be yesterday's date instead of today's date.
Patch based on DateTime field type impl.: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php#L114 
> 2. Create new Content Type with the Date Field Type. Set "Current date" as the default value for this field.
> 3. In the Platform UI, navigate to "Content structure", click "Create" button and select the Content Type created in the previous step.
> 4. Notice that the Date field will be …

EZP-28513: Current date populated as the default value for Date field type should be the absolute value

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
eZ/Publish/Core/Limitation/ParentContentTypeLimitationType.php
eZ/Publish/Core/Limitation/SubtreeLimitationType.php

| ------------- | --- |
| JIRA Issue | [EZP-28615](https://jira.ez.no/browse/EZP-28615) |
| Bug fix?      | yes |
| New feature?  | no |
| BC breaks?    | no |
| Tests pass?   | ? |
| Doc needed?   | no |
`\eZ\Publish\SPI\Limitation\Type::evaluate` accepts `null` for `$targets` instead of empty array and internally methods rely on that value, so any method using that argument has to allow `null` also, otherwise it ends up in argument type PHP error.
Actual fix: 0c562aa.
**TODO**:

EZP-28615: Cannot check content/create permission with ContentCreateStruct without target location

---

composer.json
eZ/Publish/API/Repository/Tests/ContentServiceTest.php

**Target branch**: 6.12
**Bug fix**: yes
This PR fixes broken integration tests after merging up EZP-28615 from `6.7`. The method `createRoleWithPolicies` was added to `BaseTest` in the mentioned fix for EZP-28615, but since `6.8` already existed in `ContentServiceTest`. My bad :(

[Tests] Fixed usages of createRoleWithPolicies after EZP-28615 fix

---

doc/specifications/cache/persistence/Readme.md
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php

| Question           | Answer |
| -----------------  | ------ |
| **JIRA issue**     | [EZP-28352](https://jira.ez.no/browse/EZP-28352) |
| **Target version** | `7.x` |
| **Bug fix**        | yes |
| **New feature**    | no |
| **BC breaks**      | no |
| **Tests pass**     | yes |
| **Doc needed**     | no |
This PR replaces invalidating `location-data-<locationId>` with `location-<locationId>` Persistence Cache Tag after Location Swap. 
It turns out that besides Location data, Content is also affected when swapping Main Location.
**TODO**:

EZP-28352: After swapping the location of the content item, the main location of the content item is unassigned	

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl

JIRA issue: https://jira.ez.no/browse/EZP-28623
URL to the unaccessible linked content shouldn't be rendered as an anchor with empty `href` attribute. The whole anchor should be omitted, and only the wrapping paragraph should be rendered during the XML to HTML5 conversion.
Currently:
`<p><a href="#" target="_self">Link</a></p>`
After change:
`<p>Link</p>`

EZP-28623: Display paragraph when user haven't permissions to see linked content

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/012-literallayout.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/ezxml/012-literallayout.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/012-literallayout.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/012-literallayout.xml

> JIRA: https://jira.ez.no/browse/EZP-28328
This PR contains patch for ignored `<br />` tags inside text formatted with bold, italic, underlined, strikedthrough, del and mix of them. 
Note to reviewers: This patch doesn't provide support for line breaks inside text formatted in `ezxml`.  
> 2. Go to the Platform UI. Create new article there.
> 3. In one of the article's Rich Text fields (for example "Intro"), enter few lines of text. Lines should be inside one paragraph and separated by line breaks (Shift + Enter).
> 4. Select the entire just created paragraph and make it bold by clicking the "B" icon.
> 5. Publish the article.
> 6. Edit the article again. Notice that the line breaks are gone.

EZP-28328: RichText Field Type shouldn't remove line breaks inside formatted paragraphs

---

eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/RegenerateUrlAliasesCommand.php

> JIRA: [EZP-28740](https://jira.ez.no/browse/EZP-28740)
Excerpt from JIRA:
> RegenerateUrlAliasesCommand sometimes tries to create aliases for child nodes before their parent alias is created. This results in "0" being written in the parent column. "0" is also an id representing the root Content, which causes malfunction.
The issue was caused by using `orderBy` because it overrides the previous setting. `addOrderBy` should be used instead (the second time).

Fix EZP-28740: RegenerateUrlAliasesCommand sometimes generates alias with wrong parent (0)

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Content.php

JIRA: https://jira.ez.no/browse/EZP-28728
If set a defaultValue of an arrayNode config symfony will fill this for every siteaccess/sitaccess group:
https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Config/Definition/ArrayNode.php#L245
I think it is enough to set it in the default_settings.yml
https://github.com/ezsystems/ezpublish-kernel/blob/6.7/eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml#L87

Fix EZP-28728: Default TTL in default scope would be set to 60 from siteaccess scope

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

> Fix https://jira.ez.no/browse/EZP-28726
> Sent to QA
Edit preview of single selection fails when it's empty, with HTTP 500: `Key "0" does not exist as the array is empty.`
Fix by checking array length. If it's empty there's no need to do anything, same as in the multiselect case above.

EZP-28726: Selection edit preview fails when empty

---

composer.json

While ircmaxell/password-compat was created to provide userland implementation of password_* functions to PHP 5.3 and 5.4, do we still need this library ?

Removed password-compat lib from dependencies

---

eZ/Publish/Core/SignalSlot/Tests/TrashServiceTest.php
eZ/Publish/Core/SignalSlot/TrashService.php

> JIRA: https://jira.ez.no/browse/EZP-28775
When the trash item is restored under old parent location, `\eZ\Publish\Core\SignalSlot\Signal\TrashService\RecoverSignal` is emitted with empty (null) value of `newParentLocationId` which prevents a HTTP cache to be purged for old parent location. 
> 1. Create a new eZ Platform installation and launch it in prod environment.
> 2. Create new folder named Foobar
> 3. Create new article Foo under folder Foobar
> 4. Create new article Bar under folder Foobar
> 5. Move article Foo to trash
> 6. Restore Foo from trash
> 7. Go to Foobar folder location and notice that Sub-items pagination is broken (see attached screenshot)

EZP-28775: TrashService\RecoverSignal::$newParentLocationId shouldn't be null when trash item was restored under old parent location

---

eZ/Bundle/EzPublishIOBundle/Command/MigrateFilesCommand.php

The script asks for confirmation : 
Are you sure you want to proceed?
IMO, the script should proceed, not abort if user provides `--no-interaction`

ezplatform:io:migrate-files command with --no-interaction should default to true

---

eZ/Publish/Core/Base/Tests/PHPUnit5CompatTrait.php

PHPUnit5CompatTrait is not required any more as now we are using PHPUnit v6.

Deprecate PHPUnit5CompatTrait

---

composer.json

| **JIRA issue**     | none
| **Bug fix**        | no
Currently dev dependency `mikey179/vfsStream` is not used inside this repository, it can be removed.

Remove mikey179/vfsStream from dev dependencies

---

eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Map/URI.php

> JIRA: https://jira.ez.no/browse/EZEE-1866
`\eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\Map\URI::analyseURI` should remove siteaccess part only if is present (as in the case of `\eZ\Publish\Core\MVC\Symfony\SiteAccess\Matcher\URIElement::analyseURI`)

EZEE-1866: Map\URI::analyseURI should remove siteaccess part only if is present

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Session/Handler/NativeSessionHandler.php

Storing session in Redis is needed on platform.sh
The [current code](https://github.com/ezsystems/ezplatform/pull/254) does [not work](https://jira.ez.no/browse/EZP-28800).
This is the kernel part of the fix for [EZP-28800](https://jira.ez.no/browse/EZP-28800)
The corresponding PR for ezplatform is [here](https://github.com/ezsystems/ezplatform/pull/262)
My idea for solving this is to create a simple redis session handler ( which just enables the PHP build in redis session handler) and then user this handler on platform.sh
Reviewers should have a look at the [jira ticket](https://jira.ez.no/browse/EZP-28800) as there are several ideas on how to solve the problem.

EZP-28800: Added Redis session service

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/slot.yml
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/CreateUserGroupSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/CreateUserSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Http/SignalSlot/UpdateUserGroupSlot.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/CreateUserGroupSlotTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/CreateUserSlotTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/SignalSlot/UpdateUserGroupSlotTest.php

| **JIRA issue**     | [EZP-28846](https://jira.ez.no/browse/EZP-28846)
| **Bug fix**        | yes
Follow up for https://github.com/ezsystems/ezplatform-http-cache/pull/50, regarding to built-in HTTP Cache purging. 
**TODO**:

EZP-28846: HTTP Cache purge when UserService\{CreateUser,CreateUserGroup,UpdateUserGroup}Signal is emited

---

.github/pull_request_template.md

Unsure how to specify it in short amount on space, but the template should:
1. specify features goes to master
2. mention improvements can optionally be backported, when they are smaller things to improve overall use, typically to unlock usage of existing features. For instance something not correctly implemented but documented/specified, half way done, or otherwise where real world usage expose needs for improvements to a feature.
Main goal here is avoid confusion, as we happen to also have notation of improvements in JIRA which falls between bug and feature.

[Github] Clarify template a bit more in regards to improvements

---

eZ/Publish/Core/Persistence/Cache/AbstractHandler.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php

| **JIRA issue**     | no
| **Bug fix**        | no
Small change in order to improve code for multi loading SPI Cache methods:
- Unsets cache items not found by database.
_Found by Ramzi when search where wrongly configured to pull data from another repository
where cache items would be returned for items not found in database. Also needed if this is ever exposed by API methods._
- Refactor to let the abstract method handle more of the logic in order to avoid even more code duplication for these methods, especially if we add more of them in the future, for future lazy properties. …

[SPI Cache] Small refactoring to make multi load abstract more solid

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/FieldType/RichText/ezrichtext.yml
eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/_fixtures/ezrichtext/custom_tags/invalid/equation.xml
eZ/Publish/API/Repository/Tests/FieldType/_fixtures/ezrichtext/custom_tags/invalid/unknown_tag.xml
eZ/Publish/API/Repository/Tests/FieldType/_fixtures/ezrichtext/custom_tags/invalid/video.xml
eZ/Publish/API/Repository/Tests/FieldType/_fixtures/ezrichtext/custom_tags/valid/equation.xml
eZ/Publish/API/Repository/Tests/FieldType/_fixtures/ezrichtext/custom_tags/valid/video.xml
eZ/Publish/Core/FieldType/RichText/CustomTagsValidator.php
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/Tests/RichText/CustomTagsValidatorTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/RichText/Renderer.php
eZ/Publish/Core/settings/fieldtype_services.yml
eZ/Publish/Core/settings/fieldtypes.yml

| Question  | Answer
| ------------- | ---
| **Status** | Ready for testing
| **JIRA issue** | [EZP-28110](https://jira.ez.no/browse/EZP-28110)
| **Related PR** | ezsystems/ezplatform-admin-ui#320
| **Bug fix** | no
| **New feature**  | yes
| **Target version** | 7.1
| **BC breaks**    | no |
| **Tests pass**   | yes, CI failure unrelated
This PR introduces Semantic Configuration definition of RichText Custom Tags as specified in the JIRA issue.
Semantic Configuration is divided into two parts:
1. Global configuration under `ezpublish.ezrichtext.custom_tags` key containing all settings.
2. SiteAccess configuration under `ezpublish.system.<scope>.fieldtypes.ezrichtext.custom_tags` which is scalar array containing list of custom tags available for the given scope/SiteAccess. The list must …

EZP-28110: As a developer, I want to define attributes for custom tags

---

doc/specifications/api/README.md
doc/specifications/api/lazy_properties.md
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Values/ContentType/ContentTypeGroupProxy.php
eZ/Publish/Core/Repository/Values/GeneratorProxyTrait.php

> Issue: https://jira.ez.no/browse/EZP-27924
> Replaces: #2094
Introduces concept of lazy loaded properties in order to be able to:
- gradually expose more information on API, especially useful in templates
- without causing additional load if not used
- with capability of bulk loading to be able to avoid O^n loading lazy properties often imply.
In this PR the concept is applied to existing `ContentType->contentTypeGroups` property as:
1. An example for how to implement lazy properties _(in this case array property, but singular once also possible and there will be followup PR for that)_
2. Performance improvment since most cases never need them when loading content types
---
This is done using proxy object of (in this case) Content Type Group with takes a
Generator and object id as …

EZP-27924: As a Developer I want lazy loading certain API properties

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
eZ/Bundle/EzPublishCoreBundle/Resources/translations/content_fields.en.xlf
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

> JIRA: https://jira.ez.no/browse/EZP-28647
When we set latitude and longitude to '0' we should see proper information, not "Not set" message.
Additionally when we did not provide values for latitude and longitude, we still should see a map on the frontend page, with zoom level 1 and coordinates equal 0,0. This PR also changed google maps to openStreetMaps.

EZP-28647: Difference in edit and preview mode for map location

---

eZ/Publish/Core/QueryType/OptionsResolverBasedQueryType.php

> JIRA: https://jira.ez.no/browse/EZP-28679
The `OptionsResolver Based QueryType` is designed to be the base class for  QueryTypes with parameters.  As a developer, when I extend this class I expect that `OptionsResolverBasedQueryType` already implements `QueryType` interface.

EZP-28679: As a developer, I expect that OptionsResolverBasedQueryType implements QueryType interface

---

eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php
eZ/Publish/Core/MVC/Symfony/View/Builder/Registry/ControllerMatch.php

| **JIRA issue**     | [EZP-28860](https://jira.ez.no/browse/EZP-28860)
| **Target version** | `6.x`/`7.x`
In Symfony, controller can be a closure, in addition to referencing the controller with 'service:method' or 'Bundle:Controller:Action'.
Using closure as a controller results in a warning that strpos cannot be used because the argument is not a string.
The error comes from the view builder system that assumes that the controller is always a string.
**TODO**:

EZP-28860: Limit building views with view builders to string controllers

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-28883](https://jira.ez.no/browse/EZP-28883)
| **Target version** |  `6.13`
This little bug makes possible for admin users to delete random records from the `ezurlalias_ml` database table in multilanguage setups which breaks all url's for a language.
To reproduce:
1. Install clean ezplatform, eg a v2
2. on the admin create a new valid language
3. create a folder under the home, translate it to both language and publish; note the location id of this folder (should be 54 or around that for clean installs)
4. check db query: `SELECT * FROM ezurlalias_ml WHERE …

EZP-28883: Removing Translation from Draft corrupts all Url Aliases for the removed Translation

---

appveyor.yml

For some time now AppVeyor fails due to restrictions on windows.php.net resources.
I found another way of installing `PHP` and `Composer` packages - via [Chocolatey package manager](https://chocolatey.org/) which is already available in AppVeyor build images (`cinst` command).
**TODO**:

[CI][AppVeyor] Improved PHP and Composer installation process

---

eZ/Publish/Core/FieldType/Page/Value.php

| **JIRA issue**     | [EZP-28886](https://jira.ez.no/browse/EZP-28886)
| **Target version** | `6.7`/`6.13`/`7.0`
Excerpt from JIRA:
> Currently, the method eZ\Publish\Core\FieldType\Page\Value::__toString() does not always return String. It returns null if the page layout equals null. This can cause further issues because PHP throws an error if magic method __toString() returns something different then String. 
Most of the other Value classes are casting the value returned from __toString() to String, so this is what most probably should also be done in this case.
**TODO**:

EZP-28886: Method eZ\Publish\Core\FieldType\Page\Value::__toString() does not always return String

---

eZ/Publish/Core/Persistence/Cache/ContentHandler.php

| **JIRA issue**     | [EZP-28853](https://jira.ez.no/browse/EZP-28853)
This is a followup to https://github.com/ezsystems/ezpublish-kernel/pull/2254 adding a relevant cache clear to a method added between versions 6.7 and 6.13.
**TODO**:

EZP-28853: Add VersionInfo to persistence cache (followup for 6.13)

---

eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php
eZ/Publish/Core/Persistence/Cache/URLHandler.php

| **JIRA issue**     | [EZP-28585](https://jira.ez.no/browse/EZP-EZP-28585)
| **Target version** | `>= 7.0`
This PR includes clearing SPI cache for related content when URL address is update.
**TODO**:

EZP-28585: SPI cache purge for related content when URL is updated

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_denied.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_inline.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_inline_denied.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_denied.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_inline.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_inline_denied.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

| **JIRA issue**     | [EZP-28848](https://jira.ez.no/browse/EZP-28848)
| **Target version** | 6.13
Testing note:
- With ezplatform-http-cache: This will only effectively work with v0.4.2 and higher, on lower versions it will not be part of xkey headers.
- Without ezplatform-http-cache: This will have no effect, and realtions cache claring is already cleared as part of the deprecated "Smart HTTP cache clearing" system, so no change there.
Review note:
- This implies a dependency on foshttpcache package until these field types are moved out to own bundles. However it will at least be …

EZP-28848: Add relation cache tags to default relation fields

---

eZ/Publish/Core/REST/Common/FieldTypeProcessor/BinaryInputProcessor.php

| **JIRA issue**     | [EZP-28070](https://jira.ez.no/browse/EZP-28070)
Added cleaning up for `eZ_REST_BinaryFile` temporary files created by `BinaryInputProcessor::preProcessValueHash()`
**TODO**:

EZP-28070: Cleaning up temporary files created by BinaryInputProcessor::preProcessValueHash

---

doc/bc/changes-7.1.md

| **JIRA issue**     | [EZP-28926](https://jira.ez.no/browse/EZP-28926)
This PR adds missing BC break notice in docs.

Added PermissionResolver::hasAccess BC break notice

---

eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/API/Repository/UserService.php
eZ/Publish/API/Repository/Values/User/UserTokenUpdateStruct.php
eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php
eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/User/Handler.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/SignalSlot/Signal/UserService/UpdateUserTokenSignal.php
eZ/Publish/Core/SignalSlot/UserService.php
eZ/Publish/SPI/Persistence/User/Handler.php
eZ/Publish/SPI/Persistence/User/UserTokenUpdateStruct.php

| **JIRA issue**     | [EZP-28917](https://jira.ez.no/browse/EZP-28917)
| **Doc needed**     |yes\*
\* We need to document that changing password requires at least `user / password` policy.
This PR adds the new loadUserByToken, updateUserToken and expireUserToken methods which is needed to be able to reset user password.
**TODO**:

EZP-28917: As a Developer I want API to manipulate User Tokens

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/API/Repository/Tests/PHPUnitConstraint/ValidationErrorOccurs.php
eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Helper/RelationProcessor.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
eZ/Publish/Core/settings/repository.yml

| **JIRA issue**     | [EZP-28836](https://jira.ez.no/browse/EZP-28836)
This PR introduces skipping validation of non-modified fields when content is updated. Otherwise, an editor is unable to publish content if two or more translations contain validation error. 
**TODO**:

EZP-28836:  Skipping validation of non-modified fields when content is updated

---

eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
eZ/Publish/Core/Repository/LocationService.php

| **JIRA issue**     | [EZP-28934](https://jira.ez.no/browse/EZP-28934)
| **Bug**| yes
This PR adds additional permission checking on the location creating. As in legacy, `content/manage_locations` policy should be check. 
**TODO**:

EZP-28934: LocationService doesn't check content/manage_locations policy during location create

---

eZ/Publish/Core/REST/Server/Controller/Content.php

| **JIRA issue**     | [EZP-27271](https://jira.ez.no/browse/EZP-27271)
This PR contains small refactoring in `eZ\Publish\Core\REST\Server\Controller\Content` which allows PlatformUI to reuse once parsed Request as `RestContentCreateStruct`.
Related PlatformUI PR: https://github.com/ezsystems/PlatformUIBundle/pull/953
**TODO**:

EZP-27271: Unable to upload large binary file using REST / Platform UI

---

eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php

| **JIRA issue**     | [EZP-28279](https://jira.ez.no/browse/EZP-28279)
| **Target version** | `6.x`/`7.x` for bug fixes or improvements _(on existing features)_, `master` for features
For image fieldtype the max size input value was expecting size in bytes, then it was converted for mb for database and for frontend iw was converted back again to bytes. This unifies it across all file filedtypes.
Not sure where I should target this one. 
PR with corrected label: https://github.com/ezsystems/repository-forms/pull/226
Frontend display and validation: …

EZP-28279: User cannot set max file size in Image field type

---

eZ/Publish/Core/Repository/LocationService.php

| **JIRA issue**     | [EZP-28934](https://jira.ez.no/browse/EZP-28934)
| **Bug**| yes
The previous PR (https://github.com/ezsystems/ezpublish-kernel/pull/2276) introduced `content/manage_locations` policy check, but it was based on the wrong context. This PR fixes it. The problem was discovered by QA during tests. 
**TODO**:

EZP-28934: Incorrect variable in policy check context

---

eZ/Publish/Core/FieldType/RichText/Converter/Render/Template.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/TemplateTest.php

| **JIRA issue**     | [EZP-28972](https://jira.ez.no/browse/EZP-28972)
| **Required by**     | ezsystems/ezplatform-demo#75
| **Target version** | `7.1`
The HTML5 output converter responsible for rendering RichText Custom Tag frontend template tried to get align attribute from `xlink` namespace. The correct one is `ezxhtml`.
**TODO**:

EZP-28972: RichText Custom Tag align attribute is not present in Tag template

---

eZ/Publish/Core/SignalSlot/Signal/URLService/UpdateUrlSignal.php
eZ/Publish/Core/SignalSlot/Tests/URLServiceTest.php
eZ/Publish/Core/SignalSlot/URLService.php

| **JIRA issue**     | [EZP-28585](https://jira.ez.no/browse/EZP-28585)
| **Target version** | `>= 6.13`
Added flag to URLService\UpdateUrlSignal indicating that URL address was changed in . Main reason behind this change is proper HTTP Cache purge for content which contain updated URL: to avoid HTTP Cache purge if only URL status was updated. 
**TODO**:

 EZP-28585: Added flag to URLService\UpdateUrlSignal indicating that URL address was changed

---

eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
eZ/Publish/Core/FieldType/RichText/CustomTagsValidator.php
eZ/Publish/Core/FieldType/Tests/RichText/CustomTagsValidatorTest.php

| **JIRA issue**     | [EZP-28959](https://jira.ez.no/browse/EZP-28959)
| **Target version** | `7.1`
| **BC breaks**      | no, fixed
Since RichText Custom Tags use pre-existing DocBook markup (`eztemplate` tag), due to BC policy missing configuration cannot result in validation error on publishing. 
**This PR introduces a deprecation error instead.**
**NOTE**: Initial resolution suggested making a setting that would either disable or enable that validation. Unfortunately my tests show that `@trigger_error` doesn't get logged when building Symfony container. 
Symfony provided deprecation messages appear in logs, …

EZP-28959: Prevent publishing errors on pre-existing, undefined Custom Tags

---

eZ/Publish/Core/FieldType/Url/Type.php

| **JIRA issue**     | [EZP-28554](https://jira.ez.no/browse/EZP-28554)
Adding additional condition to if statement prevents exception to happen when link value is not provided but text is. This however only prevents 500 error to show as the fieldvalues are not saved (identical to 1.X version).
**TODO**:

EZP-28554: Error 400 after filling Text field in URL field type

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Publish/API/Repository/Values/Content/ContentInfo.php
eZ/Publish/Core/MVC/Symfony/FieldType/Relation/ParameterProvider.php
eZ/Publish/Core/MVC/Symfony/FieldType/RelationList/ParameterProvider.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/Relation/ParameterProviderTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_content_from_rows_result.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php
eZ/Publish/SPI/Persistence/Content/ContentInfo.php

| **JIRA issue**     | [EZP-28439](https://jira.ez.no/browse/EZP-28439), (also solves [EZP-28781](https://jira.ez.no/browse/EZP-28781) and [EZP-28865](https://jira.ez.no/browse/EZP-28865))
| **Doc needed**     | yes (new `in_trash` variable in `objectrelation` and `objectrelationlist` filed type templates)
**TODO**:

EZP-28439: Related content is still displayed after it is moved to trash

---

data/mysql/dfs_schema.sql
data/mysql/schema.sql
data/update/mysql/dbupdate-6.12.0-to-7.1.0.sql
data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
doc/upgrade/7.2.md
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql

| **JIRA issue**     | [EZP-28950](https://jira.ez.no/browse/EZP-28950)
| **Bug fix**        | no
| **New feature**    | kind of
| **Target version** | 7.2
| **BC breaks**      | kind of (shorter indexes)
| **Doc needed**     | yes (for changing existing databases)
We should use the `utf8mb4` mysql charset which supports all of unicode, instead of `utf8` which does not support 4-byte characters (which includes some Chinese, emojis, and other things).
~Note that for collation I selected `utf8mb4_unicode_520_ci` instead of `utf8mb4_unicode_ci`, because the latter treats all 4-byte characters as the same. Ref https://core.trac.wordpress.org/ticket/32105#comment:3~ We will leave collation for …

Set utf8mb4 charset and collation on mysql kernel schema and fixtures

---

data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
doc/upgrade/7.2.md

| **JIRA issue**     | [EZP-28950](https://jira.ez.no/browse/EZP-28950)
| **Target version** | master / 7.2
| **BC breaks**      | kind of
https://github.com/ezsystems/ezpublish-kernel/commit/0f82a088ebe7949970f9cf1acb687b21b42a0779 did not contain statements or info on how to change table charset on existing tables, when upgrading to 7.2.
Here I explain how to do it, rather than provide the complete set of SQL commands, because I want administrators to think carefully about which tables to convert, and which collation to use, rather than just copy a bunch of SQL commands. Also, because the number of tables varies …

EZP-28950: Show how to change table character set

---

composer.json

| **Target version** | `6.7` and higher
This PR adds Composer `conflict` on `doctrine/dbal:2.7.0` due to discovered PDO fetch_style regression.
**TODO**:

[Composer] Added conflict with doctrine/dbal:2.7.0 due to fetch_style bug

---

eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Signal/ContentService/CreateContentDraftSignal.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php

CreateContentDraft signal didn't include Version number of new Draft.
| **JIRA issue**     | [EZP-28882](https://jira.ez.no/browse/EZP-28882)
| **Target version** | `7.1`
This PR is bugfix and feature in one.
It adds `newVersionNo` property to `CreateContentDraftSignal`. For someone relying on that signal this is very useful information.
**TODO**:

Fixed EZP-28882: Added newly created Version no. to CreateContentDraft Signal

---

eZ/Publish/Core/MVC/Symfony/Locale/LocaleConverter.php

| **JIRA issue**     | [EZP-29018](https://jira.ez.no/browse/EZP-29018)
Just a change in the log messages we get in this kind of situatios, becuase ezpublish.yml is not there anymore. 
@andrerom i set target version to master, let me know if this is ok or if this should be target to 6.x/7.x instead.

Improve message related to conversion to and from Posix

---

composer.json
eZ/Bundle/EzPublishRestBundle/Features/Context/RestClient/BuzzDriver.php
eZ/Bundle/EzPublishRestBundle/Features/Context/RestClient/DriverHelper.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTypeTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/LocationTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ObjectStateTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RootTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SectionTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TrashTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/UrlAliasTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/UrlWildcardTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/UserTest.php

| **JIRA issue**     | [EZP-29048](https://jira.ez.no/browse/EZP-29048)
| **Target version** | `7.0`, `7.1`, `master`
This PR fixes failing REST Behat BuzzDriver and Functional tests on `ezpublish-kernel:^7.0`.
The failure is caused by the most recent `v0.17.0` release of `kriswallsmith/buzz`. The easy way out would be to force `v0.16.1`, but new changes to the Buzz library impose best practices and use of PSR7-related namespace and conventions. It also was a good chance to fix other bugs in our REST tests.
Technical background for the changes:
- PSR7 defines specific interfaces, so …

Fixed EZP-29048: Aligned Behat BuzzDriver and Functional REST tests with PSR-7

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/018-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/ezxml/018-htmlTable.lossy.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/018-htmlTable.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/018-htmlTable.xml

| **JIRA issue**     | [EZP-28967](https://jira.ez.no/browse/EZP-28967)
Description from JIRA:
>In RichText Editor, you can create line breaks (inside a paragraph) by pressing Shift + Enter. 
If you create a table using the rich text field type and type some text in a table cell then add a line break and then add some more text after saving the line break is removed.
If you add a new paragraph in the table cell by pressing Enter then delete the second line with Backspace and then you do the text + line break + text as I've written in the previous line the …

Fix EZP-28967: RichText FieldType removes line breaks inside table cells

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml

| **JIRA issue**     | [EZEE-1864](https://jira.ez.no/browse/EZEE-1864)
When building Symfony DI Container, CachePool is created from factory
prior to setting SiteAccess-aware context. 
However the factory depends on SA-aware `ConfigResolver` which contains a setting for Persistence Cache Service (Filesystem, Redis, Memcached).
The issue occurs only in CLI mode, in HTTP Request context proper setting is already present when building Persistence handler.
Making `ezpublish.cache_pool` lazy solves problem of getting SA-specific `cache_pool_name` too early. …

Fixed EZEE-1864: Set ezpublish.cache_pool Service to be lazy

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/YamlConfigurationContext.php

| **JIRA issue**     | [EZP-28224](https://jira.ez.no/browse/EZP-28224)
| **Target version** | 7.1
| **Tests pass**     | Yes
**Problem description:**
Currently repository-forms tests are not passing on Travis. There are some issues that will be fixed in a separate PR there (https://github.com/ezsystems/repository-forms/pull/235), but it also fails because the cache-clearing does not work.
Example:
```
And the following user registration group configuration:                    # EzSystems\RepositoryForms\Features\Context\UserRegistrationContext::addUserRegistrationConfiguration()
"""
ezpublish:
system:
default: …
```

EZP-28224: Change the way cache is cleared in Behat tests

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/core.xsl

| **JIRA issue**     | [EZP-29116](https://jira.ez.no/browse/EZP-29116)
This PR ensures that all `xml:id` are unique within the same field attribute
**TODO**:

Fix EZP-29116 : Conversions from ezxmltext to ezrichtext fails if ezxmtext have duplicate xhtml ids

---

eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ContentTypeGroup.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ImageVariation.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Location.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ObjectStateGroup.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Policy.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Role.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Section.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Trash.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/URLAlias.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/URLWildcard.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/UserSession.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Version.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/VersionInfo.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/VersionTranslationInfo.php

| **JIRA issue**     | [EZP-29106](https://jira.ez.no/browse/EZP-29106)
Partial refactored eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/** to be able to add custom attributes in descendants classes
**TODO**:

EZP-29106: Refactored eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/** to be able to add custom attributes

---

eZ/Publish/API/Repository/Tests/RoleServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractCacheHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php

| **JIRA issue**     | [EZP-29113](https://jira.ez.no/browse/EZP-29113)
| **Target version** | `7.x` 
**TODO**:

EZP-29113: UserHandler::assignRole should invalidate `location-path-` tags

---

eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/core.xsl

| **JIRA issue**     | [EZP-29135](https://jira.ez.no/browse/EZP-29135)
With this PR, the xlt will only deal with `<embed>` and `<embed-inline>` tags which has a `node_id` or `object_id` attribute.
And a fix in [ezplatform-xmltext-fieldtype](https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/41) will instead output warning if neither `node_id` or `object_id` is set.
**TODO**:

Fixed EZP-29135 : Converting ezxmltext to richtext when embed tag contains neither node_id or object_id fails

---

composer.json

There's no breaking changes in v2.0 apart from bumping PHP requirements to PHP 7.
https://github.com/whiteoctober/Pagerfanta/compare/v1.1.0...v2.0.0
**TODO**:

Allow installing Pagerfanta 2.0

---

eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php

| **JIRA issue**     | [EZP-29211](https://jira.ez.no/browse/EZP-29211)
| **Target version** | `7.x` 
Missing cache items in the methods using AbstractHandler::getMultipleCacheItems should be logged as `FQCN::method` instead of `FQCN\{closure}` e.g. `\eZ\Publish\Core\Persistence\Cache\ContentHandler::loadContentInfoList` instread of `\eZ\Publish\Core\Persistence\Cache\ContentHandler\{closure}`
Otherwise 
https://github.com/ezsystems/ezpublish-kernel/blob/e2d26faa54715675fc8f1eef3defbe192973bf5b/eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php#L77
will cause `Notice: …

EZP-29211: Fixed logs for missing cache items in the methods using AbstractHandler::getMultipleCacheItems

---

composer.json

This PR solves this PR: https://github.com/symfony/thanks/pull/57 on the eZ side.
After a quick discussion with @nicolas-grekas and the fact eZ is not using any git subtree or anything.
`ezpublish-kernel` is always required and a forward "thanks" is a better option. I am closing the PR on symfony/thanks in favor of that one.

Add a star to ezsystems/ezplatform when ezpublish-kernel is installed.

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/PlaceholderProviderPass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGenerator.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGeneratorConfigurator.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider/GenericProvider.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider/RemoteProvider.php
eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProviderRegistry.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/PlaceholderProviderPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorConfiguratorTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderProvider/GenericProviderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderProviderRegistryTest.php

| **JIRA issue**     | [EZP-29137](https://jira.ez.no/browse/EZP-29137)
> Currently, when doing development on an eZ Platform site, you have to sync all of the images down to your local machine. This is not feasible for medium to large sites with > 1GB (arguably, over more than 300MB) of images. 
In general the idea is to generate a image placeholders on the fly for missing images. 
From technical POV:  `PlaceholderAliasGenerator` decorates `AliasGenerator` as this is the only one place where we might get width and height of original image which are …

EZP-29137: As a developer, I want to replace missing images with placeholders

---

doc/upgrade/7.2.md

| **JIRA issue**     | [EZP-28950](https://jira.ez.no/browse/EZP-28950)
| **Bug/Improvement**| bug
| **Target version** | 7.2
| **Tests pass**     | doc only
[The original PR #2277](https://github.com/ezsystems/ezpublish-kernel/pull/2277) had this change in i18n.ini, for reasons unknown/forgotten. It should work fine according to docs, and no problem was found in testing. But @emodric [reported failures](https://github.com/ezsystems/ezpublish-kernel/pull/2277#discussion_r189580624) due to the mysql `utf8mb4` charset being expected in ini-files and templates. As he pointed out, site.ini is the right/best place for the DB charset, since you …

EZP-28950 Correct legacy instructions, site.ini is the best place for DB charset

---

data/mysql/schema.sql
data/update/mysql/dbupdate-6.7.7-to-6.7.8.sql
data/update/postgres/dbupdate-6.7.7-to-6.7.8.sql
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql

| **JIRA issue**     | [EZP-29206](https://jira.ez.no/browse/EZP-29206)
| **Target version** | `6.7` and up.
This PR presents one of the possible solutions for database deadlocks that occur when concurrently moving subtree. The solution was suggested by the Customer and improved by us.
The solution splits update-where-id-in-select query into two separate queries to avoid locks. While possible deadlocks are documented for InnoDB and solution is to set proper indices, there's no solution for the case when update and select operate on different tables.
Therefore obvious choice would be to …

EZP-29206: MySQL deadlock errors happen when concurrently moving subtree

---

eZ/Publish/Core/Limitation/ObjectStateLimitationType.php
eZ/Publish/Core/Limitation/Tests/ObjectStateLimitationTypeTest.php

| **JIRA issue**     | [EZEE-1976](https://jira.ez.no/browse/EZEE-1976)
| **Target version** | `7.1` 
| **Tests pass**     | 
As there are no existing object states assigned to contentInfo at location 0, we can skip whole evaluation process.
**TODO**:

EZEE-1976: Cannot display Home when Content / Read has everything selected in State

---

eZ/Publish/Core/Persistence/Cache/BookmarkHandler.php

| **JIRA issue**     | [EZP-29211](https://jira.ez.no/browse/EZP-29211)
Same as https://github.com/ezsystems/ezpublish-kernel/pull/2334 but for `\eZ\Publish\Core\Persistence\Cache\BookmarkHandler::loadByUserIdAndLocationId` 😉 
**TODO**:

EZP-29211: Fixed logs for missing cache items in BookmarkHandler::loadByUserIdAndLocationId

---

eZ/Publish/Core/Persistence/Cache/UserHandler.php

| **JIRA issue**     | [EZP-29296](https://jira.ez.no/browse/EZP-29296)
| **Bug**| yes
| **Target version** | `7.1` & `master`
As described in JIRA issue, `UserService::loadByEmail` returns an empty array when following steps described in the ticket scenario. 
**TODO**:

EZP-29296: UserService loadByEmail returns empty array from cache

---

eZ/Bundle/EzPublishCoreBundle/Imagine/AliasGenerator.php
eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
eZ/Bundle/EzPublishCoreBundle/Imagine/Variation/ImagineAwareAliasGenerator.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/AliasGeneratorTest.php

| **JIRA issue**     | [EZP-25487](https://jira.ez.no/browse/EZP-25487)
| **Target version** | `6.7`, `6.13`, `7.1`, `master`
| **Doc needed**     | yes\*
This is #2121 by @kmadejski including minor improvements.
This approach uses Persistence Cache to store Image variation. The only difference when compared to #2121 is type-hinting `Psr\Cache\` interface instead of the one from `Stash` to make merging up to 7.x easier. Moreover I've changed slashes in cache key to dashes as this is what we use in 7.x stack.
Using persistence cache here might be seen as a workaround, but I rather see it as a clean solution. …

EZP-25487: Stored Image Variation in Image Variation Cache

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SlugConverterConfigurationPass.php

| **JIRA issue**     | [EZP-29167](https://jira.ez.no/browse/EZP-29167)
| **Related PR** | ezsystems/ezplatform#297 |
| **Target version** | `master` (`7.2`)
This PR adds a warning to the Container log (`var/cache/*.log`) about relying on default URL alias Slug Converter transformation configuration instead of setting it explicitly via:
```yaml
ezpublish:
url_alias:
transformation: '<urlalias, urlalias_iri, urlalias_compat, urlalias_lowercase>'
```
Note that usual log destination `var/log/<SYMFONY_ENV>.log` is not available yet when building container, therefore Contailer Builder log …

EZP-29167: Logged a warning about using default URL alias transformation

---

eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/TemplateTest.php

| **Target version** | `7.1`, `master` (`7.2`)
We've missed incorrect case used in XML testing Custom Tags. It wasn't discovered until the latest release of [sebastian/comparator](https://packagist.org/packages/sebastian/comparator) ([`v3.0.1`](https://github.com/sebastianbergmann/comparator/releases/tag/3.0.1)) which introduces the sebastianbergmann/comparator#53 fix.
**TODO**:

[Tests] Fixed incorrect case in expected XML for Custom Tag

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php

To verify this works on Travis to, this adapts REST functional tests so it will support port in host name which is useful for local development.

[TESTS] Support usage of port in host name for local testing

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml

| **JIRA issue**     | [EZP-25487](https://jira.ez.no/browse/EZP-25487)
| **Target version** | `master` (`7.2`)
As a result of #2311 feature, the `ezpublish.twig.extension.image` Twig Extension service got injected with `@ezpublish.image_alias.imagine.alias_generator`, which is core implementation that right now doesn't include caching.
I believe we still should use `@ezpublish.fieldType.ezimage.variation_service` to ensure proper layers are preserved.
This fixes problem with [EZP-25487](https://jira.ez.no/browse/EZP-25487) not working on `master`.
What needs to be checked is if it …

EZP-25487: Fixed incorrect variation service passed to Twig Image Ext.

---

doc/specifications/rich_text/ezdocbook.md
eZ/Publish/Core/FieldType/RichText/Converter/Ezxml/ToRichTextPreNormalize.php
eZ/Publish/Core/FieldType/RichText/Resources/schemas/ezxml/ezxml.xsd
eZ/Publish/Core/FieldType/RichText/Resources/schemas/ezxml/xhtml.xsd
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/ezxml.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/ezxml/docbook/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/DocbookToEzxmlTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/EzxmlToDocbookTest.php

| **JIRA issue**     | Do I need one?
This deprecates conversion from/to ezxmltext
Related to [ezxmltext PR](https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/46)
**TODO**:

Deprecate ezxml

---

eZ/Publish/Core/settings/repository.yml

| **JIRA issue**     | [EZP-28774](https://jira.ez.no/browse/EZP-28774)
Since the Symfony 3.4, services which do not specify explicit their visibility are private by default (Ref. https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default). Trying to access them directly from container (for instance using has or get method) will generate deprecation warning e.g. "User Deprecated: Checking for the initialization of the "ezpublish.api.repository" private service is deprecated since Symfony 3.4 and won't be supported anymore in Symfony 4.0." …

EZP-28774: Marked PAPI services as public

---

eZ/Publish/Core/Limitation/OwnerLimitationType.php

Can't test for self if content does not yet have an id.
| **JIRA issue**     | [EZP-29326](https://jira.ez.no/browse/EZP-29326)
| **Bug*| yes
| **Target version** | `6.x`/`7.x` `master` 
OwnerLimitationType can't check for self if id does not exist yet, also as user needs to have been created already we now this is not "self".
**TODO**:

EZP-29326: Fix OwnerLimitationType check ContentCreateStruct

---

eZ/Publish/Core/settings/policies.yml

Read and Remove both allow state limitations.  So should versionRead and VersionRemove.
| **JIRA issue**     | [EZP-29093](https://jira.ez.no/browse/EZP-29093)

EZP-29093: Add state limitations to versionRead and VersionRemove

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/TranslationCollectorPassTest.php

| **JIRA issue**     | [EZP-29322](https://jira.ez.no/browse/EZP-29322)
| **Improvement**| no
refers to https://github.com/ezsystems/ezplatform-admin-ui/pull/532
**TODO**:

EZP-29322: As an editor I want to use translated Admin panel

---

eZ/Bundle/EzPublishCoreBundle/Command/ResizeOriginalImagesCommand.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml

| **JIRA issue**     | [EZP-29238](https://jira.ez.no/browse/EZP-29238)
This PR provides the new command for resizing original images. It was initially created by Support as an example for the customer, but after that, the customer requested to add it to the product. 
The command helps to optimize storage usage by changing original images size and quality according to the selected variation.
**TODO**:

EZP-29238: As an Administrator I want to resize original images

---

eZ/Bundle/EzPublishCoreBundle/Routing/DefaultRouter.php
eZ/Bundle/EzPublishCoreBundle/Tests/Routing/DefaultRouterTest.php
eZ/Publish/Core/MVC/Symfony/Routing/Generator.php

| **JIRA issue**     | [EZEE-2145](https://jira.ez.no/browse/EZEE-2145)
This PR changes DefaultRouter and Generator to use proper method of `\Symfony\Component\Routing\RequestContext` to set HTTP port depending on used URI scheme.
Symfony's `RequestContext` distinguishes between HTTP and HTTPS ports by the means of two different methods, therefore we also should take that into the account.
This fixes the root cause of [EZEE-2145](https://jira.ez.no/browse/EZEE-2145).
**TODO**:

EZEE-2145: [Router] Fixed generating Req. Context to include URI scheme

---

eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SortClauseTest.php
eZ/Publish/Core/REST/Server/Input/Parser/Query.php
eZ/Publish/Core/REST/Server/Input/Parser/SortClause/Field.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/SortClause/FieldTest.php

| **JIRA issue**     | [EZP-28942](https://jira.ez.no/browse/EZP-28942)
| **Target version** | 6.7
This PR adds an option to use Field sort clause in REST API requests in `ViewInput`.
XML example:
```xml
<SortClauses>
<Field contentTypeIdentifier="content" fieldDefinitionIdentifier="field1">descending</Field>
<Field identifier="content/field2">ascending</Field>
</SortClauses>
```
JSON example:
```json
"SortClauses": {
"Field": [
{
"contentTypeIdentifier": "content",
"fieldDefinitionIdentifier": "field1",
"direction": "descending"
},
{
"identifier": "content/field2",
"direction": …
```

EZP-28942: As a REST consumer, I want to sort a view using a Field

---

composer.json

| **JIRA issue**     | [EZP-28950](https://jira.ez.no/browse/EZP-28950)
Due to utf8mb4 changes, only ezsystems/ezpublish-legacy version compatible is 2018.06, to be released soon. All other versions will fail with the error described in https://github.com/ezsystems/ezpublish-legacy/pull/1361
**TODO**:

Add ezsystems/ezpublish-legacy < 2018.06 to conflict section

---

data/mysql/schema.sql
data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
doc/upgrade/7.2.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/NotificationRendererPass.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/NotificationRendererPassTest.php
eZ/Publish/API/Repository/NotificationService.php
eZ/Publish/API/Repository/Tests/NotificationServiceTest.php
eZ/Publish/Core/Notification/Renderer/NotificationRenderer.php
eZ/Publish/Core/Notification/Renderer/Registry.php
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
eZ/Publish/Core/Repository/NotificationService.php
eZ/Publish/SPI/Persistence/Handler.php

| **JIRA issue**     | [EZEE-2081](https://jira.ez.no/browse/EZEE-2081)
Cleaned things missed in https://github.com/ezsystems/ezpublish-kernel/pull/2356. Most important points:
* Replaced tag `ezstudio.notification.renderer` with `ezpublish.notification.renderer`
* Moved `NotificationRenderer` to `eZ\Publish\Core\Notification\Renderer\`
* Added `\eZ\Publish\API\Repository\Values\Notification\CreateStruct` validation
**TODO**:

EZEE-2081: NotificationService clean up    

---

data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql

| **JIRA issue**     | Follow-up for [EZP-29206](https://jira.ez.no/browse/EZP-29206)
This is a `7.2` follow-up for #2339 adding new database table indices to solve [EZP-29206](https://jira.ez.no/browse/EZP-29206).
It is intended for Developers upgrading from the last stable `7.1` to the new stable `7.2.0`.
The portion of the script is wrapped in a transaction to perform unrelated updates even if adding indices fails, because they already exist (for Developers updating from `6.7.x` or `6.13.4` to `7.2.0`).
**TODO**:

[7.2] EZP-29206: Added missing upgrade scripts

---

data/update/mysql/dbupdate-6.13.3-to-6.13.4.sql
data/update/postgres/dbupdate-6.13.3-to-6.13.4.sql

| **JIRA issue**     | Follow-up for [EZP-29206](https://jira.ez.no/browse/EZP-29206)
This is a `6.13` follow-up for #2339 adding new database table indices to solve [EZP-29206](https://jira.ez.no/browse/EZP-29206).
It is intended for Developers upgrading from the last stable `6.13.3` to the new stable `6.13.4`.
The portion of the script is wrapped in a transaction to update `ezpublish-version` even if the indices already exist (for Developers updating from `6.7.x` to `6.13.4`).
**TODO**:

[6.13] EZP-29206: Added missing upgrade scripts

---

eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml

| **JIRA issue**     | [EZP-29387](https://jira.ez.no/browse/EZP-29387)
| **Bug** | yes
| **Target version** | `6.7`/`6.13` / `7.2`
As stated in the JIRA issue, variation cache should be SiteAccess aware. 
**TODO**:

EZP-29387: Variation cache should be SiteAccess and domain aware

---

eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
eZ/Publish/Core/SignalSlot/Repository.php

| **JIRA issue**     | [EZP-29376](https://jira.ez.no/browse/EZP-29376)
| **Target version** | 7.2
| **Tests pass**     | yes _(but we should find a way to add more functional testing around this)_
| **Doc needed**     | no _(well yes, but for the feature itself, not this bug fix)_
Another issue [found and fixed late in the review of SiteAccess Aware repo:
- https://github.com/ezsystems/ezpublish-kernel/pull/2064#discussion_r197780401
Broke usage in some cases out of the box with ContentView as it is using sudo() which was no longer
passing right repository by SignalSlot repo.
PR here is cleaning up the signature for sudo() on all Repo …

EZP-29376: New SiteAccess aware repo not handling languages with sudo()

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/TranslationCollectorPassTest.php

| **JIRA issue**     | [EZP-29377](https://jira.ez.no/browse/EZP-29377)
Source translation (en) should be always available. Otherwise, it won't be properly resolved if: 
1. English is the primary language in the browser 
2. Other i18n package is installed from the list of preferred languages in browser
**TODO**:

EZP-29377: Source translation (en) should be always available

---

eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
eZ/Publish/Core/FieldType/Tests/RichText/Validator/DocbookTest.php

| **JIRA issue**     | [EZP-29385](https://jira.ez.no/browse/EZP-29385)
| **Target version** | `6.7`/`6.13`/`7.x` for bug fixes or improvements _(on existing features)_, `master` for features
This one fixes [EZP-29385](https://jira.ez.no/browse/EZP-29385)
The fix is based on Petar's fix to a [similar issue](https://github.com/ezsystems/ezpublish-kernel/pull/740/commits/8324a9f9c00267b96aa1f11c60fe774324f38dac) with `<section>`.
Honesty, I don't quite understand Petar's fix, but based on his comment it seems to be a workaround for a libxml bug.
**TODO**:

EZP-29385: Richtext : blockquote does not allow multiple titles on the same level

---

data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql

| **JIRA issue**     | [EZEE-2176](https://jira.ez.no/browse/EZEE-2176)
| **Target version** | `7.x` 
In the EE installations database schema update script is failing because the `eznotification` table already exists. To proper update also the following queries should be executed (needs to be mentioned in documentation // cc @DominikaK @MagdalenaZuba)
```sql
ALTER TABLE `eznotification` 
CHANGE COLUMN `data` `data` BLOB NULL ;
ALTER TABLE `eznotification` 
DROP INDEX `owner_id` ,
ADD INDEX `eznotification_owner` (`owner_id` ASC);
ALTER TABLE `eznotification` 
DROP INDEX `is_pending` , …
```

EZEE-2176: Fixed fail of the db schema update script when the eznotification table already exists

---

phpunit-integration-legacy-elasticsearch.xml
phpunit-integration-legacy-solr.xml
phpunit-integration-legacy.xml
phpunit-integration-rest-json.xml
phpunit-integration-rest-xml.xml

| **Target version** | `6.7`, `6.13`, `7.2`, `master`
According to the [PHPUnit XSD schema for configuration file](https://github.com/sebastianbergmann/phpunit/blob/4.8/phpunit.xsd#L139-L142), the `directory` entries should preceed `file` entries in a configuration file.
This PR fixes our PHPUnit configuration files to conform to that schema.
While [validation error occurs](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/400907867#L738-L744) when using PHPUnit `^7.2`, I'm fixing it for Kernel `6.7` (using PHPUnit `^4.8`), because it has never been correct. We saw it only now because …

[PHPUnit] Fixed configuration files to conform to XSD schema

---

eZ/Publish/API/Repository/Tests/BaseTest.php

| **JIRA issue**     | Not needed
This changes fetching of test `SetupFactory` class from `$_ENV` to `getenv()`, which will also check system's environment variables. It will enable overriding of `<env name="setupFactory" ... />` directive in PHPUnit configuration from command line, which is useful for example for running kernel integration tests from external repo to test for regressions.
Several other `<env ... />` configurations already use `getenv()`, for example `CORES_SETUP` and `fixtureDir`:
- …

Use getenv() to retrieve test testup factory

---

.travis.yml

| **JIRA issue**     | Done as part of https://jira.ez.no/browse/EZEE-2236
| **Bug/Improvement**| CI improvement
| **Target version** | 6.7, 6.13, 7.2 and master
This PR adds Slack notifications about broken builds on Travis, something I've talked with @alongosz some time ago. It will posts messages negative results to two channels:
- #travis-notifications on eZ Systems Polska workspace (an existing channel, used for AdminUI already)
- #travis-notifications on eZ Crew workspace (new channel created for notifications purposes)
**TODO**:

[TRAVIS] EZEE-2236: Add Slack notifications about broken builds

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php

| **Bug**| yes
| **Target version** | `6.x`,`7.x`
Broken UrlAliast (for example with not-existent parent) will throw "Array to string conversion" exception, which is very misleading. This happens because `$path` for a proper exception is generated via `implode` with an array of arrays as a parameter (not array of strings).
This PR fixes it, so instead `RuntimeException: "Path ({$path}...) is broken, last id is '{$id}'` will be thrown. 
**TODO**:

"Array to string conversion" exception when UrlAlias has non-existent parent.

---

eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php

| **JIRA issue**     | [EZP-29421](https://jira.ez.no/browse/EZP-29421)
Now we fetch all referenced files. If are any referenced files and the sent file is not in referenced files we remove old file and store file reference.
**TODO**:

EZP-29421: Contents of file field are lost if object is saved before publishing

---

eZ/Publish/Core/MVC/Symfony/View/ContentView.php

| **JIRA issue**     | [EZP-29462](https://jira.ez.no/browse/EZP-29462)
Improve docblock and return type hint for `\eZ\Publish\Core\MVC\Symfony\View\ContentView::getLocation` method. Because we did not set `$this->location` in the constructor, it is a possibility to have `$this->location` as null, ex https://jira.ez.no/browse/EZP-29342
**TODO**:

EZP-29462: Improve docblock and return type hint for ContentView::getLocation method

---

eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/panel.html.twig
eZ/Publish/Core/Persistence/Cache/PersistenceLogger.php
eZ/Publish/Core/Persistence/Cache/Tests/PersistenceLoggerTest.php

| **JIRA issue**     | [EZP-29470](https://jira.ez.no/browse/EZP-29470)
| **Doc needed**     | _maybe update of screenshoots_
Adds a simplified trace on the listing of un-cached `Persistence\Cache` calls in order to simplify identifying where they are called. 
- Changes order so siteaccess info is shown first to not have to scroll down on long un-cached list
- Updated headers to make it more clear what this _(Persistence call info)_ is, and what is part of it
Screenshoot of frontpage for clean install, trace immediately identifies two possible improvements:
1. [Bug] Admin UI seems to wrongly load config …

EZP-29470: As a developer I want trace for uncache Persistence calls

---

eZ/Publish/API/Repository/Tests/UserServiceTest.php

Attempt at fixing the integration test failure on travis when using Solr, the test is missing a `refreshSearch()` so attempting to add it to see if that is the culprit.
As for why this pops up now, probably because we now set config slightly different as of 1.5.3/1.5.4,
we now also set auto soft commit time even for CI runs so might be something in regards to that.
Todo:

[Travis] Fix integration test failure on Solr with all branches

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ConsoleCacheWarmupPass.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php

| **JIRA issue**     | [EZP-29034](https://jira.ez.no/browse/EZP-29034)
| **BC breaks**      | kinda: disables class cache warmer
| **Tests pass**     | 
| **Doc needed**     | maybe: mention that class cache warmer is disabled on cli?
Add ConsoleCacheWarmupPass which disables class cache warmer on CLI.
Part of https://github.com/ezsystems/ezplatform/pull/317
Replaces hack: https://github.com/ezsystems/ezplatform/commit/7e6b4716480d16e45d0ac4bd75b2b319cff42ff7
Based on Symfony `AddCacheWarmerPass`: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Compiler/AddCacheWarmerPass.php
**TODO**:

EZP-29034: Cannot install ezplatform on 1.7 branch

---

eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php

| **JIRA issue**     | [EZP-29536](https://jira.ez.no/browse/EZP-29536)
This is a follow-up for https://github.com/ezsystems/ezpublish-kernel/pull/2419. This PR contains a test case for `ContentViewBuilder`. It doesn't cover everything, but at least performs checks for expected exceptions.

Test case for ContentViewBuilder

---

.travis.yml
bin/.travis/prepare_unittest.sh

| **JIRA issue**     | Done as part of https://jira.ez.no/browse/EZEE-2236
| **Bug/Improvement**| CI improvment
| **Target version** | 6.7, 6.13, 7.2, master
Sometimes `composer install` fails because of network connection problems, for example:
```
```[37;41m                                                                               [39;49m
[37;41m  [Composer\Downloader\TransportException]                                     [39;49m
[37;41m  The "http://packagist.org/p/ezsystems/ezpublish%24668516c3c81fe7235019645bb  [39;49m
[37;41m  ea5df277a1823a31351e9a2b6dd701bbfbb404e.json" file could not be downloaded …

[TRAVIS] EZEE-2236: Retry installation after Composer failure

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php

Issues can be seen doing for instance this where we would expect frontend to crash:
```
ezpublish:
system:
site:
languages: [eng-GB]
site_group:
cache_service_name: cache.xxxx
```
Checked what differed between 6.x and 7.x and noticed that I added default value for 7.x's `cache_service_name` parameter compared to 6.x `cache_pool` parameter which did not have any.
```
$ grep --include=\*.xml  -rnw var/cache/ -e 'cache_service_name'
var/cache//dev/appDevDebugProjectContainer.xml:846:    <parameter key="ezsettings.default.cache_service_name">cache.app</parameter>
var/cache//dev/appDevDebugProjectContainer.xml:3867:    <parameter key="ezsettings.admin_group.cache_service_name">%env(CACHE_POOL)%</parameter>
var/cache//dev/appDevDebugProjectContainer.xml:3934:    <parameter …
```

EZP-28888: Custom cache_service_name can not be set from siteaccess group

---

eZ/Publish/API/Repository/Tests/UserPreferenceServiceTest.php
eZ/Publish/API/Repository/UserPreferenceService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
eZ/Publish/Core/SignalSlot/Tests/UserPreferenceServiceTest.php
eZ/Publish/Core/SignalSlot/UserPreferenceService.php

| **JIRA issue**     | [EZP-29577](https://jira.ez.no/browse/EZP-29577)
This PR adds missing getUserPreferenceCount() method to public API.
**TODO**:

EZP-29577: As a developer, I want a API to count user preferences

---

eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php

| **JIRA issue**     | [DEMO-201](https://jira.ez.no/browse/DEMO-201)
Added validation for `NULL` value which comes from `dataInt1` Legacy Storage Engine field for existing CT's which have Author Field Type.
**TODO**:

DEMO-201: User is unable to create Article from COTF

---

eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php
eZ/Publish/SPI/Persistence/Content/Handler.php
eZ/Publish/SPI/Persistence/Content/LoadStruct.php

| **JIRA issue**     | See #2423,
| **Target version** | 7.2+
| **BC breaks**      | yes for SPI, but we don't have BC promise there yet
This is in order to enable work on #2423, @alongosz identified several issues with current bulk loading logic which slows it down on larger batches:
1. The SQL becomes to big as we build up a large OR expression, which also means we repeat language filtering per item
2. version filtering was not done on the join meaning DB had to do a lot more work to filter out correct items after all data is joined
3. loadVersionedNameData was given a lot of duplicated entries which caused the …

Optimize content bulk loading for use with larger batch sizes

---

composer.json

| **Bug/Improvement**| n/a
| **New feature**    | n/a
| **Target version** | 7.2, when merged to master should be set to master
Kernel tests are failing because they are using the master branch on metarepo, which contains incompatible changes with 7.2 kernel. These tests should use the 2.2 branch.

[Travis] Set correct metarepo branch for 7.2 branch

---

composer.json
eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php

Our REST tests executed from eZ Platform meta-repository fail when any code triggers deprecations. It allows us to quickly identify potential near-future issues.
This PR aligns code with the most recent changes in `kriswallsmith/buzz` ([`v0.17.2`](https://github.com/kriswallsmith/Buzz/blob/0.17.2/CHANGELOG.md#0172)) to avoid deprecation failures.
| Question    |  Answer
| **Target version** | `7.2`+
**TODO**:

[REST Tests] Aligned code with Buzz v0.17.2

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

| **JIRA issue**     | [EZP-29504](https://jira.ez.no/browse/EZP-29504)
| **Bug**| yes
Add siteaccess parameter when ezplatform:reindex is run in multi-process on a multi-siteaccess multi-repository environment
**TODO**:

EZP-29504 : add siteaccess parameter to ezplatform:reindex

---

eZ/Publish/API/Repository/PermissionResolver.php
eZ/Publish/API/Repository/Tests/SectionServiceAuthorizationTest.php
eZ/Publish/Core/Limitation/SubtreeLimitationType.php
eZ/Publish/Core/Limitation/Tests/SubtreeLimitationTypeTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/LanguageService.php
eZ/Publish/Core/Repository/ObjectStateService.php
eZ/Publish/Core/Repository/SectionService.php
eZ/Publish/Core/Repository/Tests/Service/Integration/TrashBase.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/Core/Repository/URLWildcardService.php

| **JIRA issue**     | [EZP-29474](https://jira.ez.no/browse/EZP-29474)
| **BC breaks**      | yes _(2, see below)_
| **Doc needed**     | afaik no
Fix wrong usage\* of `hasAccess()` in repository in favor of `canUser()` in order to solve:
- Issues when there are Role Assignment Limitation, as in this case they will return info to permission system they `abstain` from "voting"
- As policies are now extendable, make code prepared in case someone needs to customize and add limitations to any of these functions, or we end up adding it out of the box ourselves.
In effect this makes Repo more correctly use …

EZP-29474: Fix wrong usage of hasAccess in repository

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default_inline.html.twig
eZ/Publish/Core/FieldType/RichText/Converter/Render/Style.php
eZ/Publish/Core/FieldType/RichText/RendererInterface.php
eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/EmbedTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/StyleTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/TemplateTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/032-ezstyleinline.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/032-ezstyleinline.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/031-ezstyle.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/032-ezstyleinline.xml
eZ/Publish/Core/MVC/Symfony/FieldType/RichText/Renderer.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RichText/RendererTest.php

| **JIRA issue**     | https://jira.ez.no/browse/EZP-29554
**TODO**:
Added a way to declare and use custom "styles" in richtext (https://alloyeditor.com/docs/features/styles.html)
PR for the admin ui : https://github.com/ezsystems/ezplatform-admin-ui/pull/602
``` yaml
ezpublish:
system:
default:
fieldtypes:
ezrichtext:
custom_styles: [highlighted_block, highlighted_word]
ezrichtext:
custom_styles:
highlighted_word:
template: '@ezdesign/field_type/ezrichtext/custom_style/highlighted_word.html.twig'
inline: true
highlighted_block:
template: …
```

EZP-29554: As an editor, I want to be able to apply custom styles to part of my text

---

eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php

| **Target version** | `6.7`+
| **Tests pass**     | let's see...
In Twig 2.0 the prototype of `\Twig_Test_IntegrationTestCase::doIntegrationTest`
changed and since we extend that class, it results in a warning:
```
PHP Warning:  Declaration of eZ\Publish\Core\MVC\Symfony\Templating\Tests\Twig\Extension\FileSystemTwigIntegrationTestCase::doIntegrationTest($file, $message, $condition, $templates, $exception, $outputs) should be compatible with Twig_Test_IntegrationTestCase::doIntegrationTest($file, $message, $condition, $templates, $exception, $outputs, $deprecation = '')
```
Since we …

[Tests] Fixed Twig integration tests warning about method prototype

---

eZ/Publish/Core/REST/Common/Output/Generator.php
eZ/Publish/Core/REST/Common/Output/Generator/Json.php
eZ/Publish/Core/REST/Common/Output/Generator/Xml.php

| **JIRA issue**     | [EZP-29234](https://jira.ez.no/browse/EZP-29234)
| **BC breaks**      | no (I hope so)
This PR contains improvement for customizing REST `Accept` header based response. The idea is to ged rid of overriden format generators which only responsibility is to set `$vendor` prefix which could be defined as an argument in `services.yml`. It will simplify customization of API response which was introduced in: https://github.com/ezsystems/PlatformUIBundle/pull/964 and described in cookbook: https://github.com/ezsystems/developer-documentation/pull/288. As a followup, …

EZP-29234: As a developer, I want to read about customizing REST API response

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Publish/Core/FieldType/ImageAsset/Type.php
eZ/Publish/Core/FieldType/ImageAsset/Value.php
eZ/Publish/Core/FieldType/Tests/ImageAssetTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageAssetConverter.php
eZ/Publish/SPI/Tests/FieldType/ImageAssetIntegrationTest.php

| **JIRA issue**     | [EZP-29508](https://jira.ez.no/browse/EZP-29508)
Impl. possibility to define Alternative Text for Image Asset. 
**TODO**:

 EZP-29508: As an editor I want to manage ALT field with an image asset field type

---

eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php

| **JIRA issue**     | Follow-up for [EZP-29139](https://jira.ez.no/browse/EZP-29139)
| **Target version** | `6.13`, `7.2`, `7.3` (`master`)
| **Doc needed**     | maybe (if not present yet)
This PR adds to the `ezplatform:urls:regenerate-aliases` command an info, requested by @mnocon, about a need to manually clear HTTP cache afterwards in the following places:
- before the command is executed,
- after the command ends.
Since HTTP Cache got decoupled from Kernel in `1.13`/`6.13`, I'm targeting this PR to `6.13` and up. In `6.7` it was possible to inject cache purger service to this command, so it's not needed …

EZP-29139: Added more info about clearing HTTP cache after running cmd

---

eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/BackgroundIndexingTerminateListenerTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/AliasGeneratorTest.php
eZ/Publish/Core/Base/Tests/PHPUnit5CompatTrait.php
eZ/Publish/Core/FieldType/Tests/RichText/InternalLinkValidatorTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/InstantCachePurgerTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
eZ/Publish/Core/REST/Server/Tests/Security/CsrfTokenManagerTest.php
eZ/Publish/Core/REST/Server/Tests/Security/RestLogoutHandlerTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php

This PR replaces PHPUnit's deprecated getMock with createMock and deprecates PHPUnit5CompatTrait.
It's been causing [a lot of warnings](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/428329482#L899) when executing tests, so it's the highest time to improve that.
**TODO**:

[Unit Tests] Replaced deprecated getMock with createMock

---

eZ/Publish/Core/REST/Client/LocationService.php
eZ/Publish/Core/REST/Server/Controller/Content.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/Tests/LocationServiceTest.php

| **JIRA issue**     | [EZP-29518](https://jira.ez.no/browse/EZP-29518)
| **Bug**| yes
| **Target version** | `6.7+`
Setting ContentType option "Default field for sorting children" had no effect on newly created Content Object of said ContentType - they were always set to default "Content Name Ascending". This PR fixes it.
**TODO**:
**TODO ON MERGE**
- Adapt SiteAccessAware Repo when merging to 2.2

EZP-29518: ContentType option "Default field for sorting children" has no effect on new created objects

---

eZ/Publish/API/Repository/Values/Content/Relation.php
eZ/Publish/Core/FieldType/ImageAsset/Type.php
eZ/Publish/Core/FieldType/Tests/ImageAssetTest.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
eZ/Publish/Core/REST/Client/Input/Parser/Relation.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestRelation.php
eZ/Publish/Core/Repository/Helper/RelationProcessor.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
eZ/Publish/SPI/Persistence/Content/Relation.php

| **JIRA issue**     | [EZP-29408](https://jira.ez.no/browse/EZP-29408)
| **Required by** | ezsystems/ezplatform-admin-ui#591
| **Tests pass**     |  yes
This PR introduces a new type of relation type between content: `ASSET`. This allow to distinct the relation to the content items of type dedicated to represent assets (e.g Image, File, Media).
Typicaly a relation type created by ImageAsset, but also in the future by other "Asset" field types. 
**TODO**:

EZP-29408: Implemented Asset Relation type

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

> https://jira.ez.no/browse/EZP-29531
Without this fix, rendering relation and selection items in eZ Platform Admin UI v2 looks like this:
With the fix, it looks like this:

EZP-29531: Do not render layout when rendering selection and relation items

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RichTextHtml5ConverterPass.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Publish/Core/FieldType/RichText/Converter/ProgramListing.php
eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
eZ/Publish/Core/FieldType/RichText/Resources/schemas/ezxhtml5/output/changes.rst
eZ/Publish/Core/FieldType/RichText/Resources/schemas/ezxhtml5/output/ezxhtml5.xsd
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/Xhtml5ToDocbookTest.php
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/033-programlisting.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/033-programlisting.xml
eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/033-programlisting.xml

| **JIRA issue**     | [EZP-29328](https://jira.ez.no/browse/EZP-29328)
| **Bug/Improvement**| improvment
We need `<programlisting>` for literal, see [EZP-29328](https://jira.ez.no/browse/EZP-29328)
See corresponding [PR for conversion script ( ezxmltext -> docbook )](https://github.com/ezsystems/ezplatform-xmltext-fieldtype/pull/71)
With this PR, the alloy editor is able to edit existing programlistings, but button for creating new programlisting should be created in a separate admin-ui PR.
**TODO**:

EZP-29328: Allow docbook tag "programlisting"

---

eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasMapperTest.php
eZ/Publish/Core/Repository/URLAliasService.php
eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php

| **JIRA issue**     | [EZP-29721](https://jira.ez.no/browse/EZP-29721), follow-up to [EZP-29139](https://jira.ez.no/browse/EZP-29139)
| **Target version** | `5.4`, `6.7`+
| **BC breaks**      | not yet
This is an attempt to fix edge case discovered by @mnocon - when parent of a nested URL alias was gone due to data corruption, the command displayed error referring to itself. It was fixed by moving cleanup prior to regenerating aliases, which was rather a workaround.
This solution consists of several parts:
1. Cleaning corrupted aliases is done after performing refresh (21a5726).
2. …

EZP-29721: Broken URL alias history is not restored after regenerating aliases

---

composer.json

> **Target version**: `7.3`
Switched composer.json `extra->_ezplatform_branch_for_behat_tests` to 2.3 to test `7.3` bug fixes on `2.3` branch.
**TODO**:

[Composer][7.3] Switched eZ Platform branch for behat tests to 2.3

---

.travis.yml
bin/.travis/prepare_unittest.sh

| **JIRA issue**     | [EZP-29740](https://jira.ez.no/browse/EZP-29740)
| **Bug/Improvement**| Improvement
| **Target version** | 7.3, master
Adds a job running Legacy integration tests on MariaDB 10.3. This PR contains two commits:
https://github.com/ezsystems/ezpublish-kernel/pull/2468/commits/cd6779360e61463927c3b1de9ac47a297cd49f11 adds the job, https://github.com/ezsystems/ezpublish-kernel/pull/2468/commits/cbaceec1b8bae6b782f89edcdd8363e49af349a7 is a temporary one that verifies that `mysql` command is in fact MariaDB 10.3. (`mysql -uroot -V` returns `mysql  Ver 15.1 Distrib 10.3.10-MariaDB, for …

Add additional databases setup on Travis

---

eZ/Publish/Core/MVC/Symfony/Controller/Controller.php

Added Missing use Statement for ContainerInterface to \eZ\Publish\Core\MVC\Symfony\Controller\Controller

Missing use statement in  eZ/Publish/Core/MVC/Symfony/Controller/Controller

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

| **JIRA issue**     | [EZP-29801](https://jira.ez.no/browse/EZP-29801)
| **Target version** | `7.2+`
If you somehow provide location id to Content View, then it will throw the following now after ContentProxy feature was added in 2.2:
```
Argument 'Location' is invalid: Provided location does not belong to selected content as requested via contentId parameter
```
This for instance break Step 3 in Bike Ride tutorial where you are asked to enter following url, last parameter is optional so removing it makes it work:
`http://<yourdomains>/view/content/<ContentId>/<language>/full/true/<Loc …

EZP-29801: Content View breaks when providing location id as param

---

eZ/Publish/Core/MVC/Symfony/FieldType/Tests/Relation/ParameterProviderTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
eZ/Publish/Core/REST/Client/LocationService.php
eZ/Publish/Core/REST/Client/Repository.php
eZ/Publish/Core/REST/Client/Tests/Output/ValueObjectVisitor/RestContentMetadataUpdateStruct.php
eZ/Publish/Core/REST/Client/UserService.php

| **JIRA issue**     | ---
| **Bug/Improvement**| ---
I wanted to run PHPStan against `ezpublish-kernel`, but during the static analysis, PHP interpreter complained about a few minor issues like incorrect namespaces or missing implementations of interfaces methods. This PR fixes all of them, therefore it's possible to finish PHPStan execution. 
There is a plan for another PRs in the future, regarding the issues found by the mentioned tool.
**TODO**:

Fixes for the issues causing PHP fatal errors during the static analysis

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php

| **JIRA issue**     | none
This PR removes `api_keys.google_maps` setting to be automatically set as null. By explicitly setting it to null,  has effect to all configuration scopes like `global` and `default` which makes impossible to set values per siteaccess. The only way to override it is by adding `ezsettings.global.api_keys.google_maps` to parameters.yml.
Fallback is already provided by https://github.com/ezsystems/ezpublish-kernel/blob/36f372c3b7c21adec7970439af8e2ca9e775097e/eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml#L95, so …

api_keys.google_maps should not be set as null by default

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/ezrichtext_default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/richtext.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/richtext/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/richtext/templating.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Publish/Core/settings/containerBuilder.php
eZ/Publish/Core/settings/fieldtype_external_storages.yml
eZ/Publish/Core/settings/fieldtype_services.yml
eZ/Publish/Core/settings/fieldtypes.yml
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/richtext.yml
eZ/Publish/Core/settings/richtext/fieldtype_external_storages.yml
eZ/Publish/Core/settings/richtext/fieldtype_services.yml
eZ/Publish/Core/settings/richtext/fieldtypes.yml
eZ/Publish/Core/settings/richtext/indexable_fieldtypes.yml
eZ/Publish/Core/settings/richtext/storage_engines/legacy/external_storage_gateways.yml
eZ/Publish/Core/settings/richtext/storage_engines/legacy/field_value_converters.yml
eZ/Publish/Core/settings/storage_engines/legacy/external_storage_gateways.yml
eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml

| **JIRA issue**     | [EZP-28009](https://jira.ez.no/browse/EZP-28009)
| **Target version** | `master (7.2)`
Required to prevent conflicts with [ezsystems/ezplatform-richtext](http://github.com/ezsystems/ezplatform-richtext).
Two small changes to `EzPublishCoreBundle` and `EzPublishCoreExtension`. In both, disables some components of core richtext if the package is installed (default settings and config parser).

EZP-28009: Provided compatibility with external RichText package

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/RelationTest.php
eZ/Publish/Core/REST/Client/Input/Parser/Relation.php
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestRelation.php

| **JIRA issue**     | [EZP-29375](https://jira.ez.no/browse/EZP-29375)
If a content has a relation with e. g. COMMON and EMBED relation type, the REST API can't load it.
Following exception is thrown:
```
Unknown relation type 3
```
**TODO**:

Fix EZP-29375: REST API doesn't support multiple relation types

---

eZ/Publish/Core/Repository/LocationService.php

| **Target version** | 6.7
The ContentService includes information about the content in question when throwing `UnauthorizedException`s (as seen for example in https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/ContentService.php#L136), which helps when inspecting/debugging thrown exceptions.
I'd like to propose a similar approach for `UnauthorizedException`s thrown from the LocationService.
:octocat:

Add location id information to UnauthorizedExceptions when using API LocationService

---

eZ/Publish/Core/FieldType/Tests/StringLengthValidatorTest.php
eZ/Publish/Core/FieldType/Tests/TextLineTest.php
eZ/Publish/Core/FieldType/TextLine/Type.php
eZ/Publish/Core/FieldType/Validator/StringLengthValidator.php

| **JIRA issue**     | [EZP-29864](https://jira.ez.no/browse/EZP-29864)
**TODO**:

EZP-29864: Spelling mistake in Content Type alert warnings

---

eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php

JIRA: https://jira.ez.no/browse/EZP-28099
If you have 2 path prefixes that starts with the same name.
e.g.
- eZ Platform
- eZ Platform Enterprise
And generate a link from the short path prefix to the large. The url is generate without leading slash and with half path prefix.
e.g.
`-Enterprise/Imprint`
instead of
`/eZ-Platform-Enterprise/Imprint`

Fix EZP-28099: Wrong Urls at equal beginning path prefixes

---

eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/API/Repository/UserService.php
eZ/Publish/API/Repository/Values/Translation/Message.php
eZ/Publish/API/Repository/Values/Translation/Plural.php
eZ/Publish/API/Repository/Values/User/PasswordValidationContext.php
eZ/Publish/Core/Base/Exceptions/UserPasswordValidationException.php
eZ/Publish/Core/FieldType/Tests/UserTest.php
eZ/Publish/Core/FieldType/User/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
eZ/Publish/Core/REST/Client/UserService.php
eZ/Publish/Core/Repository/Helper/UserPasswordValidator.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UserPasswordValidatorTest.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/Repository/Validator/UserPasswordValidator.php
eZ/Publish/Core/SignalSlot/Tests/UserServiceTest.php
eZ/Publish/Core/SignalSlot/UserService.php
eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml

| **JIRA issue**     |  https://jira.ez.no/browse/EZP-29122
This PR adds a new settings to the `ezuser` field type, which allows to specify the following password requirements:
* Minimum password length
* Password must contain at least one uppercase letter 
* Password must contain at least one lowercase letter
* Password must contain at least one number
* Password must contain at least one non-alphanumeric character
Added  new `UserService::validatePassword` method:
```php
interface UserService 
{
// ...
/**
* Validates given password.
*
* @param string …
```

EZP-29122: As a developer, I want to configure password policies in ezuser

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig

| **JIRA issue**     | [EZP-29887](https://jira.ez.no/browse/EZP-29887)
| **Requires** | ezsystems/ezplatform-richtext#24
| **Target version** | `7.4 for eZ Platform 2.4`
This PR introduces default view template for `embed-inline` View type.
Due to order of merging of arrays with SA-aware configuration, it's impossible to set this default template via `content_view` setting like it was done in ezsystems/ezplatform-richtext#23.
**TODO**:

EZP-29887: Added default view template for embed-inline View type

---

.travis.yml

| **Target version** | `6.7`and up
PHP 7.3 is out, so time to start testing against it.
For behat/functional that will require https://github.com/ezsystems/docker-php/pull/32
**TODO**:

[Travis] Add testing on PHP 7.3

---

eZ/Publish/API/Repository/LocationService.php
eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/REST/Client/LocationService.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php
eZ/Publish/Core/SignalSlot/LocationService.php
eZ/Publish/Core/SignalSlot/Tests/LocationServiceTest.php
eZ/Publish/SPI/Persistence/Content/Location/Handler.php

| **JIRA issue**     | [EZP-29851](https://jira.ez.no/browse/EZP-29851)
| **Doc needed**     | _maybe_
Motivation
----------
Like the other bulk loading API's added recently this is to optimize usage in:
- Page builder
- Cron Jobs / Commands
- GraphQL
- REST
- Admin UI
- Internally in Repository itself
- ...
Any place where several content / locations might be loaded today.
These changes allows for less PHP code to execute, less SQL lookups, and less cache lookups by taking advantage of Symfony Cache's multi get support.
Biggest benefit will be on setups where cache server is on a different machine, this can …

EZP-29851: As a developer I want to be able to load several Locations at once, fast

---

eZ/Publish/API/Repository/TrashService.php
eZ/Publish/API/Repository/Values/Content/Trash/TrashItemDeleteResult.php
eZ/Publish/API/Repository/Values/Content/Trash/TrashItemDeleteResultList.php
eZ/Publish/Core/Persistence/Cache/TrashHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/TrashHandlerTest.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/Core/SignalSlot/Signal/TrashService/DeleteTrashItemSignal.php
eZ/Publish/Core/SignalSlot/Signal/TrashService/EmptyTrashSignal.php
eZ/Publish/Core/SignalSlot/Tests/TrashServiceTest.php
eZ/Publish/Core/SignalSlot/TrashService.php
eZ/Publish/SPI/Persistence/Content/Location/Trash/Handler.php

| **JIRA issue**     | [EZP-29997](https://jira.ez.no/browse/EZP-29997)
| **BC breaks**      | yes/no
I described the problem in the ticket and here is the quick and dirty implementation. I need your validation on the idea.
After discussion I can fix naming (TrashedItem, TrashItem... it's kind of a mess now :P), update tests.
**TODO**:

EZP-29997: Exposed information about removed content items in EmptyTrashSignal and DeleteTrashItemSignal

---

eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-30004](https://jira.ez.no/browse/EZP-30004)
| **Target version** | `6.7`, `6.13`, `7.3`, `7.4`, `master`
Setting parent of archived entry based on original entry results in moving that archived entry in subtree, which makes no sense and results in unique constraint violation if archived name is the same as already existing one for that parent.
To keep the feature of repairing broken entries, parent of archived element is updated using original entry, only in case when that parent is broken (meaning it doesn't exist). In other cases current parent is reused for …

EZP-30004: ezplatform:urls:regenerate-aliases changes parent of broken link

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/FieldTypeContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/UserContext.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/RootTest.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php

| **JIRA issue**     | [EZP-30008](https://jira.ez.no/browse/EZP-30008)
| **Target version** | `6.x`/`7.x`
Use `prefix` and `more_entropy` wherever possible. Otherwise, silence warnings with `@noinspection`.
See also https://github.com/ezsystems/BehatBundle/pull/72 and https://github.com/ezsystems/repository-forms/pull/271
**TODO**:

EZP-30008: More unique uniqid()

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/FieldTypeContext.php

Similar as in https://github.com/ezsystems/repository-forms/pull/275 - the dot cannot be used in Content Type identifier.
Regression from https://github.com/ezsystems/ezpublish-kernel/pull/2523

Remove dot from Content Type identifier

---

eZ/Publish/Core/FieldType/RelationList/Type.php
eZ/Publish/Core/FieldType/Tests/RelationListTest.php

| **JIRA issue**     | [EZP-29924](https://jira.ez.no/browse/EZP-29924)
| **Bug**| yes
| **Target version** | `6.7`/`6.13`/`7.3`/`7.4`/`master`
Please refer to the JIRA ticket for more information. 
**TODO**:

EZP-29924: Can't save ContentType with RelationList which has selectionMethod from legacy

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

| **JIRA issue**     | [EZP-29959](https://jira.ez.no/browse/EZP-29959)
| **Target version** | `6.7`/`6.13`/`7.3`/`master` 
During merge-up (into 7.3 and higher) it might be a good idea to inject `PermissionResolver` instead of getting it from `Repository`. 
Tests for `ContentViewBuilder` were introduced in `7.3` therefore some additional changes are necessary. 
**TODO**:

EZP-29959: Token not found exception in ContentViewBuilder when used to build own exception page

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

| **JIRA issue**     | [EZP-29959](https://jira.ez.no/browse/EZP-29959)
| **Bug**| yes
| **Target version** | `6.7`/`6.13`/`7.3`/`7.4`/`master`
As reported on Slack, the incorrect permission function has been used.
**TODO**:

Fixed incorrect permission function

---

eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
eZ/Publish/Core/Persistence/Cache/TrashHandler.php

| **JIRA issue**     | [EZP-29041](https://jira.ez.no/browse/EZP-29041)
| **Bug**| yes
| **Target version** | `7.3`
**TODO**:

EZP-29041: Content still visible in ezobjectrelationlist after sending it to trash

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-28663](https://jira.ez.no/browse/EZP-28663)
| **Target version** | `6.7`, `6.13`, `7.2`, `7.3`, `7.4`, `master`
This PR fixes the issue with swapping non-main Location of Content items.
The root cause of this issue was forcing joining Content Info data by main Location w/o taking into the account that a Location might not be the main one.
The second issue is the state of Main Location. In the case of swapping of main Location with non-main Location, that state needs to be swapped as well.
Note: Content Id is in the square brackets:
```
Root
└── [50] Content1 …
```

EZP-28663: Cannot swap location when viewing item from non-main location

---

eZ/Publish/API/Repository/Repository.php
eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/Core/REST/Client/Repository.php
eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
eZ/Publish/Core/Repository/Permission/PermissionResolver.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
eZ/Publish/Core/SignalSlot/Repository.php

| **JIRA issue**     | [EZP-30028](https://jira.ez.no/browse/EZP-30028)
| **New feature**    | _API Interface wise yes, otherwise no_
A bit overdue change perhaps.
Needed so:
- It can be found easier by developers, and so we can document it as part of how to get content current user does not have access to.
- So it can become official so Developers feels safe using it
Note, this does not:
- Remove the need to continue adding bulk loading API's that don't throw but instead just filters on permission
- Remove the possible future option of adding arguments on these bulk load methods to opt out of permission …

EZP-30028: As a Developer I'd like sudo() to be exposed on API

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
eZ/Publish/Core/MVC/Symfony/Locale/Tests/UserLanguagePreferenceProviderTest.php
eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProvider.php

| **JIRA issue**     | [EZP-29961](https://jira.ez.no/browse/EZP-29961)
relates to [https://github.com/ezsystems/ezplatform-admin-ui/pull/774](https://github.com/ezsystems/ezplatform-admin-ui/pull/774)
**TODO**:

EZP-29961: Add preferred language value to User Preferences

---

data/mysql/cleandata.sql
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
eZ/Publish/Core/MVC/Symfony/FieldType/ImageAsset/ParameterProvider.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/ImageAsset/ParameterProviderTest.php

| **JIRA issue**     | [EZP-29980](https://jira.ez.no/browse/EZP-29980)
| **Target version** | 7.4
Adds permission for Anonymous user to view_embed images and files
Allow users with view_embed permission to see image assets
**TODO**:

EZP-29980 : Anonymous should be able to see images 

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

| **JIRA issue**     | [EZP-30013](https://jira.ez.no/browse/EZP-30013)
| **Bug**| yes
| **Target version** | `6.7`, `6.13`, `7.4`

EZP-30013: --env option not passed to parallel processes of `ezplatform:reindex` Command

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/UserTest.php

| **Target version** | 6.13 
The build for 1.13 version is currently failing: https://travis-ci.org/ezsystems/ezplatform/jobs/494621949 with
```
There was 1 warning:
1) eZ\Bundle\EzPublishRestBundle\Tests\Functional\UserTest::testLoadSubUserGroups
This test depends on "eZ\Bundle\EzPublishRestBundle\Tests\Functional\UserTest::testCreateGroup" which does not exist.
--
```
This is a similar failure to the one that happened on Friday (fixed in https://github.com/ezsystems/ezpublish-kernel/commit/7d82ac85be44c66298c687664f8ab0350e1cf020 )
Changed the dependency to …

Set dependency to existing testCreateUserGroup test

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/RelationList/ParameterProvider.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php

| **JIRA issue**     | [EZP-30029](https://jira.ez.no/browse/EZP-30029)
In order to optimize logic in  RelationList/ParameterProvider, and other places eventually.
**TODO**:
**Design:**
`public function loadContentInfoList(array $contentIds, bool $filterOnUserPermissions = true): iterable;`
**REVIEW NOTE***
- ~I'm not sold on adding `bool $filterOnUserPermissions` param myself, but it aligns with `SearchService`, and it also fits well with `loadContentListByContentInfo` which explicitly does not check permissions as it expects that to already have been done on provided content …

EZP-30029: As a Developer I'd like API for bulk loading Content Info Items

---

eZ/Publish/API/Repository/Tests/BaseTest.php

This PR adds autoconfiguration for Repository integration tests, so running them (by default as Legacy Storage tests on SQLite in-memory database and Legacy Search Engine) does not require providing dedicated `phpunit-integration-legacy.xml` configuration file.
This improves DX, because each time we'd like to run and/or debug a test from an IDE, we needed to configure this file, which is very annoying. Integration test knows everything to be executed as integration test. Configuration file should provide only:
- explicit list of test suite classes when executing all tests,
- alternative search engine.
- alternative DBMS (SQLite in-memory by default for performance and simple config).
For most of the day-to-day development tasks, especially working with IDE, all of this is not needed …

[DX] Provided autoconfiguration for API/Repository integration tests

---

eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
eZ/Publish/Core/Search/Common/Slot/UpdateUser.php
eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml
eZ/Publish/Core/settings/search_engines/legacy/slots.yml

| **JIRA issue**     | [EZP-30136](https://jira.ez.no/browse/EZP-30136)
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/496053283), requires ezsystems/ezplatform-solr-search-engine#130
| **Target version** | `6.7, 6.13, 7.3, 7.4`, `master`
Recreated this PR, as the last one got automatically closed after rebase.
This is part one of the fix for changes after updating content with `ezuser` field not being committed.
Part two `ezsystems/ezplatform-solr-search-engine`:
https://github.com/ezsystems/ezplatform-solr-search-engine/pull/130
**TODO**

EZP-30136: Updating content with "ezuser" field will not commit changes to Solr

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/TrashServiceAuthorizationTest.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/TrashService.php

| **JIRA issue**     | [EZP-29539](https://jira.ez.no/browse/EZP-29539)
Checking permission to remove content for all elements in the subtree.
**TODO**:

EZP-29539: Deleting object will remove all subtree items even when user does not have permission to delete them

---

data/mysql/schema.sql
data/update/mysql/dbupdate-7.4.0-to-7.5.0.sql
data/update/postgres/dbupdate-7.4.0-to-7.5.0.sql
eZ/Publish/Core/Persistence/Legacy/Notification/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql

| **JIRA issue**     | [EZP-30149](https://jira.ez.no/browse/EZP-30149)
| **Needed for** | [EZP-29938](https://jira.ez.no/browse/EZP-29938)
| **Target version** | `7.5 for eZ Platform 2.5 LTS`
This PR unifies `eznotification` database table definition between PostgreSQL and MySQL databases.
> 1. The `is_pending` column has `tinyint(1)` and `integer` data types for MySQL and PostgreSQL respectively. Doctrine Schema Tool transforms `tinyint(1)` to `boolean`, therefore this should be uniform data type. It's important for PostgreSQL because of strict type comparison in queries, which means …

EZP-30149: Unified eznotification table definition for MySQL and PostgreSQL

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/TranslationCollectorPassTest.php

This PR should be merged only when new translation files, with names which follow Symfony a strict convention, will be generated and available to download.
| **JIRA issue**     | [EZP-30144](https://jira.ez.no/browse/EZP-30144)
| **Bug**| yes
| **Doc needed**   | no
Now we use compiler pass to map and add translation files. Files comes from non-standard location and has names which not follow Symfony convention. The problem occurs when we generate translation files for javascript components. For example for translation file which holds locale 'fr', generated file is with 'fr_FR' keys. To avoid those problems …

EZP-30144: Add paths option for translator service instead of injecting files into the translator service paths

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/TemplatesTest.php

| **JIRA issue**     | [EZP-29724](https://jira.ez.no/browse/EZP-29724)
| **Target version** | 7.3
Default values are hardcoded and it is hard to override them in a clean way, and it is crucial for Standard Design to do so.
**TODO**:

EZP-29724: Parametrized base default templates to ease overriding

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-30204](https://jira.ez.no/browse/EZP-30204)
| **Target version** | `6.7`, `6.13`, `7.3`, `7.4` and `7.5 (master)`
Sometimes, especially when using PostgreSQL, records returned from a database are ordered randomly.
When repairing broken archived URL Alias entries, when fetch is executed, usually two original entries exist - the just corrected one and a broken one.
To make sure correct entry is using for repairing, this PR adds checking if entry parent exists. If it doesn't it means entry is broken.
**TODO**:

EZP-30204: Checked if orig URL Alias is correct when repairing arch.

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

| **JIRA issue**     | [EZP-29279](https://jira.ez.no/browse/EZP-29279)
| **BC breaks**      | minor
Currently, the value for Date Field Type displayed in the front office is affected by the server's timezone, meaning that if the server has timezone below (west of) UTC, then the previous day is displayed.
The value stored in the database is always midnight in UTC.
Twig by default applies the server's timezone when using its `localizeddate` method, so in this PR I fix the issue by making sure it doesn't.
The minor BC break that I mentioned is that someone could rely on the wrong …

EZP-29279: Fix value displayed by the Date Field Type being affected by server time zone

---

composer.json
eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
phpunit-integration-legacy-elasticsearch.xml
phpunit-integration-legacy-solr.xml
phpunit-integration-legacy.xml
phpunit.xml

| **New feature**    | yes/no
| **Target version** | `7.x` _(paratest requires php7)_
I don't expect this to pass with mysql/postgres/sorl, as we should setup different databases for the different processes using [test token](https://github.com/paratestphp/paratest#test-token).
**TODO**:

[Tests] Speed up tests by using paratest

---

eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/field_rendering_functions/ez_render_field_exception.test

| **Target version** | `6.13`, `7.3`, `7.4`, `master`
Most recently Twig introduced forced switch to PSR-4 namespaces.
This affects our test fixture which checks Twig exception message.
`Twig_Error_Runtime` became `Twig\Error\RuntimeError`
The mentioned fixture is present since `6.10`, so I fixed it in `6.13` LTS.
Applies to Twig versions:
- `v1.38.1` (surprisingly, tbh).
- `v2.7.1`.
**TODO**:

[Tests] Refactored Twig runtime error checking to be less strict

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php

| **JIRA issue**     | [EZP-30147](https://jira.ez.no/browse/EZP-30147)
**TODO**:

EZP-30147: Fixed moving a subtree with invisible items

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Values/Content/ContentMetadataUpdateStruct.php
eZ/Publish/Core/Repository/ContentService.php

| **JIRA issue**     | [EZP-30107](https://jira.ez.no/browse/EZP-30107)
part of https://github.com/ezsystems/ezplatform-admin-ui/pull/897
**TODO**:

EZP-30107: Name of Content Item is not updated after changing the main language

---

doc/specifications/rest/REST-API-V2.rst
doc/specifications/rest/xsd/Content.xsd
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php

| **JIRA issue**     | [EZP-30111](https://jira.ez.no/browse/EZP-30111)
Currently I do not have the opportunity to know if the content is in the trash, right?
The code is similar to the VersionInfo output visitor
**TODO**:

EZP-30111: [REST] Added Content status to RestContent output

---

eZ/Publish/Core/Repository/Helper/DomainMapper.php
eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php

| **JIRA issue**     | [EZP-30300](https://jira.ez.no/browse/EZP-30300)
| **Target version** |`7.x` 
Methods `\eZ\Publish\Core\Repository\Helper\DomainMapper::buildLocationWithContent` and `\eZ\Publish\Core\Repository\Helper\DomainMapper::buildLocation` should behave exactly the same way in case of tree root (location with id == 1).
**TODO**:

EZP-30300: Methods buildLocationWithContent and buildLocation should behave exactly the same in case of tree root 

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-30230](https://jira.ez.no/browse/EZP-30230)
Contents location should not be revealed when you reveal parent locations content, but contents location should remain hidden if any parent locations content is still hidden.
**TODO**:

EZP-30230: Fixed issue revealing content with hidden children/parent

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php

| **JIRA issue**     | Follow-up for [EZP-30139](https://jira.ez.no/browse/EZP-30139) and #2549 
| **Blocks** | [EZP-30061](https://jira.ez.no/browse/EZP-30061)
| **Target version** | `7.5 (master)` for `eZ Platform 2.5 LTS`
This is a follow-up for #2549 and randomly failing Repository integration test `testRevealContent` on PostgreSQL, which also blocks [EZP-30061](https://jira.ez.no/browse/EZP-30061).
The list of loaded Locations is not ordered by anything (and there's nothing relevant to order by), so the result of `loadLocations` is not deterministic. There's no relevant Location id …

EZP-30139: Fixed testRevealContent randomly failing on PostgreSQL

---

eZ/Publish/SPI/Persistence/Content/Handler.php

Stumbled on this, seems signature was not adapted when adding this argument in https://github.com/ezsystems/ezpublish-kernel/pull/2447.

[SPI] Add missing phpdoc and param for ContentHandler->copy()

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php

| **JIRA issue**     | [EZP-30271](https://jira.ez.no/browse/EZP-30271)
| **Target version** | `7.4`, `master`
**TODO**:

EZP-30271: Published version table disappears after bulk removing of drafts under edit

---

eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php

This PR fixes Command UpdateTimestampsToUTCCommand failing on php 5.6 due to `self::MODES[$this->mode]` is treated as expression.

Command UpdateTimestampsToUTCCommand will fail on php 5.6

---

eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php

getListCacheValue and getCacheValue is already doing this correct, but in getMultipleCacheValues() cache hits from symfony cache pool is wrongly logged as in-memory cache hits.
**TODO**:

 Fix wrongly logging Cache hits as in-memory in getMultipleCacheValues()

---

eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
eZ/Publish/Core/Persistence/Cache/ContentLanguageHandler.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php

In the end made it optional, but avoid hardcoding __construct() signature in handlers.
**TODO**:

 [AbstractInMemoryHandler] Add a init() method to avoid overloading __construct()

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Repository/LocationService.php

| **JIRA issue**     | [EZP-30300](https://jira.ez.no/browse/EZP-30300)
| **Target version** | `7.4`, `master`
Follow up for https://github.com/ezsystems/ezpublish-kernel/pull/2560. If the first argument of  `\eZ\Publish\API\Repository\LocationService::loadLocationList` contains the id of root location, it will generate `Notice: Undefined offset: 0`in https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Repository/LocationService.php#L250
**TODO**:

EZP-30300: Fixed "Undefined offset: 0" notice when LocationService::loadLocationList is invoked with id of the root location

---

eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractInMemoryCacheHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UserPreferenceHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UserPreferenceHandler.php
eZ/Publish/Core/settings/storage_engines/cache.yml
eZ/Publish/SPI/Persistence/UserPreference/Handler.php

| **JIRA issue**     | [EZP-30340](https://jira.ez.no/browse/EZP-30340)
| **Target version** | `7.5.x`
Does:
- Add cache for lookups of missing preferences (NotFound)
- Makes all preferences lookups also cached in-memory
- Drops cache of preferences count as it does not seem to be used that many places
- _Defintly open for debate, but could not find any heavy use of this _(aka if it's used, it's probably only used on specific page where you list up all preferences only, not on every admin page)_ so felt like we can rather drop it._
**TODO**:

EZP-30340: Add in-memory cache for User Preferences

---

eZ/Publish/Core/Persistence/Cache/InMemory/InMemoryCache.php
eZ/Publish/Core/Persistence/Cache/Tests/InMemory/InMemoryCacheTest.php

| **JIRA issue**     | [EZP-30335](https://jira.ez.no/browse/EZP-30335)
| **Target version** | 7.5.x
This PR changes in-memory cache eviction / vacuumin to LFU approach.
Rationale for doing this in story, but main part of it:
> .. as cache will be added for more objects, and/o for larger installs the default limit of 100 items will be reached rather fast. Effect will be that cache items that are very often requested (especially languages and content types) will be evicted from the cache and will be needed to be re-fetched much more often then needed.
> 
> (...)
> 
> NOTE: The reason why LFU and not LRU is proposed is …

EZP-30335: In-memory cache to clear cache using LFU approach

---

eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php

| **JIRA issue**     | [EZP-30365](https://jira.ez.no/browse/EZP-30365)
| **Bug**| yes
| **Target version** | `7.4`, `master`
For more information please refer to the JIRA ticket. 
This PR covers filtering of missing _reserved characters_ (ref: https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Cache/CacheItem.php#L161).
**TODO**:

EZP-30365: Accessing some invalid links will result in 500 error instead of 404

---

data/mysql/schema.sql
data/update/mysql/dbupdate-7.4.4-to-7.4.5.sql

| **JIRA issue**     | [EZP-29324](https://jira.ez.no/browse/EZP-29324)
| **Target version** | `7.4` and up
From https://github.com/ezsystems/ezpublish-kernel/pull/2495
> Without this fix, `composer ezplatform-install` leads to
```
SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. 
```
**TODO**:

EZP-29324: Limited ezcontentobject_tree_contentobject_id_path_string index column length

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml

| **JIRA issue**     | [EZP-30374](https://jira.ez.no/browse/EZP-30374)
| **Target version** | `7.5 for eZ Platform 2.5`
This PR limits varchar columns lengths which are a part of primary key so they can fit maximum index length when `innodb_large_prefix` is set to `OFF` on MySQL instance (less characters can fit as we've switched to `utf8mb4` (4-bytes-long UTF8 characters)).
Related to tables/columns:
* `ezprest_authcode`.`id`
* `ezprest_token`.`id`
Note: my initial idea to workaround `Doctrine\DBAL\Schema` missing feature of including that length by extending `Schema` is not possible to …

EZP-30374: Limited PK columns lengths to fix max index size limit

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php

| **JIRA issue**     | [EZP-30367](https://jira.ez.no/browse/EZP-30367)
| **Target version** | `7.4` 
https://github.com/ezsystems/ezplatform-admin-ui/pull/936
**TODO**:

EZP-30367: Error: `Location cannot be displayed as it is flagged as invisible.`

---

eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/Persistence/Cache/AbstractHandler.php
eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php

| **JIRA issue**     | [EZP-30475](https://jira.ez.no/browse/EZP-30475)
Changes cache key escape logic to be seperate function to be able to reuse consistently in cases known to maybe contain disallowed characters:
- login name _(e.g. Active directory login names as reported in JITA issue)_
- email addresses
- url
- remote id
**TODO**:

EZP-30475: Escape user login name so domain login names works as intended

---

eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
eZ/Publish/Core/Persistence/Cache/PersistenceLogger.php

| **JIRA issue**     | [EZP-29470](https://jira.ez.no/browse/EZP-29470)
As a developer I want a trace when using Repo/Persistence which more clearly shows which part of my code is triggering the call so I can more easily find it.
Example:
As future improvment, maybe find a way to allow developer to expand trace further himself as long as this does not eat up to much memory.
**TODO**:

EZP-29470: As a developer I want improved trace for all Persistence calls

---

eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php

| **JIRA issue**     | [EZP-30405](https://jira.ez.no/browse/EZP-30405)
On case where user changes email, the cache code failed to clear the cache for lookups by that email.
Given email lookup is essentially a list of objects, this can cause issues for `loadByEmail()` if:
- Cache is warmed up and contains 0 hits
- There is another user with that email already and cache is warmed up with 1 user hit
- _SIDE NOTE: @Plopix I think eZ Core Extra Bundle will fail in this case, [it assumes only one user](https://github.com/lolautruche/EzCoreExtraBundle/blob/master/Security/UserProvider.php#L60 …

EZP-30405: Fixed user load by email if someone changes email to it

---

eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/Resolver/ProxyResolver.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/ProxyResolverTest.php

| **JIRA issue**     | [EZP-30333](https://jira.ez.no/browse/EZP-30333)
| **Target version** | `6.7`/`6.13`/`7.4`/`7.5`/`master`
Please take a look at JIRA ticket for more information. 
**TODO**:

EZP-30333: The host's port is added to image variations URIs when configured through image_host

---

eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
eZ/Publish/Core/Persistence/Cache/Adapter/InMemoryClearingProxyAdapter.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Cache/LocationHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/Adapter/InMemoryClearingProxyAdapterTest.php
eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
eZ/Publish/Core/settings/storage_engines/cache.yml

| **JIRA issue**     | [EZP-30298](https://jira.ez.no/browse/EZP-30298)
Adds in-memory cache for content but with a lower TTL and seperate pool so it does not compete about place with metadata which is tiny bit more long lived. The Symfony cache pool decorator becomes helpful here so cache clearing is always sent to all pools, in-memory or not.
**Description**
This, together with improvements in TagsBundle 3.4 concludes the work on improving caching performance in eZ Platform 2.x for now by also adding in-memory caching for content, locations and content related lookups for url aliases …

EZP-30298: As a Cluster User I want in-memory cache for all content related lookups

---

eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
eZ/Publish/Core/Persistence/Tests/DatabaseConnectionFactory.php
eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
eZ/Publish/Core/settings/tests/integration_legacy.yml
eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml

| **JIRA issue**     | [EZP-30061](https://jira.ez.no/browse/EZP-30061)
| **Related to** | [EZP-29938](https://jira.ez.no/browse/EZP-29938)
| **Requires** | ezsystems/doctrine-dbal-schema#1
| **Target version** | `7.5 (master)` for eZ Platform `v2.5 LTS`
This PR changes the way Repository integration test schema is built to use `SchemaImporter` from [`ezsystems/doctrine-dbal-schema`](https://gitub.com/ezsystems/doctrine-dbal-schema). It re-uses `schema.yaml` used by eZ Platform installer. While disadvantage is it creates more tables (once on all tests startup), we can at least be sure …

EZP-30061: Created integration tests schema using Schema Importer

---

doc/bc/changes-7.4.md
eZ/Publish/Core/FieldType/RichText/Converter.php
eZ/Publish/Core/FieldType/RichText/Converter/Aggregate.php
eZ/Publish/Core/FieldType/RichText/Converter/Link.php
eZ/Publish/Core/FieldType/RichText/Converter/ProgramListing.php
eZ/Publish/Core/FieldType/RichText/Converter/Render.php
eZ/Publish/Core/FieldType/RichText/Converter/Render/Embed.php
eZ/Publish/Core/FieldType/RichText/Converter/Render/Template.php
eZ/Publish/Core/FieldType/RichText/Converter/Xslt.php
eZ/Publish/Core/FieldType/RichText/ConverterDispatcher.php
eZ/Publish/Core/FieldType/RichText/CustomTagsValidator.php
eZ/Publish/Core/FieldType/RichText/InternalLinkValidator.php
eZ/Publish/Core/FieldType/RichText/Normalizer.php
eZ/Publish/Core/FieldType/RichText/Normalizer/Aggregate.php
eZ/Publish/Core/FieldType/RichText/Normalizer/DocumentTypeDefinition.php
eZ/Publish/Core/FieldType/RichText/README.md
eZ/Publish/Core/FieldType/RichText/RendererInterface.php
eZ/Publish/Core/FieldType/RichText/RichTextStorage/Gateway.php
eZ/Publish/Core/FieldType/RichText/SearchField.php
eZ/Publish/Core/FieldType/RichText/Type.php
eZ/Publish/Core/FieldType/RichText/Validator.php
eZ/Publish/Core/FieldType/RichText/ValidatorDispatcher.php
eZ/Publish/Core/FieldType/RichText/Value.php
eZ/Publish/Core/FieldType/RichText/XmlBase.php

| **JIRA issue**     | [EZP-30281](https://jira.ez.no/browse/EZP-30281)
| **Target version** | `7.4`
`eZ\Publish\Core\FieldType` has been deprecated since eZ Platform 2.4, when we introduced [RichTextBundle](https://github.com/ezsystems/ezplatform-richtext), but I've forgotten to add proper deprecation notices.
I can't find this information explicitly available, so maybe we need to add a note saying that 
> Relying on any class from the `eZ\Publish\Core\FieldType` namespace is deprecated.
> If you're implementing any interface or extending any base class from that namespace, refer to its …

EZP-30281: Added deprecation info to Core RichText FT namespace

---

eZ/Publish/Core/Persistence/Tests/DatabaseConnectionFactory.php

| **JIRA issue**     | n/a, follow-up for #2548 
| **Requires** | ezsystems/doctrine-dbal-schema#5
The event subscriber enabling foreign keys for Sqlite is unfortunately always added which causes warnings (this is why I didn't spot this earlier) when executing tests using SchemaImporter. 
It also causes [failures](https://travis-ci.org/ezsystems/ezplatform-richtext/jobs/521305165#L664) in our other repositories relying on these tests, which was visible only after merging.
This is a result of tagging every instance of `DbPlatform` and injecting a list. At …

[Tests] Called DbPlatform::addEventSubscribers prior to connecting

---

doc/bc/changes-7.5.md
eZ/Publish/API/Repository/PermissionResolver.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/BaseLimitationIntegrationTest.php
eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/ContentLimitationsMixIntegrationTest.php
eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/LanguageLimitationIntegrationTest.php
eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
eZ/Publish/API/Repository/Values/User/LookupLimitationResult.php
eZ/Publish/API/Repository/Values/User/LookupPolicyLimitations.php
eZ/Publish/Core/Limitation/LanguageLimitationType.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
eZ/Publish/Core/Repository/Permission/PermissionResolver.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/settings/roles.yml
eZ/Publish/SPI/Limitation/Target.php
eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
eZ/Publish/SPI/Limitation/Target/Version.php
eZ/Publish/SPI/Limitation/TargetAwareType.php
eZ/Publish/SPI/Tests/Limitation/Target/Builder/VersionBuilderTest.php
phpunit-integration-legacy.xml

| **JIRA issue**     | [EZP-30344](https://jira.ez.no/browse/EZP-30344)
| **Required by** | ezsystems/ezplatform-admin-ui#934
| **Target version** | `7.5.1` for eZ Platform `2.5.1 LTS`
| **BC breaks**      | yes, minor (see JIRA issue)
This PR:
Squashed into one PR due to time constraints.
Many Limitations throw exception when dealing with unknown objects or targets, which makes it impossible to set some specific mixes of Limitations on a given policy. This had hit us in the past and now makes current changes impossible to implement.
To solve this issue we're introducing two new interfaces:
We've created the …

EZP-30344: Allowed limiting Content management to specific translations

---

.travis.yml
composer.json

| **Bug/Improvement**| n/a
| **New feature**    | n/a
| **Target version** | 6.7 and 6.13, not applicable for higher versions
Some jobs for 6.13 branch are failing by exceeding Composer's memory limits, see: https://travis-ci.org/ezsystems/ezpublish-kernel/builds/521932866
Bumping the minimal required Symfony version should do the trick, as it makes Composer's job easier when it comes to resolving dependencies. Using latest values from 2.x and 3.x releases: https://github.com/symfony/symfony/releases

Bumped minimal Symfony version to reduce Composer's work

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php

| **Target version** | `7.5` and `master`
Fixed SOLR integration tests with dedicated cores setup which fails on `ContentServiceTest::testCopyTranslationsFromPublishedToDraft`, because of endpoint mapping for `fre-FR` language is missing. See: https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/jobs/524875041#L966
The following line  https://github.com/ezsystems/ezpublish-kernel/blob/a708aa8181516eca59bace9cc7a93af5fd8e8e6c/eZ/Publish/API/Repository/Tests/ContentServiceTest.php#L6595  is a redundant step: so getting rid of it will also simplify test. …

Fixed SOLR integration tests with dedicated cores setup fails on ContentServiceTest::testCopyTranslationsFromPublishedToDraft

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

| **JIRA issue**     | [EZP-30504](https://jira.ez.no/browse/EZP-30504)
| **Target version** | 7.x
The blank space in the twig template after each img attr makes w3c output some error. fix is quite simple, just delete the space there. 
ping @andrerom @lserwatka

EZP-30504: Removed trailing space from img attributes

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

See https://jira.ez.no/browse/EZP-29865
If we are trying to output an ezxml field from an object within an ezpage block template override and the ezxml content is something like:
```
<emphasize>second</emphasize> <strong>paragraph</strong>
```
And then we define a template like this:
```
block_view:
BannerCarouselBlock:
controller: "MarigoldBaseBundle:EzFlowBlocks:bannerCarousel"
template: "@ezdesign/blocks/banner_carousel.html.twig"
match:
Type: banner_carousel
```
And try to output the ezxml content, the {% spaceless %} twig operator in content_fields.html.twig will make the output become secondparagraph instead of second paragraph.
It is necessary to remove that operator and the developer should specify it by himself.

EZP-29865: Removed spaceless Twig tag from ezpage_field block

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
eZ/Publish/Core/settings/storage_engines/cache.yml

| **JIRA issue**     | [EZP-30546](https://jira.ez.no/browse/EZP-30546)
Cache service being in wrong instance seems to be caused by a few things:
- Changes in 2.5 where `ezplublish.cache_pool.inner` service was introduced ( 8baa4f4bdb37be39d9477405d1d7c385a4d02d0f) seems to cause it to no longer be lazy loaded.
- I'm actually a bit unsure why, however opted to move lazy definition to same as had this before: `ezpublish.cache_pool`. 
- The loading was caused by command services that rely on repo services, these are loaded long before console event is triggered and siteaccess is set. To …

EZP-30546: Cache service has wrong instance on command line

---

appveyor.yml

| **Target version** | `6.7`, `7.4`, `7.5`, `master`
My attempts to setup Travis for Windows testing seems to be pointless, because php is not supported directly with windows there and also it's not possible to prepare uniform travis.yml nor to launch test matrix for alternative `.travis.yaml` (AFAICS).
So for now we need to stick to AppVeyor unfortunately.
This PR:
**TODO**:

[CI] Fixed AppVeyor memory issues

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalAnd.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOperator.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOr.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalAndTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOrTest.php

| **JIRA issue**     | [EZP-30027](https://jira.ez.no/browse/EZP-30027)
| **Target version** | 6.7
**TODO**:

EZP-30027: [REST] Fixed logical op. parsing for Criterions of the same type

---

eZ/Publish/Core/SignalSlot/Signal.php
eZ/Publish/Core/SignalSlot/Slot.php

| **JIRA issue**     | [EZP-28135](https://jira.ez.no/browse/EZP-28135)
This class has been used by other packages for ages so this removes some deprecation notices from the logs.
**TODO**:

EZP-28135: Removed @internal tag from SignalSlot classes

---

.travis.yml
eZ/Bundle/EzPublishCoreBundle/Features/Content/content_preview.feature
eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentPreviewContext.php

| **JIRA issue**     | Follow up to https://jira.ez.no/browse/EZP-29858
| **Target version** | master (3.0)
In https://jira.ez.no/browse/EZP-29858 I've been refactoring BehatBundle (and it's usage in Kernel) and missed that changes are required to these tests (making them broken in the process).
Failing on master: https://travis-ci.org/ezsystems/ezplatform/jobs/533048313
Passing on 2.5: https://travis-ci.org/ezsystems/ezplatform/jobs/532772906
This PR contains two changes:
1) Adds execution of Core Kernel suite to Travis matrix - up to discussion, it's currently executed on `ezplatform` …

EZP-29858: Fix broken Core tests

---

composer.json

| **Target version** | `6.7`, `6.13`, done in `7.x` via #2247
Looks like this is a follow up for #2247.
Quick grep looking for `org\bovigo` namespace registered by the `mikey179/vfsStream` package tells me it's not used anymore even in `6.7`. It's also a require-dev dependency, so it seems safe to drop it completely.
The reason for doing it for all supported branches also is that it shows deprecation error on every install:
```
Deprecation warning: require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use …
```

[Composer][6.7] Dropped mikey179/vfsStream from dev dependencies

---

eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/Resolver/RelativeResolver.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Publish/Core/settings/storage_engines/cache.yml

| **JIRA issue**     | [EZP-30546](https://jira.ez.no/browse/EZP-30546)
This fixes warnings that will show up in EE 1.7 once #2636 is merged.
TL;DR; Commands are loaded to get their name long before siteaccess event is fired, so they have services with wrong SA settings injected.
Partly replaces #2634 with aim to have fix for all branches, and w/o having to rely on lazy commands unless needed _(remaining cases will be commands directly or indirectly relying on config resolver in ctor/configure/init, @alongosz should be happy :) )_.
**TODO**:

EZP-30546: Several core services risks having wrong instance due to early config resolver use

---

eZ/Bundle/EzPublishCoreBundle/EventListener/PreviewRequestListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php

| **JIRA issue**     | [EZP-30508](https://jira.ez.no/browse/EZP-30508)
| **Bug**| yes
This PR fixes 500 being thrown when previewing content that requests hidden content in its template. More in JIRA issue.
**TODO**:

EZP-30508: Fixed Exception being thrown when previewing

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php

| **JIRA issue**     | [EZP-25721](https://jira.ez.no/browse/EZP-25721)
| **BC breaks**      | _Aiming for no_
Detect if parameters are read before siteaccess has been initialized, and warn developer about unsafe usage of this to avoid very hard to debug issues.
*WARNING*: For class based services, will currently warm even when service is what DynamicSettingsListener considers as $updatableServices which is safe. So might warn for cases where we don't need to warn as system is able to update value inline _(when setter is used)_.
**TODO**:

EZP-25721: Warn development upfront of ConfigResolver initialization order issues

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Signal/ContentService/PublishVersionSignal.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
eZ/Publish/Core/settings/storage_engines/legacy/content.yml

| **JIRA issue**     | [EZEE-2661](https://jira.ez.no/browse/EZEE-2661)
| **Target version** | `7.5` (`2.5.1`)
As a part of fix, we decided to add possibility to publish specific translations only.
As it seems more clearer now, I have decided to move previous logic from Handler inside ContentService and resolve it on API level.
**TODO**:

EZEE-2661: Allowed translation filtering when publishing version

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php

| **JIRA issue**     | [EZP-30573](https://jira.ez.no/browse/EZP-30573)
| **Target version** | `7.5`/`master`
This PR introduces the new `$status` argument for `ContentService::loadVersions` method.
For more information please refer to JIRA ticket. 
**TODO**:

EZP-30573: As a Developer I want to filter by status when using ContentService::loadVersions method

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

| **JIRA issue**     | [EZP-30635](https://jira.ez.no/browse/EZP-30635)
When content-count % iteration-count === 0, aka when last iteration would have empty results, there would be faulty call to with empty ´--content-ids=´ causing whole new index process to start again with purge and everything.
**TODO**:

EZP-30635: Fixed infinite loop in Reindex Command on the last iteration

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php

| **JIRA issue**     | [EZP-25721](https://jira.ez.no/browse/EZP-25721)
| **Doc needed**     | yes _for the warning message example_
_Updated on 4th of June:_ Followup on #2636
Improves output to show what might be more relevant blame for the eager loading, the first service triggering the load _(last in trace)_, command name if detected, and swaps the order to rather output params per blame found instead of opposite to produce less bloated output.
Gives the following output on 2.5-dev (EE):
> 19:46:46 WARNING   [app] ConfigResolver was used by "@ezpublish.helper.language_resolver" before SiteAccess was …

EZP-25721: Improve warning on config resolver eager loading to show more clear blame

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml

| **JIRA issue**     | [EZP-30643](https://jira.ez.no/browse/EZP-30643)
| **Target version** |`master` 
fixes configuration
**TODO**:

EZP-30643: Images are stored under wrong path

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/DataAttributesExtensionTest.php
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/filters/ez_data_attributes_serialize.test
eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/DataAttributesExtension.php

| **JIRA issue**     | [EZP-29301](https://jira.ez.no/browse/EZP-29301)
| **Required by** | ezsystems/ezplatform-richtext#39
| **Target version** | `7.5.2` for eZ Platform `v2.5.2 LTS`
| **Doc needed**     | ezsystems/developer-documentation#633
As a result of QA we found out that custom classes and data attributes set in OE are not rendered on the output (front SiteAccess). This is because `embed(inline)` elements are handled completely different, via `viewAction` subrequest.
This PR:
For the input:
```php
[
'my-attr1' => 'value1',
'my-attr2' => 'value2,value3',
]
```
we get
```
data-my-attr1="value1" …
```

EZP-29301: Added class and data attributes support for embed(inline)

---

.php_cs
.travis.yml
composer.json
eZ/Bundle/EzPublishCoreBundle/Command/DebugConfigResolverCommand.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/Core/FieldType/RichText/Converter/Link.php
eZ/Publish/Core/MVC/Symfony/Matcher/MatcherInterface.php
eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
eZ/Publish/Core/Search/Elasticsearch/Content/SortClauseVisitor/Field/MapLocationDistance.php

| **Target version** | `6.7`, `6.13`, `7.4`, `7.5`, `master`
This PR
As a follow-up there will be a PR adding Code Style check via Travis job, which will depend on these changes.
**TODO**:

[CS] Bumped php-cs-fixer to v2.15.0

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPass.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Publish/Core/Base/Container/Compiler/FieldTypeCollectionPass.php
eZ/Publish/Core/Base/Container/Compiler/Search/FieldRegistryPass.php
eZ/Publish/Core/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
eZ/Publish/Core/Base/Tests/Container/Compiler/FieldTypeCollectionPassTest.php
eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPassTest.php
eZ/Publish/Core/settings/fieldtypes.yml
eZ/Publish/Core/settings/indexable_fieldtypes.yml
eZ/Publish/Core/settings/richtext/fieldtypes.yml
eZ/Publish/Core/settings/richtext/indexable_fieldtypes.yml
eZ/Publish/Core/settings/richtext/storage_engines/legacy/field_value_converters.yml
eZ/Publish/Core/settings/search_engines/common.yml
eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml

| **JIRA issue**     | [EZP-30462](https://jira.ez.no/browse/EZP-30462)
Tags used to register Field Type features in the dependency injection container should be consistent and follow Symfony convention (snake case)
```
ezpublish.fieldType => ezplatform.field_type
ezpublish.fieldType.indexable => ezplatform.field_type.indexable
ezpublish.storageEngine.legacy.converter => ezplatform.field_type.legacy_storage.converter
ezpublish.fieldType.parameterProvider => ezplatform.field_type.parameter_provider
ezpublish_rest.field_type_processor => …
```

EZP-30462: Unified Field Type service tag names

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/Matcher/ClassNameMatcherFactory.php
eZ/Publish/Core/MVC/Symfony/Matcher/ConfigurableMatcherFactoryInterface.php
eZ/Publish/Core/MVC/Symfony/Matcher/DynamicallyConfiguredMatcherFactoryDecorator.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/DynamicallyConfiguredMatcherFactoryDecoratorTest.php

| **JIRA issue**     | [EZP-30647](https://jira.ez.no/browse/EZP-30647)
| **Bug/Improvement**| bug
Due to Dynamic Settings being partially broken in Symfony 4, this fixes related content preview issue by using ConfigResolver. View matching configuration is fetched before matching operation.
**TODO**:

EZP-30647: Refactored View Matcher Factory to use ConfigResolver

---

eZ/Publish/Core/FieldType/FieldType.php

| **JIRA issue**     | [EZP-30457](https://jira.ez.no/browse/EZP-30457)
| **Doc needed**     |  no
Method `eZ\Publish\Core\FieldType\FieldType::getSortInfo` should be implemented by Developer only if the FT is sortable.  
Currently, the default implementation throws a `RuntimeException:  "Not implemented, yet."`.  Usually, the developer figures out that something is missing on the first try of adding FT to the CT ...
**TODO**:

EZP-30457: FieldType::getSortInfo should be implemented by impl. only if the FT is sortable

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Bundle/EzPublishCoreBundle/SiteAccess/LanguageResolver.php
eZ/Publish/API/Repository/LanguageResolver.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
eZ/Publish/Core/Repository/SiteAccessAware/Language/AbstractLanguageResolver.php
eZ/Publish/Core/Repository/SiteAccessAware/Language/LanguageResolver.php
eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php
eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/Language/LanguageResolverTest.php
eZ/Publish/Core/Repository/SiteAccessAware/URLAliasService.php
eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
eZ/Publish/Core/settings/repository/siteaccessaware.yml

| **JIRA issue**     | [EZP-30629](https://jira.ez.no/browse/EZP-30629)
| **Requires** | #2676
| **Target version** | `7.5` for eZ Platform `v2.5`, compatible with eZ Platform `v3.0`
| **BC breaks**      | TBD
This PR:
This PR fixes a few issues with LanguageResolver across Core and Bundle layer.
First of all we needed to get rid of injecting dynamic setting (`$languages$`) too early to avoid injecting them from unresolved SiteAccess scope.
On the other hand, we're forced to drop dynamic settings due to changes to Symfony Container in Symfony 4.x, so here we should inject ConfigResolver instead.
I've discovered a …

EZP-30629: Injected ConfigResolver into LanguageResolver

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml

| **JIRA issue**     | [EZP-30699](https://jira.ez.no/browse/EZP-30699)
| **Requires** | <ul><li>ezsystems/ezplatform-admin-ui#1026</li><li>#2662</li></ul>
| **Target version** | `7.5` for eZ Platform `v2.5.2 LTS`
when executing
```
php bin/console bazinga:js-translation:dump web/assets --merge-domains
```
which is triggered both by `composer install` and `composer update`, we get the following warning:
```
WARNING   [app] ConfigResolver was used by "@twig" before SiteAccess was initialized, loading parameter(s) "$io.binarydata_handler$", "$fieldtypes.ezimageasset.mappings$", …
```

EZP-30699: Made image rendering services used by Twig extensions lazy

---

.travis.yml
bin/.travis/check_code_style.sh
bin/.travis/prepare_unittest.sh

| **Requires** | #2647
| **Target version** | `6.7`, `6.13`, `7.4`, `7.5`, `master`
This PR:
The CS job checks only PHP files modified in a PR.
It has been successfully tested via #2681 - ref. [failing build](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/551807410).
**TODO**:

[CS][Travis] Added Code Style checking job to Travis

---

.php_cs
eZ/Publish/API/Repository/Repository.php

| **JIRA issue**     | [EZP-30696](https://jira.ez.no/browse/EZP-30696)
Current implementation forces descendants to change typehint to `Repository` interface. While it works (because descendants inherits Repository anyway), `self` is invalid in this context. `self` should be used only in case of indicating self-referenced instances, and not for typehinting current interface.
**TODO**:

EZP-30696: Changed Repository::sudo typehint form self to Repository

---

eZ/Publish/Core/Repository/Helper/RelationProcessor.php

Fixed imports in `\eZ\Publish\Core\Repository\Helper\RelationProcessor`: `eZ\Publish\SPI\FieldType\Value` should be used instead of `eZ\Publish\Core\FieldType\Value`.
**TODO**:

Fixed incorrect Value class import in RelationProcessor

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php

This PR refactors tests to get rid of some left-over PHPUnit 8.x deprecation warnings.
Handled the following deprecated warnings:
**TODO**:

[Tests] Fixed PHPUnit 8.x deprecated assertions warnings

---

eZ/Publish/API/Repository/Values/Content/Field.php

| **Target version** | 6.7
PHPStan Error:
```
Access to protected property                             
eZ\Publish\API\Repository\Values\Content\Field::$value.
```

Missing property type in Field DocBlock

---

eZ/Bundle/EzPublishCoreBundle/Console/Application.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ConsoleCommandListener.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConsoleCommandListenerTest.php
eZ/Publish/Core/MVC/Symfony/Event/ConsoleInitEvent.php
eZ/Publish/Core/MVC/Symfony/MVCEvents.php

| **JIRA issue**     | [EZP-30722](https://jira.ez.no/browse/EZP-30722)
| **Bug**| yes
This fixes the root issue of siteaccess being set after commands are loaded when you run them.
Implies some of the fixes done on 2.5.2 can be reverted, specifically: 
- The once making services lazy _can_ be omitted. 
- Maybe also the once making commands lazy
Changes to drop use of dynamic settings _should_ probably stay as it makes the code more bullet proof also for request scope cases of this, and it aligns code with v3.
**TODO**:

EZP-30722: Make sure siteaccess is loaded before console commands on run

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php

| **JIRA issue**     | [EZP-2572](https://jira.ez.no/browse/EZP-2572)
Previous PR changed the logic to show last service to be able to show command name, however it makes it hard to read the error.
Now it becomes:
> 13:42:38 WARNING   [app] ConfigResolver was used by "Console_Command_EzsystemsEzplatformgraphqlCommandGenerateplatformschemacommand(@ezpublish.siteaccessaware.service.content_type) -> @ezpublish.helper.language_resolver" before SiteAccess was initialized, loading parameter(s) "$languages$". As this can cause very hard to debug issues, try to use ConfigResolver lazily, make …

EZP-25721: Return to show first service name in resolver warning

---

doc/specifications/security/authentication_symfony.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/ViewbaseLayout.php

| **JIRA issue**     | [EZP-30503](https://jira.ez.no/browse/EZP-30503)
https://github.com/ezsystems/ezpublish-kernel/pull/2629 was incomplete. Default value for `page_layout` parameter did not exist.
**TODO**:

EZP-30503: Fixed missing default value for the new page_layout parameter

---

eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/ExternalStorageRegistryPassTest.php
eZ/Publish/Core/settings/fieldtype_external_storages.yml
eZ/Publish/Core/settings/richtext/fieldtype_external_storages.yml

| **JIRA issue**     | [EZP-30745](https://jira.ez.no/browse/EZP-30745)
| **Target version** |`master`
Follow up for #2653: 
* `ezpublish.fieldType.externalStorageHandler` has been deprecated in favour of `ezplatform.field_type.external_storage_handler`
* `ezpublish.fieldType.externalStorageHandler.gateway` has been deprecated in favour of `ezplatform.field_type.external_storage_handler.gateway`
**TODO**:

EZP-30745: Introduced new names for External Storage service tags

---

data/update/mysql/dbupdate-7.5.2-to-7.5.3.sql
data/update/postgres/dbupdate-7.5.2-to-7.5.3.sql
eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml

| **JIRA issue**     | [EZP-30571](https://jira.ez.no/browse/EZP-30571)
| **Bug**| yes
This PR increases `data_text1` column length to 255 characters in `ezcontentclass_attribute` table. For more information please refer to mentioned JIRA ticket. 
**TODO**:

EZP-30571: Legacy storage column size for default TextField value is too short

---

data/update/mysql/dbupdate-7.5.3-to-8.0.0.sql
data/update/mysql/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql
data/update/postgres/dbupdate-7.5.3-to-8.0.0.sql
data/update/postgres/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql

| **JIRA issue**     | [EZP-30571](https://jira.ez.no/browse/EZP-30571)
| **Bug**| yes
Follow-up for https://github.com/ezsystems/ezpublish-kernel/pull/2702 against `8.0`. For more information please refer to the original PR. 
**TODO**:

[8.0] EZP-30571: Legacy storage column size for default TextField value is too short

---

eZ/Publish/API/Repository/Tests/Regression/EnvTest.php
eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
eZ/Publish/Core/Persistence/Cache/AbstractInMemoryPersistenceHandler.php
eZ/Publish/Core/Persistence/Cache/Adapter/TransactionAwareAdapterInterface.php
eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalCacheAdapterDecorator.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractCacheHandlerTest.php
eZ/Publish/Core/Persistence/Cache/Tests/TransactionHandlerTest.php
eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
eZ/Publish/Core/settings/storage_engines/cache.yml

| **JIRA issue**     | [EZP-30721](https://jira.ez.no/browse/EZP-30721)
| **Bug/Improvement**| bug
This is a solution proposed by Andre in https://jira.ez.no/browse/EZP-30721. It waits with tags invalidation and items deletion until transaction is finished.
**TODO**:

EZP-30721: Implemented deferred tags invalidation and items deletion for transactions

---

eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
eZ/Publish/Core/Limitation/SubtreeLimitationType.php
eZ/Publish/Core/Repository/Permission/PermissionResolver.php

| **JIRA issue**     | [EZP-30697](https://jira.ez.no/browse/EZP-30697)
| **Bug**| yes
If policy has no limitation and role assignment has limitation incorrect result of hasAccess method was returned. If the limitation is met there is no need to check if policy limitations array is not empty.
Related PR:
- https://github.com/ezsystems/ezplatform-admin-ui/pull/1039
**TODO**:

EZP-30697: Fixed content creation under subtree when assignment limitation is used

---

eZ/Publish/API/Repository/Tests/PermissionResolverTest.php

Fixed test which fails on PostgreSQL because it depends on items order in array of expected Policies. In reference to https://jira.ez.no/browse/EZP-30697
**TODO**:

Fixed test which fails on PostgreSQL because it depends on items order

---

eZ/Publish/API/Repository/ContentTypeService.php
eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/Core/REST/Client/ContentTypeService.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
eZ/Publish/Core/SignalSlot/ContentTypeService.php
eZ/Publish/Core/SignalSlot/Tests/ContentTypeServiceTest.php

| **JIRA issue**     | [EZP-30724](https://jira.ez.no/browse/EZP-30724)
Allowed to load content type draft owned by any user via API
**TODO**:

EZP-30724: Allowed to load content type draft owned by any user via API

---

eZ/Publish/API/Repository/SectionService.php
eZ/Publish/API/Repository/Tests/SectionServiceAuthorizationTest.php
eZ/Publish/Core/REST/Client/SectionService.php
eZ/Publish/Core/Repository/SectionService.php
eZ/Publish/Core/SignalSlot/SectionService.php

| **JIRA issue**     | [EZP-30753](https://jira.ez.no/browse/EZP-30753)
Changed `loadSection()` method to filter the available sections and not throw an exception when the user has no permission to all sections. This change is needed to allow display user a list of section available to him in the administration panel.
**TODO**:

EZP-30753: Changed loadSections method to filter available sections

---

.travis.yml
bin/.travis/prepare_unittest.sh

| **Target version** | `7.5` and `master (8.0)`
According to the doc [we require at least MySQL 5.7](https://doc.ezplatform.com/en/2.5/getting_started/requirements/#recommended-setups) in version 2.5, so we should align that on Travis as well.
The background reason for this change is faulty default configuration of MySQL 5.6 which leads to unsolvable otherwise false negative test results in #2621.
`Xenial` supports MySQL 5.7 out of the box, so we've decided to bump entire dist. `Trusty` is quite old, so it's the highest time.
**TODO**:

[Travis] Bumped dist to Xenial to use MySQL 5.7

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Security/PolicyProvider/PolicyProviderInterface.php

| **JIRA issue**     | none
| **Target version** | `master` for features
This PR removed return from PHP Doc comment. Implementation expects `ConfigBuilderInterface` argument to be updated, instead of returning an array with policies.

Removed wrong return doc

---

eZ/Publish/API/Repository/Tests/PermissionResolverTest.php

| **JIRA issue**     | [N/A]
Because we want to get the first element of the array and `array_filter` preserve keys we can not get the first element by `[0]`. See [travis](https://travis-ci.org/ezsystems/ezpublish-kernel/jobs/565253192)
**TODO**:

Fixed random error during the test with PostgreSQL

---

eZ/Publish/Core/SignalSlot/Signal/ContentService/TranslateVersionSignal.php

As in the title, moved to the right block.

TranslateVersionSignal has @deprecated tag in wrong DocBlock

---

composer.json
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default_inline.html.twig
eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig

| **JIRA issue**     | https://jira.ez.no/browse/EZP-30814
* `spaceless` tag was deprecated in favor of `spaceless` filter recently. This uses the `apply` tag added in Twig 2.9 to apply the filter to chunks of markup instead of using the tag.
* `for ... if` is deprecated since Twig 2.10
**TODO**:

Remove Twig deprecations

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Publish/Core/settings/containerBuilder.php
eZ/Publish/Core/settings/repository/autowire.yml
eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php

| **JIRA issue**     | [EZP-29386](https://jira.ez.no/browse/EZP-29386)
| **Doc needed**     | could improve DX
This PR adds Repository API service aliases to simplify autowiring.
We already use this feature in at least two `EzPublishCoreBundle` commands, thus it is considered to be a bug. It works because these aliases are defined in AdminUI which is a flaw in the architecture.
**TODO**:

EZP-29386: Added FQCN-named Repository services to simplify autowiring

---

eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php

| **JIRA issue**     | [EZP-30817](https://jira.ez.no/browse/EZP-30817)
The ezplatform:timestamps:to-utc command doesn't respect the primary keys of ezcontentobject_attribute table and writes field values in all versions. So the times are not correct after update

EZP-30817: Fixed ezplatform:timestamps:to-utc cmd to respect version no.

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
eZ/Publish/Core/Repository/UserService.php

| **JIRA issue**     | [EZP-30807](https://jira.ez.no/browse/EZP-30807)
When a user has `administrator` access but limited do subtree of Users, he is unable to enter Users tab in the Admin section in the top menu. This is because we try to load the parent location in method `buildDomainUserGroupObject`. ~~We can catch `APIUnauthorizedException` and set `parentId` to null because `parentId` in `UserGroup` is nullable and in existed code when we can not access parent location we set `null`~~ We are using a locationHandler to load the Location without checking …

Fixed error when building UserGroup when a user has no access to a parent location

---

eZ/Bundle/EzPublishCoreBundle/EventListener/ConsoleCommandListener.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php
eZ/Publish/Core/Helper/ContentPreviewHelper.php
eZ/Publish/Core/Helper/Tests/ContentPreviewHelperTest.php
eZ/Publish/Core/MVC/Symfony/EventListener/SiteAccessMatchListener.php
eZ/Publish/Core/MVC/Symfony/EventListener/Tests/SiteAccessMatchListenerTest.php
eZ/Publish/Core/MVC/Symfony/Routing/Generator/RouteReferenceGenerator.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/RouteReferenceGeneratorTest.php
eZ/Publish/Core/MVC/Symfony/Security/EventListener/SecurityListener.php
eZ/Publish/Core/MVC/Symfony/View/Manager.php
eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/EventDispatcherInjector.php
eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php
eZ/Publish/Core/MVC/Symfony/View/Tests/Renderer/TemplateRendererTest.php

| **JIRA issue**     | [EZP-30812](https://jira.ez.no/browse/EZP-30812)
Fixed the following deprecation message:
```
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
```
by swapping argument order in  `Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()` method calls.  
**TODO**:

EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml

| **JIRA issue**     | [EZP-30819](https://jira.ez.no/browse/EZP-30819)
Referencing controllers with `<Bundle>:<Controller>:<Action>` syntax (aka bundle notation) is deprecated since Symfony 4.1  and generate the following log entries:
```
[2019-08-05 19:39:35] php.INFO: User Deprecated: Referencing controllers with FrameworkBundle:Redirect:redirect is deprecated since Symfony 4.1, use "Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing …
```

EZP-30819: Removed deprecated controller references from routes definitions

---

eZ/Publish/API/Repository/Tests/URLServiceAuthorizationTest.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UrlTest.php
eZ/Publish/Core/Repository/URLService.php

| **JIRA issue**     | [EZP-30821](https://jira.ez.no/browse/EZP-30821)
Fix wrong usage of hasAccess() in repository in favor of canUser(). This is needed to solve an issue when there is a Role Assignment Limitation. In this case, they will return info to permission system they abstain from "voting" and return an array of Limitations.
Methods in `URLService` that threw an exception, but now filter list of returned objects:
- findUrls
**TODO**:

EZP-30821: Fixed wrong usage of hasAccess in URLService

---

eZ/Bundle/EzPublishCoreBundle/Composer/ScriptHandler.php

| **Doc needed**     | _maybe_
We had a case where a developer tried to use `server:run` for remote dev server.
This tries to avoid such misunderstandings by:
- mentioning it's local only
- expand on what it is, and its limitations so new devs can better make judgment of when to use it and not.
Also expand on what the alternative specifically is, as most have heard about Nginx/Apache.
**TODO**:

[Composer] Improve install instructions on install splash screen

---

eZ/Publish/API/Repository/RoleService.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/RoleServiceAuthorizationTest.php
eZ/Publish/Core/REST/Client/RoleService.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RoleTest.php
eZ/Publish/Core/SignalSlot/RoleService.php

| **JIRA issue**     | [EZP-30808](https://jira.ez.no/browse/EZP-30808)
Fix wrong usage of hasAccess() in repository in favor of canUser(). This is needed to solve an issue when there is a Role Assignment Limitation. In this case, they will return info to permission system they abstain from "voting" and return an array of Limitations.
Methods in `RoleService` that threw an exception, but now filter list of returned objects:
- loadRoles
- getRoleAssignmentsForUser
- getRoleAssignmentsForUserGroup
**TODO**:

EZP-30808: Fixed wrong usage of hasAccess in RoleService

---

eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/Core/Repository/TrashService.php

| **JIRA issue**     | [EZP-30831](https://jira.ez.no/browse/EZP-30831)
Fix wrong usage of hasAccess() in repository. This is needed to solve an issue when there is a Role Assignment Limitation. In this case, they will return info to permission system they abstain from "voting" and return an array of Limitations. 
To avoid enforce an administrator to create dedicated Role only to allow empty the Trash an exception will be returned only when the user has no access to perform this action.
**TODO**:

EZP-30831: Fixed wrong usage of hasAccess in TrashService

---

eZ/Publish/API/Repository/Tests/URLAliasServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
eZ/Publish/Core/Repository/URLAliasService.php

| **JIRA issue**     | [EZP-30822](https://jira.ez.no/browse/EZP-30822)
Fix wrong usage of hasAccess() in repository in favor of canUser(). This is needed to solve an issue when there is a Role Assignment Limitation. In this case, they will return info to permission system they abstain from "voting" and return an array of Limitations.
**TODO**:

EZP-30822: Fixed wrong usage of hasAccess in URLAliasService

---

eZ/Publish/API/Repository/Tests/URLWildcardServiceAuthorizationTest.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
eZ/Publish/Core/Repository/URLWildcardService.php

| **JIRA issue**     | [EZP-30832](https://jira.ez.no/browse/EZP-30832)
Fix wrong usage of hasAccess() in repository. This is needed to solve an issue when there is a Role Assignment Limitation. In this case, they will return info to permission system they abstain from "voting" and return an array of Limitations.
**TODO**:

EZP-30832: Fixed wrong usage of hasAccess in URLWildcardService

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php

| **JIRA issue**     | [EZP-30515](https://jira.ez.no/browse/EZP-30515) (private)
| **Target version** | 7.5
| **BC breaks**      | maybe?
| **Tests pass**     | yes, with https://github.com/ezsystems/ezplatform/pull/435
https://github.com/ezsystems/ezplatform/pull/435 enables CSRF token in login forms by default. This is a publicly known security issue which isn't merged yet due to a problem with kernel tests, but users have been warned to enable it. This kernel PR fixes the test.
https://share.ez.no/community-project/security-advisories/ezsa-2019-004-csrf-token-in-login-form-is-disabled-by-default
⚠ SessionTest will fail here, but passes …

Enable CSRF token in login form by default

---

eZ/Publish/Core/MVC/Symfony/Event/APIContentExceptionEvent.php
eZ/Publish/Core/MVC/Symfony/Event/ContentCacheClearEvent.php
eZ/Publish/Core/MVC/Symfony/Event/PostSiteAccessMatchEvent.php
eZ/Publish/Core/MVC/Symfony/Event/PreContentViewEvent.php
eZ/Publish/Core/MVC/Symfony/Event/RouteReferenceGenerationEvent.php
eZ/Publish/Core/MVC/Symfony/Event/ScopeChangeEvent.php
eZ/Publish/Core/MVC/Symfony/View/Event/FilterViewBuilderParametersEvent.php
eZ/Publish/Core/MVC/Symfony/View/Event/FilterViewParametersEvent.php

| **JIRA issue**     | [EZP-30828](https://jira.ez.no/browse/EZP-30828)
Replaced `\Symfony\Component\EventDispatcher\Event` usage in favor of `Symfony\Contracts\EventDispatcher\Event`. 
**TODO**:

EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishIOBundle/DependencyInjection/Configuration.php

| **JIRA issue**     | [EZP-30846](https://jira.ez.no/browse/EZP-30846)
| **Target version** |  `master` 
Since Symfony 4.3 configuration root name should be passed via constructor instead of using "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method.
More information:
* https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
* https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config
**TODO**:

EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls

---

eZ/Publish/SPI/FieldType/Generic/Type.php

Follow up for https://github.com/ezsystems/ezpublish-kernel/pull/2632. Fixed reference to undefined property "settingsSchema" (replaced by `getSettingsSchema` method) in `eZ\Publish\SPI\FieldType\Generic\Type::validateFieldSettings`.
**TODO**:

Fixed reference to undefined property "settingsSchema" in Generic\Type::validateFieldSettings

---

eZ/Publish/SPI/FieldType/ValidationError/NonConfigurableValidationError.php
eZ/Publish/SPI/FieldType/ValidationError/UnknownValidatorValidationError.php

Follow up for #2632. Added missing `%` in the parameters names passed to message template in `eZ\Publish\SPI\FieldType\ValidationError\{UnknownValidatorValidationError,NonConfigurableValidationError}`
**TODO**:

Fixed missing % in parameters names passed to {UnknownValidator,NonConfigurable}ValidationError

---

eZ/Publish/Core/Helper/PreviewLocationProvider.php
eZ/Publish/Core/Helper/Tests/PreviewLocationProviderTest.php
eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php

| **JIRA issue**     | [EZP-30839](https://jira.ez.no/browse/EZP-30839)
Preview's hardcoded "draft location" was not adapted when introducing `$location->getContent()` causing code that took advantage of this feature to break on un-published 1st drafts.
*REVIEW NOTE:* API is changed (in safe way) to take Content as argument as we need to make sure it's the same content as loaded by the system _(same translation and same version)_. This also saves having to load this info twice, and makes sure the instance is the same in case of for instance content proxy being used.
_Note: this is not …

EZP-30839: Fixed loading Content of Location for 1st draft in preview

---

eZ/Publish/API/Repository/Tests/SectionServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/SectionServiceTest.php
eZ/Publish/Core/Repository/SectionService.php

| **JIRA issue**     | [EZP-30852](https://jira.ez.no/browse/EZP-30852)
User should add and edit section without having view permission. Section/View policy was required because we use API methods `loadSectionByIdentifier` and `loadSection` instead of those from Handler. 
Also, I improved tests to check if `UnauthorizedException` message is correct.
Depends on: https://github.com/ezsystems/ezplatform-admin-ui/pull/1057
**TODO**:

EZP-30852: Section handler has been used in methods create and updateSection

---

eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml

| **JIRA issue**     | [EZP-30729](https://jira.ez.no/browse/EZP-30729)
| **Bug**| yes
| **Target version** | `6.7`/`6.13`/`7.5`/`master`
This PR adds a possibility to exclude particular ContentTypes of which versions should not be removed. This option **always** includes content objects of default `User` ContentType (ID: `4`, unfortunately, there is no `const` anywhere to use it instead of hardcoding it).
Moreover, I've added a ProgressBar which indicates the progress. In some cases, it takes some time to clean up a huge number of versions so the user might have a wrong impression that nothing is going on. 
A …

EZP-30729: Added a possibility to exclude Content Types when running CleanupVersionsCommand

---

eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Helper/DomainMapper.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php

| **JIRA issue**     | [EZP-30796](https://jira.ez.no/browse/EZP-30796)
This issue occurs because we try to load content without location (Location is created after Content is copied) by API service. And then permission to read is checked. Fetching internal resources should be done by handler instead of API service in this case. 
Additionally, I added a method `buildContentDomainObjectFromPersistence` to `\eZ\Publish\Core\Repository\Helper\DomainMapper` to build Content from Content and ContentType which both comes from SPI. 
Also, ContentServiceAuthorizationTest …

EZP-30796: Fixed copying content with Subtree limitation

---

eZ/Publish/Core/MVC/Symfony/Controller/SecurityController.php
eZ/Publish/Core/MVC/Symfony/View/LoginFormView.php
eZ/Publish/Core/MVC/Symfony/View/Tests/AbstractViewTest.php
eZ/Publish/Core/MVC/Symfony/View/Tests/ContentViewTest.php
eZ/Publish/Core/MVC/Symfony/View/Tests/LoginFormViewTest.php

| **JIRA issue**     | [EZP-30869](https://jira.ez.no/browse/EZP-30869)
| **BC breaks**      | yes/no
Introduced `\eZ\Publish\Core\MVC\Symfony\View\LoginFormView` to be able to extend login form by subscribing `\eZ\Publish\Core\MVC\Symfony\MVCEvents::PRE_CONTENT_VIEW` event.   
Example use cases:
* Passing additional parameters to view e.g. https://github.com/crevillo/ezplatform-captcha/blob/master/src/bundle/MVC/Symfony/Controller/SecurityController.php#L70
* Completely change render view based on occurred login error as in case of EZP-30797:
Example code: …

EZP-30869: Added extension point in login form view

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-30681](https://jira.ez.no/browse/EZP-30681)
Use case:
1. Under "Home" location (#2) create two folders: "Parent" and "Move me".
2. Move "Move me" folder to "Parent".
3. Check `ezcontentobject_tree.path_identification_string` for moved node.
Expected result: `node_2/parent/move_me`
Actual result: `node_2/parent//move_me`
**TODO**:

EZP-30681: Fixed double slash in path_identification_string after moveSubtree

---

doc/bc/changes-8.0.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SiteAccessMatcherRegistryPass.php
eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/SiteAccess/MatcherBuilder.php
eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistry.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/SiteAccessMatcherRegistryPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/MatcherBuilderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/SiteAccessMatcherRegistryTest.php

| **JIRA issue**     | [EZP-30598](https://jira.ez.no/browse/EZP-30598)
This PR removes `Container::get` calls from `MatcherBuilder`. You can still use old syntax for using siteaccess matchers based on services:
```yaml
siteaccess:
list: [site]
groups:
site_group: [site]
default_siteaccess: site
match:
'@App\Matcher\MySiteaccessMatcher': 1
``` 
But it now requires to tag the service using `ezpublish.siteaccess.matcher` tag.
**TODO**:

EZP-30598: Removed Container::get calls from SiteAccess MatcherBuilder

---

eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php

| **Required by** | #2753
This refactor is a result of working on ContentService and a need to add some new tests and change the old ones in https://jira.ez.no/browse/EZP-30427
**TODO**:

Refactored integration test for ContentService

---

doc/bc/changes-7.5.md
eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/SchemaBuilderInstallerPass.php
eZ/Bundle/PlatformInstallerBundle/src/EzSystemsPlatformInstallerBundle.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

| **JIRA issue**     | [EZP-30912](https://jira.ez.no/browse/EZP-30912)
| **Target version** | `7.5` (see #2751 `master` changes)
| **Doc needed**     | ezsystems/developer-documentation#758
When working on [EZP-30624](https://jira.ez.no/browse/EZP-30624) and [EZP-30898](https://jira.ez.no/browse/EZP-30898) I realized that there was no way to use `CoreInstaller` as a `parent` in Dependency Injection Container because only BC was provided w/o actual forward compatibility. It wasn't the intention so I've qualified this as a bug.
This PR introduces the following changes:
warning and removal of the dependent …

EZP-30912: Provided forward compatibility for CoreInstaller

---

eZ/Bundle/PlatformBehatBundle/Context/Argument/AnnotationArgumentResolver.php

| **JIRA issue**     | [EZP-30884](https://jira.ez.no/browse/EZP-30884)
| **Target version** | 7.5
This regex, as part of EzSystemsBehatExtension, is responsible for splitting a string like:
`injectService $argumentParser @EzSystems\BehatBundle\Helper\ArgumentParser`
into three parts:
- `injectService`
- `$argumentParser`
- `@EzSystems\BehatBundle\Helper\ArgumentParser`
Unfortunely currently it works as:
- `injectService`
- `$argumentParser`
- `@EzSystems`
which makes it impossible to inject services using class name.
Usage: https://github.com/ezsystems/ezplatform-admin-ui/pull/1068/files# …

[Behat] EZP-30884: Added support for class name as service id

---

doc/bc/changes-8.0.md
doc/specifications/debug/data_collectors.md
eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml
eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/layout.html.twig
eZ/Publish/Core/MVC/Symfony/Controller/SecurityController.php
eZ/Publish/Core/MVC/Symfony/View/Manager.php
eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php
eZ/Publish/Core/MVC/Symfony/View/Tests/Renderer/TemplateRendererTest.php
eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php

| **JIRA issue**     | [EZP-30906](https://jira.ez.no/browse/EZP-30906)
| **Target version** | `master` for features
main PR:
https://github.com/ezsystems/ezplatform/pull/453
**TODO**:

EZP-30906: Removed deprecated templating component integration

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/Adapter/Item/TransactionItem.php
eZ/Publish/Core/Persistence/Cache/Adapter/TransactionAwareAdapterInterface.php
eZ/Publish/Core/Persistence/Cache/Adapter/TransactionItem.php
eZ/Publish/Core/Persistence/Cache/CacheServiceDecorator.php
eZ/Publish/Core/Persistence/Cache/Tests/TransactionHandlerTest.php
eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
eZ/Publish/Core/Repository/ContentTypeService.php

| **JIRA issue**     | [EZP-30823](https://jira.ez.no/browse/EZP-30823)
| **Target version** | `6.7`+ _(see #2749 for 7.x PR)_
Similar to what was done for 2.5.3 (#2703) and followup in #2749, but adapted for Stash:
- As Stash has "fat Items" need to catch calls to store/clear on the object itself, this part is not relevant for 7.x
- Route calls to store items to just deferred delete the key instead
- Make it so that Items with keys that are marked as invalidated gets returned as a "miss" by the system
- And with that be able to get rid of the need to clear all cache on rollback, we instead just need to wipe out …

EZP-30823: [6.x] Isolated cache during transactions to avoid race condition

---

doc/bc/changes-8.0.md
eZ/Publish/API/Repository/SearchService.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php
eZ/Publish/SPI/Repository/Decorator/SearchServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/SearchServiceDecoratorTest.php
eZ/Publish/SPI/Search/Capable.php

| **JIRA issue**     | [EZP-30790](https://jira.ez.no/browse/EZP-30790)
| **Requires** | ezsystems/ezplatform-solr-search-engine#145
| **Target version** | `master (8.0)` for eZ Platform `v3.0`
| **Tests pass**     | yes, Solr fails due to missing PR dependency.
| **Doc needed**     | yes[1]
This PR introduces strict types for the following methods:
I've just seen a call like
```php
$searchService->supports('CAPABILITY_FACETS');
```
so it will be a DX improvement to get here concrete error instead of `false` result.
[1] We should probably improve [this doc](https://doc.ezplatform.com/en/latest/api/public_php_api_search/#difference-between-f …

EZP-30790: Introduced strict types for Search supports methods

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
eZ/Publish/Core/REST/Server/Controller/Content.php

| **JIRA issue**     | [EZP-30382](https://jira.ez.no/browse/EZP-30382)
This adds missing functionality on hide/reveal content via REST API.
When merging up this must be moved to new REST repository and only REST DOC file need to be merged up!
**TODO**:

EZP-30382: Add content hide/reveal to REST API

---

eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php

| **JIRA issue**     | [EZP-30911](https://jira.ez.no/browse/EZP-30911)
This PR adds an option to pass array option `location-id` so regeneration of URL aliases can be done for only specific locations, like this:
`php bin/console ezplatform:urls:regenerate-aliases --location-id=1 --location-id=2 --location-id=100`
**TODO**:

EZP-30911: Added option to pass location-id parameter to URL alias regeneration Command

---

composer.json
eZ/Publish/API/Repository/Tests/Parallel/BaseParallelTestCase.php
eZ/Publish/API/Repository/Tests/Parallel/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/Parallel/ParallelProcessList.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/SPI/Persistence/Content/Handler.php
phpunit-integration-legacy.xml

| **JIRA issue**     | [EZP-30469](https://jira.ez.no/browse/EZP-30469)
This PR resolves an edge case where two Editors publish different Versions of the same Content item at the same time.
This PR also creates base for parallel integration testing of Repository services, for now for internal use by the Repository.
The process of publishing archives recently published content item, therefore at the moment of update there should be no published version. This is the basis for both blocking publishing of another version and assessment if someone else published …

EZP-30469: Fixed parallel Content publishing

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
eZ/Publish/SPI/Persistence/Content/Handler.php

| **JIRA issue**     | [EZP-30968](https://jira.ez.no/browse/EZP-30968)
This method is needed to add pagination to content's reverse relation list
**TODO**:

EZP-30968: Added method to count the number of content's reverse relations

---

bin/.travis/prepare_unittest.sh

| **JIRA issue**     | n/a, see: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/152
To quote from https://github.com/ezsystems/ezplatform-solr-search-engine/pull/152:
> Due to the major changes in Solr, support for 7.X will be part of the ezplatform-solr-search-engine 2.0 release which will be compatible with eZ Platform 2.5 release. Solr 6.X will be dropped in this release.
> Solr 7.X and Solr 8.X will be officialy supported in ezplatform-solr-search-engine 3.0 release which will be compatible with eZ Platform 3.X.

[Travis] Bumped solr version in tests to 3.0

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Lists/UnauthorizedListItem.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Values/Content/RelationList.php
eZ/Publish/API/Repository/Values/Content/RelationList/Item/RelationListItem.php
eZ/Publish/API/Repository/Values/Content/RelationList/Item/UnauthorizedRelationListItem.php
eZ/Publish/API/Repository/Values/Content/RelationList/RelationListItemInterface.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/SPI/Persistence/Content/Handler.php

| **JIRA issue**     | [EZP-30969](https://jira.ez.no/browse/EZP-30969)
| **Required by** | ezsystems/ezpublish-kernel#2774
| **Target version** | `7.5` for eZ Platform `v2.5.x` LTS
This method is needed to add pagination to content's reverse relation list. It is related to [https://jira.ez.no/browse/EZP-30900](https://jira.ez.no/browse/EZP-30900) and [https://jira.ez.no/browse/EZP-30968](https://jira.ez.no/browse/EZP-30968)
A command which can help during QA: https://gist.github.com/mikadamczyk/1d45ef638ffb18357883e7c301fa5c15
**TODO**:

EZP-30969: Added method to fetch paginated list of content's reverse relations

---

eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalInMemoryCacheAdapter.php

| **JIRA issue**     | Follow-up [EZP-30823](https://jira.ez.no/browse/EZP-30823)
| **Target version** | <ul><li>`7.5` for eZ Platform `v2.5.x`</li><li>`master (8.0@dev)` for eZ Platform `v3.0`</li></ul>
| **Tests pass**     | yes ([`master`](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/593071347), [`7.5`](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/593178560))
This PR is an attempt to fix failing CI without reverting #2749 (as done in #2794).
~First approach is to restore explicit cache clearing in `\eZ\Publish\Core\Persistence\Cache\TransactionHandler::rollback`. Since this should be …

EZP-30823: Cleared in-memory cache pools during rollback

---

eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php

Removed unused docblock parameters in Content Gateway

---

eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/SPI/Persistence/Content/CreateStruct.php

| **JIRA issue**     | [EZP-30889](https://jira.ez.no/browse/EZP-30889)
https://jira.ez.no/browse/EZP-30889
Excerpt from JIRA:
>Content marked as "hidden" does not preserve this state after copying it to another Location.
**TODO**:

EZP-30899: Propagated ContentInfo::isHidden status when publishing

---

eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/FieldType/Tests/UserTest.php
eZ/Publish/Core/FieldType/User/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
eZ/Publish/Core/Repository/UserService.php

| **JIRA issue**     | [EZP-30983](https://jira.ez.no/browse/EZP-30983)
| **New feature**    | yes/no
Prevent users from reusing old (current) password when password expiration is enabled.
**TODO**:

EZP-30983: Prevented users from reusing old password

---

data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql
data/update/postgres/dbupdate-7.5.4-to-7.5.5.sql

Added `password_updated_at` column initialization to the `data/update/{mysql,postgres}/dbupdate-7.5.4-to-7.5.5.sql`
**TODO**:

Added password_updated_at column initialization to the 7.5.3 to 7.5.4 update scripts

---

data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql

Follow up for https://github.com/ezsystems/ezpublish-kernel/pull/2803. Fixed the following error during the update eZ Platform from 2.5.5 to 2.5.6 on 10.4.6-MariaDB
**TODO**:

Fixed "Out of range value for 'password_update_at'" error during the 7.5.4 to 7.5.5 update script execution on Maria DB

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Publish/Core/settings/repository/autowire.yml
eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
eZ/Publish/Core/settings/storage_engines/legacy.yml
eZ/Publish/Core/settings/tests/integration_legacy.yml

Related upgrade notes: https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#dependencyinjection (2nd point)
**TODO**:

EZP-30985: Replaced deprecated DI short factory syntax

---

composer.json

| **JIRA issue**     | [EZP-31006](https://jira.ez.no/browse/EZP-31006)
| **Target version** | `master` for eZ Platform v3.0
Just to keep deps uptodate, no relevant breaking changes as far as I can see.
**TODO**:

EZP-31006: Bumped hautelook/templated-uri-bundle to v3

---

eZ/Publish/Core/Repository/LocationService.php

| **Target version** |`7.x` 
Fixed `\eZ\Publish\API\Repository\PermissionCriterionResolver::getPermissionsCriterion` calls without required `module` and `function` parameters:
https://github.com/ezsystems/ezpublish-kernel/blob/b40ee9a5a7297e6161cfc4855e6cb9b3d65c83d5/eZ/Publish/API/Repository/PermissionCriterionResolver.php#L28
in `\eZ\Publish\Core\Repository\LocationService`. It depends on `\eZ\Publish\API\Repository\PermissionCriterionResolver` and shouldn't rely on default values from concrete implementation: …

Fixed PermissionCriterionResolver::getPermissionsCriterion calls without parameters

---

eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php

| **JIRA issue**     | [EZP-31000](https://jira.ez.no/browse/EZP-31000)
Since Symfony 3.2 it allows defining the fragment when generating a URL with reserved routing property `_fragment`. URLAliasGenerator has no support for this parameter. This resulted in an error when the URL for pagination embedded in the tab was generated.
**TODO**:

EZP-31000: Added support to fragment identifier for URL alias generator

---

eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php

| **JIRA issue**     | [EZP-31026](https://jira.ez.no/browse/EZP-31026)
| **Doc needed**     |  no
_Issue discovered while working on https://github.com/ezsystems/ezpublish-kernel/pull/2786_
Method `\eZ\Publish\API\Repository\ContentService::loadContentListByContentInfo` called from the site access aware layer doens't respect current siteaccess languages settings.
**TODO**:

EZP-31026: Fixed resolving of lang params in SA loadContentListByContentInfo

---

eZ/Publish/API/Repository/LanguageService.php
eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
eZ/Publish/Core/Event/LanguageService.php
eZ/Publish/Core/Repository/LanguageService.php
eZ/Publish/Core/Repository/SiteAccessAware/LanguageService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/LanguageServiceTest.php
eZ/Publish/SPI/Repository/Decorator/LanguageServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/LanguageServiceDecoratorTest.php

| **JIRA issue**     | [EZP-30885](https://jira.ez.no/browse/EZP-30885)
| **BC breaks**      | yes!
This PR introduces strict types for the `\eZ\Publish\API\Repository\LanguageService`
**TODO**:
**QA**

EZP-30885: Introduced strict types for LanguageService

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php
eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php
eZ/Publish/Core/MVC/Symfony/Translation/TranslatableExceptionsFileVisitor.php
eZ/Publish/Core/MVC/Symfony/Translation/ValidationErrorFileVisitor.php

Part of the patch changes methods which implement `JMS\TranslationBundle\Translation\Extractor\FileVisitorInterface::visitTwigFile` which still uses old Twig class names. However, this is perfectly valid. The following code runs fine:
```php
<?php
require 'vendor/autoload.php';
interface Foo
{
public function foo(\Twig_Node $node);
}
class Bar implements Foo
{
public function foo(\Twig\Node\Node $node)
{
return 'foo';
}
}
$b = new Bar();
echo $b->foo(new \Twig\Node\Node());
echo …
```

EZP-30985: Replaced deprecated Twig classes

---

.travis.yml

| **Bug/Improvement**| sort of improvement for Travis
| **Target version** | 6.7, 6.13, not applicable for 7.5 or master
This PR tries to reduce the job queue on Travis. When something is merged to 6.7 and then upstrem it triggers 36 jobs on Travis (10 for each 6.7, 6.13, 7.5 and 6 for master), which can take some time to finish.
This PR changes how the jobs are run - after a PR to 6.7 or 6.13 is merged jobs won't be triggered, 
instead they will be triggered during the nightly build (we're running cron build for all supported branches, example: …

[Travis] Disabled testing 6.7 and 6.13 branches on push / merge

---

composer.json
eZ/Bundle/EzPublishCoreBundle/Command/ResizeOriginalImagesCommand.php
eZ/Bundle/EzPublishCoreBundle/Imagine/BinaryLoader.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/BinaryLoaderTest.php

Continuation of #2781 (in order not to block it since it is already approved)
**TODO**:

EZP-30985: Replaced deprecated ExtensionGuesser with MimeTypes class from symfony/mime

---

eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php

| **JIRA issue**     | [EZP-31050](https://jira.ez.no/browse/EZP-31050)
| **Doc needed**     |  no
_Issue discovered while working on https://github.com/ezsystems/ezpublish-kernel/pull/2786_
Method `\eZ\Publish\Core\Repository\SiteAccessAware\ContentTypeService::loadContentTypeList` called from the site access aware layer doesn't respect current siteaccess languages settings.
**TODO**:

EZP-31050: Fixed resolving of lang params in SA ContentTypeService::loadContentTypeList

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
eZ/Publish/Core/MVC/Symfony/Security/Tests/User/ProviderTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/UserCheckerTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/UserTest.php
eZ/Publish/Core/MVC/Symfony/Security/Tests/UserWrappedTest.php
eZ/Publish/Core/MVC/Symfony/Security/User.php
eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php
eZ/Publish/Core/MVC/Symfony/Security/UserChecker.php
eZ/Publish/Core/MVC/Symfony/Security/UserInterface.php
eZ/Publish/Core/MVC/Symfony/Security/UserWrapped.php

| **Required by** | ezsystems/ezplatform#469
**TODO**:

EZP-30985: Removed usage of deprecated AdvancedUserInterface

---

eZ/Publish/API/Repository/RoleService.php
eZ/Publish/Core/Event/RoleService.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/RoleServiceDecoratorTest.php

| **JIRA issue**     | [EZP-31029](https://jira.ez.no/browse/EZP-31029)
This PR introduces strict types for the `\eZ\Publish\API\Repository\RoleService`
Related to https://github.com/ezsystems/ezplatform-admin-ui/pull/1111
**TODO**:
**QA**

EZP-31029: Introduced strict types for RoleService

---

eZ/Bundle/EzPublishCoreBundle/Resources/translations/fielddefinition.en.xlf
eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig

| **BC breaks**      | yes? (New translation strings required)
`transchoice` has been deprecated since Symfony 4.2.
Here, I've opted for using separate translation strings, rather than reimplementing `trans` with ICU MessageFormat which requires renaming translation files to have a new prefix for ICU messages to be recognized.
**TODO**:

EZP-30985: Replaced usage of deprecated transchoice Twig function

---

eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/ContentService.php

| **JIRA issue**     | [EZP-31053](https://jira.ez.no/browse/EZP-31053)
_Issue discovered while working on https://github.com/ezsystems/ezpublish-kernel/pull/2786_
Method `\eZ\Publish\Core\Repository\ContentService::internalLoadContent` ignores language priority while loading content type.  
**TODO**:

EZP-31053: Prioritized languages should be respected by Content::getContentType

---

doc/bc/changes-8.0.md
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php

| **JIRA issue**     | [EZP-30689](https://jira.ez.no/browse/EZP-30689)
| **Required by** | #2651 
| **Target version** | `master (8.0@dev)` for eZ Platform v3.0
This PR both provides an improvement and fixes broken behat test for Query Types by providing automatic configuration for them (`autoconfigure: true` causing auto-tagging of the services which implement `\eZ\Publish\Core\QueryType\QueryType` with `ezpublish.query_type`).
The reason for doing it now is unblocking Travis for #2651 to proceed with QA.
Traversing through bundles to automatically register Query Types by the naming …

EZP-30689: Registered Query Types for automatic configuration

---

eZ/Publish/API/Repository/Tests/URLServiceTest.php
eZ/Publish/API/Repository/Values/URL/Query/Criterion/SectionId.php
eZ/Publish/API/Repository/Values/URL/Query/Criterion/SectionIdentifier.php
eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/VisibleOnlyTest.php
eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Base.php
eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionId.php
eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionIdentifier.php
eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/VisibleOnly.php
eZ/Publish/Core/settings/storage_engines/legacy/url_criterion_handlers.yml

| **JIRA issue**     | [EZP-30988](https://jira.ez.no/browse/EZP-30988)
| **Target version** | `7.5.x` for eZ Platform `v2.5.x` LTS
- Implement Section criteria for URL lookup
- Fix slow query when filter by VisibleOnly criteria
// Edited by @alongosz:
- You can play with the test command to find URLs filtered by Content Section:
https://github.com/ezsystems/ezplatform/compare/2.5...alongosz:for-qa-ezp-30988-find-urls-cmd.
Usage: `php ./bin/console test:find-urls [<url1> <url2> ...]`. No arguments returns all registered URLs. An URL is registered when e.g. added to Content RichText field …

EZP-30988: Implemented Section filtering URL Query Criterion

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-31023](https://jira.ez.no/browse/EZP-31023)
| **Tests pass**     | -
_Correct if I'm wrong and this is expected behavior. Issue discovered while working on https://github.com/ezsystems/ezpublish-kernel/pull/2786_
Currently, it's not possible to load the root location (id = 1) with the prioritized language list  
```php
$rootLocation = $repository
->getLocationService()
->loadLocation(
$this->generateId('location', 1),
[
'eng-GB',
'ger-DE',
]
);
```
instead of `\eZ\Publish\API\Repository\Exceptions\NotFoundException` is thrown. Ref. …

EZP-31023: Fixed root location loading with prioritized languages

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
eZ/Publish/Core/MVC/Symfony/Controller/Content/QueryController.php

| **JIRA issue**     | [EZP-30567](https://jira.ez.no/browse/EZP-30567)
| **Target version** | `master (8.0@dev)` for eZ Platform `v3.0`.
The ez_query:pagingQueryAction will return a pagerFanta object set to the assign_to_result parameter.
alongside with the assign_to_result param as described a limit parameter can be added to set the page number of items.
**TODO**:

EZP-30567: Impl. ez_query:pagingQueryAction to handle pagination

---

eZ/Publish/API/Repository/Values/Content/LocationList.php
eZ/Publish/API/Repository/Values/Content/Search/SearchResult.php

| **JIRA issue**     | [EZP-24520](https://jira.ez.no/browse/EZP-24520)
Implemented `\IteratorAggregate` for 
* `eZ\Publish\API\Repository\Values\Content\Search\SearchResult`
* `eZ\Publish\API\Repository\Values\Content\LocationList`
to be able to natively use the `foreach` statement and align them with other List/Result structures in PAPI.
**TODO**:

EZP-24520: Impl. IteratorAggregate for SearchResult and LocationList

---

eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php

| **JIRA issue**     | [EZP-30865](https://jira.ez.no/browse/EZP-30865)
added support for attaching language to existing urlaliases in :
`eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php`
**TODO**:

EZP-30865: Fixed creating the same custom URL alias for different language

---

eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php

| **JIRA issue**     | [EZP-30733](https://jira.ez.no/browse/EZP-30733)
| **Target version** | `7.5`/`master`
This PR introduces the usage of the new argument of `ContentService::loadVersions()` method (ref: https://github.com/ezsystems/ezpublish-kernel/pull/2652)which should have a significant, positive impact on the performance of CleanupVersionsCommand. 
This PR depends on https://github.com/ezsystems/ezpublish-kernel/pull/2691 which **needs to be** merged first and this one will have to be rebased afterward. 
**TODO**:

EZP-30733: CleanupVersionsCommand should use new ContentService::loadVersions status argument for better performance

---

composer.json

|            |  |
| **Target version** | `6.7`, `6.13`, `7.5`, `master (8.0@dev)`
There are two outstanding issues related to the latest releases of PHP-CS-Fixer and `Doctrine\DBAL`.
1. #2857: Due to php-cs-fixer RuleSets being unstable, even for patch releases, the package version needs to be locked at `2.15.3` for now.
In the future we'd need to create our own list of rules (see /ezsystems/ezplatform-code-style#3), to avoid using RuleSets (except maybe PSR2).
Ideally we should create our own RuleSet, but AFAICS custom rule sets are not exposed by php-cs-fixer config factory ATM.
2. The `2.10.0` release of `doctrine/dbal` introduced strict return types on e.g. `QueryBuilder`. Unfortunately [old PHPUnit 4.8.x can't handle mocking of such classes …

[6.7] Fixed failing CI

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php

| **JIRA issue**     | [EZP-31114](https://jira.ez.no/browse/EZP-31114)
| **Target version** | `7.5`/`8.x` 
Added `--disable-index` option for `ezplatform:install` command. 
**TODO**:

EZP-31114: Added "skip-indexing" option for install command

---

eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
eZ/Publish/Core/Persistence/Cache/TrashHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/TrashHandlerTest.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/SPI/Persistence/Content/Location/Trash/Handler.php
eZ/Publish/SPI/Persistence/Content/Location/Trash/TrashResult.php

| **JIRA issue**     | [EZP-31084](https://jira.ez.no/browse/EZP-31084)
Reports from customer**s** that trash exceeds memory use _or_ timeouts on large amounts of trash.
This PR solves part 1 of this:
- Provide a way for SPI to be able to tell how many items there are in trash, without having to set limit= 0 and load the whole trash basket into basket.
- Use this to fix `emptyTrash()` function in `Persistence/Legacy` and in `Persistence/Cache` to avoid the issues memory/timeout issue there
**Follow up fixes to solve the overall user issues around this**:
- Find a way to take into …

EZP-31084: Memory exhausted / timeout on too many items in the trash - part 1

---

eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
eZ/Publish/Core/Persistence/Cache/TrashHandler.php

| **JIRA issue**     | [EZP-31084](https://jira.ez.no/browse/EZP-31084)
Attempt to fix issue found in #2847 by @mnocon.

EZP-31084: Fix infinitive loop in cache emptyTrash()

---

eZ/Publish/Core/MVC/Symfony/Security/EventListener/SecurityListener.php

| **JIRA issue**     | [EZP-XXXXX](https://jira.ez.no/browse/EZP-XXXXX)
Currently protected function *hasAcces*  is  called twice with unneeded 2nd paramter $username.
(technically not an error - but not intended I guess)
**TODO**:

Removed 2nd parameter on SecurityListener::hasAccess calls

---

eZ/Publish/API/Repository/ContentTypeService.php
eZ/Publish/Core/Event/ContentTypeService.php
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/ContentExtensionTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php
eZ/Publish/SPI/Repository/Decorator/ContentTypeServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/ContentTypeServiceDecoratorTest.php

| **JIRA issue**     | [EZP-31103](https://jira.ez.no/browse/EZP-31103)
This PR introduces strict types for the `\eZ\Publish\API\Repository\ContentTypeService`
**TODO**:

EZP-31103: Introduced strict types for ContentTypeService

---

eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml

| **JIRA issue**     | [EZP-31119](https://jira.ez.no/browse/EZP-31119)
Replaced usage of deprecated `\Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand` class (since SF 4.2) in favour of `\Symfony\Component\Console\Command\Command` and dependency injection in `eZ\Bundle\EzPublishCoreBundle\Command\CheckURLsCommand`
**TODO**:

EZP-31119: Fixed usage of deprecated ContainerAwareCommand class in CheckURLsCommand

---

eZ/Publish/API/Repository/Tests/URLServiceTest.php
eZ/Publish/API/Repository/URLService.php
eZ/Publish/Core/Event/URLService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UrlTest.php
eZ/Publish/Core/Repository/URLService.php
eZ/Publish/SPI/Repository/Decorator/URLServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/URLServiceDecoratorTest.php

| **JIRA issue**     | [EZP-31097](https://jira.ez.no/browse/EZP-31097)
This PR introduces strict types for the` \eZ\Publish\API\Repository\URLService`
**TODO**:

EZP-31097: Introduced strict types for URLService

---

eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ChainRoutingPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/FragmentPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/SecurityPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishIOBundle/Tests/DependencyInjection/Compiler/IOConfigurationPassTest.php
eZ/Publish/Core/Base/Tests/Container/Compiler/GenericFieldTypeConverterPassTest.php

| **Tests pass**     |  yes, except behat (not related)
Ensured that all services ids used in unit tests based on `\Matthias\SymfonyDependencyInjectionTest\PhpUnit\AbstractCompilerPassTestCase` are defined in the Dependency Injection Container (if it's possible)
Otherwise `CheckExceptionOnInvalidReferenceBehaviorPass` introduced in `symfony/dependency-injection` 4.4.0 will throw  an exception:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException : The service "ezpublish.console_event_listener" has a dependency on a non-existent service …
```

Ensure that all services ids used in compiler passes tests are defined

---

composer.json

| **JIRA issue**     | Discovered while working on [EZP-30806](https://jira.ez.no/browse/EZP-30806)
| **Target version** | `7.5`, `master (8.0@dev)`
This PR adds to the `composer.json` `require` section the `ext-dom` extension. 
It's a DX improvement. Static analysis reports it as missing which slightly slows down development when stopping to investigate the highlighted issue. Moreover if composer is used on a system w/o that extension, it will be immediately reported.
Seems [requirements page](https://doc.ezplatform.com/en/2.5/getting_started/requirements/#other-supported-setups) is missing information that …

[Composer] Added missing ext-dom requirement

---

.travis.yml
bin/.travis/enable_swap.sh
bin/.travis/prepare_behat.sh
composer.json

| **JIRA issue**     | https://jira.ez.no/browse/EZP-31189
| **Target version** | 6.7, 6.13 -> swap is not required for 7.5 and master and as it takes time we shouldn't use it where it's not necessary
Travis is failing because of memory issues, this PR:
1) Reduces memory required by Composer by adding a branch alias to the PR dependency and bumping minimal Symfony requirements
2) Sets up swap to increase the memory available to Composer and sets memory_limit=-1

[Travis] Fix memory issues during build

---

eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature

Requires: https://github.com/ezsystems/BehatBundle/pull/114
After Symfony 4.4.0 release the Query Controller tests stopped passing, because the `dump` HTML output has changed. This PR changes the dependency from Symfony's `{{ dump }} ` function to something that is completely in our control.
**TODO**:

Fixed Query Controller tests

---

doc/upgrade/7.5.md
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Cache/ContentHandler.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
eZ/Publish/Core/REST/Client/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
eZ/Publish/Core/SignalSlot/ContentService.php
eZ/Publish/Core/SignalSlot/Signal/ContentService/CreateContentDraftSignal.php
eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
eZ/Publish/Core/SignalSlot/Tests/ServiceTest.php
eZ/Publish/SPI/Persistence/Content/Handler.php

| **JIRA issue**     | [EZP-30936](https://jira.ez.no/browse/EZP-30936)
As updating content without provided fields still try to fetch and validate them in order to provider proper name for content, most viable solution instead of updating content with only language, is to allow to instantly create draft in wanted language.
usage:
https://github.com/ezsystems/ezplatform-admin-ui/pull/1134
**TODO**:

EZP-30936: Added option to create content draft in provided Language

---

composer.json

Added missing dependency coming from
https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php#L93
**TODO**:

Added missing dependency on symfony/security-bundle

---

doc/bc/changes-8.0.md
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/Repository/ObjectStateService.php
eZ/Publish/Core/Repository/Values/ObjectState/ObjectState.php
eZ/Publish/Core/Repository/Values/ObjectState/ObjectStateGroup.php
eZ/Publish/Core/settings/repository.yml
eZ/Publish/Core/settings/repository/siteaccessaware.yml

| **JIRA issue**     | [EZP-30973](https://jira.ez.no/browse/EZP-30973)
| **BC breaks**      | yes/no
**TODO**:
**QA**:

EZP-30973: Made siteaccess aware repository to be used as default

---

eZ/Publish/Core/Search/Common/Slot/AssignSectionToSubtree.php
eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml
eZ/Publish/Core/settings/search_engines/legacy/slots.yml

| **JIRA issue**     | [EZP-31113](https://jira.ez.no/browse/EZP-31113)
| **Bug**| yes
| **Target version** | `7.5`/`master`
`AssignSectionToSubtreeSignal` is not handled properly in both search implementations as well as in HTTP cache. 
_Note_: These changes will be removed on merge-up and the second PR targeting master will be created. 
**TODO**:

EZP-31113: Implemented indexing subtree after assigning Section to it

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php

| **JIRA issue**     | [EZP-30754](https://jira.ez.no/browse/EZP-30754)
| **Target version** | `6.13`, `7.5`, `master (8.0@dev)`
This PR fixes two separate issues, related to handling of the always available flag, which occur during ContentInfo (Content metadata) update.
The first issue is about updating only the always available flag and nothing else, as reported via kaliop-uk/ezmigrationbundle#209 and [EZP-30754](https://jira.ez.no/browse/EZP-30754).
To solve that we need to check if there's anything to update before trying to execute database update.
It's not easy with our own database …

EZP-30754: Fixed handling always available flag for ContentInfo update

---

eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php
eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOperator.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/BaseTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalAndTest.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOperatorTestCase.php
eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOrTest.php

| **JIRA issue**     | [EZP-30806](https://jira.ez.no/browse/EZP-30806)
| **Target version** | `6.13`, `7.5` (#2886), `master (8.0@dev)`
| **Tests pass**     | [yes](https://travis-ci.org/ezsystems/ezpublish-kernel/builds/617188988)
| **Doc needed**     | #2879
See 879d769 for the fix and df4b6f9 for deprecation.
This PR fixes a regression introduced via #2527 for the following REST view payload:
``` json
{
"ViewInput": {
"identifier": "test",
"public": true,
"LocationQuery": {
"Filter": {
"OR": [
{
"ContentTypeIdentifierCriterion": "folder"
},
{
"ContentTypeIdentifierCriterion": "article"
}
]
},
"FacetBuilders": {},
"SortClauses": {}, …
```

EZP-30806: Fixed processing REST logical op. input with list of objects

---

doc/specifications/rest/REST-API-V2.rst

| **JIRA issue**     | [EZP-30806](https://jira.ez.no/browse/EZP-30806)
| **Target version** | `7.5`, `master (8.0@dev)`.
| **Doc needed**     | yes, RAML update
This PR introduces proper example of usage of logical operators in REST search endpoint (`/views`).
**TODO**:

EZP-30806: Added example of REST search query with logical operators

---

eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php

| **JIRA issue**     | [EZEE-2876](https://jira.ez.no/browse/EZEE-2876)
| **Bug**| yes
When loading multiple values from In Memory cache, results might come in different order. This is caused by implementation of `\eZ\Publish\Core\Persistence\Cache\AbstractInMemoryHandler::getMultipleCacheValues` which first gets elements from InMemory cache (hits) and appends cache misses to the end of the list. This affects results of `LocationService::loadLocationList` which should always return the results in particular order.
The fix is actually simple, instead of preparing empty `$list` array, …

EZEE-2876: Fixed invalid list order being returned by AbstractInMemoryHandler

---

doc/specifications/rest/REST-API-V2.rst

Correcting typo in `rest-api-v2.rst`.

Typo in rest-api-v2.rst

---

doc/specifications/rest/REST-API-V2.rst
eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php

| **JIRA issue**     | [EZP-31125](https://jira.ez.no/browse/EZP-31125)
Added `TranslatedName` property to Content/ContentInfo in REST response which contains content name translated according to current site access setting.
**TODO**:

EZP-31125: Added TranslatedName to Content/ContentInfo in REST response

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Handler.php

| **JIRA issue**     | [EZP-29586](https://jira.ez.no/browse/EZP-29586)
This if followup with bugfix to this https://github.com/ezsystems/ezpublish-kernel/pull/2447
**TODO**:

EZP-29586: Set ownership of copied Content Versions to the current User

---

eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
eZ/Publish/Core/Limitation/LanguageLimitation/ContentTranslationEvaluator.php
eZ/Publish/Core/Limitation/LanguageLimitation/NewDraftEvaluator.php
eZ/Publish/Core/Limitation/LanguageLimitation/VersionPublishingEvaluator.php
eZ/Publish/Core/Limitation/LanguageLimitation/VersionTargetEvaluator.php
eZ/Publish/Core/Limitation/LanguageLimitation/VersionTranslationUpdateEvaluator.php
eZ/Publish/Core/Limitation/LanguageLimitationType.php
eZ/Publish/Core/settings/limitations/language.yml
eZ/Publish/Core/settings/roles.yml

| **JIRA issue**     | [EZP-31235](https://jira.ez.no/browse/EZP-31235)
| **Target version** | `7.5.6` for eZ Platform `v2.5.8 LTS`
There's been a bug in validation of translation (language codes) list for publishing in LanguageLimitation which caused a regression to a result of evaluation for version translation update.
The fix itself was as simple as:
``` diff
-        if (!empty($version->forPublishLanguageCodesList) || null !== $version->forPublishLanguageCodesList) {
+        if (!empty($version->forPublishLanguageCodesList)) {
```
because the property `forPublishLanguageCodesList` …

EZP-31235: Fixed validating translation list for publishing in LanguageLimitation

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

| **JIRA issue**     | [EZP-31203](https://jira.ez.no/browse/EZP-31203)
| **Bug**| yes
This PR fixes the wrong connection being used with `ezplatform:install` command.
**TODO**:

EZP-31203 (1.13): Fixed always using default connection for install Command

---

eZ/Publish/API/Repository/Exceptions/BadStateException.php
eZ/Publish/API/Repository/Exceptions/ContentFieldValidationException.php
eZ/Publish/API/Repository/Exceptions/ContentTypeFieldDefinitionValidationException.php
eZ/Publish/API/Repository/Exceptions/ContentTypeValidationException.php
eZ/Publish/API/Repository/Exceptions/ContentValidationException.php
eZ/Publish/API/Repository/Exceptions/Exception.php
eZ/Publish/API/Repository/Exceptions/ForbiddenException.php
eZ/Publish/API/Repository/Exceptions/InvalidArgumentException.php
eZ/Publish/API/Repository/Exceptions/InvalidVariationException.php
eZ/Publish/API/Repository/Exceptions/LimitationValidationException.php
eZ/Publish/API/Repository/Exceptions/NotFoundException.php
eZ/Publish/API/Repository/Exceptions/NotImplementedException.php
eZ/Publish/API/Repository/Exceptions/PropertyNotFoundException.php
eZ/Publish/API/Repository/Exceptions/PropertyReadOnlyException.php
eZ/Publish/API/Repository/Exceptions/UnauthorizedException.php

| **JIRA issue**     | [EZP-31251](https://jira.ez.no/browse/EZP-31251)
Introduced `eZ\Publish\API\Repository\Exceptions\Exception` in https://github.com/ezsystems/ezpublish-kernel/pull/2905/commits/11a76e04266ac3d65bfec9ed1d6fb4dedda19a5b be able to distinguish PAPI related exceptions form others. 
Additionally unified file headers in `eZ\Publish\API\Repository\Exceptions` namespace (see  https://github.com/ezsystems/ezpublish-kernel/pull/2905/commits/6402af0e4fd783855162250827d3455d4b7e1df3)
**TODO**:

EZP-31251: Introduced base exception for PAPI

---

doc/bc/changes-8.0.md
eZ/Publish/API/Repository/Exceptions/OutOfBoundsException.php
eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
eZ/Publish/API/Repository/Values/ContentType/ContentType.php
eZ/Publish/API/Repository/Values/ContentType/FieldDefinitionCollection.php
eZ/Publish/Core/Helper/Tests/FieldHelperTest.php
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/ContentExtensionTest.php
eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FieldRenderingExtensionIntegrationTest.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
eZ/Publish/Core/Repository/Tests/Values/ContentType/ContentTypeTest.php
eZ/Publish/Core/Repository/Tests/Values/ContentType/FieldDefinitionCollectionTest.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/Core/Repository/Values/ContentType/ContentType.php
eZ/Publish/Core/Repository/Values/ContentType/ContentTypeDraft.php
eZ/Publish/Core/Repository/Values/ContentType/FieldDefinitionCollection.php

| **JIRA issue**     | [EZP-31078](https://jira.ez.no/browse/EZP-31078)
1. Introduced `eZ\Publish\API\Repository\Values\ContentType\FieldDefinitionCollection` which takeover responsibility of providing access field definitions:
```php
interface FieldDefinitionCollection extends Countable, IteratorAggregate, ArrayAccess
{
/**
* This method returns the field definition for the given identifier.
*
* @param string $fieldDefinitionIdentifier
*
* @return \eZ\Publish\API\Repository\Values\ContentType\FieldDefinition|null
*/
public function get(string …
```

EZP-31078: Enhanced Content Type Value Object

---

.travis.yml
eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php

| **JIRA issue**     | https://jira.ez.no/browse/EZP-31268
| **Bug/Improvement**| issue in tests
| **Target version** | 6.13, 7.5 (not needed for master, as it requires PHP 7.3)
| **Tests pass**     | should
The REST functional tests job in ezplatform-http-cache is failing: https://travis-ci.org/ezsystems/ezplatform-http-cache/jobs/626775072
This is caused by the usage of heredoc syntax that has been allowed only since PHP 7.3:
https://www.php.net/manual/en/migration73.new-features.php#migration73.new-features.core.heredoc
This PR:
1) b152807f1536141aca4ffac769d51b6075762d45 (to uncover the issue): lowers the PHP versions on which tests (the …

[Travis] Fixed REST tests failing for PHP < 7.3

---

eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php

This PR adds test so IsEmpty Critertion is checked for `SearchService::findLocations` as well.
Also (a little out-of-scope) fixes one test for `findContent` which was never executed :P
Followup for: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/164

EZP-31275: Added tests for SearchService findLocations method covering IsEmpty Criterion

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryConfigurationProvider.php
eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml

This PR is a followup for https://github.com/ezsystems/ezpublish-kernel/pull/2900 which adds an additional connection parameter for `doctrine:database-create` so correct database is created when `ezplatform:install` command is executed using SiteAccess with connection different than default.

EZP-31203: Fixed wrong connection being used for database creation when SiteAccess option is used

---

eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleDownOnlyFilterLoader.php
eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoader.php
eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoader.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleDownOnlyFilterLoaderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoaderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoaderTest.php

| **JIRA issue**     | [EZP-31258](https://jira.ez.no/browse/EZP-31258)
All "scaledown" aliases (https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml#L174) are using the "outbound" thumbnail mode. This is because the Liip thumbnail filter loader is expecting the text "inset" (https://github.com/liip/LiipImagineBundle/blob/master/Imagine/Filter/Loader/ThumbnailFilterLoader.php#L25) instead of "ImageInterface::THUMBNAIL_INSET" (https://github.com/ezsystems/ezpublish-kernel/blob/7.5/eZ/Bundle/EzPublis …

EZP-31258: Use "inset" for "scaledown" aliases to avoid undesired image cropping

---

eZ/Publish/Core/MVC/Symfony/SiteAccess.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessService.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php

| **JIRA issue**     | [EZP-31320](https://jira.ez.no/browse/EZP-31320)
| **Bug**| yes
This issue is present in Behat tests when `default` Site Access is present and Site Access is not matched by Matcher. As a bonus, the fix also simplifies SiteAccessService::getCurrent method and correct docblock for `$provider` property of Site Access object.
**TODO**:

EZP-31320: Fixed issue when `default` Site Access is unmatched

---

eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/DoctrineStorage.php
eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-31123](https://jira.ez.no/browse/EZP-31123)
| **Target version** | `7.5.x` for eZ Platform 2.5.x LTS.
This PR is a cumulative fix for strict types casting issues found while working on [EZP-30921](https://jira.ez.no/browse/EZP-30921) and [EZP-31088](https://jira.ez.no/browse/EZP-31088) (and possibly others).
- Keyword FT
- Url FT
- Urls in RichText.
- Creating Content
- Adding new Locations
- Adding new Sections
- Adding new Content Types and Field Definitions
- Adding Url Aliases.
- Adding Url wildcard aliases (if possible from UI).
**TODO**:

EZP-31123: Fixed strict types-related casting issues

---

eZ/Publish/API/Repository/Values/Content/Query/Criterion/Ancestor.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/LocationRemoteId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/RemoteId.php

| **Bug/Improvement**| Improvement
The value parameter for the `Ancestor` criterion is documented as string, while it also accepts an array of strings.

Fine-tuned value argument PHPDoc for Ancestor and RemoteId Criteria

---

doc/bc/changes-8.0.md
eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ConfigResolverCleanup.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ChainConfigResolverPass.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ChainConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/ContainerConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/EventListener/ConfigScopeListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Cache/Warmer/ConfigResolverCleanupTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ChainConfigResolverPassTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/TemplatesTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConfigScopeListenerTest.php
eZ/Publish/Core/MVC/ConfigResolverInterface.php
eZ/Publish/Core/MVC/Symfony/Configuration/VersatileScopeInterface.php

| **JIRA issue**     | [EZP-31046](https://jira.ez.no/browse/EZP-31046)
| **Related to**     | https://github.com/ezsystems/ezplatform-richtext/pull/92
This PR improves ChainConfigResolver by extracting code to separate config resolvers (default, site access, site access group and global resolver). In addition, it adds type hints to Configresolver, removed Site Access relation handling (which is replaced by a dedicated method in SiteAccessService in the previous PR).
**TODO**:

EZP-31046: Improved ChainConfigResolver by extracting code to separate config resolvers

---

eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php

| **New feature**    | -
Integration tests in ezplatform-solr-search-engine@1.7 and 2.0 are using ezpublish-kernel@7.5  so SearchServiceTranslationLanguageFallbackTest should take into account index naming convention for both: Solr Clound 6.X and 7.X (which slightly differs)
Example failed build: 
https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/jobs/642365371?utm_medium=notification&utm_source=github_status
Example successful builds:
* https://travis-ci.org/ezsystems/ezplatform-solr-search-engine/jobs/643324123
* …

Fixed index name assertion for Solr Cloud 6.X in SearchServiceTranslationLanguageFallbackTest

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/ezpublish_minimal.yml

| **JIRA issue**     | [EZP-31048](https://jira.ez.no/browse/EZP-31048)
There is a possibility that SiteAccessProvider will return Site Accesses dynamically. This is why the Site Access group must be initially allowed to be empty.
**TODO**:

EZP-31048: Allowed empty Site Access groups

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/ContentTypeIdentifier.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml

| **JIRA issue**     | [EZP-31127](https://jira.ez.no/browse/EZP-31127)
Makes it possible to use non existent content type identifiers in the criterion (e.g. when coming from an outside DB field, where the content type might be deleted in the meantime).
Otherwise, you'd have to use `ContentTypeId` and load the IDs yourself.
**TODO**:

EZP-31127: Skipped non-existing Content Types in ContentTypeIdentifier criterion

---

eZ/Bundle/EzPublishCoreBundle/Tests/URLChecker/URLCheckerTest.php
eZ/Publish/API/Repository/Tests/RoleServiceTest.php
eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php

Because PHPUnit has dedicated assertion which sorts both arrays before the actual comparison we can improve the code in several places. This assertion can be only used to replace sorting with the `SORT_REGULAR` flag.
**TODO**:

Changed assertEquals to assertEqualsCanonicalizing in tests

---

eZ/Publish/API/Repository/Tests/SearchServiceFulltextTest.php

Since eZ Platform 3.0 will support Solr 7 only we might want to drop obsolete tests for Solr 6.
This is an alternative to #2934
**TODO**:

[Tests] Dropped Solr 6 tests

---

doc/bc/changes-8.0.md
eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/Ancestor.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeGroupId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeIdentifier.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/FieldRelation.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/FullText.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/LanguageCode.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/LocationId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/LocationRemoteId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchAll.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchNone.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/MoreLikeThis.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ObjectStateId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ParentLocationId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/RemoteId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/SectionId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/Subtree.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/Visibility.php

| **JIRA issue**     | [EZP-31348](https://jira.ez.no/browse/EZP-31348)
| **Target version** |`master`
Methods `ceateFromQueryBuilder` in the criterion classes has been deprecated sine eZ Platform 2.2. See  https://github.com/ezsystems/ezpublish-kernel/pull/2330 for more details
**TODO**:

EZP-31348: Dropped deprecated createFromQueryBuilder method from the Criterion classes

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessor.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/Contextualizer.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessorTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/SiteAccessAware/ContextualizerTest.php

| **JIRA issue**     | [EZP-31047](https://jira.ez.no/browse/EZP-31047)
Before this PR when we have a Site Access group with some configuration and Site Access group has no assigned Site Access than this configuration is not available in DIC. This is because Site Access group configuration is accessible by `ezsettings.{SA_NAME}.param_name`. Now parameter will be available by `ezsettings.{SA_GROUP_NAME}.param_name`
**TODO**:

EZP-31047: Made Site Access group configuration available in DIC

---

eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ContentList.php
eZ/Publish/Core/REST/Server/Values/ContentList.php

| **JIRA issue**     | Used in [EZP-31316](https://jira.ez.no/browse/EZP-31316) for https://github.com/ezsystems/ezplatform-query-fieldtype/pull/20
| **Bug/Improvement**| improvement
| **Target version** | `7.x` & `8.x`
Adds a `totalCount` attribute to the REST response for `ContentList`. Used for pagination.

Added totalCount attribute to REST ContentList response

---

.travis.yml
eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Exception.php
eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ExceptionTest.php

| **JIRA issue**     | [EZP-31298](https://jira.ez.no/browse/EZP-31298)
| **Bug**| yes
This PR hides potentially sensitive data that could be leaked on REST exceptions.
**TODO**:

EZP-31298: Made non verbose exception messages in REST responses

---

eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php

| **JIRA issue**     | [EZP-31329](https://jira.ez.no/browse/EZP-31329)
| **Improvement** | yes
| **Target version** | eZ Platform `2.5.x`+ LTS 
When running reindexing command with multiple processes, the value of console path is always `app/console` instead of  `bin/console` and a General error is written to log instead of getting the exact error ẁish is `Could not open input file: app/console`:
```
Re-indexing started for search engine: eZ Platform Solr Search EnginePurging index...
Re-Creating index for 19190 items across 384 iteration(s), using 2 parallel child processes:
1/384 [>---------------------------] …
```

EZP-31329: Injected project dir into ezplatform:reindex cmd to find console path

---

eZ/Publish/Core/Search/Common/IncrementalIndexer.php
eZ/Publish/Core/Search/Legacy/Content/Indexer.php

| **JIRA issue**     | [EZP-30664](https://jira.ez.no/browse/EZP-30664)
Similar to https://github.com/ezsystems/ezplatform-solr-search-engine/pull/139, but it is done for legacy search engine.
**TODO**:

EZP-30664: Skipped indexing erroneous Content and logged all exceptions

---

eZ/Bundle/PlatformBehatBundle/Initializer/BehatSiteAccessInitializer.php
eZ/Bundle/PlatformBehatBundle/ServiceContainer/EzBehatExtension.php

| **JIRA issue**     | [EZP-31313](https://jira.ez.no/browse/EZP-31313)
| **New feature**    | for Behat
| **Target version** | 7.5, not for master - PlatformBehatBundle has been moved to BehatBundle in master and the solution will be ported there
| **Doc needed**     | added short doc in https://github.com/ezsystems/BehatBundle/pull/124/commits/4380a8fcff48abd3b406f3ee6252a399303f6ba8
Adding the possibility to set the SiteAccess used by Behat when running tests. If the `EZPLATFORM_SITEACCESS` env variable is not present then the default one will be used.
WIll be used by multirepository suite added in …

[Behat] Make Behat SiteAccess aware

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/ContentTypeService.php
eZ/Publish/Core/Repository/Helper/NameSchemaService.php
eZ/Publish/Core/Repository/LocationService.php
eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
eZ/Publish/Core/Repository/Mapper/ContentTypeDomainMapper.php
eZ/Publish/Core/Repository/Mapper/ProxyAwareDomainMapper.php
eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapper.php
eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperFactory.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/Core/settings/repository/inner.yml

| **JIRA issue**     | [EZP-31279](https://jira.ez.no/browse/EZP-31279)
| **BC breaks**      | no (internal Service)
This PR makes Content Type and Content domain mappers injectable Symfony Services and injects them into the Repository instead of building them on the fly.
Moreover those mappers were moved into the proper namespace:
- `\eZ\Publish\Core\Repository\Helper\ContentTypeDomainMapper`
into `\eZ\Publish\Core\Repository\Mapper\ContentTypeDomainMapper`,
- `\eZ\Publish\Core\Repository\Helper\DomainMapper` 
into …

EZP-31279: Injected content domain mappers into the Repository

---

eZ/Publish/Core/Limitation/ObjectStateLimitationType.php
eZ/Publish/Core/Limitation/Tests/ObjectStateLimitationTypeTest.php

| **JIRA issue**     | [EZP-31002](https://jira.ez.no/browse/EZP-31002)
| **Bug**| yes
| **Target version** | 7.x
ContentCreateStructs do not possess location id, evaluating for RootLocation is not necessary in their case, so the additional check has been added.
**TODO**:

EZP-31002: Skipped Location check for ContentCreateStruct in ObjectStateLimitation

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserBasedFalse.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserBasedTrue.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserEnabledFalse.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserEnabledTrue.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/ObjectStateIdentifier.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/SectionIdentifier.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserEmail.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserIdEq.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserIdIn.php
eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserLogin.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/IsUserBased.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/IsUserEnabled.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/ObjectStateIdentifier.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/SectionIdentifier.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserEmail.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserId.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserLogin.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/IsUserBased.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/IsUserEnabled.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/ObjectStateIdentifier.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/SectionIdentifier.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserEmail.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserId.php
eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserLogin.php
eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml

| **JIRA issue**     | [EZP-31080](https://jira.ez.no/browse/EZP-31080)
This PR adds new criterions. REST implementation is provided in https://github.com/ezsystems/ezplatform-rest/pull/39
Matches content that are also User instances (usually `user` content type but may very on different installations). Supported operators: `EQ`
`{"IsUserBasedCriterion": false}`
Matches only enabled/disabled users (via `ezuser` fieldtype attribute). Supported operators: `EQ`
`{"IsUserEnabledCriterion": true}`
Matches only particular User IDs. Supported operators: `EQ`, …

EZP-31080: Created missing search Criterions

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolver.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ChainConfigResolverTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolverTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php

| **JIRA issue**     | [EZP-31436](https://jira.ez.no/browse/EZP-31436)
| **Bug**| yes
When the configuration for SiteAccess group was fetch and group was empty then an exception was thrown. The fix is based on the fact that now we check if the scope is a SiteAccess group and proper fetch is done.  
**TODO**:

EZP-31436: Fixed fetching configuration for SiteAccess group

---

bin/.travis/check_code_style.sh
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleDownOnlyFilterLoaderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoaderTest.php
eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoaderTest.php
eZ/Publish/Core/FieldType/Tests/BinaryBaseTest.php
eZ/Publish/Core/FieldType/Tests/ImageTest.php
eZ/Publish/Core/FieldType/Validator/FileExtensionBlackListValidator.php
eZ/Publish/Core/FieldType/Validator/ImageValidator.php
eZ/Publish/Core/settings/containerBuilder.php
eZ/Publish/SPI/Tests/FieldType/BinaryFileIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
eZ/Publish/SPI/Tests/FieldType/MediaIntegrationTest.php

|     |     |
| --- | --- |
| **Brief**: | bug in automated CS check |
| **Affects**: | `6.13`, `7.5`, `master` |
Seems when I've introduced CS checking via Travis, I've made a mistake for the case when checking CS for branch (it still can occur that something gets in outside PR workflow, e.g. security fixes). 
The expectation for branches was to run CS check for all PHP files, the result was that no files were checked, because when `--path-mode=intersection` is used with empty list of files, CS fixer doesn't check anything (makes sense). So to solve that, in case of branch CS check, a default option is used.
Failing CS job on branch: https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/661158539 (yes, we have CS issues in the codebase because of this bug).
Passing CS job on …

[CS][Travis] Fixed Code Style check for branches

---

data/update/mysql/dbupdate-7.5.6-to-7.5.7.sql
data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql

| **JIRA issue**     | [EZP-31299](https://jira.ez.no/browse/EZP-31299)
| **Target version** | `7.5`, `master (8.0@dev)`
DML statement closing semicolon was missing.
**TODO**:

EZP-31299: Added semicolon in dbupdate-7.5.6-to-7.5.7.sql

---

eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/ImageAsset/AliasGeneratorTest.php
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/Core/Event/ContentService.php
eZ/Publish/Core/FieldType/ImageAsset/Type.php
eZ/Publish/Core/FieldType/Relation/Type.php
eZ/Publish/Core/MVC/Symfony/FieldType/Relation/ParameterProvider.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/SearchService.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
eZ/Publish/Core/Repository/TrashService.php
eZ/Publish/Core/Repository/UserService.php
eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php

| **JIRA issue**     | [EZP-31118](https://jira.ez.no/browse/EZP-31118)
This PR introduces strict types for the `\eZ\Publish\API\Repository\ContentService`
**TODO**:

EZP-31118: Introduced strict types for ContentService

---

eZ/Publish/Core/Limitation/SiteAccessLimitationType.php
eZ/Publish/Core/Limitation/Tests/SiteAccessLimitationTypeTest.php
eZ/Publish/Core/settings/roles.yml
eZ/Publish/Core/settings/tests/common.yml

| **JIRA issue**     | [EZP-31477](https://jira.ez.no/browse/EZP-31477)
| **Related to**        | https://github.com/ezsystems/ezplatform-admin-ui/pull/1272
List of SiteAccesses on limitation list should be fetched from the service, not from configuration. We have an extension point which allows extending the list of SiteAccesses. To fetch all of SiteAccesses the siteAccessService should be used.
**QA**:
you need to check whether the limitations based on SiteAccesses continue to work
**TODO**:

EZP-31477: Fixed loading Site Accesses on limitation list

---

.travis.yml

| **Bug/Improvement**| fix in test setup
| **Target version** | 7.5, not needed for master
Tests in this repo are failing with:
```
PHP Fatal error:  Declaration of Behat\Behat\Definition\Translator\Translator::trans($id, array $parameters = Array, $domain = NULL, $locale = NULL) must be compatible with Symfony\Contracts\Translation\TranslatorInterface::trans(string $id, array $parameters = Array, ?string $domain = NULL, ?string $locale = NULL) in /var/www/vendor/behat/behat/src/Behat/Behat/Definition/Translator/Translator.php on line 5
``` …

[Travis] Specified PHP dev image for jobs using full product setup

---

eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
eZ/Publish/Core/settings/storage_engines/legacy/language.yml

| **JIRA issue**     | [EZP-31088](https://jira.ez.no/browse/EZP-31088)
This PR refactors Content Language gateway to rely on `\Doctrine\DBAL\Connection` instead of our own deprecated `DatabaseHandler`.
Affected implementation:
- `\eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway`
- `\eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\DoctrineDatabase`
- `\eZ\Publish\Core\Persistence\Legacy\Content\Language\Gateway\ExceptionConversion`
Additionally strict types were introduced to the all Language gateway …

EZP-31088: Refactored Language GW to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Section/Handler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Section/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/settings/storage_engines/legacy/section.yml

This PR refactors the Legacy (Content) Section Gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\Content\Section\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` instead of our custom Database Handler.
**TODO**:

EZP-31088: Refactored Section GW methods to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/ObjectState/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/settings/storage_engines/legacy/object_state.yml

This PR refactors the Legacy (Content) ObjectState Gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\Content\ObjectState\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` instead of our custom Database Handler. Some CS alignment, optimizations, strict types enforcement (as it proved to be safe) has been done along the way.
The full list of tasks done for the …

EZP-31088: Refactored ObjectState GW methods to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/AbstractTestCase.php
eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml

This PR refactors the Legacy Storage Content Model **`Content Type`** gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\Content\Type\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` and `QueryBuilder` instead of our custom Database Handler from legacy Zeta Components.
This time, unlike in most of the related refactoring, I've taken a bit different approach. Refactoring …

EZP-31088: Refactored Content Type GW to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
eZ/Publish/Core/Persistence/Legacy/Content/TreeHandler.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
eZ/Publish/Core/settings/storage_engines/legacy/location.yml
eZ/Publish/SPI/Persistence/Content/Location/Handler.php

This PR refactors the Legacy (Content) Location Gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\Content\Location\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` instead of our custom Database Handler.
**TODO**:

EZP-31088: Refactored Location gateway methods to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/UrlWildcardHandlerTest.php
eZ/Publish/Core/settings/storage_engines/legacy/url_wildcard.yml

This PR refactors the Legacy Storage Content Model **`UrlWildcard`** gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\Content\UrlWildcard\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` and `QueryBuilder` instead of our custom Database Handler from legacy Zeta Components.
**TODO**:

EZP-31088: Refactored UrlWildcard GW to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Tests/User/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
eZ/Publish/Core/settings/storage_engines/legacy/user.yml

This PR refactors the Legacy Storage Content Model **`User`** gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\User\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` and `QueryBuilder` instead of our custom Database Handler from legacy Zeta Components.
**TODO**:

EZP-31088: Refactored User GW to use Doctrine\DBAL

---

eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/Gateway/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
eZ/Publish/Core/settings/storage_engines/legacy/user.yml

This PR refactors the Legacy Storage Content Model `User` **`Role`** gateway implementation (`\eZ\Publish\Core\Persistence\Legacy\User\Role\Gateway\DoctrineDatabase`) to rely on `\Doctrine\DBAL\Connection` and `QueryBuilder` instead of our custom Database Handler from legacy Zeta Components.
**TODO**:

EZP-31088: Refactored User Role GW to use Doctrine\DBAL 

---

eZ/Publish/API/Repository/PermissionCriterionResolver.php
eZ/Publish/API/Repository/PermissionResolver.php
eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
eZ/Publish/Core/Repository/Permission/PermissionCriterionResolver.php
eZ/Publish/Core/Repository/Permission/PermissionResolver.php
eZ/Publish/Core/Repository/Tests/Permission/CachedPermissionServiceTest.php

| **JIRA issue**     | [EZP-31480](https://jira.ez.no/browse/EZP-31480)
This PR introduces strict types for the `\eZ\Publish\API\Repository\\eZ\Publish\API\Repository\PermissionResolver` and `\eZ\Publish\API\Repository\PermissionCriterionResolver`
**TODO**:

EZP-31480: Introduced strict types for PermissionResolver & PermissionCriterionResolver

---

eZ/Publish/Core/FieldType/Image/ImageThumbnailStrategy.php
eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
eZ/Publish/Core/Repository/Strategy/ContentThumbnail/Field/ContentFieldStrategy.php
eZ/Publish/Core/Repository/Tests/ContentThumbnail/ContentFieldStrategyTest.php
eZ/Publish/Core/settings/thumbnails.yml
eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/Field/FieldTypeBasedThumbnailStrategy.php

| **JIRA issue**     | [EZP-30882](https://jira.ez.no/browse/EZP-30882)
Improved the way how new fieldtype thumbnail strategies are injected. Instead of plain hardcoded hashmap, make strategies tagged services. This will make thumbnails much easier to extend or overwrite new strategies.
Late follow-up to: https://github.com/ezsystems/ezpublish-kernel/pull/2868
Previous:
```yaml
arguments:
$strategies:
ezimage: '@eZ\Publish\Core\FieldType\Image\ImageThumbnailStrategy'
ezimageasset: '@eZ\Publish\Core\FieldType\ImageAsset\ImageAssetThumbnailStrategy'
```
Now: …

EZP-30882: Changed the way new fieldtype thumbnail strategies are injected

---

eZ/Publish/Core/Repository/URLAliasService.php

| **JIRA issue**     | [EZP-31448](https://jira.ez.no/browse/EZP-31448)
Fixed broken build: https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/663994735
`$locationId` should be casted to int in the `\eZ\Publish\Core\Repository\URLAliasService::createGlobalUrlAlias` before passing it to `\eZ\Publish\API\Repository\LocationService::loadLocation` 
**TODO**:

EZP-31448: Added missing casting $locationId to int in the URLAliasService::createGlobalUrlAlias

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserMetadata.php

| **JIRA issue**     | [EZP-31482](https://jira.ez.no/browse/EZP-31482)
https://github.com/ezsystems/ezpublish-kernel/pull/2989 follow up: allowed `null` as  $operator` in the`\eZ\Publish\API\Repository\Values\Content\Query\Criterion\UserMetadata` criterion
**TODO**:

EZP-31482: Allowed null as $operator in UserMetadata criterion

---

eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php

| **JIRA issue**     | [EZP-30956](https://jira.ez.no/browse/EZP-30956)
| **Target version** | `6.13 / 7.x`
Replacement of https://github.com/ezsystems/ezpublish-kernel/pull/2771 
**TODO**:

EZP-30956: fix false positive view parameters detection

---

data/mysql/cleandata.sql
data/postgresql/cleandata.sql

| **JIRA issue**     | [EZP-31497](https://jira.ez.no/browse/EZP-31497)
| **Target version** | `master (8.0.0@dev)`  for eZ Platform `v3.0.0`
I've dropped obsolete data from `ezpackage` and prepared `ezsite_data` for eZ Platform 3.0.0 release.
Moreover added a follow-up to #2984 - cleaned up clean SQL data dumps for MySQL and PostgreSQL.
Dumps were not very optimal. We can insert multiple rows at once, reducing number of queries from ~300 to ~30-~60 depending on DBMS.
Also modified dumps are much more readable.
Should I aim to align all queries to fit on a screen by wrapping? (a.k.a 100 …

EZP-31497: Prepared clean data for eZ Platform 3.0 release

---

eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php

| **JIRA issue**     | [EZP-31134](https://jira.ez.no/browse/EZP-31134)
Added exit codes to be aligned with current Symfony recommendations, ref: https://symfony.com/blog/new-in-symfony-4-4-console-improvements#make-it-mandatory-to-return-the-command-exit-status.
**TODO**:

EZP-31134: Added exit codes to UpdateTimestampsToUTCCommand to reflect Sf5 standards

---

eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php

| **JIRA issue**     | [EZP-31457](https://jira.ez.no/browse/EZP-31457)
| **Bug**| yes
| **Target version** | `7.x`,master
Issue introduced by recent changes in Symfony:
https://github.com/symfony/symfony/commit/fb0be81b7a26f96f65bed5d774771bba026a78fd#diff-3f33c4b578f7ceb90dae8836c3c9a9a7R178
https://github.com/symfony/symfony/blob/fb0be81b7a26f96f65bed5d774771bba026a78fd/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L178
**TODO**:

EZP-31457: Fix supportsClass in user provider

---

eZ/Publish/Core/QueryType/BuiltIn/AbstractLocationQueryType.php
eZ/Publish/Core/QueryType/BuiltIn/AbstractQueryType.php
eZ/Publish/Core/QueryType/BuiltIn/Tests/AncestorsQueryTypeTest.php
eZ/Publish/Core/QueryType/BuiltIn/Tests/ChildrenQueryTypeTest.php
eZ/Publish/Core/QueryType/BuiltIn/Tests/SiblingsQueryTypeTest.php
eZ/Publish/Core/QueryType/BuiltIn/Tests/SubtreeQueryTest.php

| **JIRA issue**     | [EZP-31507](https://jira.ez.no/browse/EZP-31507)
Built-in Ancestors/Children/Siblings/Subtree Query Types should produce `\eZ\Publish\API\Repository\Values\Content\LocationQuery` instead of `\eZ\Publish\API\Repository\Values\Content\Query` to be compatible with location search. Issue found by @DominikaK . 
**TODO**:

EZP-31507: Allowed to use Ancestors/Children/Siblings/Subtree Query Types with location search

---

eZ/Publish/Core/FieldType/RichText/SearchField.php
eZ/Publish/Core/FieldType/Tests/RichText/SearchFieldTest.php

| **JIRA issue**     | [EZP-31512](https://jira.ez.no/browse/EZP-31512)
| **Target version** | `7.5.x` for eZ Platform 2.5.x LTS
| **Tests pass**     | [yes](https://travis-ci.org/github/ezsystems/ezpublish-kernel/builds/666484894)
This PR fixes wrong traversing through child nodes of `\DOMNode` to extract from RichText DocBook XML a Search Field value for indexing. It worked before _most probably_ due to [PHP Bug #79271](https://bugs.php.net/bug.php?id=79271) which was fixed in the most recent patch release of PHP `v7.3.16`.
RichText in Kernel is provided for `7.5` as a BC layer and is used by integration tests. …

EZP-31512: Fixed extracting Search Fields from RichText

---

eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php

| **JIRA issue**     | [EZP-31463](https://jira.ez.no/browse/EZP-31463)
```
$contentTypeHandler->getFieldDefinition(0, Type::STATUS_DEFINED);
```
throws an error:
```
TypeError: Argument 1 passed to eZ\Publish\Core\Persistence\Legacy\Content\Type\Mapper::extractFieldFromRow() must be of the type array, bool given, called in /Users/sd/Projects/ez/bundles/ezpublish-kernel/eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php on line 504
```
Instead of throwing ` \eZ\Publish\Core\Base\Exceptions\NotFoundException`
**TODO**:

EZP-31463: Handled fetching of non existing type field type

---

phpunit-integration-legacy-solr.xml
phpunit-integration-legacy.xml
phpunit.xml

| **Target version** | `7.5`, `master`, `ezplatform-kernel:master`
| **Tests pass**     | [pending](https://travis-ci.org/github/ezsystems/ezpublish-kernel/builds/667251001)
This PR changes the default behavior of all test configs to fail on warning.
Travis gives us a false positive if a warning occurs in PHPUnit test suite. It's because warning is by default a soft issue. Though in many cases it indicates that we missed something (e.g. during refactoring or during implementing tests - AFAIR erroneous data providers trigger such warning as well).
See false positive example: https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/304586 …

[Tests] Enforced failure on warning

---

.travis.yml

Attempting to unblock #3009
Seems composer replace can't handle ezplatform-kernel dependency issue on PRs. I prefer to have it stable anyway, so investigating a fix (~probably by forcing older beta~).
The issue ATM:
```
Problem 1
- ezsystems/ezplatform-solr-search-engine v3.0.0-rc1 requires ezsystems/ezplatform-kernel ^1.0 -> satisfiable by ezsystems/ezplatform-kernel[1.0.x-dev, v1.0.0-rc1] but these conflict with your requirements or minimum-stability.
- ezsystems/ezplatform-solr-search-engine v3.0.0-beta4 requires ezsystems/ezpublish-kernel ^8.0 -> satisfiable by ezsystems/ezpublish-kernel[8.0.x-dev, v8.0.0-beta1, v8.0.0-beta2, v8.0.0-beta3, v8.0.0-beta4, v8.0.0-beta5] but these conflict with your requirements or minimum-stability.
- ezsystems/ezplatform-solr-search-engine v3.0.0-beta3 …
```

[Tests] Fixed Solr Bundle dependency issue for ezpublish-kernel:master

---

eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
eZ/Bundle/EzPublishCoreBundle/EventListener/RejectExplicitFrontControllerRequestsListener.php
eZ/Bundle/EzPublishCoreBundle/Resources/config/http_kernel.yml
eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RejectExplicitFrontControllerRequestsListenerTest.php

| **JIRA issue**     | [EZP-31519](https://jira.ez.no/browse/EZP-31519)
| **New feature**    | yes/no (it's new to the kernel but not to the application)
**TODO**:

EZP-31519: Move app.php rejection snippet from front controller to ezpublish-kernel

---

eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConsoleCommandListenerTest.php
eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/LocationServiceTest.php
eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterTest.php

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | -
| **Target eZ Platform version** | `master`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
See https://github.com/ezsystems/ezplatform-kernel/pull/27

Replaced usages of deprecated expectExceptionMessageRegExp() with expectExceptionMessageMatches()

---

eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
eZ/Publish/Core/FieldType/Url/UrlStorage.php

| **JIRA issue**     | [EZP-31136](https://jira.ez.no/browse/EZP-31136)
| **Target version** | ``7.5` for bug fixes or improvements
**TODO**:

EZP-31136: Added unlink to remove old link from ezurl table

---

composer.json
eZ/Publish/Core/Persistence/Cache/ContentLanguageHandler.php
eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
eZ/Publish/Core/Persistence/Cache/SectionHandler.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php

| **JIRA issue**     | [EZP-31558](https://jira.ez.no/browse/EZP-31558)
| **Target version** | `7.5`/`master`
**TODO**:

EZP-31558: Updated loadByIdentifier to use escapeForCacheKey function before get value from cache

---

eZ/Publish/API/Repository/Tests/BaseTrashServiceTest.php
eZ/Publish/API/Repository/Tests/TrashServiceTest.php
eZ/Publish/API/Repository/Values/Content/Query/SortClause/Trash/DateTrashed.php
eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php

| **JIRA issue**     | [EZP-31411](https://jira.ez.no/browse/EZP-31411)
Currently, admin interface has trashed items sorted by priority, which makes it hard to find recently trashed items.
This PR will allow sorting by trashed date, so we can do further improvement of sorting order in admin UI.
**TODO**:

EZP-31411: Added ability to sort Trash items by trashed date

---

eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
eZ/Publish/Core/IO/Tests/MetadataHandler/ImageSizeTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/LocalPurgeClientTest.php
eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/LocationAwareStoreTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/Relation/ParameterProviderTest.php
eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeGroupTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/LocationTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentLocationTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/RemoteTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/SectionTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ContentTypeTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/MultipleValuedTest.php
eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/UrlAliasTest.php
eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Update/Handler/DoctrineDatabaseTest.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
eZ/Publish/Core/SignalSlot/Tests/SlotFactory/GeneralSlotFactoryTest.php

| **JIRA issue**     | [EZP-31560](https://jira.ez.no/browse/EZP-31560)
| **Target version** | `6.13`+
This PR aligns namespaces not following defined psr-0 convention. Fortunately for this package only test cases are affected. See [EZP-31560](https://jira.ez.no/browse/EZP-31560) for more details.
**TODO**:

EZP-31560: [Tests] Fixed namespaces not following PSR

---

data/mysql/schema.sql

| **JIRA issue**     | [EZP-31592](https://jira.ez.no/browse/EZP-31592)
| **Doc needed**     | ezsystems/developer-documentation#1029
When introducing PostgreSQL support via #2552 I've replaced usage of `data/mysql/schema.sql` with generic `eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml`.
The intention was to deprecate `schema.sql` because it was possible 3rd party packages or project relied on it directly or at least on `CleanInstaller` consuming it. I've forgotten to do it, which I've fixed in this PR.
Please note that I'm not deprecating anything in the next 2.5.x, just adding a …

EZP-31592: Added missing deprecation info to data/mysql/schema.sql

---

data/mysql/schema.sql

| **JIRA issue**     | [EZP-31586](https://jira.ez.no/browse/EZP-31586)
| **Target version** | `7.5` for eZ Platform `v2.5.x`
This PR updates `data/mysql/schema.sql` according to upgrade scripts in `data/update/mysql/dbupdate-*-to-7.5.*sql` - note that only two updates were missing.
While `data/mysql/schema.sql` is deprecated, custom installation process relying on that file results in a broken instance if not maintained during 2.5.x LTS service life. This wasn't the intention.
In eZ Platform v3.0.0 (eZ Platform Kernel) this file is gone completely.
You can override your installation with `data/mysql/schema.sql`, …

EZP-31586: Added missing columns to data/mysql/schema.sql

---

.travis.yml
eZ/Bundle/EzPublishCoreBundle/Tests/Assetic/AssetFactoryTest.php
eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
eZ/Publish/Core/FieldType/BinaryFile/SearchField.php
eZ/Publish/Core/FieldType/DateAndTime/SearchField.php
eZ/Publish/Core/FieldType/Image/SearchField.php
eZ/Publish/Core/FieldType/MapLocation/SearchField.php
eZ/Publish/Core/FieldType/Media/SearchField.php
eZ/Publish/Core/FieldType/Relation/Type.php
eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateConverter.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/TimeConverter.php
eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
eZ/Publish/Core/Persistence/TransformationProcessor/PcreCompiler.php
eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
eZ/Publish/Core/Repository/UserPreferenceService.php

| **JIRA issue**     | [EZP-31542](https://jira.ez.no/browse/EZP-31542)
**TODO**:

EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)

---

eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
eZ/Publish/Core/Search/Common/FieldValueMapper/StringMapper.php

| **JIRA issue**     | [EZP-31248](https://jira.ez.no/browse/EZP-31248)
Replaces all special chracaters to avoid issues with SolR
**TODO**:

EZP-31248: Fixed handling non-printable characters for Search

---

.travis.yml

| **JIRA issue**     | https://jira.ez.no/browse/EZP-31613
| **Bug/Improvement**| fix for Travis
| **Target version** | 6.13, 7.5, separate value for v3 in https://github.com/ezsystems/ezplatform-kernel/pull/61
Regenerated Slack integration after workspace name change.
I've also removed the integration with our other workspace, as it hasn't really been used.
**TODO**:

[Travis] Changed notification key after rebranding

---

eZ/Publish/API/Repository/Tests/SearchServiceTest.php

| **JIRA issue**     | Work-around due to [EZP-31325](https://jira.ez.no/browse/EZP-31325)
| **Target version** | `7.5` and maybe up
Sorting by Location ID is broken on Solr for some edge cases, see [EZP-31325](https://jira.ez.no/browse/EZP-31325) for more details.
This PR is not an actual solution, but a work-around to unblock [failing](https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/684529155#L763) [CI](https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/684175531#L763).
The essence of the failing test is not about ordering, so should be fine for now.
The root cause is that Solr treats `"location_id"` Field as a …

[Tests] Stopped relying on Location ID SortClause in testContentWithMultipleLocations

---

eZ/Publish/API/Repository/Tests/SearchService/DeleteTranslationTest.php
eZ/Publish/Core/Search/Common/EventSubscriber/ContentEventSubscriber.php

This is a technical PR to test alignment of a fix from #3013 to see if tests are passing. Cherry-picked from ezsystems/ezplatform-kernel#58, because needs to be applied here first and merged horizontally into ezplatform-kernel.

EZP-31420: Aligned changes from #3013 with master

---

eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php

Integration tests and some API doc refer to 4.x behavior, often as opposed to what _was_ planed for 5.x back in 2011. However in some cases the referred to 4.x behaviour is plain wrong, and if not platform today is either behaving as described as 4.x, and others as 5.x. So time to start to cleanup this I guess. 
There are other cases I don't cover here as I'm unsure what is exactly right in terms of how Platform behaves today, someone will need to check against tests:
This PR does:
- Removed effectively unused `isVersion4()` checks …

[Tests] deprecate isVersion4() & attempt to cleanup some API doc on this

---

eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php

| **Type**| improvement
| **Target version** | `7.5` and up (incl. ezplatform-kernel)
Looks like `SearchServiceLocationTest::testFieldIsEmptyInLocation` fails sometimes due to lack of deterministic ordering. Hopefully this test case won't be affected by [EZP-31325](https://jira.ez.no/browse/EZP-31325).
**TODO**:

[Tests] Added SortClause in testFieldIsEmptyInLocation
